### ISSUE TITLE
Test SAML plugin with JWT/UI

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10057]

**Comment by jdotcms** [comment]
we may need to discuss a little bit more about the 3.7 and saml integration.
For instance if I get log in on SAML, should the user being automatically remember me on dotCMS?
Since the cookie creation is made on the LoginAction or AuthenticationResource, and on SAML we are not calling it (b/c it is for 3.6 and JWT does not exists)
Also would need to define the scenario when you send a token on the header.

Probably would be better to create a 3.7 plugin to be align with the desire behavior
