### ISSUE TITLE
Error when you try to add/remove portlets  and the session has expired

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10118]
## Expected Behavior
When you try to add or remove any portlet and the session has expired, we need redirect to the login page 

## Current Behavior
The system is showing an error message 

SC: 
![r1](https://cloud.githubusercontent.com/assets/2641437/20283133/66ede9c0-aa7d-11e6-88e8-adf6b73975bd.gif)

## Your Environment
Tested on master-3.7 // H2 // FF

**Comment by jgambarios** [comment]
Back end code started in: https://github.com/dotCMS/core/pull/10250

**Comment by wezell** [comment]
So do we still have a session keep-alive in the new UI?  We had one in the old UI What we need is a websocket event that will redirect the user to the login screen if their session dies.

Take a look at the code around here:

https://github.com/dotCMS/core/blob/master-3.7/dotCMS/src/main/webapp/html/common/bottom_portal_inc.jsp#L54

We had a config variable called : KEEP_SESSION_ALIVE .  If this was set to true, we would keep the session alive. Otherwise, we would kill the session after 30m.  We will need to mirror this behavior, I think.

**Comment by bryanboza** [comment]
Now we have the specific error on logs, but the system never redirects to the login page...

**Comment by jdotcms** [comment]
We need to define what to do with this ticket!
