### ISSUE TITLE
Remove assignPermissions from com.dotmarketing.business.PermissionBitAPIImpl

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#10142]
We have the **com.dotmarketing.business.PermissionBitAPIImpl.assignPermissions** method that calls the **com.dotmarketing.business.PermissionBitFactoryImpl.assignPermissions** but that **com.dotmarketing.business.PermissionBitAPIImpl.assignPermissions** method is used only 3 times and practically does the same as the **com.dotmarketing.business.PermissionBitAPIImpl.save** method which is widely used.

The logic of the **assignPermissions** permissions is almost the same as the **save** inside the **PermissionBitAPIImpl** and inside the **PermissionBitFactoryImpl**, we could remove it from those two clases.

I think this is confusing and it is prone error, we are still using the **assignPermissions** in a couple of places when everywhere we move to the use of the **save** logic instead, in order to avoid to break plugins we could deprecated the **assignPermissions** and internally make it use the **save** method.

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10434

**Comment by agomez-dotcms** [comment]
Hey Guys,

After analysis, the original intends described by this ticket could not addressed as such: even they have some similarity, the methods "assignPermissions" and "save" have subtle functional differences and different usages that make them dangerous to be coerced into one single method.

Alternatively, this ticket was addressed by removing redundancy in favor of performance and mantainability between "assignPermissions" and "save" methods in permissions api and factory classes:
1. In PermissionBitFactoryImpl, "save" now relies on "assignPermissions" for the main part of the functionality
2. In PermissionBitAPIImpl, "save" now introduces a performance improvement by relying on "in-bulk" assignPermissions for part of the functionality.

Finally, "assignPermissions" was deprecated in favor of "save" in order to avoid spreading the disparities in functionality for future usages of the api/factory.

**Comment by dsilvam** [comment]
Permissions tests failing in jenkins after this change: https://cb.dotcms.com/view/master-4.0/job/Git_Master_Int_Funct_Test_Runner_4.0_MySQL/78/

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10454

**Comment by agomez-dotcms** [comment]
Hey Guys,

After running tests, it was was found that PermissionAPI functional-tests failed due to applied refactorings. To finish this issue, it was decided to revert the refactorings and leave both "assign-permissions" and "save" methods as they were before. We are additionally deprecating "assign-permissions" in favor of "save" method.
