### ISSUE TITLE
Remove the Structure and Field entries in the hibernate.hbm files

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10289]
The 'Structure' and 'Field' mappings need to be removed from the hibernate files:

dotCMS/src/main/resources/com/dotmarketing/beans/DotCMSId.hbm.xml
dotCMS/src/main/resources/com/dotmarketing/beans/DotCMSSeq.hbm.xml

**Comment by wezell** [comment]
Be mindful, this will require a new starter.

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10699

**Comment by agomez-dotcms** [comment]
Hey Guys,

This ticket has been fixed by:
1. Migrating the Structure and Field support in Export/Import functionality to now rely on Content-Types (Immutables).
2. Removing Structure and Field entries in the hibernate.hbm files.
3. Replacing the Structure and Fields data in Starter.zip (now JSON -based).

Thus, codebase is now cleaned-up in Hibernate configuration files and now running with a new starter.

Thanks,
Anibal

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10705

**Comment by erickgonzalez** [comment]
Steps Tested:
1- Start dotcms
2- Create a new content type
3- Download Data/Assets
4- Shutdown dotcms
5- Delete assets, dotsecure, and DB to do a fresh install
6- Rename the downloaded zip to starter.zip
7- Replace the starter.zip
8- Start dotcms

The new starter with the new content-type is imported successfully.
