### ISSUE TITLE
Unable to import tags

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#10322]
## Expected Behavior
We need be able to import tags without problems 

## Current Behavior
We are having when you try to import tags from a csv file, the system si throwing an error and isn't importing the tags 

Here the log: https://gist.github.com/bryanboza/f591a236144e75591d594815382e51db

## Steps to Reproduce (for bugs)
1. Login 
2. Go to tags portlet 
3. Click to add/import tags
4. Select the csv file 
5. Try yo import 

## Your Environment
Tested on master-3.7 // H2 // FF

**Comment by shaydotcms** [comment]
This issue is still happening on 4.0.
To be more specific, csv files are imported successfully, however these are the errors showing when you try to import a csv files containing tags with:

**Empty tag name**:
https://gist.github.com/shaydotcms/c4ac393c174d0244e38d1821924ab8f7#file-1-empty-tag-name

**Empty host id**:
https://gist.github.com/shaydotcms/c4ac393c174d0244e38d1821924ab8f7#file-2-empty-host-id
