### ISSUE TITLE
Create StaticDependencyBundler and implement force push logic

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10458]
We are not doing any dependency management yet with Static PP.  I think we will need a DependencyBundler that runs first that builds the dependencies for when a user chooses to publish a folder or host.

The logic here is easier than what is in the Live PushPublishing DependencyBundler because all we need to do is build the correct lucene patterns to include in our static publishing.  Here is a first pass at it.

**Comment by jtesser** [comment]
In addition to need to integrate with the DependencySet and Push-asset-History

**Comment by oarrietadotcms** [comment]
ee PR: https://github.com/dotCMS/enterprise-2.x/pull/419

**Comment by agomez-dotcms** [comment]
Passed QA. Assets and Folders are not pushing again if nothing has changed in them. On the other hand, Force Push is making Assets and Folders to push even they have not changed. Moving ticket to Done.

**Comment by dsilvam** [comment]
EE PR 2: https://github.com/dotCMS/enterprise-2.x/pull/424

**Comment by oarrietadotcms** [comment]
ee PR: https://github.com/dotCMS/enterprise-2.x/pull/427
This PR includes the force push on html page (always) and the removal of AWSS3_PUBLISHER_ALLOWSCREATENEWBUCKET_CONFIG_PARAM_KEY property

**Comment by agomez-dotcms** [comment]
Passed QA. After re-pushing a site with changes on containers and templates, the system forced push of the pages, which makes the tests meet the expectations. Remarkably, even the second push performed had less size in bytes (actually half of the original size, in terms of the bundle), it is important to say that it also pushed all the contentAssets referenced by the pages. At this point, it is understood that this is by design. Moving ticket to Done.
