### ISSUE TITLE
Generic Static Publisher logic

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#10519]
@chrismccracken is doing quick test with the static publishing to an alternate endpoint:  i.e. Google Cloud storage is S3-compatible.

- [ ] Don't use [list buckets](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#listBuckets--) : This API op is not a strict storage op, and if the API user isn’t the OWNER of the buckets it will fail
- [ ] aws_bucket_region doesn’t apply if you’re using pre-configured buckets so this should probably not be a required param

**Comment by oarrietadotcms** [comment]
ee PR: https://github.com/dotCMS/enterprise-2.x/pull/422
core PR: https://github.com/dotCMS/core/pull/10522

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/426

**Comment by agomez-dotcms** [comment]
Hey Guys,

This ticket has been additionally fixed with work-around for basic connectivity test performed upon submission of Add Server UI on Push Publishing configuration. After tests performed with a permission-limited IAM user for AWS-S3, it was noticed that basic connectivity test needed code update. After code update, configuration and tests, it could be noticed that Static Publisher does not require aws_bucket_region and that basic connectivity test / work-around would only be useful for checking IAM user credentials (aws_access_key and aws_secret_access_key). On the other hand, the tests against an alternate storage endpoint (ie. Google Cloud storage) did not succeed but this is not a requirement for now.

Finally, below you may find the minimal set of permissions that have been used as security policy for the permission-limited IAM user for AWS-S3 (this may be configured on AWS's IAM console). For testing purposes, please notice the update required for bucket-name under Resource nodes:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1485382222000",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectTagging",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:PutObjectTagging"
            ],
            "Resource": [
                "arn:aws:s3:::dot-bucket-anibal-12-demo.dotcms.com/*"
            ]
        },
        {
            "Sid": "Stmt1485382223000",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::dot-bucket-anibal-12-demo.dotcms.com"
            ]
        }
    ]
}
`

Thanks,
Anibal

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/enterprise-2.x/pull/428

**Comment by agomez-dotcms** [comment]
Hi Guys,

After feedback and discussion, work-around for basic connectivity test has been improved by incorporating a new property "AWS_VALIDATION_BUCKET". This property is meant to hold the bucket name against which "headBucket" operation is performed and may be configured in file "dotmarketing-config-ext.properties". By default (if not configured), the system will use a value driven by a random UUID (to prevent collision with a global existing bucket and/or malicious intervention).

Remarkably, if the property is customized via configuration file it is assummed that the user has access permissions to the placeholder bucket referenced by the property in order the basic connectivity check work as expected.

Thanks,
Anibal

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/429
