### ISSUE TITLE
Second Static Publish of a Site does not force push and is missing all files

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10560]
I have my static push environment set to create a different bucket each time using the date parameter. 

{hostname}-{languageIso}-{date}

 I push the demo.dotcms.com site to the environment, works fine, takes everything.

The second time, I push again without changing anything, and my new bucket is broken because no files are sent.  Menus don't work, no javascript, etc.

**Comment by agomez-dotcms** [comment]
PR Core: https://github.com/dotCMS/core/pull/10569
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/432

**Comment by agomez-dotcms** [comment]
Hi Guys,

This issue has been fixed by forcing static push over file-assets when bucket does not exist. Due to chicken-egg problem (between bucket-name interpolation and bundler/publisher lifecycle), the check is done by aws-s3-publisher at file-asset-bundle creation-time. In order to not impact performance, the check is cached at aws-s3-publisher side.

Thanks,
Anibal

**Comment by bryanboza** [comment]
Fixed, tested in the last master-3.7 // H2 // Chrome
