### ISSUE TITLE
"Download Data Only" & "Download Data/Assets" not working in 4.1

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10678]
Go to System > Maintenance -> Tools, neither "Download Data Only" nor
 "Download Data/Assets" options are working. No errors in the log

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/10687

**Comment by agomez-dotcms** [comment]
Hi Guys,

This issue has been fixed by restoring backend-end logic to handle "Download Data" and "Download Data/Assets" actions, which was removed in following commit 
https://github.com/dotCMS/core/commit/d6ee648c10dd3469a6dc52aa1f69d233329722f5#diff-1153938464b3e49c36b56466333c68db. After confirmation, the logic was added intact (with no functional changes) and was tested with success.

Thanks,
Anibal

**Comment by nollymar** [comment]
Tested. Working as expected.
