### ISSUE TITLE
Clicking on a top level Nav item should expand and deliver user to Top portlet in sub-nav list

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#10724]
Clicking on a top level nav item should make the following two things happen:

1) The sub-nav list should be exposed, however, the user should also 2) Be delivered by default to the top portlet in the sub-nav list.

For Example:

-A single click on Site Browser top nav should expand the Site Browser sub-nav and deliver the user to the Site Browser portlet.
-A single click on Content, should expand the sub-nav and deliver the user to the Content Search portlet.
![topclick](https://cloud.githubusercontent.com/assets/1569167/22946206/5f0715ec-f2bc-11e6-8670-8d13eca15ebd.png)

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core-web/pull/273

**Comment by jgambarios** [comment]
@DeanGonzalez @wezell @fishsmith 
Ozzy already finished this task as requested but now we are wondering, what about if you just want to look and use a different portlet and not just the default one of each group, in order to expand the sub-menu you need to load a portlet you don't need, let's say you want to go to the Configuration portlet and if we merge this code you need to load first the Users portlet just to expand the su-menu and that apply for each Layout group, so, you wont have to do extra clicks on just a few portlets, for the rests of them I think it will be worse.

Initially looks like that is how the old UI used to work but remember that in the old UI we expand the menu on hover, you could go directly to any portlet you want, I think we should re-think this implementation, and remember that a hover does not play well on mobile devices or tables, I think we should wait on this and not merge this code, what do you guys think?.

**Comment by bryanboza** [comment]
Here we need wait to take a final decision...

**Comment by wezell** [comment]
Do not merge this one.  Instead, I think we need to keep menus open so a user can easily cross-navigate portlets (like my commit did as a POC)

**Comment by fishsmith** [comment]
My vote is for opening on click and only loading a new page when specific
tool is selected.

My $0.02
- I don't like keeping them open
- I don't like defaulting to the first tool either

Here is how this small start up is handing their nav UI. You might have
heard of them, they seem to be getting some traction in the marketing place.

http://recordit.co/GqzbGFp1Vx

**Comment by dotcmsCodeReview** [comment]
So, what do you show when a user logs in?  I am talking for 4.0 launch, not
what we want ultimately.

**Comment by fishsmith** [comment]
I'm fine with showing them the first tool under the first menu item (how it works now). I just meant when they click on another top level menu item, it should not navigate to the first tool but rather just open the menu and close the current one (with some highlight showing your still on that menu). Watch the video from 0:12 - 0:25
