### ISSUE TITLE
Use a circuit breaker for $json.fetch and url reading

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11035]
We need a circuit breaker library to prevent thread blocking when a remote endpoint goes down.  This means that if a $json.fetch(url) is down after say 5 tries, the system will give up for 30sec and stop trying to use it, allowing other threads to execute.  After 30s it will try again.

An additional benefit is that if you do a url forward in a vanity url, then it will proxy the request to the new url rather than doing a redirect.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15744

**Comment by wezell** [comment]
Notes for @documentation

1. This changes the behavior of Vanity URLs when you have a "forward" vanityurl that includes a fully qualified path, e.g. `forward -- https://google.com`.  What happened in <5.1 is that this would automatically become a 302 redirect.  Now, if you include a `//hostname` in your forward url, the system will try to transparently proxy the request to the forwarded url without changing the visitors url.  Obviously the old behavior is still available and controllable if you change your vanity url to a redirect.

2. All calls to the velocitytools $import and $json use this new functionality and will circuit break.  Default timeout is still 15 seconds and can be adjusted on a per call basis.

3. When circuitbreaking a url, it will use the url + the timeout sent to the circuitbreaker as the key, meaning if you use the same url with 5 different timeouts across your site, each one of those will trip separate circuitbreakers.  To insure that an endpoint circuit is broken sitewide, you should make sure that your timeout values are all the same (this will happen by default if you don't explicitly set a timeout).

**Comment by fabrizzio-dotCMS** [comment]
Overall this looks good. I created a Widget that uses the Json View Tool. 
then I called it from within a PageAsset  
I used this https://httpstat.us/ to simulate timeout 
And this one https://my-json-server.typicode.com/typicode/demo
To test the good json response  
Both scenarios work just fine. 
My only observation here is that you can actually configure the CircuitBraker per call basis as it is stated in the Notes above. But once the Breaker is wrapped within the JSONTool this capability is lost. 
This because the Class constructor grabs an individual property 'URL_CONNECTION_TIMEOUT' from the .properties which will be applied to all the urls proxying the tool.

**Comment by wezell** [comment]
Glad it worked - there is an overloaded $json.fetch that allows you to specify a specific timeout:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/JSONTool.java#L100
