### ISSUE TITLE
Multi container problems with the new starter 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#11049]
We are having some problems wen you go to demos --> Multi container, this is trying to use a view tool in the vtl file and this is showing an erorr on logs 

## Expected Behavior
We should be able to navigate in the system without errors... 

## Current Behavior
We are having this problems and also we have the same error creating the past time machine snapshot. 

ST: https://gist.github.com/bryanboza/76a9a4b9f3b3e542c2ebd347fc3d5ee0

## Steps to Reproduce (for bugs)
1. From FE navigate to demos --> multi-containers 
2. Check the dotcms.log

## Your Environment
Tested on master-4.0 // H2 // FF

**Comment by jcastro-dotcms** [comment]
This is not a code issue, but a data issue in the starter probably caused by the deletion of legacy files.

The contentlet causing problems is associated to the Identifier ``9f303322-a908-4df0-8194-e1323f11b008``, and can be reached from the UI. It is referencing a file with the Identifier ``2896c216-9d15-49b0-9ff9-6bfff113cc4a``, which does not exist anymore. The steps to fix this problem are the following:

* Log into the Starter Site.
* Go to Content > Search. In the ``Type`` drop-down, select "Event".
* Click the contentlet with the title "dotCMS Online Training Session (w/ Image)".
* Scroll down to the ``File`` field. This is the one referencing an Identifier that does not exist. Just go ahead and select any valid file in the system, and click "Save / Publish".
* Go back to the same contentlet, scroll down to the same ``File`` field, and click the "Remove" button in order to leave this field blank. Click "Save / Publish".
* Go back to the same contentlet one last time, go to the ``History`` tab and leave only the latest contentlet version.
