### ISSUE TITLE
"Server" should be changed to "Endpoint" when adding a new endpoint for Push Publishing

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11074]
Tested on latest dotCMS 4.0 build

We forgot to completely replace the old "server" terminology from the add a new endpoint popup light box.

![endpoint - not server](https://cloud.githubusercontent.com/assets/1569167/24051664/7c7d5ce0-0af8-11e7-8d15-5a7c8592b000.png)

Since the endpoint can be either static aws or a dynamic server, then "server" is no longer the correct term here.

**Comment by john-thomas-dotcms** [comment]
Yes, this was intentionally left for 4.0.0, since it would have required some code changes (as opposed to just language props changes), and we didn't want to make code changes so close to the release.

The issue is that the same popup window code is used for both the popup to add a new Send To Environment and the popup to add a new Receive From Server.  So in addition to a separate language prop string being needed, the code to generate the popups also needs to identify which type of server is being added and display the appropriate string.

Reference:

* https://github.com/dotCMS/core/blob/e9903ec6bdaacb090e2ee495fa3a4c3ae44bb643/dotCMS/src/main/webapp/html/portlet/ext/cmsconfig/remotePublishing.jsp#L711
* https://github.com/dotCMS/core/blob/e9903ec6bdaacb090e2ee495fa3a4c3ae44bb643/dotCMS/src/main/webapp/html/portlet/ext/cmsconfig/remotePublishing.jsp#L733

(Separation of strings for both these functions are needed).

**Comment by DeanGonzalez** [comment]
Good cautionary warning there John - I guess we need to make this popup window smarter then so that it knows whether you have click on send two or receive from and message properly.

**Comment by bryanboza** [comment]
Fixed, tested in the last master and now we have this improvements
