### ISSUE TITLE
Gradle, IDE, submodules and immutables cleanup 

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#11120]
We need to fix 4.1 and forward as it is difficult to build and setup the development environment right now. 

We have created Submodules for License and Enterprise.

- [x] Make the deploy.gradle file build EE from the submodule and upload with the correct name. IN addition to this it can add the Enterprise folder, the submodule folder in git/core to the core so it stays in sync 
- [x] In the deploy.gradle we need to do the same for license as EE
- [x] We need a gradle task to compile the imutables to a generated folder that is used by both the IDE and the build process.  
- [x] In IDEA task we need to add the sources for EE, License and Generated Imutables can be done with this command sourceSets.main.java.srcDir new File(buildDir, "generated-src/java")
- [x] We need 2 tasks for setting up the environment after clone. setUpDevFull AND setUpDev. The full will setup EE.  It can run git submodule init and git submodule update and will also generate the imutables folder. We can have this folder in Github BUT souuld add to the ignore everything in it. 

- [x] Take care of Eclipse (starting in neon) and IntelliJ

**Comment by nollymar** [comment]
In order to automate the upload artifact process, new tasks were implemented in deploy.gradle:
* uploadEnterprise: generates and uploads ee_*.jar
* uploadLicense: generates and uploads ee_lic_*.jar
* upload Dotcms: generates and uploads dotcms_*.jar
* uploadAntTooling: uploads ant-tooling*.jar
* uploadStarter: uploads starter*.zip

Tasks above can be used to upload snapshot and release versions

PR Core: https://github.com/dotCMS/core/pull/11241
PR Enterprise: https://github.com/dotCMS/enterprise-2.x/pull/456/files
PR License: https://github.com/dotCMS/license/pull/46

**Comment by nollymar** [comment]
Now, the dotCMS project can be configured easily in Eclipse following these steps: https://docs.google.com/document/d/1GAwk3fgSDVZXF7hdKQnHmoO_8Gklyo1FuPrsa93EMrA/edit?pli=1#

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/developing-from-source

**Comment by DeanGonzalez** [comment]
I also did QA on this with Nolly's help, all working fine.
