### ISSUE TITLE
CSV importer/exporter - needs touchup for 4.1

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11392]
- [] The current CSV content importer / exporter imports columns by field name.  In 4.1 we have removed the getFieldByName method.  We need the CSV importer/exporter to rely on the Field Variables.

This needs to happen on both the CSV example download, the CSV preview and finally the upload

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/11410

**Comment by bryanboza** [comment]
Now the import/export is working as expected....

Here we have another improvement: 

- [ ] When you are trying to import some content, before import we have the option to see a type of preview, **but this is just a preview**,  if you have some error here, we just should show the Error on summary (UI) because you are not doing any action yet, but we are showing all the errors on log 
Here a log example: https://gist.github.com/bryanboza/90c3c4c1808dd70d5233162163040493
FYI: this log is just in preview mode.... If you import we have the same errors again...

**Comment by jgambarios** [comment]
@bryanboza This is how has been always worked, please create a different ticket for this improvement.

**Comment by bryanboza** [comment]
Fixed, some new improvement here #11448
