### ISSUE TITLE
visitor.referer is not set properly

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11494]
placeholder

**Comment by jgambarios** [comment]
Related or maybe a dup of https://github.com/dotCMS/core/issues/11473

**Comment by jcastro-dotcms** [comment]
This issue is not reproducible with the latest code anymore. This is the test scenario:

1. Kick off two dotCMS instances (one running on http://localhost:8080 and the other on http://localhost:8081).
2. In instance # 1 (http://localhost:8080), create a simple page: ``/page-1``. Add a widget with the following code:
```
Visitor's IP: $visitor.ipAddress<br/>
Visitor's Referrer: $visitor.referrer
```
3.  In instance # 2 (http://localhost:8081), create a simple page: ``/page-2``. Add a widget with a link that points to the page created in instance # 1:
```
<a href="http://localhost:8080/page-1">Go to the other instance.</a>
```
Now, follow these steps:

* Open up another browser (or an incognito window) and go to http://localhost:8081/page-2
* Click the ``Go to the other instance.`` link.
* In the page, you should see something like this:
```
Visitor's IP: /0:0:0:0:0:0:0:1
Visitor's Referrer: http://localhost:8081/page-2
```

**Comment by wezell** [comment]
Guys, did we make a code change anywhere? this happens specifically when referred from google.com - chrome must be doing some pre-fetching or something.

**Comment by jcastro-dotcms** [comment]
Here's a video showing my local HTTPS setup and the test I did using our Demo Site. @wezell @jgambarios @bryanboza please take a look at it and let me know of any other test you'd like to do.

![issue-git-11494](https://cloud.githubusercontent.com/assets/8779585/25913617/a2759e58-3578-11e7-99eb-0d82be8fa2ae.gif)
