### ISSUE TITLE
non-Macros rendering differently in 4.1

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11516]
This is critical path rendering the below code shows differently in 4.0 and 4.1.  This is @fishsmith issue with a css #color not rendering on flowdock.

## Try this code
```
Here is my color #efefefe ("asdasd")
<hr>

Here is my color #asaaaaaaASÅ (asdasd)
<hr>

And my second #numberTEst

<hr>
#testMacro("One Arg")

<hr>
#testMacro("TWO Args" "asdasdsad")

<hr>
#testMacro2()
```

**Comment by wezell** [comment]
We have made a LOT of changes in Velocity.  This broke when we applied the memory fixes from Velocity 2.0

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/11522

**Comment by jgambarios** [comment]
@bryanboza we need to test please defining a macro inline in a template

**Comment by oswaldogallango** [comment]
Hi @wezell, I did different tests adding macros directly and with a dotParse on the template, also with a generic content and with a simple widget. It seems that everything is working fine. The only thing I noticed is that if we define a macro on a generic content, on "edit mode" is not evaluating the macro (I mean, the velocity code) and it's showing the code like this:

<img width="1149" alt="screen shot 2017-05-10 at 3 12 21 pm" src="https://cloud.githubusercontent.com/assets/1569280/25916584/26e0fa06-3593-11e7-87b4-7dfaaba7ab67.png">

On preview mode, live mode and frontend work fine. But, I'm not sure if this should be reported as an error or if it's ok in "Edit mode" for general contents (not widgets) that the velocity code not is evaluated?

**Comment by wezell** [comment]
And this worked differently in 4.0?   If so, I would say we need to get this in the pipeline.

**Comment by oswaldogallango** [comment]
@wezell well on 4.0 works the same way as in 4.1. 
<img width="1153" alt="screen shot 2017-05-10 at 4 45 04 pm" src="https://cloud.githubusercontent.com/assets/1569280/25920459/0fc1599e-35a0-11e7-97b1-9c1a38165184.png">

Because of that, I'm not sure if this should be reported as a bug that came from the previous version or if it's ok to have that behavior in edit mode, since 4.0. 

However, on 3.7.0 that doesn't happen

<img width="1145" alt="screen shot 2017-05-10 at 4 41 23 pm" src="https://cloud.githubusercontent.com/assets/1569280/25920314/8cae45b2-359f-11e7-9c7b-2c44f860525b.png">

**Comment by bryanboza** [comment]
We need resolve this macros on edit mode...

**Comment by bryanboza** [comment]
Fixed, as talk with @wezell that's the expected....
