### ISSUE TITLE
User email address validation needs to be RFC 5322 compliant

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#11565]
We are throwing a com.liferay.portal.UserEmailAddressException when trying to create a user whose email address contains an apostrophe in the name portion of the address. It looks like this is probably in https://github.com/dotCMS/core/blob/3.7.1/src/com/liferay/util/Validator.java#L224-L234. The character set we allow there for email address is more restrictive than the full charset allowed for email addresses per https://tools.ietf.org/html/rfc5322. By fixing this and allowing more chars, we also need to be mindful of SQL injection (and other concerns) and handle the string with care.

**Comment by chrismccracken** [comment]
Re: https://my.dotcms.com/tickets/detail.dot?id=13279c90-a53a-4547-8e33-c41ca927328e

**Comment by chrismccracken** [comment]
From https://en.wikipedia.org/wiki/Email_address:
> The local-part of the email address may use any of these ASCII characters:
> 
> - uppercase and lowercase Latin letters A to Z and a to z;
> - digits 0 to 9;
> - special characters !#$%&'*+-/=?^_`{|}~;
> - dot ., provided that it is not the first or last character unless quoted, and provided also that it does not appear consecutively unless quoted (e.g. John..Doe@example.com is not allowed but "John..Doe"@example.com is allowed);
> - space and "(),:;<>@[\] characters are allowed with restrictions (they are only allowed inside a quoted string, as described in the paragraph below, and in addition, a backslash or double-quote must be preceded by a backslash);
> - comments are allowed with parentheses at either end of the local-part; e.g. john.smith(comment)@example.com and (comment)john.smith@example.com are both equivalent to john.smith@example.com.

**Comment by nollymar** [comment]
@dsilvam , @jgambarios , @jtesser , @wezell , @chrismccracken  


I have created this PR https://github.com/dotCMS/core/pull/11746 to support custom email validation through a regex. 

So far, for the client requirements, this regex meets his needs (even when it is not 100% rfc 5322 compliant): 

```
dotcms.use.regex.to.validate.emails=^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$
```

I think we are covered from xss attacks here: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/liferay/portal/model/UserModel.java#L416-L418

However, I really appreciate you take a look at the changes because it could affect the security of the app (I want to be sure I am not missing something) . This is a critical change for the client.

Thanks!

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/11746

**Comment by oarrietadotcms** [comment]
PR with regex as default and unit test: https://github.com/dotCMS/core/pull/11934

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/password-security-configuration

**Comment by oarrietadotcms** [comment]
PR adding 2 more emails: https://github.com/dotCMS/core/pull/11941

**Comment by DeanGonzalez** [comment]
Documented: https://auth.dotcms.com/docs/latest/user-email-validation-configuration
