### ISSUE TITLE
Enhancement: Navigation Tool should respect Page Fall Thru Property when displaying pages

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#11640]
Tested on latest 4.1 build

Right now the page fall thru property is set to true by default.  However, if you create a page only in the English default language with show on menu, then you set language_id=2, the page disappears from the Navigation Menu.  This is because the navigation tool does not display default language pages when their is no secondary language version of the page - which is counter-intuitive, considering the function of the page fall thru property being set to true by default.

If default language versions of pages are supposed to be be reachable, even if they do not exist in a secondary language, then the navigation tool should respect the property and display the name of the page, as long as it has the "show on menu" property checked in the default language version of the page.

If the page fall thru property is set to false, then the navigation menu should not display default language pages if the page does not exist in the secondary language.

**Comment by bryanboza** [comment]
The problem here is that we are not respecting that property **"DEFAULT_PAGE_TO_DEFAULT_LANGUAGE=true"** because if you turn of that property we should see a 404 error if you try to see other language version of any page, and right now of you turn off this, the system continue working according that other properties 
**DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=false
DEFAULT_WIDGET_TO_DEFAULT_LANGUAGE=true**

At the end, the DEFAULT_PAGE_TO_DEFAULT_LANGUAGE should invalidate this other properties

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/12018

**Comment by DeanGonzalez** [comment]
Passed QA - tested with the property set to both false and true navigation tool respects the fall thru property.
