### ISSUE TITLE
Content Fallback default has changed

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11648]
![screen shot 2017-05-19 at 9 27 02 am](https://cloud.githubusercontent.com/assets/934364/26249702/93cc44a2-3c75-11e7-821c-252410b725ef.png)

**Comment by bryanboza** [comment]
Ok Will, I see the same behavior on both versions, the problem here is that in the 4.0 version you are testing on demo, and in the 4.0 starter the index page have a version in Spanish without content. That's why you see a blank page... In the last starter we deleted that page. 
IMG: https://screencast.com/t/V1tpNDYRUFWf

**Comment by wezell** [comment]
@bryanboza I don't think that is it.  Here is from 3.7

![screen shot 2017-05-19 at 11 35 45 am](https://cloud.githubusercontent.com/assets/934364/26255453/a27d466a-3c87-11e7-9c33-e3eac42ccf8d.png)

**Comment by wezell** [comment]
This is 4.1 with the fix
----
![screen shot 2017-05-19 at 11 39 48 am](https://cloud.githubusercontent.com/assets/934364/26255534/eb635540-3c87-11e7-9a6a-799fee5de551.png)

**Comment by bryanboza** [comment]
Fixed, tested all the combinations with the properties and now we have an enhancement here: #11640
