### ISSUE TITLE
Create a light test run that uses a primed instance

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11673]
30+min is being taken up doing the git clone and ./gradle dependencies downloads.  We need a base AWS test instance that has all this heavy stuff already downloaded so we don't have our tests waiting for the environment to be set up.

Faster Testing feedback loops = better testing.

**Comment by agomez-dotcms** [comment]
Hi Guys,

Today, following tasks were done:
1. AWS/EC2 AMI was modified in order to have gradle dependencies pre-downloaded. This will improve execution time because dependencies won't need to be downloaded on every build
2. Date -based logging was added for every command on build scripts. This will let us analyze/detect/determine bottle-necks and further performance improvements that may be done in future.

On the other hand, it was analyzed/determined that GIT clone is not taking a significant portion of the build's execution time (less than 1 minute). So, no changes were done in regards to cloning code from GIT.

For now, I am leaving this ticket "In Progress" just case we determine further paths for improving the performance of the build (while I continue addressing the [Enhancements to Testing Infrastructure](https://github.com/dotCMS/core/issues/11196) epic).

Thanks,
Anibal
