### ISSUE TITLE
Fix ContentTypeResourceTest

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11735]
A ContentTypeResourceTest was written but has never been hooked up.  It was also intended to provide examples of how to use the endpoint.

It now only tests the create method. We need need to complete it to test the other methods and  add it to our test runner.

**Comment by dsilvam** [comment]
@wezell @agomez-dotcms worked on this already: https://github.com/dotCMS/core/blob/master/dotCMS/src/integration-test/java/com/dotcms/rest/api/v1/contenttype/ContentTypeResourceTest.java#L32

I guess it should had been in the other class instead of creating a new one. Now we have two ContentTypeResourceTest under different paths

**Comment by dsilvam** [comment]
PR for 4.1: https://github.com/dotCMS/core/pull/11738

**Comment by dsilvam** [comment]
PR to master for setting host: https://github.com/dotCMS/core/pull/11771
