### ISSUE TITLE
Create KeyValueAPI

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11924]
have a 
- fromContentlet()
- get(key, User, respectFrontEnd) List<>
- get(key, ContentType, User, respectFrontEnd)) List<>
- get(key, Language, ContentType, User, respectFrontEnd)) KeyValue

**Comment by jdotcms** [comment]
fromContentlet() --- DONE
get(key, User, respectFrontEnd) List<> -- DONE
get(key, ContentType, User, respectFrontEnd)) List<> -- DONE
get(key, Language, ContentType, User, respectFrontEnd)) KeyValue -- DONE
In addition to:
get(final String key, final long languageId, final ContentType contentType, final User user,
                    final boolean respectFrontendRoles)

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12082

**Comment by jdotcms** [comment]
FYI: this is the way that the priority in the languages works:

1) the Language.properties files (with the i18n resolution)
2) the Properties added on the Languages portlet (similar to the #1 since it is just a merge to the respective Language.properties)
3) the New KeyValue content Languagevariable (by the resolution by lang id+ country, lang id and default lang [if DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=true])

**Comment by bryanboza** [comment]
Fixed, some improvements opened in new cards
