### ISSUE TITLE
Upgrade to latest dojo 1.8 - was: Dropdowns and Filtering Selects broken on Windows 10

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12007]
It seems that on newer windows laptops running windows 10 and Chrome that dojo dropdown and filtering selectors are broken and the user is unable to make a selection.

It seems that this affects only windows 10 computers that have a touchscreen (which is every single one), but the bug basically breaks all ways to select - mouse, touchpad and touchscreen.

This was reproducible on dotcms v3 and v4

I can confirm that upgrading to dojo release-1.8.14 fixes the issue

This is the issue on dojo's issue tracker:

https://bugs.dojotoolkit.org/ticket/13048

**Comment by gabbydotCMS** [comment]
Reported by: https://my.dotcms.com/tickets/detail.dot?id=acef6240-cb17-412f-8040-418af9f440f2 and https://my.dotcms.com/tickets/detail.dot?id=dbcf84e9-1250-4d87-bb87-c920c6b9ea89

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/12027

**Comment by wezell** [comment]
We need to back this change out. We have a much simpler and safer fix, I believe.

I think all we need to do is set this to false:

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/webapp/html/js/dojo/custom-build/dojo/touch.js#L7

**Comment by agomez-dotcms** [comment]
Hi Guys,

The fix for this issue on a client was approached, by using solution suggested by @wezell on comment above, via a hotfix, which worked successfully on our tests (against Windows 10, IE10 and Ipad) and client still is on his way to testing it.

The fix for this issue may also be found on hot-fix at https://github.com/dotCMS/support/tree/master/hotfixes/hotfix-GIT-12007_v3.7.0. Also, the original Support ticket may be accessed at https://my.dotcms.com/tickets/detail.dot?id=dbcf84e9-1250-4d87-bb87-c920c6b9ea89.

Thanks,
Anibal

**Comment by dsilvam** [comment]
Dojo upgrade backed out: https://github.com/dotCMS/core/pull/12147

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/12149

**Comment by dsilvam** [comment]
@bryanboza this we can re-tested now

**Comment by bryanboza** [comment]
Tested in the iPad with the last master, and now works as expected, just need confirm in Windows10 touch PC, @wezell can you help us with this test?
