### ISSUE TITLE
Problems adding forms to a content page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#12019]
We are having some problems trying to add new forms to a content page and we are unable to add the form 

## Expected Behavior
We should be able to add forms to the pages without problems 

## Current Behavior
We are having an error with the "**PermissionBitAPIImpl**" and we are unable to add the form  
ST: https://gist.github.com/bryanboza/a300556b7c33305a0aac864e74e1c500

## Steps to Reproduce (for bugs)
1. Login 
2. Add a new form 
3. Add a new page and try to add the form to the page 

## Your Environment
Tested on master // Postgres

**Comment by wezell** [comment]
actually, the above commit will not work.  Thinking about this is the same issue we had with the categoryAjax (I think) method - we can't use the proxy here because the PermissionProxy needs the right parent permissible and we are not looking that up.  We need the real "Inode"

I guess we can check the shorty and if it is a structure, just load the real one.

**Comment by jgambarios** [comment]
Related to: https://github.com/dotCMS/core/issues/12285

**Comment by jgambarios** [comment]
PR: 
https://github.com/dotCMS/core/pull/12284
https://github.com/dotCMS/enterprise-2.x/pull/497

**Comment by bryanboza** [comment]
We still having problems in #12312

**Comment by jgambarios** [comment]
This ticket is done but QA is waiting of the fixes in https://github.com/dotCMS/core/issues/12312
