### ISSUE TITLE
Cluster test vanity urls and language variables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12026]
Make sure cluster invalidations are happening appropriately.   You will need to test using the $text.get("languuageVariable") velocity methods

**Comment by oswaldogallango** [comment]
The Language Variables are working fine. If you add some language variable in a server the other one can see it, if you publish or unpublish changes are also reflected.

The only issue I found was with Vanity URLs. When you add multiples vanities on a server, sometimes throw a 404 for some of those vanities in the same server where they were added, but the second server displayed without issues.  This issue was reported here https://github.com/dotCMS/core/issues/12258

**Comment by bryanboza** [comment]
Fixed, tested with a cluster in the last master // MySQL
