### ISSUE TITLE
Edit/Preview mode: Left menu is completely broken if language in session is French

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#12092]
Once we log in to the backend in French and then attempt to look a page in Edit or Preview mode, the entire left menu on these views is broken. 

<img width="1657" alt="screen shot 2017-07-11 at 1 54 19 pm" src="https://user-images.githubusercontent.com/1717110/28087781-e035a3fc-6640-11e7-839c-0c15c2c119bc.png">
<img width="1661" alt="screen shot 2017-07-11 at 1 54 08 pm" src="https://user-images.githubusercontent.com/1717110/28087780-e0111c94-6640-11e7-816b-5918b8b437aa.png">
The error comes from the preview_left_menu_page_as_content.vtl file and missing ways to escape Language variables that could contain single quotes on them. 

## Expected Behavior
Left Menu on Edit/Preview mode should work fine regardless of the language in session.

## Possible Solution
Escape for Javascript every occurrence of $languagewebapi or any other Velocity code that pulls Language variables.

## Known Workarounds
Logout and then log back in with a different Language.

## Steps to Reproduce (for bugs)

1. Go to demo.dotcms.com/dotAdmin site.
2. On the language dropdown, select French as language. This will switch the backend locale to French.
3. Go to site browser and then open a page in Edit Mode. 

## Context
Reproduced on a customer running 3.7.1 using French - Canada for backend session https://my.dotcms.com/tickets/detail.dot?id=7a573cb8-a767-4914-b8d0-629c3daef257 and also on demo site through a GTM session.

## Your Environment

* dotCMS 3.7.1, 4.1.1.
* Any OS/Browser.
* Any Application server.
* Java 8u121
* Any DB.

**Comment by john-thomas-dotcms** [comment]
This is a bigger issue, in that the way we escape language variables varies in different places within the code.  This makes it difficult to manage the language strings/translations, since some characters (like single quotes) work in some places in code but not others - and there's no way to tell what will work where when you're working on the language files.  Testing the translations is also not always easy, since it's not always clear where the strings are being used and/or it may be difficult to reproduce the conditions which make the messages display so the translations can be tested.

So what we really need is some consistency standards on how we escape the language strings, and then once we have those we need to go through the translations and verify that the strings will display properly when escaped according to those standards.

Needless to say, this would be a big job :)   But without this, we're likely to periodically have these kinds of issues where the translations end up using strings that cause problems in places.

**Comment by joseorsini** [comment]
Reproduced in 4.2.2 using Firefox Quantum. After switching backend session language to French, Edit/Preview mode is broken.

<img width="1490" alt="screen shot 2017-11-20 at 9 42 52 am" src="https://user-images.githubusercontent.com/1717110/33026904-3d2fdc96-cdd7-11e7-8ff2-67535ab578e3.png">

**Comment by mattyarbrough** [comment]
This is actually broken worse in 5, and the Content Search page doesn't render at all.

**Comment by wezell** [comment]
@john-thomas-dotcms 

We need to insure that the keys are translated - there are a number of cases where we are missing translations.  Let's discuss.

**Comment by mattyarbrough** [comment]
This is still an issue in 5.0.3.

**Comment by mattyarbrough** [comment]
Note that this is still present in 5.1.6
