### ISSUE TITLE
Class conflicts with classes in aws-java-sdk-core-1.11.66.jar file

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#12187]
In order to get ES auto discovery working properly on AWS, we had to remove aws-java-sdk-core-1.11.66.jar because the classes in it collided with the classes in the version of this library that we had to use for auto discovery.  The version of this library needed for auto discovery is tied to the version of ES that we use - 1.10.12 is the version needed for AWS ES auto discovery.

1.11.66.jar is the version currently being used for static publishing.

I see two possible solution paths here:
* Explore and test whether static publishing works with the 1.10.12 versions of these library
* Repackage the classes in aws-java-sdk-core-1.11.66.jar so that they do not interfere.  Not sure whether the aws-java-sdk-kms-1.11.66.jar and aws-java-sdk-s3-1.11.66.jar files would be affected or not

**Comment by oarrietadotcms** [comment]
I changed the dependency to use 1.10.12, had to make small modifications because code differences. 

PR core: https://github.com/dotCMS/core/pull/12195
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/488

**Important Note**: when testing with demo site (locally), I saw [this stack trace](https://gist.github.com/oarrietadotcms/9d8b39beef633387ae0c1e22312d263e) a couple of times when the Static Publish is uploading/transferring the files to S3. **_This is not an error_**, it is an info message handled very poorly by the Amazon SDK as they explain here: https://github.com/aws/aws-sdk-java/issues/567 .

**Comment by oarrietadotcms** [comment]
PR p8 ee: https://github.com/dotCMS/enterprise-2.x/pull/489
PR p8 core: https://github.com/dotCMS/core/pull/12197

**Comment by dsilvam** [comment]
@DeanGonzalez please include this known stack in the log in the changelog maybe: https://github.com/dotCMS/core/issues/12187#issuecomment-317541683

**Comment by DeanGonzalez** [comment]
Documented in known issues under the auth changelog and also here: https://auth.dotcms.com/docs/latest/implementing-static-publishing#VerifySite
