### ISSUE TITLE
Research: Add Material Design icons to primeng

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12240]

**Comment by hmoreras** [comment]
Some findings after review the Material Design icons:

- They have two approaches, font-icons  and svg icons. To re-write the the prime-ng icons we need to use the font-icons approach, to overwrite the styles via class name. 
- Regarding accessibility, we will disable the "Aira" in scenarios where the icons are together with text. When the icons are alone, we will include a <span> element and hide it in the DOM, so "Aira" can read that text.
-  We decide not to include SVG, the reason is that we currently are loading font-awesome icons and will include the font-icons from material design. And we don't want to include another approach. 

Some links: 

https://www.filamentgroup.com/lab/bulletproof_icon_fonts.html
https://www.sitepoint.com/tips-accessible-svg/
https://css-tricks.com/icon-fonts-vs-svg/
http://fontawesome.io/accessibility/
