### ISSUE TITLE
Bundle resending options showing in the receiver node

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#12463]
Some options related to re-sending a bundle are also showing in the receiver node.

They don't make sense in this context. Related to: https://github.com/dotCMS/core/issues/11500

![receiver_bundle_detail](https://user-images.githubusercontent.com/1576794/29883121-da951152-8d74-11e7-9ae9-d28984be272c.png)

**Comment by john-thomas-dotcms** [comment]
This happens because the same popup is shown for both the sender and receiver.  It makes it hard to display appropriate text (e.g. "server" vs. "endpoint") on the popup as well; when I went through all the strings for the 4.0 release all the text in that popup was set to "server" instead of "endpoint", but I haven't looked yet to see what changes have been made to the strings since then.

**Comment by wezell** [comment]
![screen shot 2017-09-05 at 11 25 57 am](https://user-images.githubusercontent.com/934364/30119628-591ae9aa-92f4-11e7-9bee-0ebbfa7b42c3.png)

**Comment by dsilvam** [comment]
Fixe included here: https://github.com/dotCMS/core/pull/12530

**Comment by bryanboza** [comment]
Fixed,  new improvements reported here: #12554
