### ISSUE TITLE
Back button not updating the url

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#12728]
As as stakeholder I want to users be able to use the browser back button

## Expected Behavior
When the user click back button browser should go to previous page and url in the address bar should update.

## Current Behavior
When user click back button, browser go to previous page BUT url in address bar it's not updated.

## Possible Solution
Not sure but, good to know:
1. https://developer.mozilla.org/en-US/docs/Web/API/History_API
2. There are [some](https://stackoverflow.com/questions/44437117/angular2-back-button-issue-url-not-changing-angular-universal) [people](https://github.com/angular/angular/issues/12272) with the same issues.

## Known Workarounds
Click twice in the back button.

## Steps to Reproduce (for bugs)

1. Login
2. Start navigating for 3-4 portlets (only iframes)
3. Click back button
4. See how the page went back but the url remains the same

**Comment by hmoreras** [comment]
Initial Findings: 

- This happens on legacy portlets that uses the iframe approach. When the 'src' attribute is changed in an iframe the browser by default add one entry to the history, so that is causing the wrong behavior between the URL & Routing.   

- Possible fix, use 'ngIf' directive to remove the element from the DOM while the src parameter changes.

**Comment by bryanboza** [comment]
Fixed, tested in the last master and multiple browsers and now this is working fine
