### ISSUE TITLE
Migrate REST example to core code base

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#12737]
We need to migrate this OSGI rest plugin example https://github.com/wezell/com.dotcms.rest.page into our core code base.

**Comment by wezell** [comment]
No, we need to include this into the core - not as a plugin.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/12832

**Comment by bryanboza** [comment]
We have problems when you try to get this information with some valid credentials but with a limited user, this because we are getting a 400 error (bad request), we need get 401 (Unauthorized) in this case. 
To reproduce try with:  Chris@dotcms.com // chris 

**FYI: In you send the request without credentials or with an invalid user/pass, we have the correct error, the problems is just with valid credentials but limited user.**

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12911

**Comment by bryanboza** [comment]
We still having problems when you try with render, with the last fix we have the 401 but just trying with json, if you try with render we have a 500 error

**Comment by oswaldogallango** [comment]
P.R https://github.com/dotCMS/core/pull/12923

**Comment by bryanboza** [comment]
Fixed, tested with postman in the last master and now the responde code looks good.
