### ISSUE TITLE
.vtls are readable via url

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#12855]
Currently, it is possible to read .vtl files from their urls. This can expose scripts and implementation details which might otherwise want to be kept secret.

**Comment by jgambarios** [comment]
PR:
https://github.com/dotCMS/core/pull/12858 (master)
https://github.com/dotCMS/core/pull/12857 (4.2)

**Comment by bryanboza** [comment]
Fixed, now we are unable to read this files via URL

**Comment by john-thomas-dotcms** [comment]
So a note here: Whenever you view a file in the back-end, we give a link to the file that allows you to open the file directly.  This link is now broken for VTL files, since when you follow it you're accessing the VTL file directly (which we no longer allow).  Now when I try to access that link, I get redirected to the back-end (to my default Workflow Tasks screen).

I think this is a minor issue, since for a VTL file you can see the contents of the VTL file in an edit window in the file properties screen; but I do think it's an issue.  Ideally we should remove the link for files (like VTL files) which you can't access directly.

### Example (in the starter site on the 10/13 master)

Here's the link on the file edit screen:

![image](https://user-images.githubusercontent.com/13456955/31587144-079563c4-b191-11e7-912a-789813d2ae7e.png)
