### ISSUE TITLE
Sort order of fields getting corrupted

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#13052]
Related to changes in #12164

**Comment by dsilvam** [comment]
https://github.com/dotCMS/core/pull/13054

**Comment by john-thomas-dotcms** [comment]
Note: One of the symptoms of this issue is that field var names in Binary fields may be renamed to `binary47` or something similar, and all Binary fields in the content type will show the same field var name.  The fix is to install 4.2.2 and then manually reorder the fields - when you do this the field var names of the Binary fields will be restored to appropriate values.
