### ISSUE TITLE
Check what happen with rules so we can update angular to 5

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#13159]
We need to make sure rules it's completely independent so we can update angular without any problems.

https://github.com/dotCMS/dotcms-rules-engine

Make sure we pack this into js files, right now we are sending .ts files to npm

**Comment by hmoreras** [comment]
I tried to update to angular 5.1.0, that was released December 6. but there are some bugs when allowing .js files in the code ` "allowJs": true` in the `tsconfig.json`. Reference https://github.com/angular/angular/issues/19757.

We agree in wait a few weeks before try this update again, since currently do not represent a priority.
