### ISSUE TITLE
Content type with multiple category fields populates REST API improperly, crashes Query Tool

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#13367]
Customer created a custom content type which has two different category fields (each one uses its own parent category). This works fine most of the time, for example when using those fields in velocity.

## Expected Behavior
REST calls should populate both category fields separately with their distinct content

## Current Behavior
The dotCMS Content REST API will show both fields, but only show the correct categories for one of those fields. In the JSON response, the categories for the other category field are the same as from the first field. So it is not possible to get the complete/correct output of both fields.

In addition, when using the Query Tool on this content type in the admin console the console crashes, with an error of 

Caused by: java.lang.NullPointerException 
at com.dotmarketing.portlets.categories.business.CategoryAPIImpl.isParent(CategoryAPIImpl.java:659) ~[dotcms_4.2.0_999999.jar:?]

## Your Environment

* dotCMS version used: 4.2.0

**Comment by cfalzone** [comment]
I noticed this is still an issue in the latest dotCMS.

If you have 2 category fields on a contenttype the rest api returns the contents of both category fields in both category fields.  

For instance a blog post has topics and tags field, it has a topic of "Web Development" and tags like "Web Development, Programming"
The list returned by the api looks like "Web Development, Web Development, Programming"

Further the list only returns the names not the variables so it is completely useless if you want then use the API to say update some content.  You pull the content to update it, but then cannot save it because there is no current way to translate Name to Key for the category.  There is no Category Rest endpoint.  And, in the above example, two different categories can have the same name, so is it the topic "Web Development" or the tag "Web Development"?

The implementation makes it very hard to use the API and is preventing us from doing more with the REST API.
