### ISSUE TITLE
Prevent Relationships with same relationTypeValue

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#14296]
[relationTypeValue is built here](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/structure/action/EditRelationshipAction.java#L166-L167).

Our relationship logic is heavily based on the relationTypeValue, for example our link between the relationship table and the tree table is based on relationTypeValue(not by inode). 
```
Table: relationship, Column: relation_type_value -> Table: tree, Column: relation_type
```
## Expected Behavior

We shouldn't allow to create a Relationship with a relationTypeValue already in the DB.

## Current Behavior

1. UI: If the user tries to create a new relationship with same relationTypeValue [we display a UI error](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/structure/action/EditRelationshipAction.java#L183-L188). **Note** that the validation is in the Ajax class and not in the API, but so far we are avoiding same relationTypeValue from UI.
2. Push Publish: If we create the same relationship in both ends(sender and receiver). dotCMS will assign a different UUID for the inode for each environment. Now, if you push a related content the handler [will validate if the relationship exists using the inode](https://github.com/dotCMS/enterprise-2.x/blob/master/src/main/java/com/dotcms/enterprise/publishing/remote/handler/RelationshipHandler.java#L60-L62), not the relationTypeValue. This will create a duplicated relationship, everything except the inode. **This is a problem.**
## Possible Solution

- Validate in API, not in UI. Also use the API instead calling the Factory directly.
- Create a Unique Key and a Foreign Key (upgrade task).

## Known Workarounds

None. Integrity checker doesn't validate this.

## Steps to Reproduce (for bugs)

1. Set up Push Publish environment.
2. Create same relationship in both ends.
3. Relate a content using that relationship just created.
4. Push Publish that content.
5. You will see in Receiver the relationship duplicated.

## Context

Client ticket: https://dotcms.zendesk.com/agent/tickets/95747

## Your Environment

* dotCMS version used: 3.7.1 (master source code looks the same)

**Comment by wezell** [comment]
Nice issue report @oarrietadotcms !

**Comment by dsilvam** [comment]
we need a unique on `relation_type_value` but not the FK

**Comment by oarrietadotcms** [comment]
Just as a heads up from the client, PP is not the only scenario when duplicated relationship could be created: https://dotcms.zendesk.com/agent/tickets/95801

**Comment by bryanboza** [comment]
We need some work here, now we detect is the same relationship, and isn't pushing it. But if you edit the relationship,  then add another content and try to push, we are having an because we are unable to update the relationship. 
To reproduce: 

1. Set up Push Publish environment.
2. Create same relationship in both ends.
3. Relate a content using that relationship just created.
4. Push Publish that content.
5. Make sure the relationship isn't duplicated
6. Edit the relationship on receiver and change the child content type 
7. Add a new content, with the new relationship
8. Push it 

We are having an error, here the stacktrace: https://gist.github.com/bryanboza/41607322e27cf980d7e888ddb81f2b4f

**Comment by bryanboza** [comment]
Tested after the last changes and we have problems once you have been pushed, modify the relationship and then push again. 
Log: https://gist.github.com/bryanboza/55db078af379170c83c0db02e8f47960

**Comment by bryanboza** [comment]
Hey guys @wezell @oarrietadotcms 

After the last fix;

Once you have been created the relationship, we don't have some way to edit the parent or child content types. We only are able to edit the type of relationship and if the parent or child are required. 

Now, if you need to edit the relationship, we need to remove this from the sender side and create a new one, but we don't have a way to push individually relationships, just by dependency. The dependency manager isn't handling the delete of relations. Then If I push it again, on the receiver side I'll have both relationships the old one and the new one. 

The only solution here is, goes manually to the receiver side and delete the relation (which is contradictory to the recommendations) or push remove the entire content type, then delete the relationship from sender side, create the new one and force push again. 

Not sure in this case if this is the expected behavior?

**Comment by wezell** [comment]
I mean, this is the same issue as "I've deleted a relationship on the sender and it is still on the receiver
"how to I push delete a relationship?"
it is a current shortcoming, no?

**Comment by DeanGonzalez** [comment]
When you push a piece of content, relationship dependencies pass with that contentlet and update the relationships on the receiving side, including blowing away "extra" relationships that are not found on the sender.  Forcing administrators to go to the receiver to remove relationships manually is neither expected, nor should it ever be desired behavior.  

We should make a new ticket to add this functionality after we pass this one "as-is"  that is my two cents.

**Comment by bryanboza** [comment]
Fixed, this fix is ok for now. New improvement here #14528

**Comment by DeanGonzalez** [comment]
Documented in changelog and here: https://github.com/dotCMS/core/issues/14296
