### ISSUE TITLE
Sitemap generator does not respect https

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#14336]
When generating a sitemap all links are HTTP://, even if HTTPS Required is selected on a page.  

## Expected Behavior
Generator should respect HTTPS Required, there should also be a config option (since SSL Termination may take place at load balancer) in the Sitemap config to make links HTTP or HTTPS

## Steps to Reproduce (for bugs)
On demo.dotcms.com
1. Add sitemap configuration to configuration plugin
2. Deploy plugins
3. Restart dotcms
4. Check generated sitemaps

## Your Environment
>
* dotCMS version used: 4.3.3 and prior

**Comment by john-thomas-dotcms** [comment]
So the real issue here is that if a page has the "Require HTTPS" option set, then the URL that the sitemap uses for that page is still going to use http, so it won't work (unless maybe there's an nginx server or something else to reroute it properly).

To complicate the potential solutions, the XML sitemap specification does not allow a sitemap to mix both HTTP and HTTPS protocols in the same sitemap (from https://www.sitemaps.org/protocol.html: `Note that this means that all URLs listed in the Sitemap must use the same protocol (http, in this example) and reside on the same host as the Sitemap.`).  So if a single page in the sitemap has "Require HTTPS" selected, then it seems that the entire sitemap needs to use HTTPS instead of HTTP.

The really simple potential fix for this is just to add an option that specifies whether the XML sitemap uses all-HTTP or all-HTTPS.  With an option, the use cases of having a site that is all-HTTPS (e.g. with ngingx enforcing https on all pages) or having any individual pages that require HTTPS could be easily handled without having to try and figure out whether HTTPS or HTTP is needed for the sitemap.

**Comment by wezell** [comment]
https should be the default.
