### ISSUE TITLE
Ask user to save the changes before close the contentlet editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#14472]
We need verify if you have changes and ask before close, in order to avoid a lot of work in a piece of content and close accidentally. This since we are closing the dialog if you click out of it.
SC: https://screencast.com/t/dq2xZcIC

## Possible Solution
1. If you edit a `vtl` file
2. Type something in the code field
3. Hit back in the browser
4. It shows a dialog "Changes you made may not be saved."

Maybe we can use this to do this issue.

## Acceptance Criteria

1. If ANY contentlet field is edited we need to ask the user if want to close the dialog without saving
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by fmontes** [comment]
## Known issuses:

Because we're using what is in place in the jsps to know when a contentlet change:

1. When you edit a `WYSIWYG` field it doesn't show the dialog
2. When you edit a `radio` or `checkbox` doesn't show the dialog

It work the same way in 4.X

**Comment by bryanboza** [comment]
We need fix this know issues since the more used fields for the body of the contents are the WYSIWYG and usually when you edit the content you edit just the body, not the title or any other field. Then, we are losing the changes without asking before.

**Comment by bryanboza** [comment]
Ok, we have some special cases here: 

- [ ] If you edit some content and generate a new version of the content in another language, you can close the dialog without saving and the system isn't asking if you want to save the new version or not. 

- [ ] We are not detecting changes in radio, checkboxes and this kind of fields

- [ ] If you edit a piece of content make some changes in permissions, you can close without save and lost the changes. 

- [ ] If the content type has a tag field, if you edit a piece of content and delete some tag, the system isn't detecting this change and you are able to close without confirmation 

- [ ] If you edit a piece of content, edit some value, but then put again the original, we need be able to close without asking for changes because you have everything as the original, no have changes

**Comment by fmontes** [comment]
Close for 5.0

**Comment by wezell** [comment]
Good for now -other cases will be taken care of when we redesign the edit contentlet screen
