### ISSUE TITLE
Content whose workflow has been reset should index like new content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#14633]
When you reset a contentlets workflow or when a content has workflow_task.status ==null, we need to index that content like a new piece of content, e.g. show it in the first step of all the workflow schemes that it belongs to. Currently, we are not indexing any step or scheme information.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14634

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF

**Comment by jgambarios** [comment]
I found a couple of issues we need to fix here:

1. The Reset Action is not updating the index in order to set the `wfscheme` and `wfstep` properties, it is just modifying the workflow task records.

2. Adding new Workflow Schemes to a Content Type should refresh the index of the Contentlets under that Content Type if they are not in a Workflow Step in order to update the `wfscheme` and `wfstep` properties in the index.

**Comment by wezell** [comment]
Great catches @jgambarios

**Comment by fabrizzio-dotCMS** [comment]
Nor Archiving neither Deleting a workflow causes an index update. 
All Actions from archived WF continue to appear on the Bulk available actions dialog. 
When the workflow is physically removed. The Bulk Actions break from trying to load the information of a step that no longer exists.

Another detail is that whenever a reset takes place. The Index is updated to show the first step of each and every workflow that might be assigned to the contentlet. However, if a reorder operation is executed on the UI. The information initially saved on the index becomes outdated and inaccurate.
Not sure about the functional impact this might have.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/14829

**Comment by bryanboza** [comment]
Fixed, tested with the last changes and now it is working as expected
