### ISSUE TITLE
Need create an upgrade task to create the "Device" content type 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14642]
In 3.x versions, the content type device does not exist, then after you upgrade to master we don't have this content type and this is needed in the new edit mode. 

## Expected Behavior
We need to create a new upgrade task in order to create this content type. 

Otherwise, since the device and persona content types are needed in the new edit mode, maybe we need to change this to system content types and lock this to avoid some user delete one of those.

## Current Behavior
After the upgrade, we don't have this content type, then this is crashing the drop down in the new edit mode.
SC: https://screencast.com/t/zw9xk4csQl

## Steps to Reproduce (for bugs)
1. Upgrade some instance from a 3.x version to master 
2. Login as admin
3. Try to edit some page 

## Your Environment
Tested upgrading an instance on MySQL

**Comment by john-thomas-dotcms** [comment]
I think the problem with creating an update task is that there's a reasonably good chance that at least some customer will already have a content type named "Device", so it would be a challenge to create an update task that didn't fail for some customers.  I'll make sure this is documented in the 4.0 changelogs and/or the doc which covers the device preview mode.

**Comment by john-thomas-dotcms** [comment]
As @wezell said, some simple way to create the devices would also be ideal, and we can include it in the doc.

* A bundle won't work since it's not portable between versions (so we'd need several bundles for several different releases).
* A csv file would be simplest for the content import, but won't create the content type.
* Will, when you say we can give the json for this, you mean in terms of a REST call?
