### ISSUE TITLE
Content types base types not pulling right data with/without license

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#14787]
Portlets are being browser cached and thus not making requests to backend unless you refresh (CMD+R, in mac) the browser. 

One case for testing:
1. Start dotCMS as community, go to content types portlet and click "+" button. Forms and Personas base types should *not* show up.
2. Apply enterprise license
3. Go back to content types portlets and still no Forms or Personas when adding new type. 

You need to CMD+R on the browser for the types to show up. (They only show up when enterprise license)

**Comment by dsilvam** [comment]
Related to: https://github.com/dotCMS/core/issues/14787

**Comment by bryanboza** [comment]
Now we can't add forms and Personas content types, but we need to exclude the content types of this types from the content search portlet. This since we can't add content from their portlets, then we need to hide those options in the content search if we don't have a license. 
SC: https://screencast.com/t/bqlERGdi

**Comment by fmontes** [comment]
That's an old issue and is JSP, should be fixed by cody or rex, @wezell?

**Comment by dsilvam** [comment]
@bryanboza no working on this for now after discussing with the team.

**Comment by bryanboza** [comment]
The scope of the card is done, but we have pending changes, moved to #14858
