### ISSUE TITLE
Webdav / Content Editing / Workflows - No workflow actions available for a file (System Workflow) that has been deleted from webdav

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/core#14830]
On dotCMS 5.0 (Nightly Build from 2018-07-03 22:15 - commit 0d7d8da06a), file assets associated to the system workflow that have been deleted via webdav cannot be unarchived or deleted.

This does not happen on dotCMS 4.3.3.

## Expected Behavior
I should be able to unarchive / delete for good files that have been deleted via webdav.

## Current Behavior / How to reproduce
This is how to reproduce on dotCMS 5.0:

https://www.dropbox.com/s/cajrgzqxccclt8k/screencast%20dotcms5.0.mp4?dl=0

This is how it works on dotCMS 4.3.3:

https://www.dropbox.com/s/soh03ft7thnh9pr/screencast%20dotCMS4.3.3.mp4?dl=0

## Your Environment
* dotCMS version used: dotCMS 5.0 (Nightly Build from 2018-07-03 22:15 - commit 0d7d8da06a)
* Browser Name and version: FF
* Operating System and version: Mac
* Application Server and version: tomcat (dotCMS) 
* Java Brand and version: "1.8.0_172"
* Database and version: Postgres
* Application module (if apply): Webdav Finder (Connect to Server)

**Comment by jgambarios** [comment]
This is because webdav does not use workflows at all, so when you archive a File Asset the File Asset is never moved to a Workflow Step where a Delete action is available as a regular archive is executed (like I said not a Workflow Action) and in the Step the archived File Asset is (as it was never moved) there is not a delete action.

A workaround is to add a Delete action to the step where the File Asset is, doing that you will see the Delete action available.

Not saying we can not try to look for another approach, just trying to explain the problem.

**Comment by gabbydotCMS** [comment]
Adding "Delete" and "Unarchive" actions (just drag and drop same actions from "Archived" step) allowed me to delete for good / restore the file.

Thanks !!
