### ISSUE TITLE
Translation improvements 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15109]
We need some translation improvements in the new portlets. 

- [ ] The form adding a new content type: https://screencast.com/t/s0E3soo2o

- [ ] The cancel button of the new content dialog: https://screencast.com/t/kdpRMStdk4a7

- [x] In the page properties dialog: https://screencast.com/t/zAgTZSduIVO

- [ ] Deleting content from a page: https://screencast.com/t/qECakvuI4

## Environment 

Both cases tested in Spanish using the last master

**Comment by john-thomas-dotcms** [comment]
All of these strings are translated and in the strings files, and there are no strings for these in the strings files, so these problems appear to all be code issues not issues with the translation files.

Specifically:
* The `DOT.COMMON.DIALOG.ACCEPT` and `DOT.COMMON.DIALOG.REJECT` strings exist, but should be accessed via lower case (since all keys are case-sensitive), so it's possible the problem is that the code is trying to access them via upper case.
* The `Advanced Properties` string is translated and exists in the strings file, so it appears that the code isn't using the correct key for it.
* All of the strings on the Create Content modal are translated, so again, it appears the code isn't using the correct keys for them.

**Comment by wezell** [comment]
Page Properties Tab name is set by the content type field name.
