### ISSUE TITLE
Unable to add subcategories when parent has a non latin character

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15148]
When I create (sub-)categories with an Umlaut in the name, I will get an error when trying to create a subcategory for it. The moment I try to do that, I also become unable to delete the category containing the Umlaut. It will say that there are still dependencies for the category, even though I failed to create a subcategory.
System: Out of the box linux package from the website & demo.dotcms.com
Happens on both.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/15150

**Comment by nollymar** [comment]
Test results: Success

**Comment by bryanboza** [comment]
Ok after test with the last changes I found this: 

- [ ] We have not fully supported that kind of characters, this because we are removing it to set the key and variable values
<img width="1691" alt="test1" src="https://user-images.githubusercontent.com/2641437/44370614-3bcbdb00-a498-11e8-95e0-ae160add7dd8.png">
I think we need to have the normal behavior like in the single tags.


- [ ] Also we have problems on this portlet with the double byte characters, we allow add this kind of categories, but set a weird value to key and variable
<img width="1678" alt="test2" src="https://user-images.githubusercontent.com/2641437/44370739-bdbc0400-a498-11e8-98d4-eb31233172f5.png">
 
Both cases can cause problems trying to get categories doing queries

**Comment by bryanboza** [comment]
The last cases was moved to a new card #15174
