### ISSUE TITLE
Support searching for Related Content from the Content Search

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#15170]
Implemented here: https://github.com/dotcms/core/issues/14300

We need to make the field that is drawn on the content search screen a filtering select that queries the contentletapi  by a query that accepts either id or title `+contentTypeId:{relatedContentType} +(title:*{searchquery}* identifier:{searchquery}* inode:{searchquery}*`

`+contentType:Youtube +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +(title:*fund* 
 identifier:fund* inode:fund*) +languageId:1 +deleted:false +working:true`

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/15726

**Comment by erickgonzalez** [comment]
Tested Working as it should:
1- Add a new Relationship Field to Content Generic (to News), named **News**
2- Create a new contentlet Content Generic with a Relationship
3- On the Content Search Portlet, select the Content Generic and click over Advanced
4- You should see a search box named **News**, type the id or the title of the related content.

This should list all the contentlets that are related to that contentlet.

**Comment by bryanboza** [comment]
Ok, after test this case now we have the field in the content search to filter, but we need some improvements here: 

- Since this field is a drop-down, we need to add some values or maybe change the control to a simple text field. 

- Also, when you try to filter by id, the system is filtering the results in the drop-down, and not in the content list, maybe in this case we need to do the same filter if you type the id or the value
SC: https://screencast.com/t/uSAJZGhN4

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15806

**Comment by erickgonzalez** [comment]
Instead of the placeholder, a hint below the field was added.

**Comment by bryanboza** [comment]
We have problems changing the content type selection, the first time the filter is loading as expected, but if you change the content type and then go back to the original one, the component isn't loading 
![2019-01-10_16-32-26 1](https://user-images.githubusercontent.com/2641437/51001397-958b7b00-14f5-11e9-8035-b7b570ba4d27.gif)

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15826

**Comment by bryanboza** [comment]
Fixed, tested on the last master code // Oracle // FF

**Comment by DeanGonzalez** [comment]
I think we need to make one more pass at this.  The drop down list does not populate with the latest related titles (just does nothing), and then when you try to type the name of a matching title and select one, then the text is replaced visually with an identifier (which most users will not be able to associate with what they were searching for.  Here is a screencast: https://www.screencast.com/t/FyFOglL1lX - I think we need to display something when the select is clicked (or remove select icon), and not replace text with ID visually, even if that is what we are using to search under the covers.

**Comment by bryanboza** [comment]
After the last changes, now when you type an identifier we try to find consistencies and display the content title in the autocomplete, but when you select the available option we are adding to the filed the name of the content without deleting the identifier, then we are unable to filter the content. 
SC: https://screencast.com/t/F4kaWw0c

We need to clear the identifier from the field, this before to add the title of the selected content.

**Comment by nollymar** [comment]
@bryanboza I got a fix for that issue: https://github.com/dotCMS/core/pull/15880

**Comment by bryanboza** [comment]
We have problems with the filter fields in the content search when you add relationships with the property user searchable, we are not showing a scroll in the left menu. Then we cut some fields
SC: https://screencast.com/t/dPgq8Hvsbd

FYI: Tested with normal fields (text) the same case and works as expected, the problem is just when you add relationship fields

**Comment by DeanGonzalez** [comment]
Working much better now.  Just one small issue.  False search results may be interpreted by the user who types a negative search result text into the related field and clicks the search button - ALL content is returning.  If they don't find and don't click on any related content title, and no valid identifier is found, then we should just clear the text from that field, so that the user does not assume a positive filter match exists: https://www.screencast.com/t/1qI9nGo0kL - I think it just needs that one small tweek to be good for release.

**Comment by nollymar** [comment]
@bryanboza @DeanGonzalez I have fixed both issues here: https://github.com/dotCMS/core/pull/15916

**Comment by nollymar** [comment]
**Important for change log:** With this change https://github.com/dotCMS/core/pull/15957 some improvements were made to the way we index relationships:
- As `-order` fields support aggregations, `_dotraw` fields are not indexed.
- We still need `_dotraw` fields for relationships because this is the only way to support aggregations on these fields

**Comment by bryanboza** [comment]
Fixed, tested on master // postgres // FF

**Comment by bryanboza** [comment]
We need to add a `.trim` here, this because if you try to filter by an identifier and add an empty space at the end, we are showing the complete list of contents

**Comment by nollymar** [comment]
Fixed here https://github.com/dotCMS/core/pull/16037

**Comment by bryanboza** [comment]
Fixed, tested on master and now works as expected
