### ISSUE TITLE
xss in dotcmsV5.0.1

### ISSUE THREAD

**Issue by howchen** [dotCMS/core#15274]
## Current Behavior
dotcms V5.0.1 exists  xss in /html/portlet/ext/contentlet/image_tools/index.jsp   parameter  "fieldName" and "inode" 

## Steps to Reproduce (for bugs)
just visite the url:
`http://website/html/portlet/ext/contentlet/image_tools/index.jsp?fieldName=1%22%20%6f%6e%65%72%72%6f%72%3d%61%6c%65%72%74%28%27%31%27%29%20%3e&inode=
`
![xss](https://user-images.githubusercontent.com/14739143/45419172-15751600-b6b9-11e8-81e9-46721a84ebe8.PNG)

How to fix: https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15278

**Comment by fabrizzio-dotCMS** [comment]
Tried to access several urls under /htm/* 
They all require authentication with the exceptions listed on the interceptor 
The following patterns are allowed (any uri starting with):
/html/js/dojo
/html/images/backgrounds
/html/images/persona

Everything else will enforce user authentication.

Also tried opening an invalid url under /html/* and then login my self out. Once the session is closed. The url autmatically becomes restricted again.

**Comment by fabrizzio-dotCMS** [comment]
As a side note these URLs are case sensitive.
 
so for example 
a URL like: 
http://localhost:8080/Html/portlet/ext/contentlet/image_tools/index.jsp
Will re-deirect you to a blank page 
While this url 
http://localhost:8080/Html/portlet/ext/contentlet/image_tools/index.jsp
will take you to the actual page

Note that the first url says Html while the second url says  html.
I'm passing the ticket since the old instance of dotCMS behaves the same 

https://demo4.dotcms.com/Html/portlet/ext/contentlet/image_tools/index.jsp

**Comment by bryanboza** [comment]
This case will affect, we need be case insensitive in that case and redirect to the correct page

**Comment by wezell** [comment]
@fabrizzio-dotCMS nice catch!

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15321

**Comment by bryanboza** [comment]
Fixed, tested on master and works fine

**Comment by valentijnscholten** [comment]
Please note this issue also affects the 3.x and 4.x versions.

Looking at the commits it looks like the chosen solution is to mandate authentication for these urls. Wouldn't that leave logged in users still vulnerable?

**Comment by mattyarbrough** [comment]
This is still an issue for logged in users.
