### ISSUE TITLE
[Rules Engine] 'Is Not' comparison doesn't check if value exists

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#15330]
Client ticket: https://dotcms.zendesk.com/agent/tickets/96616

Client uses the *Is Not* comparison, but this doesn't check for if it exists or not. Basically, *Is Not* will only block if the session attribute is set and different from the provided value. 

If it's intended, I think it would be beneficial to have "does not exist" as an option for rules conditions.

## Expected Behavior
It is expected that *is not* will block every request with or without this session attribute not set to the value user wants.

## Possible Solution
None. Or maybe Custom OSGI.

## Known Workarounds
None.

## Steps to Reproduce (for bugs)
1. See screenshot.
<img width="2334" alt="screen shot 2018-09-21 at 11 00 45 am" src="https://user-images.githubusercontent.com/8225685/45895148-9d2fe400-bd8d-11e8-875d-13fe5d870f58.png">

## Your Environment
* dotCMS version used: 5.0.1

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/15843

**Comment by dsilvam** [comment]
Passed internal QA: Not setting the session attribute evaluates to _false_ and fires the actionlet

**Comment by bryanboza** [comment]
Tested after the last changes and we don't create the "does not exist", also tested with the "is not" value and we always fire the rules, we are not evaluating this correctly. 
<img width="1671" alt="rules" src="https://user-images.githubusercontent.com/2641437/54702224-11103680-4afc-11e9-838a-0a878eea346c.png">

In this case, we set the session attribute to "test", then the second rule should fire just in case the session attribute is different to "test" and we always fire the rule

**Comment by erickgonzalez** [comment]
The issue here is that regardless the order of the Rules, the one with the **Session Attribute Conditionlet** always run first and so the Session Attribute does not exist the Actionlet is executed.

With this config, the rule with the redirect is not fired:
<img width="1416" alt="Screen Shot 2019-03-27 at 10 49 00 AM" src="https://user-images.githubusercontent.com/5278970/55095558-f438ad80-507d-11e9-9e7a-8ba70a0fba13.png">

With this config the rule is fired:
<img width="1422" alt="Screen Shot 2019-03-27 at 10 50 19 AM" src="https://user-images.githubusercontent.com/5278970/55095660-21855b80-507e-11e9-8e46-c7eecb8dbb8c.png">

In both cases, you need to hit first the homepage so the Session Attribute gets Set and then hit the About-Us page.

Maybe we need an issue that the rules need to be executed in order (that order needs to be discussed could be the order of creation or the order they are shown).

**Comment by bryanboza** [comment]
Fixed for now, a new improvement reported here #16322

**Comment by wezell** [comment]
A few things:
1. We need to test all the Map based lookups, e.g. getAttribute / getHeader / getRequestParam and make sure we follow the same rules
2. Before we check the session for the existence of the value, we need to make sure a session exists. If it does not exists, we should not force the session creation.

**Comment by erickgonzalez** [comment]
Applied same logic to the following conditions:

- RequestHeader
- RequestParameter
- Session Attribute
- RequestAttribute

Now the `IS_NOT` comparison validates that the value exists, if it does not exists the rule will be fired.

Also, removed the session creation if does not exists.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/16338

**Comment by dsilvam** [comment]
Passed Internal QA.

All of the following:
* RequestHeader
* RequestParameter
* Session Attribute
* RequestAttribute

are fire when using the IS_NOT comparison even when the attribute/parameter does not exist

**Comment by bryanboza** [comment]
Fixed, tested on master and works as expected
