### ISSUE TITLE
Add /servlet/ to the DefaultBackEndLoginRequiredWebInterceptor 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15371]
We need to block unauthenticated requests to all non-front end resources
`/html/`
`/c/`
`/servlets/`
`/dotTailLogServlet/`
`/categoriesServlet/`
`/dwr/`
`/DotAjaxDirector`
`/dotScheduledJobs`
`/dotAdmin/c/`
`/categoriesServlet/`
`/JSONTags/`
`/dotAdmin/c/`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15381

**Comment by wezell** [comment]
Might be causing: #15437

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15466

**Comment by jgambarios** [comment]
Second part of the ticket will be done in https://github.com/dotCMS/core/issues/15437 by the FOX team in order to handle properly the `401` response code.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15481

**Comment by bryanboza** [comment]
Ok after testing this changes we have pending some cards: 

- [ ] The `/dotTailLogServlet/` is still open, we need to make sure that in order to use that servlet there is an authenticated user. 
Right now we are showing an NPE error when you hit this URL: 
ST: https://gist.github.com/bryanboza/677bd3379a4c06875b081ba87406c58f

- [ ] We need to improve the error page, showing a type of unauthorized message, and not show a blank page.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15519

**Comment by bryanboza** [comment]
Fixed, tested on the last master code // Oracle.
