### ISSUE TITLE
We are not respecting the installation order in plugins when you restart 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15494]
When you restart your server or just the framework, we are not respecting the installation order of the plugins and this is affecting when you have direct dependencies on plugins 
E.g:  When you have the servlet plugin, this depends of the service plugin. Then if you restart we are unable to start the plugin. 
 Log: https://gist.github.com/bryanboza/a513d69ed9051911b4efd91b1cf97372

## Expected Behavior
We need to be able to respect this order to avoid conflicts starting the plugins 

## Current Behavior
We are failing to try to start the plugin, this by the dependency of the other ones 

## Steps to Reproduce (for bugs)
1. Start a dotCMS instance 
2. From OSGI portlet upload the simple service plugin 
3. Now upload the servlet one 
4. Restart your server 
5. Make sure the plugins start correctly 

## Your Environment
Tested on release-5.0.3 // Postgres // FF

**Comment by wezell** [comment]
OSGi by design does not care about plugin order.  OSGi has start levels which start fragments before the actual OSGi classes in order to provide all that the classes need.  Basically, if you are relying on a load order for your plugin to work, you are probably doing it wrong and could rewrite the plugin/fragment so that order would not matter
