### ISSUE TITLE
Delete a container.vtl tests

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15570]
Make sure the application behaves properly when a `container.vtl` is deleted.

**Comment by jdotcms** [comment]
Edit mode is align with the delete, however the frontend still caching the version with the container deleted rendered

**Comment by jdotcms** [comment]
With the fixes on: https://github.com/dotCMS/core/pull/15677/files
this is also fixed

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15677

**Comment by fabrizzio-dotCMS** [comment]
I'm marking it as Passed-internal-QA. since it was created to account for a fix on functionality that has been corrected. But. there are new rules to deal with the deletion of a container in general. 
Please refer a: 
https://github.com/dotCMS/core/issues/15974
https://github.com/dotCMS/core/issues/15979

**Comment by bryanboza** [comment]
Fixed, tested on master // Oracle // FF
