### ISSUE TITLE
Velocity errors in the container should not break the render of the page

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#15640]
We need to make sure that when we have velocity parsing issues in our container code the page is able to render and when a parsing velocity error occurs and we are in edit mode an error event should be fired in order to be capture by a component error on the client in order to allow the user to know that the problem is.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15692

**Comment by wezell** [comment]
- Templates
- Pages
- Containers
- dotParse
- Widgets
-Content

**Comment by jdotcms** [comment]
now works on both: edit and preview

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15837

**Comment by bryanboza** [comment]
When you are in edit page and cause an error in a simple widget, and close the edit content modal, we are refreshing the content, but not receiving a WS event in order to show the toast notification until you refresh the page, we need add this notification on this resource 
`/api/v1/containers/56bd55ea-b04b-480d-9e37-5d6f9217dcc3/content/a8e8f9a4-a6ae-404c-9f08-b9bae7a2b857`

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15860

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16100

**Comment by bryanboza** [comment]
Tested after the changes to use path instead id, 
-After fix conflicts, we are having a velocity error and we are not able to render the page. 
- Since we are using path after fix these conflicts we need be able to survive and don't lose the contents of the page, right now we are losing all the contents. 

We need to update the multi-three and also invalidate the cache after change the id 
<img width="1676" alt="velocity" src="https://user-images.githubusercontent.com/2641437/53580948-46031c00-3b42-11e9-9715-5b737ee93348.png">

**Comment by bryanboza** [comment]
Fixed, now we continue rendering the page without problems
