### ISSUE TITLE
Unable to delete a field on a widget

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15664]
If you create a new widget and then try to delete the widget usage field - it fails.  See video:

![no-delete-field.gif](https://images.zenhubusercontent.com/56e187366caf56c9d38d8bc5/501b6eeb-19e4-4a9a-9a62-77fd66c09030)

**Comment by fabrizzio-dotCMS** [comment]
The reason that prevents that field from being deleted is that basically, this is a system field marked as read-only. That condition triggers an exception that returns the following message. 
"You cannot delete a fixed or read only field"

However, even though this is a 'system field' it shows the delete option in the UI because the underlying database field has a false value in the field 'fixed'. 
It would seem logical to me that system fields shouldn't be deleted but if you run this query :
SELECT * FROM field WHERE field_contentlet = 'system_field' AND read_only = 0 AND fixed = 0;
You'll see that there many entries. Apparently, this change was introduced on purpose. 
Previous to 5.x the field 'usage' couldn't be deleted. 

Need to validate the purpose of this logic before taking any further action.
