### ISSUE TITLE
Dynamically generate schema based on content types 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#15727]

**Comment by dsilvam** [comment]
https://github.com/dotCMS/core/pull/15781

**Comment by dsilvam** [comment]
Graphql API leaves under: http://yourhost/graphql.

To test you can use a GraphQL Client like [Insomnia](https://insomnia.rest/download). 

The GraphQL Schema is generated dynamically based on our content types definition. Once it's generated, it is locally cached, however, it will listen to content type / fields modifications in order to invalidate the current schema and re-generate it on the next request. 

The generated GraphQL Schema can be saved to the filesystem, under `dotsecure/graphql/` by setting the property `PRINT_GRAPHQL_SCHEMA` to `true` (`false` by default). Schema name is `schema.graphqls`

**Comment by wezell** [comment]
Remove servlet load on startup in the web.xml

**Comment by dsilvam** [comment]
Create User custom type with: userId, firstName, lastName, email

**Comment by dsilvam** [comment]
https://docs.google.com/document/d/1fRjmPgV_9Vau7wfJU8ReDx1fOLQ2e3PBHcFTdH0mK6M/edit#

**Comment by erickgonzalez** [comment]
After doing some tests I found a couple of enhancements/bugs:

- [ ] size field on binary type change from String to Long

- [ ] isImage field on binary type change from String to Boolean

- [ ] folderSortOrder field on Folder type change from String to Integer

- [ ] When you create a new field (e.g text field) on the content type and assign a default value, it shows you null until you save a new version of the contentlet

- [ ] Fields date, datetime and time showing `null` and `Internal Server Error` when pulling on graphQL (nothing on the logs)

- [ ] If you send a field that does not exist on the interface or type it returns 200 instead of 400 (it shows an error message that the field is undefined)

Please let me know if I need to create a new issue for each one.

**Comment by dsilvam** [comment]
another PR: https://github.com/dotCMS/core/pull/16001

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16007

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/16009

**Comment by bryanboza** [comment]
Fixed, now we are able to print the schema, the URL has been changed to `api/v1/graphql` and everything works as expected
