### ISSUE TITLE
Relationship Field: Add message for required parent-child relationship

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#15777]
As a stakeholder I want to make sure user knows that he can't have a relationship field where both content types are require.

## Steps to reproduce
1. Create a required relationship field in *News* that relates to *YouTube*
2. Create a required relationship field in *YouTube* and click _Existing_ so you can relate to the field you created in step 1

If you check both fields, one is going to be required: true and the other false.

The idea is that the message explains that to the user so that he does not think it is an issue, but we handle it that way because if you let both fields be required you will never be able to create content in both content types.

## Acceptance Criteria
1. Add message that "one of the fields is not require" in the relationship field form
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by wezell** [comment]
Let's enforce this in the api and use the growl alert, no?

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15817

**Comment by fmontes** [comment]
1. Message hidding wat too fast, can't read
2. If remove the field and add it again the msssage doesn't doesnt show.

**Comment by fmontes** [comment]
3. If we create AB relationship and then remove B the relationship field in A is still showing like if it was an exisiting relation.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/15841

**Comment by hmoreras** [comment]
The message regarding this issue is correct however I found this: 

https://www.screencast.com/t/aKV4RwRX

- After create a relationship, open it again to make it required, save, and then try to open, crash the first time. 
- in the listing the text `Required` is not present once I make it required (like is in the field videos), a refresh of the page is required, this happening in all fields.

**Comment by fmontes** [comment]
I found this issue: https://github.com/dotcms/core/issues/15840 @erickgonzalez is working on it.

**Comment by erickgonzalez** [comment]
> I found this issue: #15840 @erickgonzalez is working on it.

@fmontes this is already merged, still missing QA but is working as it should now.

**Comment by bryanboza** [comment]
After these changes, now we show a message about the relationship, but when you try to edit the field again, we still having the required checkbox enabled.

- The problem here is that we made the fix on the other side, not in the fields that we are editing, which is bad. We need to check the required in false in the field that you are editing. 

- If you have limited permissions in one of the content types, (just to read), we are applying the change without problems, and we are not validating that the current user does not have permissions to edit the content type.  

We need to do this change in the field that we are editing to avoid permissions problems and also confusions

**Comment by nollymar** [comment]
Fixed here: https://github.com/dotCMS/core/pull/16211
With this change, the property required will be set to false on the relationship field currently edited. The field on the other side of the relationship will not be modified

**Comment by erickgonzalez** [comment]
Now if you set required to both relationship fields, the required will be removed on the relationship field that is currently being edited.

**Comment by bryanboza** [comment]
Fixed, after the change we disabled the required property in the field that you are currently editing
