### ISSUE TITLE
Unable to see the content types in the drop down when you are adding the new relationship fields as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#15785]
We have problems when you are an as limited user but you have permissions to create new content types and fields, this because when you are creating a new relationship field, we are unable to see the list of content types in the content type field. 

## Expected Behavior
Since you have access to the content types portlet we need to be able to see this list of content types without a problem. 

## Current Behavior
We are unable to see the list to select some content type. 
SC:  https://screencast.com/t/eVBvTRLV

## Steps to Reproduce (for bugs)
1. Create a new site
2. Create a new role and give full permissions to the new site 
3. Create a new user and add the new role 
4. Login as this user and make sure you are able to add content types 
5. Create a new one and try to add a relationship field 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment]
@bryanboza does the user have read permission on the types they are looking to relate to? Otherwise, they should not see them.

**Comment by bryanboza** [comment]
Hey @wezell, Yes, in this case the role have full permissions over the new site, you can create multiple content types, but when you try to add a new relationship field, you can't see those ones in the drop-down.

**Comment by wezell** [comment]
ok, we'll get it fixed

**Comment by erickgonzalez** [comment]
**Need To Discuss**

This is happening because of how our ContentTypePagination works, right now we're pulling X amount of content types after that filter those by permissions and return that list regardless if the list is empty or have any amount of results. 

E.g: Let's say we have a total of 15 Content Types (a limited user only have permissions to the last one lets called **contentType15**), the same limited user request 10 content types, so [here](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/contenttype/business/ContentTypeFactoryImpl.java#L460) we get the first 10 content types (contentType1...contentType10) and then we filter those by user permissions in [here](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java#L1102) so that list will return 0 results b/c the user does not have permissions to any of those contentTypes just to the last one.

I think we should keep evaluating the Content Types until we get the amount requested by the user or until there are no more Content Types to evaluate, but this will change on how all the ContentTypeResource behaves and probably have some repercussions on performance.

As a workaround to this issue, you can type the name of the content type you want to relate and it will show up.

**Comment by nollymar** [comment]
Tests results: Success

**Comment by bryanboza** [comment]
Fixed, unable to reproduce in the last master code
