### ISSUE TITLE
Change how Relationships are Indexed in Elasticsearch - Nested Fields

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15940]
Currently, when we have a relationship between two content types, we create two elasticsearch fields - one that holds a list of the related children \[ids\] \(on the parent content record\) and another that holds the order of the children - id\_order \(stored on the child records\)

This means that when we save a piece a contentlet with a number of related children on it, we need to reindex the parent and ALL children to insure that both sides of the relationship are updated in ES  can be sorted by the user specified relationship order.

We need to move to store relationships using a Nested Field in Elasticsearch. This would allow us to query and sort children within elasticsearch using a single field on the parent content object and would have the following benefits:

- Saving a content object would only force a reindex on that content object
- Run Elasticsearch without customization. We could remove the custom sorting script that we use to sort relationships

### References:

Returning and sorting the nested results
https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-sorting.html

Searching for parents using values in the nested children field
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html

**Comment by nollymar** [comment]
Relationships are still being reindexed as a list of identifiers (only children identifiers are maintained).

**it’s important to consider:**
1. if there is a relationship from parent --> children, we will reindex it and lucene/ES queries will be fully supported
2. if there is a relationship field from child --> parent the field/relationship will not be indexed on the child document, only the relationship name will be indexed on the parent, so in this case lucene/ES will have limitations

To avoid confusion, we strongly suggest to use the pullRelated method instead of a raw lucene when querying over relationship fields

**Comment by nollymar** [comment]
PRs: 
https://github.com/dotCMS/enterprise-2.x/pull/667
https://github.com/dotCMS/core/pull/16603

**Comment by wezell** [comment]
Done!
