### ISSUE TITLE
APIs do not respect LoggedInSiteUser permissions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16135]
You can see this here by curling a piece of content that has only System.LoggedInSiteUser permissions - it should not be anonymously available.  

```
curl https://demo.dotcms.com/api/content/id/e28708f8-e296-4995-be50-763649c6fbd4
```

This happens because our WebResource sets user to AnonUser if no user is found, which can gum up some of the permission checks.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16353

**Comment by bryanboza** [comment]
After test the last changes we need some improvements here: 

- We are returning a message here: 
SC1: https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/793b68d1-1fcd-4267-935a-ef6171a57087/00000288.png
SC2: https://content.screencast.com/users/Bryan_Boza/folders/Jing/media/4275b81b-1900-40af-8a6e-094ddc6b7396/00000289.png

- We need to change the error code, since is permissions we need a 401 instead a 403

**Comment by bryanboza** [comment]
After discuss my comment seems that 403 is ok, Fixed tested on master// Postgres // FF
