### ISSUE TITLE
Using an API token should not log you in

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16423]
If you use an APIToken as a bearer token for an API call while on a dotCMS velocity page, it should not log you in.   Instead, it should just handle the request statelessly, as if you are that user (add the user as a requestAttribute and perhaps to the threadlocal).  It should not associate the Bearer token user with your current user session.

To reproduce, Create use an APIToken to make a js call from a velocity page, it logs you in as that user.  If you refresh the page, it will show you as logged in.

### to reproduce
- Create an API token for a user (Joe) in dotCMS
- Create a page in dotCMS
- use javascript to call an API on a velocity page passing the Joe token in as the bearer token:
- once you hit the page and the call is made, refresh the page and you will be logged in as joe.

```js
<script>
   document.addEventListener('DOMContentLoaded', function(){ 
      const getUrl="/api/content/render/false/type/json/query/+working:true";
      const token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGk5N2U0MDg2Yi0zMWJjLTQwZTEtOTBmMi1mNjkwZWQzYjU1Y2UiLCJ4bW9kIjoxNTU1NjIwMjEwMDAwLCJuYmYiOjE1NTU2MjAyMTAsImlzcyI6Ijc1MDA2MmI0LTYzMmQtNGE2Ny04OTRjLTJhMGI4YjY5MmZmYSIsImxhYmVsIjoidGVzdGluZyIsImV4cCI6MTY1MDI1NDQwMCwiaWF0IjoxNTU1NjIwMjEwLCJqdGkiOiI4YmQzM2RlOC03NTc2LTRhMGYtYTY2OS05MjJlNmZlM2I1NjAifQ.SxPFFbxmmuVvpE2gQNr2rSdHEb3SeSs5qv1Wyukw6Ws";

      var xhr = new XMLHttpRequest();
      xhr.open('GET', getUrl);
      xhr.setRequestHeader('Content-Type', 'application/json');
      xhr.setRequestHeader('Authorization', 'Bearer ' + token);
      xhr.onload = function() {
         if (xhr.status === 200) {
            alert("logged in" )
         }else{
             console.log("xhr error:", xhr);
         }

      };
      xhr.send();
   });
</script>

user: $user

```

**Comment by wezell** [comment]
PR: #16424

**Comment by jdotcms** [comment]
Jwt test jsp
[jwt.jsp.zip](https://github.com/dotCMS/core/files/3122540/jwt.jsp.zip)

In order to test this, you have to follow these steps:

1) put the jwt.jsp on the root folder.
2) request the http://localhost:8080/jwt.jsp on incognito windows
3) get login into dotCMS and request http://localhost:8080/jwt.jsp
4) Generate on user portlet a new api token and copy it
5) the jwt.jsp has to buttons, one gets the workflows schemes from the endpoint by using the api token jwt. the other one hits the endpoint to get the current session user, 
So in the jsp as incognito you can use the token and get the schemes, after that hit the get current user button, you have get an error window since not session is created after the schemes request.
In the case of the already logging window, if you execute the same exercise the get current user button will retrieve you the current user. 

Note: however the API Token is totally stateless, you may be logged in for instance with Admin, and them generate a token for Bill for example, use it to get the schemes on the logged in session, however you still being logging with the Admin user even if the request was made for Bill's account.

**Comment by bryanboza** [comment]
Fixed, tested with the provided steps and now it works as expected
