### ISSUE TITLE
content/publish fails with FileAsset

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16600]
When you try to upload a file to `/content/publish/1` using a multipart form request you get an error 500 and the log shows NullPointerExceptions and "ERROR filters.CookiesFilter - Exception processing Cookies".  It happens when authenticate using either basic auth or jwt . Saving non-file content continues working.It is confirmed that this issue not only happens on 
 installed instances and also when running the vanilla dotcms/dotcms:5.1.5 docker container.

**Comment by fabrizzio-dotCMS** [comment]
The issue is caused as a collateral effect caused by fixed previously applied for https://github.com/dotCMS/core/issues/15934 

The new code lives in a branch called `issue-16600-fileAsset-push-fails`

I have tested it works using the following examples CURL examples.

`curl -v -u admin@dotcms.com:admin -X POST \
 http://localhost:8080/api/content/publish/1 \
 -H 'cache-control: no-cache' \
 -F 'json={
    contentType:'\''fileAsset'\'',
    hostFolder:'\''demo.dotcms.com'\'',
    title:'\''lol'\'',
    fileName:'\''lol2'\''
};type=application/json' \
 -F 'file=@index.txt; type=application/plain'`

`curl -v -u admin@dotcms.com:admin -X POST \
 http://localhost:8080/api/content/publish/1 \
 -H 'cache-control: no-cache' \
 -F 'json={
    contentType:'\''fileAsset'\'',
    hostFolder:'\''demo.dotcms.com'\'',
    title:'\''lol'\'',
    fileName:'\''lol3'\''
};type=application/json' \
 -F 'file=@index.txt; type=text/plain'`

`curl -v -u admin@dotcms.com:admin \
  -XPUT http://localhost:8080/api/content/publish/1 \
  -F "json={ \
    contentType:'fileAsset', \
    hostFolder:'demo.dotcms.com:/images', \
    title:'nice.jpg', \
    fileName:'nice.jpg'}; \
    type=application/json" \
  -F "file=@liz.jpg; \
    type=application/jpg"
`

**Comment by fabrizzio-dotCMS** [comment]
Additionally, to that, I also used the example from our documentation that appears here
https://dotcms.com/docs/latest/content-api-posting-files

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16619

**Comment by jgambarios** [comment]
**Note to QA:** We also need as part of this ticket to re-test https://github.com/dotCMS/core/issues/15934

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF also retested the #15934
