### ISSUE TITLE
Enforce Folder name blacklist at the api level

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16715]
Right now, our only validation of folder names is happening in the EditFolderAction class,e.g
https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/folders/action/EditFolderAction.java#L348-L351

This does not prevent folders from being copied with new names nor from creating disallowed folders with webdav.

Folder name validation needs to happen at the API or factory level to prevent bad data from making it to the system.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/17466

**Comment by erickgonzalez** [comment]
Tried with WebDAV (finder) I was able to create a folder with the reserved names.

**Comment by nollymar** [comment]
Tests results: Success. I tried to copy/rename and create a folder setting names in the blacklist using Finder and Postman and got an error which was expected

**Comment by wezell** [comment]
We need to add `dotAdmin` and `custom_elements`

**Comment by nollymar** [comment]
`dotAdmin/` and '/custom_elements' have been included to the blacklist. PR: https://github.com/dotCMS/core/pull/17644

**Comment by freddyucv** [comment]
Passed Internal QA: tested 
- Create a folder name 'dotAdmin' in 'site-browser'. 
- Create a folder name 'custom-elements' in site browser.

**Comment by bryanboza** [comment]
We need some work here: 
- Now we are unable to create folders with those two new words, but we need to improve the error response and logs when you try this from WebDAV. 
_If you try to create a folder from the site browser, we have just a line error which  is ok,_
 
But if you try from a WebDAV client we have this response https://gist.github.com/bryanboza/2f88354f049bb5c04d19c346ef6b1a94 , and this comes from the Webdav code https://github.com/dotCMS/core/blob/cf889ed2d2f5e5e6d676ed6d1070edde52af5f69/dotCMS/src/main/java/com/dotmarketing/webdav/DotWebdavHelper.java#L1003
we need print here just a line error like we do in the site browser and also check the error response, because we are returning a (500) error
SC: https://www.screencast.com/t/JLnMbN1fZq

**Comment by wezell** [comment]
Agreed - change the line to a `.warnAndDebug` or something

**Comment by bryanboza** [comment]
Maybe we can leave as an error, but we need to avoid too many noises in the logs, we have this line when you try the same case from site browser 
`ERROR action.EditFolderAction - ERROR: Cannot save folder '/dotadmin`

**Comment by dsilvam** [comment]
We are able to change the logging and throwing at dotCMS level to do that, but still Milton (WebDAV lib) logs error including the exception `e`, so it will still be noisy. 

See: https://gist.github.com/dsilvam/a742fbc927dbf2f43ac9089ba65d82dd

**Comment by freddyucv** [comment]
Passed Internal QA: tested

Create a folder name 'dotAdmin' with webdav

**Comment by bryanboza** [comment]
Before my last comment, we are printing a line error when you try to add a folder with some reserved name from the site browser, and the problem was only with WebDAV. After the last changes now we print the complete stack trace when you try it from the site browser. 
ST: https://gist.github.com/bryanboza/52cc16272d391030d42fe93873734352

**Comment by dsilvam** [comment]
PR:  https://github.com/dotCMS/core/pull/17725

**Comment by nollymar** [comment]
**Tests Results: Success**

**Tested scenarios:** 
1. Try to create a folder with a valid/invalid name (WebDAV)
2. Try to create a folder with a valid/invalid name (Site Browser)

In both cases I checked the logs. In case of WebDAV the full stack trace is shown in case of failure. In case of SiteBrowser, only a one-line message is logged

**Comment by bryanboza** [comment]
Fixed, tested on release-5.2.2 // Postgres // FF
