### ISSUE TITLE
wrapIntoDotParseDirective can use wrong filename

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16798]
I wanted to add the banner structure to the starter's based container.  So, from the UI ,I made a copy of the document.vtl, renamed it `banner.vtl` and then added banner code to display a banner.  The banner was never displayed and resulted in this error in the logs:

```
10:38:26.243  WARN  directive.DotParse -  - unable to resolve /application/containers/large-column/document_copy.vtl getting this: No resource found for [//demo.dotcms.com/application/containers/large-column/document_copy.vtl] @ url:GET//demo.dotcms.com/api/v1/page/render/about-us/index | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:true | start:06-29-2019 10:35:24 EDT  ref:http://localhost:8080/dotAdmin/  ?language_id=1
10:38:26.243  WARN  directive.DotParse -  - at com.dotcms.rendering.velocity.directive.DotParse.resolveTemplatePath(DotParse.java:92) @ url:GET//demo.dotcms.com/api/v1/page/render/about-us/index | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:true | start:06-29-2019 10:35:24 EDT  ref:http://localhost:8080/dotAdmin/  ?language_id=1
```
### To Reproduce
1. From the browser, make a copy of ` /application/containers/large-column/document.vtl`
2. Edit it, rename the file to `banner.vtl` add "THIS DOES NOT WORK" in the file.
3. Go to a page and try to add a banner in the content area.  "THIS DOES NOT WORK" will never show up and you get an error in your logs.

### Cause

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/FileAssetContainerUtil.java#L269

The issue is caused by the use of `fileAsset.getFileName()` which returns the underlying file name and not the file name set in the identifier, which is unexpected by a developer using `FileAsset`.  

In order to clarify what the method `FileAsset.getFileName()` returns, and with an eye towards future `FileAsset` storage implementations, we need to change the a method to `FileAsset.getFileName()`so that it returns the identifier name and add a new method with a name like `fileAsset.getUnderlyingFileName()`  or `fileAsset.getImplFileName()` to return the underlying file name.  In addition, we need to put eyes on everywhere `fileAsset.getFileName()` is called and make sure that the right method (the identifier or FS name) file name is expected. 

This specific bug can be fixed by replacing 
```
return "#dotParse(\"//" + host.getHostname()  + fileAsset.getPath() + fileAsset.getFileName() + "\")";
```
 with 
```
return "#dotParse(\"//" + host.getHostname()  + fileAsset.getURI() + "\")";
```

**Comment by jdotcms** [comment]
Good

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16855

**Comment by bryanboza** [comment]
Now we are able to show the banner as a document, but we still with the error on logs: 
ST: https://gist.github.com/bryanboza/9dae951be5acc330704f2e28351fd99a

We need some work here.

**Comment by fabrizzio-dotCMS** [comment]
There's a NPE that is presented when the page loads that can not be presented on screen because the following vtl can not be found. 
Cannot parse velocity file : /static/preview_mode/error_template.vtl

The NPE isn't related to the original issue that was addressed here.
The NPE is originated when the method `FolderWebAPI.findCurrentFolder(path,.. ` is called with a null path argument.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16956

**Comment by jgambarios** [comment]
![image](https://user-images.githubusercontent.com/923947/62719016-3c6cc280-b9c4-11e9-9c60-2dcc101700e6.png)

We need to show as much velocity info as we can to help with identifying what velocity code is causing the error.

**Comment by wezell** [comment]
We now show errors, but they do not include template names or line numbers and so are not actionable or fixable by a user.  The header in the starter site throws NPE errors on every page:

![errors](https://user-images.githubusercontent.com/934364/62719057-1996da00-b9d5-11e9-99cb-847e14885c89.gif)

**Comment by fabrizzio-dotCMS** [comment]
Each error-handler handles a specific type of exception. In this case, an NPE does not provide the line number or the file name. I'm just letting the user node about the exception that is happening under the hood. 
In order to show any additional info in a scenario like this, I would probably need to feed the local thread with the velocity context or something.

If for example, you were to introduce a Velocity syntax error  by doing something like 
`if(#lol)
#en ` 

That would be captured by a Different handler and then you would see the line number template name etc...
My latest fix just makes evident that there's an error which is actually located in 
/application/themes/quest/header.vtl
and probably needs to be fixed in the starter for the next release.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/16967

**Comment by bryanboza** [comment]
Fixed, tested on master // Posgres // FF
