### ISSUE TITLE
We should have a Workflow Actionlet that for "Delete all Versions"

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#16817]
Right now when you configure a Delete sub-action in the workflow, we can only delete one language version at a time.  Meaning if you have a product related to a promotion that has 5 language translations, you would have to perform 5 deletes for each language version via rest.

We should have a "Delete all versions" sub-action to delete all language versions of a contentlet with a single workflow action.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17316

**Comment by bryanboza** [comment]
We have a special case here: 

- If some piece of content is locked by an admin or any other user and the limited user can't unlock this, but the limited have access to use this actionlet,  we are deleting all the contents including the locked one. We need to respect the LOCK and avoid the user to delete the content.

**Comment by jdotcms** [comment]
[PR](https://github.com/dotCMS/core/pull/17714/files)

**Comment by jdotcms** [comment]
After the fix, if you have two or more language version contentlet of the same identifier; if an admin locks for instance the english, and a limited user tries to destroy for instance the spanish, and error is showed instead of destroy all versions.
However if an admin destroy any lang version, the destroy will be executed successfully even if it is lock

**Comment by bryanboza** [comment]
After the fix, now we are respecting the lock of the admin user, but we have another interesting case here: 

- If some piece of content is used on a page and the limited user does not have permissions to edit the page, we are unable to destroy this piece of content because is referenced on the page, which is perfect, but if you try to destroy the same piece of content but in another language, we are destroying both without problems, skipping this validation. 
SC: https://www.screencast.com/t/ui0uayixwc6
