### ISSUE TITLE
Redirect form after success submission

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#16850]
As a user I want to show a success or confirmation page after a form is submitted in order to inform my users everything went well.

### Describe the solution you'd like
After the form is submitted (using the content  api) we need to redirect to the page user entry in the form content type in the field **Form Return Page**:

<img width="749" alt="Screen Shot 2019-07-12 at 3 52 21 PM" src="https://user-images.githubusercontent.com/751424/61160627-61e9d780-a4bd-11e9-87ec-265b2f4a92ad.png">

And we need to pass as query param the inode of the contentlet that was just created (it came in the header of the request).

### Technical Approach
Wait for the 200 response, grab the inode and redirect.

## Acceptance Criteria
1. Redirect the page after success form submission passing the inode
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by alfredo-dotcms** [comment]
**Core-Web Branch**: issue-16850-redirect-on-success-submit-dot-form
**Status**: Partial implemention, if the field on the form has the 'formReturnPage' variable, then when form submitted with success it redirects.
**TODO**: 
- The endpoint that is set on the redirect needs the _inode_ (prob another endpoint will be needed to get the inode)
- When dot-form is loaded inside the DotCms system, the dot-form _variable_ is not being set, so at the moment you need to burn it in the code, otherwise when submitted it will crash
- There's a issue/blocker in the e2e test for dot-form, when doing the submit action at the moment there's no way to mock `fetch` in the headless browser, and the fetch function crash throwing the error:
`Failed to execute 'fetch' on 'Window': Failed to parse URL from /api/content/save/`
