### ISSUE TITLE
Make PageMode respect User.isBackEnd()

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16875]
If a user does not have `User.isBackEnd()` they should only be able to have PageMode.LIVE

Front end users should never have any backend PageModes.  By default, we should always force front end users to PAGE_MODE.LIVE (though maintaining current behavior should be configurable)

**Comment by john-thomas-dotcms** [comment]
Doc: Need to make sure this is explicitly stated in the User Permissions and/or API docs

**Comment by nollymar** [comment]
**Note to QA:** 
Please test these cases from the content rest api using anonymous user: 
* filter by inode a non-live content
* filter by identifier and live param set to false, a content with non-live version
Both cases should return an empty list.
Otherwise, the live version should be returned if apply

**Comment by wezell** [comment]
@nollymar this change did not fix the contentlet relationship list so I think we need to fix your case specifically.  Please talk to @jgambarios about what he thinks needs to happen.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17298

**Comment by jdotcms** [comment]
When you tried to get logged in on BE, the user is rejected, however the process stops in the middle and some cookies are created, so when you land in the FE, you are able to see the admin mode.

**Comment by bryanboza** [comment]
Fixed, tested on master and now it works as expected
