### ISSUE TITLE
Prevent Front End User access to backend only API calls

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16870]
Initial list where we need to enforce Backend only
### Backend Only
```
/v1/notification
/ws/v1/system
/v1/portlet
/v1/sites/{siteId}/ruleengine
/v1/configuration
/osgi
/cluster
/v1/users
/v2/users
/v1/esindex
/v1/system-status
/role
/v1/roles
/license
/environment
/bundle
/ruleengine
/config
/cluster
```

**Comment by wezell** [comment]
Done as part of #17147

**Comment by jdotcms** [comment]
I have found these still open;

http://localhost:8080/api/v1/configuration


http://localhost:8080/api/user/getloggedinuser/


http://localhost:8080/api/v1/esindex/download/

http://localhost:8080/api/v1/system-status

http://localhost:8080/api/role/loadchildren/


I have created an user FE and make these request with that user and was able to get results

**Comment by fabrizzio-dotCMS** [comment]
http://localhost:8080/api/v1/configuration needs to remain open since it is used by the login-dialog screen.

Same with http://localhost:8080/api/v1/system-status it is used by support.

http://localhost:8080/api/user/getloggedinuser/
http://localhost:8080/api/v1/esindex/download/
http://localhost:8080/api/role/loadchildren/

Should probably get secured but they were not touched since I only focused on the initial list of endpoints.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/17360

**Comment by bryanboza** [comment]
Fixed, now every one of those endpoints is closed. 

Pending: We can create a new suite of postman tests to automate this validation
