### ISSUE TITLE
The Name URL field on Folders should not store capital letters - should lower the url field

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#16905]
Tested on two servers running latest release version 5.1.6

We need to always lower the url's when creating folders.  Capital letters should not be in url's:

![Screen Shot 2019-07-22 at 3 17 44 PM](https://user-images.githubusercontent.com/1569167/61666180-1214c880-ac94-11e9-9ba3-509e7ef40b43.png)

To reproduce, just right click on a host and add a folder name with capital letters in it.

**Comment by jcastro-dotcms** [comment]
Agree 100%. This has caused some Push Publishing problems on several customers.

**Comment by wezell** [comment]
@jcastro-dotcms and @DeanGonzalez as of 5.1.6, dotCMS case sensitive when displaying URLs and not when serving or resolving them via apis.  So regardless of how URIs are displayed in dotCMS UI, dotcms will resolve them and serve them case-insensitive.  

We got rid of the forced lowercase in the UI because it broke a number of cases including Push Publishing and other cases such as webdav - where you could never upload a folder with an upper case name. Now, to dotCMS, `/ABOUT-US/Index == /about-us/index == /About-us/INDEX` and if the client wants upper case on the URI or uploads an upper case file, we display it correctly and serve it correctly.

**Comment by wezell** [comment]
![case-insensitive](https://user-images.githubusercontent.com/934364/61667507-1a76fe80-aca8-11e9-8e7f-52c2e696e6f0.gif)
