### ISSUE TITLE
First 2 fields not shown for legacy content type

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#16931]
Reported via Support: Ticket [98828](https://dotcms.zendesk.com/agent/tickets/98828)
Reproducible in dotCMS 5.1.6

When editing content for a legacy content type that starts with a line divider, the first 2 fields are not shown.

### Steps to reproduce the behavior:
1. Create a new content type in dotCMS 4.3.3
2. Add a field of type 'Line Divider' as the first field for the new content type.
3. Add another couple of fields, for example 'Title' and 'Description'.
4. Upgrade to dotCMS 5.1.6
5. Go to Content -> Search portlet, and edit a contentlet of the content type
6. The first two fields (including line dividier) are not shown in the edit contentlet window.

### Expected behavior
All the fields should be shown when editing a content for a legacy content type.

### Screenshots
Content edit window in dotCMS 4.3.3 (the 2 first field are shown, including Line Divider):
![image](https://user-images.githubusercontent.com/2894221/62077047-6bd24100-b206-11e9-97f7-e9f78f66325b.png)

Content edit window in dotCSM 5.1.6 (the 2 first fields are not shown):
![image](https://user-images.githubusercontent.com/2894221/62077071-742a7c00-b206-11e9-8591-8c052b836ede.png)

### Additional context
This has been reported by customer via Support: Ticket [98828](https://dotcms.zendesk.com/agent/tickets/98828)

**Comment by wezell** [comment]
Our expectation is that customers should choose one portlet to manage their content types and not switch between the two - and by 5.2.0 they should switch to the new content type portlet  - we can message this in the change log for 5.2.0.  Regardless, the issue should be updated to read :

### Expected behavior
All the *LEGACY* fields should be shown when editing a content type via the legacy content type portlet.
