### ISSUE TITLE
POC - set up dotCMS 5.3 against Elasticsearch hosted service

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#16998]
We should try to set up dotCMS 5.3 against the hosted version of elasticsearch service, specifically against the cloud service Elastic.co offers so we can prove out the complete externalization of ES.

This would also make a good technical blog entry

**Comment by nollymar** [comment]
Connecting to hosted Elasticsearch is pretty straightforward. I just followed these steps: 
1) Register for a trial 
2) Log in and configure a deployment. It comes with several templates and I used the default one which generates an ES cluster with one node and Kibana. Currently, only two ES versions are supported: 7.3 and 7.4. I used 7.4
3) Once the deployment is completed, copy the user/password  and url provided. Use this info in the dotcms-config-cluster.properties to configure: `ES_AUTH_BASIC_USER`, `ES_AUTH_BASIC_PASSWORD`, `ES_HOSTNAME`, `ES_PORT`
4) In the dotcms-config-cluster.properties set `ES_TLS_ENABLED=false` because with the trial version of ES cloud there is no way to change the default certificates or set new ones
