### ISSUE TITLE
SiteSearch is not indexing keywords as a list

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17131]
When we are putting a sitesearch object to the index, we are putting keywords as a String and not as a list of Strings.  This makes searching and faceting on keywords fail.

To test:
1. In the demo site, create a new page with these keywords
`thisWorks, thisDoesntWork`

2. Run a site search and search for `thisDoesntWork`.  You get no results.  

3. If you search for `thisWorks*` you get results and if you search for `*thisDoesntWork*` you get results.

#### Note
We should also trim the keyword results before putting them into the index.

**Comment by john-thomas-dotcms** [comment]
Doc: The doc currently specifies that you need to use wildcards in the keywords (because of this issue).  Doc just needs to be updated to remove this requirement.

**Comment by nollymar** [comment]
PR Core: https://github.com/dotCMS/core/pull/17208
PR EE: https://github.com/dotCMS/enterprise-2.x/pull/679

**Comment by erickgonzalez** [comment]
Working as it should, now able to search `keywords` of a page.

**Comment by bryanboza** [comment]
We need some work here, tested in the last master and I have no results when I try to search for some keyword
SC: https://screencast.com/t/2xeb2613KwIf

**Comment by erickgonzalez** [comment]
After re-testing it only happens when the template of the page is **Blank** if you select any other template works as it should.

**Comment by nollymar** [comment]
The reason why it is happening on pages with **Blank** template is because keywords are not part of the metadata when Tika parses pages before adding them to the site search index (internally it calls this method `Map<String, String> map = new TikaUtils()
						.getMetaDataMapForceMemory(page.getInode(), htmlFile);`). 

I captured a screenshot of what is obtained from the map when a page with blank template is parsed:

![Screen Shot 2019-09-19 at 1 23 37 PM](https://user-images.githubusercontent.com/8741395/65271029-fbe38700-dae1-11e9-8cf9-e30a656246b7.png)

**Comment by wezell** [comment]
Right, the blank template is expected NOT to work as the page needs to be a standard html template with the `<meta name="keywords" content="dotCMS Content Management System">` in the `<head></head>` tag

**Comment by bryanboza** [comment]
Fixed.
