### ISSUE TITLE
Show 10 personas by default

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17296]
right now, we are only showing 5 personas in the page persona list.  We need to show 10 personas in the list by default.

![Screen Shot 2019-09-19 at 3 07 08 PM](https://user-images.githubusercontent.com/934364/65273621-8f6f8480-daef-11e9-9ecc-f9a3e5753421.png)

**Comment by fmontes** [comment]
Two issues here:

1. If we create a persona from the [+] button is not getting listed (this might be not related to this issue but since we're in this code let's do it)
2. When you create a persona from the [+] and get to +10 and the pagination shows up and you go to the second page (which will have less items) the height change.

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
