### ISSUE TITLE
QA: Test upgrades with real data 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17358]
We need to try to upgrade instances with real data in order to have real scenarios and make sure we have no problems after upgrade  

We need to make sure that test in every one of the supported databases

- [x] Postgres 

- [x] MSSQL

- [x] MYSQL

- [x] Oracle

**Comment by erickgonzalez** [comment]
Tested MSSQL with client data, after fixing some issues with the data, the upgrade went smoothly and was able to do a smoke test over the server.

**Comment by nollymar** [comment]
Tested on Oracle using client data. Results: I was able to start the server and run the upgrade tasks successfully. However, I had to clean up and fix some issues with the data. I was not able to login after testing with several users. No errors in log or JS console. 

From my perspective, we need more reliable data to test these scenarios. The database provided seems to be very old and has inconsistencies

**Comment by nollymar** [comment]
After testing with a new client data in Oracle, I could upgrade and log in successfully

**Comment by nollymar** [comment]
Tests results with Postgres: I had to fix a lot of data inconsistencies because of this new index constraint: `idx_ident_uniq_asset_name`. As now we don't support assets with similar names (same string, different case) on the same path, upgrading might become laborious for our clients, especially for those with large datasets. We should consider a way to ease this process.

**Comment by dsilvam** [comment]
MySQL: Upgraded successfully from provided dataset. Reindexing showed a weird behavior on the UI the first time, no progress bar and two indexes highlighted in green but the count increasing until redexing was over. Reindexed for a second time and it showed progress bar with right percentages.

**Comment by nollymar** [comment]
Because of changes on this issue https://github.com/dotCMS/core/issues/16115 , some clients might get this error during an upgrade process: 

```
14:18:19.885  INFO  db.DotConnect - Executing DROP INDEX IF EXISTS idx_ident_uniq_asset_name CASCADE
14:18:19.885  INFO  db.DotConnect - Executing CREATE UNIQUE INDEX idx_ident_uniq_asset_name on identifier (full_path_lc(identifier),host_inode)
14:18:21.204  ERROR db.HibernateUtil - ---------- DotHibernate: error on rollbackTransaction ---------------
org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
com.dotmarketing.exception.DotDataException: ERROR: could not create unique index "idx_ident_uniq_asset_name"
```
In those cases, a manual fix is required to fix data discrepancies. As it might affect thousand of records, manual updates are not a feasible solution. So, for postgres I created a function to automate this process as follows: 

1. Temporarily disable `identifier_parent_path_trigger` trigger:
`ALTER TABLE identifier DISABLE TRIGGER identifier_parent_path_trigger;`

2. Temporarily drop the unique constraint from `identifier` table: 
`ALTER TABLE identifier DROP CONSTRAINT identifier_unique_key;`

3. Create a function to clean up duplicates: 

```
CREATE OR REPLACE FUNCTION public.clean_up_assets(
	)
    RETURNS void
    LANGUAGE 'plpgsql'

    COST 100
    VOLATILE 
AS $BODY$DECLARE
	temprow record;
	temprow2 record;
BEGIN
	FOR temprow IN
		select parentPath, assetName, hostInode from (
				select lower(parent_path) as parentPath, lower(asset_name) as assetName, host_inode as hostInode from identifier 
					group by lower(parent_path), lower(asset_name), host_inode HAVING COUNT(*) > 1) as results
	LOOP
		FOR temprow2 IN
			select id as assetIdentifier, ROW_NUMBER() OVER () from identifier where lower(asset_name)=temprow.assetName and lower(parent_path)=temprow.parentPath and host_inode=temprow.hostInode
		LOOP
			IF temprow2.row_number > 1 THEN
				RAISE NOTICE 'Updating asset: % Identifier: %. RowNumber: % New asset name: % ', temprow.assetName, temprow2.assetIdentifier, temprow2.row_number, SPLIT_PART(temprow.assetName, '.', 1) || temprow2.row_number || RIGHT(temprow.assetName, LENGTH(temprow.assetName) - LENGTH(SPLIT_PART(temprow.assetName, '.', 1)));
				UPDATE identifier
					SET asset_name=SPLIT_PART(temprow.assetName, '.', 1) || temprow2.row_number || RIGHT(temprow.assetName, LENGTH(temprow.assetName) - LENGTH(SPLIT_PART(temprow.assetName, '.', 1)))
					WHERE id=temprow2.assetIdentifier;
			END IF;
		END LOOP;
	END LOOP;
END;$BODY$;

```

4. Run the function this way: 
```
select clean_up_assets();
```

5. Run this script to verify if all duplicates were fixed . In case this query returns a count > 0, run step 4 again

```
select count (*) from (
				select lower(parent_path) as parentPath, lower(asset_name) as assetName, host_inode as hostInode from identifier 
					group by lower(parent_path), lower(asset_name), host_inode HAVING COUNT(*) > 1) as results
```

6. Enable trigger
```
ALTER TABLE identifier ENABLE TRIGGER identifier_parent_path_trigger;
```
7. Add unique constraint again
```
ALTER TABLE public.identifier
    ADD CONSTRAINT identifier_unique_key UNIQUE (parent_path, asset_name, host_inode);
```

**Comment by nollymar** [comment]
**Postgres:** After fixing data inconsistencies I could upgrade and reindex using a large dataset. However, I experienced the same behavior @dsilvam commented about the progress bar. Apparently, the switchover occurs immediately after the reindex process start and the progress bar doesn't appear. Other than that, the reindex process finished successfully
