### ISSUE TITLE
View Permissions / respectFrontEndRoles Cleanup

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17518]
There is ongoing confusion in what permissions it takes for an Anon user to check-in content and what is the meaning of the `respectFrontEndRoles` boolean.  We need to come up with a very clear definition for both.  All the cases are ultimately handled by the `PermissionBitAPIImpl.doesUserHavePermission` method and this method is a hodgepodge of outside cases and old code.

There are a number of ideas to simplify permissions
1. Always respect roles and treat CMS anon just like any other role.  
2. If CMS Anon has `READ` permissions, they can only see live content, if they have `EDIT_PERMISSIONS` they can see and edit working versions of that content, just like anyone else. Maybe it takes `EDIT_PERMISSIONS` for any role to see working versions of content?
3. As a compromise, like @john-thomas-dotcms mentioned, maybe the rule is you can view working content if you have either:
• The back-end user role, or
• Edit permissions on the content. (edited)

**Comment by john-thomas-dotcms** [comment]
A couple things we need to make sure to take into account here:

**Comment by john-thomas-dotcms** [comment]
A couple things we should consider with this:

1. Historically we've allowed any back-end user with View permissions to see both working and live content.
    * I actually think it would be simplest and most consistent to make viewing of Working content tied to the Edit permission, but that would break the historic model.
    * This is why we might need to continue to allow back-end roles to see working content.
2. We need to make sure whatever we do makes sense in multi-tenant environments.
    * I think using Edit permissions to control view working permissions would be cleaner for multi-tenant environments than our current setup is.

**Possible Option:** With both the above in mind, we could change to make Edit permissions control who can view working content, but add a configuration option which allows anyone with a back-end user role to also see working content.

    * The option would be on by default, to preserve existing behavior for back-end users.
    * But having it as an option would allow people to move to the new paradigm by just turning it off.
        * This could be especially useful for multi-tenant environments where back-end users might have view permissions to other sites that they don't have edit permissions for.

**Comment by wezell** [comment]
While I like your suggestion @john-thomas-dotcms - wouldn't making "EDIT" permissions required to see the working version of a piece of content make drafting anything impossible?  An example is a new, unlaunched site.  You want your users and content editors to be able to add to it and create things on it, but it is only in the working state.  

Maybe we should have a new permission type called "View Unpublished"?  That would really clear things up.

**Comment by john-thomas-dotcms** [comment]
Yeah, so we have an interesting case right now in how we handle "Add" vs "Edit" permissions.  A user who has "Add" but not "Edit" permissions has permissions to edit any content they have created, but not to edit content other users have created.  So Add really gives a kind of limited Edit permission - which I think would apply in the context of viewing working content, and I think would cover the case you mentioned.

I think the bigger issue is actually if a back-end user doesn't have Edit permission (because the customer really does *not* want them to be able to edit content created by other users), but needs to be able to see working content created by other users before it's published.  Right now they can, but if we change things so Edit=ViewWorking then that wouldn't work any more.

I thought about have a new "View Unpublished" right too, but originally thought it might be a bit too much to add since we already have alot of rights settings in the permissions.  However I think it's probably the best solution since it makes it very clear who can do what, allows finer grained control, and I think it would be relatively straight-forward to create an upgrade task to set it so behavior doesn't change on upgrade.  So maybe it would be worth doing; alot of rights that are clear may be simpler in the long run than fewer rights to assign but lack of clarity what each of them means.
