### ISSUE TITLE
Main Nav Improvements

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17707]
Our main navigation can be daunting for first time users - or even for limited users.  We should simplify it initially and make it work even when "closed"

1. Nav closed by default
Upon initial login, the main nav should be in a closed state
2. Save Nav State
If a user opens or closes the main nav menu, we should remember that state in long term local storage and across multiple logins, meaning, if I want it opened and leave it that way, when I come back, it will still be opened.
3. If the main nav is closed, we should keep it closed
If you "close" the main nav and then click on one of the options, it navigates and then opens back up.  It should navigate AND stay closed until the user clicks the "open nav" hamburger, even if there are multiple portlets available under the nav.
4. Show Name on Hover
If the nav is closed, we need to show the name of the nav item as a mouseover, e.g. like this picture from another system (mouse not captured in screencap) 

![Screen Shot 2019-12-05 at 11 02 32 AM](https://user-images.githubusercontent.com/934364/70256601-bafd2500-1756-11ea-80a4-8baa98cd41ec.png)

5. get rid of the horizontal scroll bar in the minimized nav
6. Double click / long press when minimized opens the nav

**Comment by john-thomas-dotcms** [comment]
Question for clarification:

Right now, if I close the nav, and then click on a different Tool Group than the one I'm in, it does 2 things:
1. Changes to the first Tool within the Tool Group I clicked on.
2. Opens the nav so I can see all the Tools within the group I clicked on.

With the new method, if the main nav has been closed by the user, will it still change to the first Tool of that group?  Or will it open the main nav, without switching Tools, to allow the user to select which Tool within that group to change to?

I think it would probably be better (both in the current scheme and with the improvements), that when a user clicks on a Tool Group in the closed nav, it opens the nav without switching Tools. That allows the user to choose which Tool to switch too, and avoids an unecessary switch to the first Tool, which they might not even use.

An alternate might be to have the mouse-over open the full nav (thus showing all the Tools in the Tool group moused over) rather than just show the name of the Tool Group.

**Comment by wezell** [comment]
@john-thomas-dotcms - here is the issue we are trying to solve.  We've lost a few deals recently because we seem... too complex or heavy ... for just headless content management.  Now there are a lot of reasons for this but on logging into the demo, all the navigation "options" and 2 level deep navigation is not helping to show simplicity.    For limited and first time users, our navigation looks very daunting.  And with all the clicks and options, we have never been able to make it look ... less complex.  

This proposed change would, when the nav is closed,  just switch to the first tool in the group without opening the 2nd level nav.  If the user wants to open the 2nd level nav they can open it and keep it open using the hamburger menu.  And the system should remember that selection/preference across visitor sessions so if you want, it can operate as it does by default now.

Having the menu be minimized by default would allow for a limited user (say, one that can only edit blogs) to only see three buttons on the left hand side that, when clicked, takes them to the 3 screens they want to see.  If they wanted to, they could open up the left side and do more, but my guess is that 3 or 4 screens (workflow tasks, browser, content search) can handle 80-90% of most users needs.

**Comment by fmontes** [comment]
@wezell when you said:

> should remember that selection/preference across visitor sessions

It means we're are going to save the nav state in the backend? so if the users login in any browser will keep that state or should we only save it by browser (localstorage)?

### The tooltip
<img width="314" alt="Screen Shot 2019-12-09 at 08 39 10" src="https://user-images.githubusercontent.com/751424/70444695-ee45f980-1a5f-11ea-9b37-635bf7116c41.png">

When nav is closed we show a tooltip on hover, I like the idea, but the tooltip should say the name of the "section" or the name of the *first item* in the section because if when we click the item collapsed we are going to the first item I think the tooltip should indicate that.

@wezell when you said:

> get rid of the horizontal scroll bar in the minimized nav

Can you shot me a screenshot of that?

**Comment by wezell** [comment]
### From demo.dotcms.com
<img width="314" alt="Screen Shot 2019-12-09 at 10 14 03 AM" src="https://user-images.githubusercontent.com/934364/70448478-6d422e80-1a6e-11ea-90be-ff2cbca3451f.png">

**Comment by wezell** [comment]
> It means we're are going to save the nav state in the backend? so if the users login in any browser will keep that state or should we only save it by browser (localstorage)?

localstorage, e.g. :
https://github.com/dotCMS/core-web/compare/issue-17707-nav-state#diff-d20721dc2e70ce6bc54cad9fe44e6ae1R69

See this branch which all functioning properly except for the display of the tooltips - the events are firing but I did not know what component we wanted to use.  

https://github.com/dotCMS/core-web/tree/issue-17707-nav-state

**Comment by fmontes** [comment]
## Final

**Comment by bryanboza** [comment]
Fixed, tested base on the final comment of @fmontes and everything works fine. 
Tested on release-5.2.4 //  Postgres // FF
