### ISSUE TITLE
Unable to lock content for editing as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17711]
Related to #17533 

After the changes in the related card, now we are unable to lock a piece of content for editing as a limited user. This because we save the available workflow actions in an Array and check if the array is empty then display the message since the lock is not an action. Then if all the available actions require to lock in order to use, then we are unable to lock because we show the message and not the lock for editing option. 

### To reproduce 
- Login as admin 
- Add full permissions to some limited user to publish content/files and also content types (https://www.screencast.com/t/npbIC3rZeYh)
- Reset all children and apply 
- Make sure the content type have the same permissions, if not give the same ones 
- Log in as Chris Publisher
- Try to lock the piece of content for editing  

### Expected behavior
If we don't have available options we need to show the message and also the option to lock if you have edit permissions. 

### Desktop (please complete the following information):
 Tested on master // Postgres // FF

**Comment by wezell** [comment]
@bryanboza question on this one - are there any actions available to the limited user if the content is locked?  If there are 0 actions available to the user whether the content is locked or unlocked then it is ok to should show the message and not display lock/unlock.

**Comment by bryanboza** [comment]
Yes, @wezell in this case you have full permissions to this piece of content, the save action in the published step needs lock for editing, also you can add a new custom action and have the same problem, I think we always should show the lock for editing option.

**Comment by john-thomas-dotcms** [comment]
I think the ideal case would be to **not** show these "default" lock/unlock actions

The reason is that these Lock/Unlock actions are **_not_** part of the workflows - they're the only remaining "default" actions left-over from when we used to provide default actions to all users based only on the users' permissions to the content, regardless of how the workflows were set up.  We removed the "default" Save, Save/Publish, etc. actions, but didn't remove the default Lock and Unlock actions.  They're left-overs from when it wasn't possible to fully control the workflows, and I think they don't belong any more.

The ideal case would be that the user should *only* have lock/unlock capability if they're provided by workflow actions which are defined in the workflow.  If the workflow doesn't have an action which allows the user to lock or unlock, then the user shouldn't be able to lock/unlock.

## The problem

Here's the problem with the current setup: If I, as an admin, want to prevent a user from being able to lock/unlock a piece of content, I can't.  No matter what I do with workflows, the user can always lock/unlock the content.

And here's the real world use case - it's a real problem we have with our own documentation content type now.

As an admin, I want to make sure that whenever a user locks a piece of content, that content is moved into the Editing step of the workflow.  So I've created a "Lock and Edit" workflow action which both locks the content and moves it into the Editing step.  And in the Editing step, I have an "Unlock and Discard Changes" action which unlocks the content and moved it out of the Editing step.

However, since we provide "default" Lock/Unlock actions, here are two problems:

1. When the user selects the "default" lock action, it locks the content **_without_** moving the content into the Editing step.
    * So the actions the user really should have on the content (such as Publish) aren't available to them.
    * It looks to the user like the content should be editable, but since the content didn't get moved into the right step, they don't have the right actions available.
2. If the content is in the Editing step, and the user selects the "default" unlock action, then it unlocks the content, but does **_not_** move the content out of the Editing step.
    * So again, the user has the wrong actions available for the content after it's been unlocked.

The problem in all these cases is this: I, as the admin, can't control what actions the user does and doesn't have available.  And the reason I can't control it is because we're providing "default" lock and unlock actions that I can do absolutely nothing about.

## Suggestions

So @bryanboza I think the issue here may not be with the code change, but that the System Workflow needs to be modified to add appropriate Lock and Unlock actions.

My suggestion then is to either:
1. Eliminate the "default" lock/unlock actions.
2. Add an option to the workflows which specifies whether the default lock/unlock actions should be provided or not.

I think #1 is the simpler option for both implementation and future maintenance.  It will require proper messaging in the changelogs, and will require a review and update of the System Workflow in and Documentation Management Workflows in the starter to make sure they don't leave users suck in a state where they can't edit content.  But it will get the Workflows fully consistent with where I think we originally intended them to be.

**Comment by nollymar** [comment]
I tried to reproduce this issue with @bryanboza but we couldn't. Apparently, a change was committed and fixed the problem

**Comment by bryanboza** [comment]
After retest the same steps now I'm unable to reproduce on master.  Need to close the card
