### ISSUE TITLE
"Add Class to Box" and "Add Class to Row" not functioning - dotcms 5x

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#17760]
### Describe the bug
In dotcms 5x the "Add Class to Box" and "Add Class to Row" functionality is not outputting the class name entered into the page HTML. 

### Steps to reproduce the behavior:
1. Open a Page Asset
2. Click on 'LAYOUT'
3. Choose the "..." button to "Add Class to Row" or "Add Class to Box"
4. Enter a class name
5. Save using the button at the top of the LAYOUT window.
6. Save/Publish page
7. View page/page source in browser

### Expected behavior
The box and/or row should have the class name entered on the LAYOUT window.

### Actual Behavior:
The Class name is not in the output HTML. It still exists in the LAYOUT window.

### Screenshots
![image](https://user-images.githubusercontent.com/49727631/71480598-8dd4ed00-27bf-11ea-8809-d728d3d96671.png)

![image](https://user-images.githubusercontent.com/49727631/71480611-9af1dc00-27bf-11ea-9ecc-a0d9d71e91c8.png)

![image](https://user-images.githubusercontent.com/49727631/71480649-d1c7f200-27bf-11ea-8e3e-5ec5a3f8ff70.png)

### Desktop (please complete the following information):
 - OS: n/a
 - Browser n/a
 - Version: 5x (client on 5.1.6, tested on demo)

**Comment by wezell** [comment]
@craigWagner99 I am pretty sure this is working - the catch is that the template code needs to be updated to actually display the class values in the rendered template.  I do not think this has been done on the old starter site that is running on `demo.dotcms.com`.  Here is what the template code should look like in order to reflect the classes:

![Screen Shot 2019-12-26 at 10 44 10 AM](https://user-images.githubusercontent.com/934364/71481665-d0e98d00-27cc-11ea-87e9-d48923a55962.png)
