### ISSUE TITLE
Vanity URL not working in not edit mode

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#18098]
### Describe the bug
When you create a new Vanity URL and just save it (not publish it), and then go to Edit Page in PREVI MODE and try to get the new Vanity URL, the response is 404.

### Steps to reproduce the behavior:
1. Create a new vanity URL and just save it
2. Create a new Code Snippet Widget and set the code as;
   `<a href="Vanity URL's url"></a>` 
3. Add the new widget in any page
4. Go to Site/Browser and open the page in PREVIEW_MODE
5. Click the widget link, and you should get a 404 HTTP error.

### Expected behavior
The Vanity URL should work in PREVIEW and EDIT Mode.

**Comment by alfredo-dotcms** [comment]
Not sure if this is a bug or this is expected on the app:

- when adding the value `<a href="www.facebook.com">link</a>` to the field `WIDGET CODE`, it returns a 404 HTTP Error, but it is because the browser is trying to load the url `http://localhost:8080/www.facebook.com 404`

- if you change that value and add "HTTPS": `<a href="https://www.facebook.com">link</a>`, you also get an ERROR, but it is a browser's security behaviour that it prevents it to stop loading pages from other domains inside the IFRAME of the EDIT/PREVIEW page.

- If you add `target="_blank"` to the value: `<a target="_blank" href="www.facebook.com">link</a>` you'll get a new tab and the link will load fine!

- if you set that value to an internal page `<a href="store/index">link</a>`, once you click on it in PREVIEW/EDIT you'll get redirected to the internal page.

**Comment by wezell** [comment]
Not going to fix.  I think respecting vanities in edit mode will cause more issues than it would solve.
