### ISSUE TITLE
Export content by date range fails

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#18128]
### Describe the bug
Attempting to export content that has been limited by a date range results in a blank page and no download with a 400 error in the developer console.

### Steps to reproduce the behavior:
1. Go to Content Search
2. Select Blog Comment
3. Select Advanced options
4. Enter [01/01/2010 TO 02/01/2020] in date box
5. Select all content
6. Select Export
7. Results in blank page and 400 error

### Desktop (please complete the following information):
 - OS:  OS X
 - Browser: chrome, safari
 - Version: 5.1.6, 5.2.6

## Acceptance Criteria

1. Match the design
2. Work in all the supported browsers (don't forget IE11 and iPad)
3. Multilanguage
4. Unit test

**Comment by notmattmonroe** [comment]
![Screen Shot 2020-03-11 at 9 25 35 AM](https://user-images.githubusercontent.com/44986962/76464522-88954080-63b3-11ea-9785-f5a46b8f1b4a.png)

**Comment by yolabingo** [comment]
I believe this may be due to the square braces that the Date Range query adds to the URL.
 `...Birthday.date,[20200101%20TO%2020300101]...` 

Any request with a square brace in the URL returns a 400 - I don't see anything in dotcms.log though
https://demo.dotcms.com/?q=foo[foo
https://demo.dotcms.com/foo[foo

The full URL for the Export request is for my sample content was:
`https://demo.dotcms.com/c/portal/layout?p_l_id=71b8a1ca-37b6-4b6e-a43b-c7482f28db6c&p_p_id=content&p_p_action=1&p_p_state=maximized&angularCurrentPortlet=content&p_p_mode=view&_content_struts_action=%2Fext%2Fcontentlet%2Fedit_contentlet&_content_cmd=export&_content_referer=%2Fc%2Fportal%2Flayout%3Fp_l_id%3D71b8a1ca-37b6-4b6e-a43b-c7482f28db6c%26p_p_id%3Dcontent%26p_p_action%3D1%26p_p_state%3Dmaximized%26angularCurrentPortlet%3Dcontent%26_content_struts_action%3D%2Fext%2Fcontentlet%2Fview_contentlets&expStructureInode=5850d85c-f1e1-45ed-905a-6bb27cde4a2c&expFieldsValues=Birthday.date,[20200101%20TO%2020300101],languageId,1&expCategoriesValues=&showDeleted=false&expCurrentSortBy=score,modDate%20desc&filterSystemHost=false&filterLocked=false&filterUnpublish=false`

**Comment by yolabingo** [comment]
Note this similar issue when trying to select a Workflow for date-range-filtered data, rather than Export data https://github.com/dotCMS/core/issues/19677
