### ISSUE TITLE
Turn off hostname/cert verification for ES by default

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18229]
We want to connect to elasticsearch endpoints via HTTPS.  By default, we cannot expect for all these endpoints to have valid HTTPS Certs.  We need to disable  SSL hostname verification and other SSL verifications (expiry, Cert chain) by default.

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18305

**Comment by nollymar** [comment]
Note to QA: By default cert verification is turned off. In case you want to enable it, set `ES_TLS_ENABLED=true` in `dotcms-config-cluster.properties`. Please verify the server starts up without troubles with different values of `ES_TLS_ENABLED`

**Comment by nollymar** [comment]
**Note to Doc:** By default cert verification is turned off. In case you want to enable it, set `ES_TLS_ENABLED=true` in `dotcms-config-cluster.properties`

**Comment by fabrizzio-dotCMS** [comment]
I tested starting dotCMS using both values in 
ES_TLS_ENABLED=true|false 
Taking into account that ES_PROTOCOL is by default https it works fine In both scenarios, the server is always able to connect to Elastic Search.

However, if I switch ES_PROTOCOL to "HTTP" then the property ES_TLS_ENABLED becomes meaningless. I would like to see more info in our logs to inform the user about what protocol is used and whether or not certificates are loaded. Also, inform that if the protocol of choice is "HTTP" then certificates are ignored and warn about the unsecured connection.   

when the protocol is HTTP it is not possible to reach Elastic search. I imagine that's because ES Server is configured to accept only https requests.

**Comment by nollymar** [comment]
I have included more logging info: 

- When http protocol is used a warning with this message will be displayed: `Initializing Elastic RestHighLevelClient using an unsecured http connection`. Otherwise, you will see a logger info that will say: `Initializing Elastic RestHighLevelClient using a secured https connection`

- When `ES_TLS_ENABLED=false`, a warning with this message will appear: `Elastic RestHighLevelClient will be initialized without certificates`

**Comment by dsilvam** [comment]
Passed QA: Able to connect in both scenarios `ES_TLS_ENABLED=true|false` and also getting the proper messages in the log for each scenario and also when `ES_PROTOCOL=http`

**Comment by wezell** [comment]
This needs work - I am getting this when trying to connect to the out of the box opendistro

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/core/pull/18455

**Comment by nollymar** [comment]
Note to QA: Test using a `ES_HOSTNAME` different to `elasticsearch` and `127.0.0.1`

**Comment by nollymar** [comment]
Passed internal qa. Results: OK. 

Tested scenarios: 
- Running `02-single_node` docker implementation with a custom `ES_HOSTNAME`. It was set using this environment variable: `PROVIDER_ELASTICSEARCH_DNSNAMES`
- Running dotcms locally using an unsecured (http) connection
- Running dotcms locally using a secured connection (https) and `TLS_ENABLED=false`
- Running dotcms locally using a secured connection (https) and `TLS_ENABLED=true`
