### ISSUE TITLE
PP Filters: Allow filter for donwload bundles

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#18293]
As a PP user, I want to be able to select a filter when downloading a bundle for publish, since the download for unpublish is like the Remove option of PP, filters are not applied.

## Steps
1. Add to a Bundle any content.
2. Go to Publishing Queue > Bundles
3. Click over the SubActions of a Bundle (button with three dots on the right).
4. Download

## Mockup for the dialog
![Screen Shot 2020-07-06 at 12 04 14 PM](https://user-images.githubusercontent.com/5278970/86624605-d1838d00-bf80-11ea-9ad4-4dd4cb7bcfd8.png)

**Comment by erickgonzalez** [comment]
PR core-web: https://github.com/dotCMS/core-web/pull/1377/files

**Comment by erickgonzalez** [comment]
We have a few issues here:
* The extension of the file is being changed from `tar.gz` to `gz`, we need to keep the original extension since it's the one we allow when uploading bundles. In Chrome, there is no extension present.
*  The filename that was generated `filename=" + bundleName + "-" + bundle.getName()` it's being override with a auto-generated name

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18950

**Comment by bryanboza** [comment]
- We need to select the "force" as default filter, this because is how it works before that changes

**Comment by erickgonzalez** [comment]
After discussing this is ok for now, improvements on how will behave https://github.com/dotCMS/core/issues/19048
