### ISSUE TITLE
"What's Changed" Feature does not detect content changes on the page

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#18356]
Tested on latest 5.2.8 version

Content changes are not detected even on simple webpage content in Preview Mode on a page:

<img width="1414" alt="Screen Shot 2020-04-24 at 10 56 10 AM" src="https://user-images.githubusercontent.com/1569167/80237677-5e71a800-861a-11ea-8cdd-030ba581f47d.png">

Here is how to reproduce:

![WhatsChanged](https://user-images.githubusercontent.com/1569167/80237693-66c9e300-861a-11ea-8927-214f8178167a.gif)

**Comment by fabrizzio-dotCMS** [comment]
PR:
https://github.com/dotCMS/core/pull/18473   
https://github.com/dotCMS/enterprise-2.x/pull/726

**Comment by nollymar** [comment]
**Note to QA:** Please ask @fabrizzio-dotCMS for the data to test this issue

**Comment by alfredo-dotcms** [comment]
tested and looks fine
![image](https://user-images.githubusercontent.com/37185433/82268135-742d7100-992b-11ea-8a39-b1c6456f2515.png)

**Comment by alfredo-dotcms** [comment]
*Note:

another bug was found on `What's Changed` view. The `title` of the page is being added at the beginning of the page

![image](https://user-images.githubusercontent.com/37185433/82268205-afc83b00-992b-11ea-8c69-3ec74a3e9c97.png)

**Comment by bryanboza** [comment]
Error when you add a form to a page and then try to use the what's changed. We need some work here. 
ST: https://gist.github.com/bryanboza/18d616f4bcf4e46766274236b2f1c259

**Comment by fabrizzio-dotCMS** [comment]
Regarding the issues found by QA.
**We're looking at two separate things here.** 

1. The Form isn't rendered at all because it is all built via javascript. 

It looks something like this on the resulting page prior to comparission:

```
<dot-form id="form_1591157910794" variable='Contact'></dot-form>
<script type="text/javascript">
 document.getElementById('form_1591157292594').layout = [{"divider":{"modDate":1591124162000,"indexed":false,"dataType":"SYSTEM","contentTypeId":"897cf4a9-171a-4204-accb-c1b498c813fe","readOnly":false,"searchable":false,"required":false,"fieldTypeLabel":"Row","listed":false,"unique":false,"sortOrder":0,"name":"fields-0","variable":"fields0","fieldVariables":[],"fieldContentTypeProperties":[],"fixed":false
....
</script>

```
Then the diff comparator applies a set of transformations. Some of which are deffined in the file:

**_/core/dotCMS/src/main/resources/diff/xsl/cleanup.xsl_**

One of those transformations is removing all embedded javascript code.

```
<xsl:template match="@*[starts-with(., 'javascript:')]">
   <!-- remove script attribute ! -->
</xsl:template>
```
So the resulting "whats changed diff" has as a result all the javascript code stripped off. 
I imagine these rules are there for a reason. Looking for other versions of the file `cleanup.xsl` online they all work under the same model. 

So I think this is a **limitation** that the HTML diff tool has. 


2. The Exception reported by QA. 

```
ERROR services.DotResourceLoader - filePath: /LIVE/e43ab447-a137-4cb4-a8e7-bee1872afc38_1.contentlet, msg:cannot find content for: VelocityResourceKey [path=/LIVE/e43ab447-a137-4cb4-a8e7-bee1872afc38_1.contentlet, language=1, id1=e43ab447-a137-4cb4-a8e7-bee1872afc38, id2=null, type=CONTENT, mode=LIVE] @ url:GET//demo.dotcms.com/html/portlet/ext/htmlpages/view_live_working_diff.jsp | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:true | start:06-03-2020 10:10:21 CST  ref:http://localhost:8080/dotAdmin/  ?id=2968e2ee-d1b7-4758-9419-2440ae4f38ec&pageLang=1&in_frame=true&frame=detailFrame&container=true&angularCurrentPortlet=edit-page&url=/lol/page2&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797
org.apache.velocity.exception.ResourceNotFoundException: cannot find content for: VelocityResourceKey [path=/LIVE/e43ab447-a137-4cb4-a8e7-bee1872afc38_1.contentlet, language=1, id1=e43ab447-a137-4cb4-a8e7-bee1872afc38, id2=null, type=CONTENT, mode=LIVE]
	at com.dotcms.rendering.velocity.services.ContentletLoader.writeObject(ContentletLoader.java:570) ~[dotcms_master_bb46ef3.jar:?]
	at com.dotcms.rendering.velocity.services.DotResourceLoader.getResourceStream(DotResourceLoader.java:48)
```

It is caused by the rendering mechanism trying  to find a live version of the contentlet that isn't present. The exception gets reported as an error and then gets ignored. The Rendering process continues and the rest of the elements are presented as expected. Meaning the page isn't broken at all. It's an expected "Error" that probably should be presented as a Warning. 

Maybe We should change the error level on this one.

**Comment by fabrizzio-dotCMS** [comment]
Change the Level of the message from Error to Warning 
PR #18590 https://github.com/dotCMS/core/pull/18590

**Comment by bryanboza** [comment]
Fixed, the error was changed to a WARN and the forms problem was moved to a new card. Tested on release-5.3.2 // Postgres // FF
