### ISSUE TITLE
Session timeout does not work.

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#18465]
Currently the session timeout (either set through portal.properties or web.xml) is not logging out backend users after the timeout period.  Replicated on 5.2.0 and 5.2.8.

**Comment by alfredo-dotcms** [comment]
this happens in current master, and the fix needed since to be in the BE

the test I did was, with the socket web socket viewer connected, I logged into the app and checked that I was getting notifications from the app (making a reindex).
![image](https://user-images.githubusercontent.com/37185433/82587822-17ae9980-9b57-11ea-8902-6553b317b8f6.png)

I changed previously the session value for `3` minutes at https://github.com/dotCMS/core/blob/197c338287f5b7cbc9728fd280a337dd59e7e8e8/dotCMS/src/main/webapp/WEB-INF/web.xml#L535

then I waited for 3 minutes and did not get any timeout notification from the BE

then I waited for 30 minutes (just to see if the 3 minutes values was not set properly, so it would use the default value 30 minutes), and no notifications were sent by the BE.

talking with @freddyucv about, he thinks the fix could be around here https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/listeners/SessionMonitor.java#L118, something changed and the BE is not emitting notifications on timeout event

**Comment by yolabingo** [comment]
cloud support ticket https://dotcms.zendesk.com/agent/tickets/107834

**Comment by yolabingo** [comment]
The web.xml setting appears to be respected. Setting 
```
    <session-config>
        <session-timeout>1</session-timeout>
    </session-config>
 ```
 in  `dotserver/tomcat-9.0.41/webapps/ROOT/WEB-INF/web.xml`

does set the timeout to 1 minute
