### ISSUE TITLE
Can't open a page when you have changed the default language

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#18520]
### Describe the bug
When you set the default language to non-English, for instance Spanish, then it's not possible to open an English page in the dotCMS back-end. You get an error that the page does not exist:

![afbeelding](https://user-images.githubusercontent.com/2195163/82307488-b359d180-99c0-11ea-81fc-9a99a2de852f.png)

I was not able to reproduce this with English as the default language, but when using Spanish I was able to reproduce it on dotCMS 5.2.8 and 5.2.6.

Since most of our dotCMS instances have Dutch as the default language this is quite an issue for us.

### Steps to reproduce the behavior:
1. Download a clean dotCMS 5.2.8
2. Set the dotmarketing-config-ext.properties in the com.dotcms.config plugin as follows:
`DEFAULT_LANGUAGE_COUNTRY = Spain
DEFAULT_LANGUAGE = es_ES
DEFAULT_LANGUAGE_CODE = es
DEFAULT_LANGUAGE_STR = Spanish
DEFAULT_LANGUAGE_COUNTRY_CODE = ES`
3. Run deploy-plugins
4. Start dotCMS
5. Log in on localhost:8080
6. Go to the site browser
7. Change the language to English (there are no Spanish pages)
8. Open the index page by double-clicking on it

### Expected behavior
You would expect dotCMS to just open the page. This error does not happen when you try to open a Spanish page or even a French page.

### Extra info
I've looked into the code and I think that dotCMS tries to open the page in the wrong language or that it expects to also have the page available in the default language. Maybe the language switch doesn't change the language correctly? It should be possible to open the page using http://localhost:8080/api/v1/page/render/index?language_id=1 but that returns a 500 on the demo site. So maybe there are 2 issues here.

We also have a dotCMS where we have switched the NL and EN language ids in the database (so NL=1, EN=5), and there we have the same issue with EN pages but we are able to open an EN page using ?language_id=5 in the browser URL or in the /page/render URL. 

### Desktop (please complete the following information):
I've tried this on Windows with dotCMS 5.2.8 and the H2DB but we also have this issue on Linux with dotCMS 5.2.6 and Postgres.

**Comment by hmoreras** [comment]
looks like a BE, issue, log: https://gist.github.com/hmoreras/02de3a6322d53d037aa2f5233eda82be assingning to Ercik after a conversation.

**Comment by erickgonzalez** [comment]
This is not a bug, this is because all the files related to the theme are in English (this is how we ship our starter test site), so when dotcms are trying to get these files there are not found. 
The theme files must be created in the default language.

If a customer wants to change the default language, we allow that but the customer needs to create everything from scratch because the data and assets we ship in our starter are for English as the default language.

I use our empty starter and uploaded one theme, created a container, template, and a page in English (non-default language) and was rendered without the error. 
Even though I found some issues:
https://github.com/dotCMS/core/issues/18766
https://github.com/dotCMS/core/issues/18767
https://github.com/dotCMS/core/issues/18768

**Comment by fmontes** [comment]
We need write a document to indicating: "How to change your default language" and pass it to documentation.

**Comment by erickgonzalez** [comment]
**Note to Doc:**

If a customer wants to change the default language everything has to be created from scratch (use the empty starter) because the theme files/assets for rendering pages need to be created in the default language.

If for any reason the customer wants to use the full starter, they will need to re-upload all the files/assets related to themes in the new default language. 
The best way to achieve this is via WebDav:
1- Connect to the English language, e.g: `http://localhost:8080/webdav/live/1`
2- Navigate to the themes folder: `http://localhost:8080/webdav/live/1/demo.dotcms.com/application/themes`
3- Download both theme folders (travel and landing-page).
4- Disconnect of the server.
5- From the UI, delete both theme folders.
6- Connect to the new Default language, e.g: `http://localhost:8080/webdav/live/155813841862`
7- Navigate to the themes folder: `http://localhost:8080/webdav/live/155813841862/demo.dotcms.com/application/themes`
8- Upload both theme folders.
9- Disconnect of the server.
10- From the UI, check that both theme folders exist and that the files/assets inside are in the default language.

Another way to achieve this is from the UI:
1- Edit each file/asset inside the themes 
2- Change the language in the dropdown on the right corner of the dialog
3- A pop-up will show asking you if want to populate the content using the English content
4- Click Yes
5- Save and Publish

But we don't recommend this way since there are a lot of files inside the theme folders and the process is very slow.

**Comment by john-thomas-dotcms** [comment]
Just a note @erickgonzalez - using webdav only works for File Assets.  For all other content, the way to do this is either through the UI or using REST.  In our existing doc, we already say that if you change the default language, you need to update any existing content to the new default language, but I'll add some more specific recommendations and steps in there.
