### ISSUE TITLE
Push Publishing Notifications

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18553]
When PP a bundle we need to show a growl to the user saying the status of the bundle `Success/Failed...`.

### Success
The growl notification should show something like:
* If the Bundle has a name set, show the name: 
`Bundle Named {name} successfully published`
* If it does not have a name set by the user (it starts with bundle-), show title (assetType: assetTitle):
`Bundle that includes {title} successfully published`

Time: This message should automatically dismiss after 5 seconds.

Severity: SUCCESS

To whom should be shown: User that performed the push.

### Failure
The growl notification should show something like:
* If the Bundle has a name set, show the name: 
`Bundle Named {name} failed to publish to see details click here {link to bundle detail dialog with info}`
* If it does not have a name set by the user (it starts with bundle-), show title (assetType: assetTitle):
`Bundle that includes {title} failed to publish to see details click here {open bundle detail dialog with info}`

Time: Shown when re-publish attempts are reached and Until user dismiss it.

Severity: ERROR

To whom should be shown: User that performed the push.

**Comment by john-thomas-dotcms** [comment]
Message suggestions:

**Comment by john-thomas-dotcms** [comment]
Some thoughts on the questions above:

**Show the time?**

For a growl, I'm not sure we need to, do we?  Unless we're going to implement the ability to show older growls when a user logs in (and in that case, then yes, we should probably show the time in all growls, not just these - so I don't think it would affect the message format for these particular notifications).

**Suggestions for the message format:**

Success:

* `Bundle "{name}" successfully {published/downloaded}`
* `Bundle containing "{title}" and {count} other assets successfully {published/downloaded}`

Failure:

* `Bundle "{name}" failed to {publish/download}.<br/>For more information, please <a href="{link}" target="_blank">click here</a>`
* `Bundle containing "{title}" and {count} other assets failed to {publish/download}.<br/>For more information, please <a href="{link}" target="_blank">click here</a>`

Not sure if we can add line breaks into the growls, but if we can it would be good to use them for the failure messages, to separate the failure message from the info about the response to the failure.

**Who should see it**

I think ideally only the user that attempted to perform the push/download would see it - otherwise on large systems alot of users will get spammed by push messages they have no need to know about.

**When to show**

Probably just when retry attempts are exceeded - though there's definitely a case for showing every failure.

If we decide to show a message with every failure, then we need a different method on a failure which will be retried:

* `Bundle "{name}" failed to {publish/download}.<br/>Retrying in {time in human readable format}`
* `Bundle containing "{title}" and {count} other assets failed to {publish/download}.<br/>Retrying in {time in human readable format}`

**Comment by fishsmith** [comment]
My understanding of the time was, how long should the growl appear for before closing. Id so, I think 7 secs on success and on failor it should require the user to dismiss it.

I agree with John Thomas that it should show to user who attempted the push.

**Comment by erickgonzalez** [comment]
PR core-web new severity: https://github.com/dotCMS/core-web/pull/1376 and https://github.com/dotCMS/core-web/pull/1379

**Comment by erickgonzalez** [comment]
Right now it's redirecting to the `Publishing Queue Portlet` that's ok for now. 
As an enhancement, this issue was created https://github.com/dotCMS/core/issues/18930

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/18937

**Comment by erickgonzalez** [comment]
To Test Failure Notification:
* Create a content type
* Create a contentlet of the content type above
* PP the contentlet using the `Only Selected Items` filter.

Since the Content-Type does not exist in the receiver the PP should fail.

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.6 // Postgres // FF
