### ISSUE TITLE
Unable to pull related content through REST API with language ID other than 1

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#18635]
### Describe the bug
We are trying to upgrade dotCMS from version 5.1.6 to version 5.2.8, but have an issue with the new relationship fields and/or the new embedded ElasticSearch version 6.1.3 in combination with multiple languages and the Content REST API.

### Steps to reproduce the behavior:
If we try to pull all blog post of author John Smith on demo.dotcms.com with a REST API call and languageId 1, then we get 3 results as expected:
https://demo.dotcms.com/api/content/query/+contentType:Blog%20+languageId:1/related/Blog.author:f851e34a-d128-408e-a75a-4fa1c33201b8

But if we try to pull all blog post of author John Smith with languageId 2, then we get an empty result (but we would expect 1 result):
https://demo.dotcms.com/api/content/query/+contentType:Blog%20+languageId:2/related/Blog.author:f851e34a-d128-408e-a75a-4fa1c33201b8

If we use the languageId 2 as part of the URL or as an URL parameter, we get 3 results, but in the wrong language (language 1 instead of language 2):
https://demo.dotcms.com/api/content/query/+contentType:Blog/languageId/2/related/Blog.author:f851e34a-d128-408e-a75a-4fa1c33201b8
https://demo.dotcms.com/api/content/query/+contentType:Blog/related/Blog.author:f851e34a-d128-408e-a75a-4fa1c33201b8?languageId=2

So the languageId other than 1 is not respected when pulling related content through the REST API.

### Expected behavior
The REST API should return related content in the requested language.

### Additional context
We are relying on related content pulls through the REST API with multiple languages and therefore cannot upgrade to dotCMS 5.2.8, as long as this issue is not solved.

With dotCMS 5.1.6 and the old legacy relationships and the old embedded ElasticSearch version 1.7.3 we had no issues like this.

**Comment by wezell** [comment]
@nollymar please verify the correct behavior here.

**Comment by nollymar** [comment]
@splotzky , 

Firstly, I want to apologize because there is a typo in our documentation. The path param to filter by language in the Content Rest API is `language` instead of `languageId`. I have already reported the issue and will be fixed soon. Please take this into consideration because it is affecting your results.

On the other hand, I'd like to explain the criteria used by the Content Rest API  to pull related content. **It only considers the path param `language` when related content is filtered regardless you are using `+languageId` in the lucene query. If `language` is not provided, the default language is used instead** 

Here some examples: 

1) https://demo.dotcms.com/api/content/query/+contentType:Blog%20+languageId:1/related/Blog.author:62db4b0d-a26b-4132-977f-2e792983939f 

returns the related blog in English as `language` is not provided and the default language is used instead

2) https://demo.dotcms.com/api/content/query/+contentType:Blog%20+languageId:2/related/Blog.author:62db4b0d-a26b-4132-977f-2e792983939f

returns an empty list because `+contentType:Blog%20+languageId:2` would return a blog in Spanish, but `language` is set to default 

3) https://demo.dotcms.com/api/content/query/+contentType:Blog%20+languageId:2/language/2/related/Blog.author:62db4b0d-a26b-4132-977f-2e792983939f

returns the Blog in Spanish, because `+contentType:Blog%20+languageId:2` would return a blog in Spanish and the `language`=2

4) https://demo.dotcms.com/api/content/query/+contentType:Blog%20+languageId:2/depth/1
returns a Blog in Spanish but Authors in English (as `language` is set to default)

5) https://demo.dotcms.com/api/content/query/+contentType:Blog%20+languageId:1/depth/1
returns both Blog and Authors in English

_To avoid confusion, the general rule to pull related content is to use the `language` path param instead of the `+languageId` in a lucene query._

**Comment by splotzky** [comment]
All right, the typo in the documentation was the problem.

**Comment by splotzky** [comment]
@nollymar @wezell ,
The documentation has not yet been corrected:
https://dotcms.com/docs/latest/content-api

**Comment by wezell** [comment]
@john-thomas-dotcms see above
