### ISSUE TITLE
Login as is not respecting the selected language if you are not using the default 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#18794]
If you change the language of the system to anyone different to the default, and then try to use the login as feature, we are changing automatically the language to the default one instead allow continue navigating with the selected

After login-as everything is in the selected language but the left menu is in the default language
![image](https://user-images.githubusercontent.com/2641437/85903570-db103680-b7c3-11ea-8394-fa0484623217.png)

## To recreate
- In the login window select Spanish as language
- Login 
- Login as Chris Publisher 
- Make sure you continue navigating in Spanish

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/18533#issuecomment-650249765_

**Comment by fmontes** [comment]
As we discuss in Slack "language should not change at all when using the “Login As” feature"

https://dotcms.slack.com/archives/CE1TBQU00/p1593438517006500

**Comment by jdotcms** [comment]
Currently if an user A, gets login in French for instance, this locale will be associated to the user table.
Consequently when a user B, get login in any other language, such as Spanish for instance and get login as an user A; the language on the menu will be French since the language taken to translate the menu is the latest locale saved in the last login of the user A.

The fix will be to take the same language of the user B, which is the one that is doing the login as or the actual login. I means, all screen including the menu will be in Spanish for this particular example
