### ISSUE TITLE
Push Publishing: Parent not pushed in a self-join relationship

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#18804]
After changes implemented here: https://github.com/dotCMS/core/issues/18775. Now, if the child is pushed in a self-join relationship, the parent is not pushed as well.

Note to QA: Please, verify with this fix that legacy relationships works correctly

**Comment by nollymar** [comment]
Fixed: https://github.com/dotCMS/core/pull/18797

**Comment by fabrizzio-dotCMS** [comment]
Tested using the following set up.
Created a custom Parent Content-Type and a Child Content-Type both had a relationship field pointing to each other.
The Parent-CT had a (One-to-Many) children relationship field that pointed to Children-CT and vice-versa.

In All the following scenarios the changes are sent correctly:

- I created two instances (Parent and child) then pushed the child. &#10003;
- Modified the parent and pushed the child. &#10003; 
- Modified the child and pushed the parent. &#10003; 
- Created a second child item and relate it to the parent (so the parent now has two children) then pushed the child. &#10003; 
However sending a new child that is related to the parent does not add the new child to the parent (You have to flush cash in order to see that work).  Apparently this is a known issue already reported.
- Adding children and sending the parent sends all the child items. &#10003; 

Also tried setting up an environment on top of 5.0.0 then created another custom CT this time using the legacy relationships 
Then Ran an upgrade over the database created by the 5.0.0 dotCMS instance. Opened the Content types and tied pushing from the parent and from the children. They all seemed to work correctly when sending the content with legacy relationships.

Therefore I am passing this issue

**Comment by wezell** [comment]
does this also fix #18571

**Comment by bryanboza** [comment]
Fixed, tested on release-5.3.4 // Postgres // FF and now it is working as expected 

This configuration on both servers
