### ISSUE TITLE
2 Nodes can pick the same license

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18860]
There are two cases we need to fix here:

1. **If you have license pack, it is possible for 2 nodes to select the same license.**  This means that one of these servers does not register itself into the sitelic table.  If a server is not in the sitelic table, it will not be registered in dotCMS as a valid part of the cluster.  We need to avoid servers being able to pick the same license.
To test, bring up a cluster without licenses and upload a license pack.

2. **You can have two servers that share a serverId.** ServerIds should be unique to each dotCMS instance. Sometimes, when setting up a cluster, customers clone a server (including the `/dotsecure` folder) and point it at the same db, then two servers end up sharing the same Server Id.  This causes issue with the cluster as each server tries to take the same license and cannot register themselves. 

I think we need to add a column to the sitelic table which is called `startup_time` that records the value of:
`long jvmStartTime = ManagementFactory.getRuntimeMXBean().getStartTime();`.  In the process of updating the sitelic record, we should make sure to only update the sitelic record where the `startup_time` matches the JVMs `getStartTime()`.  If the server_ids match but the `getStartTime()`, then we know two servers are sharing a server_id and we should throw a warning in the logs.

**Comment by wezell** [comment]
We need to do a 2 phased SQL commit/lookup before applying a license.  A server should attempt to pick up a license, then check the db to make sure the license pickup worked.

**Comment by dsilvam** [comment]
PR ee: https://github.com/dotCMS/enterprise-2.x/pull/758

**Comment by victoralfaro-dotcms** [comment]
QA Note
--------
For both scenarios it is required to set up a 2 node enviroment.
For scenario #1:
- Remove data from `sitelic` table and from dotsecure for each node
- Start up one node and sign in
- Start the other one and sign in
- At the first node, go to System->Configuration->Licensing and upload a license pack with at least 2 licenses
- Make sure each server picks a different license: visible in the UI or by querying `sitelic` table

For scenario #2
- Remove data from `sitelic` table and from `dotsecure` for each node
- Start up a node
- Setup a node with a single license (Go to System->Configuration->Licensing and paste a license raw data)
- Copy `license` folder from configured node `dotsecure` location to unset node's `dotsecure` location
- Since each node will "feel" like the owner of the only license stored in `sitelic` table verify an error message is logged at server heartbeat frequency

**Comment by dsilvam** [comment]
**Passed Internal QA:** Both scenarios tested with the expected results. We suggest an enhancement though; including a Growl notification when more than one node in the cluster use the same serverid, in addition to the entry in the log.

**Comment by bryanboza** [comment]
Fixed, tested based on the comments and now it works as expected,  I moved the suggested enhancements by @dsilvam to a new card.  #18769
