### ISSUE TITLE
Remove unneeded icu4j

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18927]
We have an unneeded jar in our classpath 
`dot.icu4j-4.0.1_2.jar`

It prevents dotCMS from running in the latest versions of java 8, e.g. >=8.0.262
We need to remove it and references to it.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/core/pull/18933

**Comment by Xhiro-Yui** [comment]
I have just deployed dotCMS on an AWS instance yesterday and I am now facing this issue

`Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.dotcms.repackage.com.ibm.icu.text.SimpleDateFormat
at com.dotcms.rendering.velocity.services.PageRenderUtil.populateContext(PageRenderUtil.java:192) ~[dotcms_5.3.4.1_632e54f.jar:?]
at com.dotcms.rendering.velocity.services.PageRenderUtil.<init>(PageRenderUtil.java:114) ~[dotcms_5.3.4.1_632e54f.jar:?]`

Was the library already removed as now I am unable to view preview of my pages?

**Comment by dsilvam** [comment]
QA Done here: https://github.com/dotCMS/core/issues/18917

**Comment by dsilvam** [comment]
@Xhiro-Yui the library was not removed from artifactory

**Comment by jcastro-dotcms** [comment]
The official code changes have been included in the dotCMS 5.2.8.4 LTS release. Code changes were part of the dotCMS 5.3.8.4 LTS release already.
