### ISSUE TITLE
Allow Config properties to be overridden by environmental variables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18968]
We have a ton of properties that can be configured in the `dotmarketing-config.properties` and the `dotcms-cluster.properties`. When running dotCMS in docker, we have a few env variables that we allow to be passed in, but it would be nice if there was a way to override any of the properties set the `.properties` files by passing in environmental variables - that way when we add a new config variable, it is possible to configure it from our docker image without having to edit our docker image config scripts.

### A few rules:
- We have many environmental variables that are lowercase with periods separating, e.g. `cache.default.chain`.   Periods are not allowed in environmental variables. When looking for the environmental variable for a dotCMS variable, we will convert the dotCMS variable to uppercase and replace the periods with underscores
- We will only return values for environmental variables prefixed with "DOT_".  This will prevent variable collisions and will provide a bit of security when someone tries to call  `Config.getString("UID")` - we would look/return only the environmental variable `DOT_UID`
- So, in our previous example, to set the value for `cache.default.chain`, you would set an environmental `DOT_CACHE_DEFAULT_CHAIN`

**Comment by wezell** [comment]
PR: #19017

**Comment by fabrizzio-dotCMS** [comment]
I wrote a vtl like:
```
apps:  $config.getStringProperty("APPS_DIR_PATH_KEY") <br>
token: $config.getStringProperty("json.web.token.max.allowed.expiration.days") <br>
```
 then I override those two properties through the environment variables by doing 

```
export DOT_APPS_DIR_PATH_KEY=/Users/fabrizzio 
export DOT_JSON_WEB_TOKEN_MAX_ALLOWED_EXPIRATION_DAYS=7777
```
Then I start up the server and load the VTL code from above.

and I get the following result.

![Screen Shot 2020-08-17 at 14 42 18](https://user-images.githubusercontent.com/37148755/90444995-28aa7080-e09c-11ea-8b4b-c62742aba542.png)

The variable has been overridden but it comes back with the expected value twice.
if for example, I attempt to override the YML files folder on apps via environment vars the portlet fails to load b/c the folder path is useless since it has dupped its original value.

additionally, I think that if we refresh the properties values read from disk we should probably do the same for environment variables. I wasn't able to see the new values if I modify the environment var on a running tomcat.

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/19129

**Comment by nollymar** [comment]
Passed internal qa

**Comment by bryanboza** [comment]
Fixed, Tested based in the @fabrizzio-dotCMS comment, and I'm able to override variables and we are showing this just once. Tested on release-5.3.7 // Postgres // FF

**Comment by john-thomas-dotcms** [comment]
Documented: https://dotcms.com/docs/latest/changing-configuration-properties#EnvironmentVariables
