### ISSUE TITLE
We need to escape the site alias field

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19112]
Reported in a POC Environment.
Reproducible in dotCMS 5.3.4, and latest master.

Site Aliases in a Site allow users to add Site aliases separated by:

- New lines
- Commas
- Blank spaces

Currently, we are using line breaks as a delimiter but carriage returns and JavaScript don't play well together. We need to be sure that when returning the aliases that they are properly escaped.  Additionally, we should limit the characters allowed in the site alias field to the charset allowed for domain names + commas and line breaks.

Our current way of storing the site alias was causing a variety of problems in the POC environment, specially rendering the **Templates** portlet unusable.

**To Reproduce**
**NOTE: This was reproducible in a POC environment from a VERY important prospect. It might have been caused by hidden additional characters in the new line breaks as well, so it might not be easy to reproduce.**

**Expected behavior**
We should replace new line breaks with commas or blank spaces.

**Additional context**
For the specific POC environment, going to the Site and replacing each line break with a blank space solved their problem. During the screenshare, the customer was able to demonstrate the exact JavaScript error that came up because of the line breaks in the Site Aliases.

**Comment by john-thomas-dotcms** [comment]
With line breaks in the Aliases field, it caused the JS in the Templates screen to break.  Although this was the only portlet we know broke due to the line breaks in the aliases field, I suspect there may be others we just haven't found yet.  So we could go look for places where the aliases are used and sanitize them all, or just sanitize what gets saved in the aliases field.

We suspect, however, that the line breaks in the aliases also caused the reindex to fail.  We suspect this because the previous reindex failed, but when the line breaks were removed, the reindexes worked.  Not 100% confident about this, since we don't know when the previous (failed) reindex was run - we just saw the red errors on the reindex tab (and didn't have a chance to read the details before a new reindex was started); but it would make alot of sense.

I'll note that I've seen a number of other issues over time when the aliases field is not in the proper format (using commas and other things).  So I suspect that the safest bet overall is to just change the field to automatically sanitize the list into a standard format (with aliases separated by just spaces).  This would allow us to make a change one place (when the field is saved), and avoid potential problems everywhere it's used.

So I'm fine with however we want to address it.  But I think just saying the aliases should be in a certain format - and then enforcing that on save - would probably require the least amount of effort and provide the most reliable across-the-board fix.
