### ISSUE TITLE
Add the option to show fields in a relationship field's overview

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#19215]
In the past we had relationships, and in the list of related content you had some control over which fields were displayed. These were the same as in the content overview. For instance the field "Payment engine" in this overview:

![image](https://user-images.githubusercontent.com/2195163/91992949-0f105680-ed35-11ea-96e0-0c39566d5182.png)

But with relationship fields these fields are not shown: (same content but with relationship fields)

![image](https://user-images.githubusercontent.com/2195163/91993076-40892200-ed35-11ea-893b-4d853a0bb9d9.png)

Perhaps you could re-add the option to show the same fields as in the Content Search, or possibly add a property to the field in which you can name which fields should be displayed? For instance the language is not interesting in many of our sites. An example of how it could work:

`showFields: ['title','paymentEngine','language']`

**Comment by john-thomas-dotcms** [comment]
This is a change from prior behavior, so I've marked this as a bug, instead of an enhancement.  It makes it difficult to manage related content using relationship fields.

Customer ticket with use case showing why this is a problem: https://dotcms.zendesk.com/agent/tickets/104146

In this customer use case, they're relating to content which contains fields for a person's name and title.  So, when relating content, all they see is the person's title - not the person's name.  And since the title can have duplicate values, this makes it very difficult to relate the correct content.

The relate content popup should show all the fields which are marked as "Show in List" on the content type (just like it used to do for legacy relationships).

**Comment by wezell** [comment]
Let's use a field variable to achieve this - called `showFields` that takes a comma separated list of the fields you want to display.  If this is added and has fields that are valid, we should show then instead of what is there.  There are a few special field vars, e.g.
`titleImage` = the thumbnail
`title` = content title
`languageId` = flag

**Comment by dsilvam** [comment]
**Needs work**.

Few things found:

1. If you use valid fieldVars in the `showFields` field variable, the thumbnail shouldn't always be shown, but only if `titleImage` is included. Currently is always shown as the first column. 
2. If you add `titleImage` the titleImage of the parent contentlet is showing instead of the titleImage of each child
3. The horizontal scroll is not showing when needed and the relationship field is overlapping with other fields

<img width="1031" alt="Screen Shot 2021-07-08 at 11 57 26" src="https://user-images.githubusercontent.com/1576794/124962738-9b8a4600-dfe4-11eb-99f4-5d6b3cc66dfa.png">

**Comment by victoralfaro-dotcms** [comment]
> **Needs work**.
> 
> Few things found:
> 
> 1. If you use valid fieldVars in the `showFields` field variable, the thumbnail shouldn't always be shown, but only if `titleImage` is included. Currently is always shown as the first column.
> 2. If you add `titleImage` the titleImage of the parent contentlet is showing instead of the titleImage of each child
> 3. The horizontal scroll is not showing when needed and the relationship field is overlapping with other fields
> 
> <img alt="Screen Shot 2021-07-08 at 11 57 26" width="1031" src="https://user-images.githubusercontent.com/1576794/124962738-9b8a4600-dfe4-11eb-99f4-5d6b3cc66dfa.png">

This has been taken care of.

**Comment by dsilvam** [comment]
Still happening to me. Tested on Docker on image `21.07_prerelease_5416d7f`

**Comment by dsilvam** [comment]
**Passed Internal QA:** Issues reported properly addressed

**Comment by bryanboza** [comment]
Fixed, tested on release-21.07 // Postgres // FF

**Comment by dsilvam** [comment]
@victoralfaro-dotcms this one needs a Google doc on how to set it up and pass it to @rweiner

**Comment by jcastro-dotcms** [comment]
Note to Doc: @rweiner In practice, the Field Variable for the `showFields` property is added like this:

- Go to the Content Type that is displaying the **Relationships** field, and edit it.
- Click the **FIELD VARIABLES** tab.
- The `showFields` property contains a comma-separated list of the Velocity Variable Names of each column that will be displayed. For example, if the child Content Type has two fields: `Name`, and `Department`, the property will look like this:
-- Key = `showFields`
-- Value = `name,department`

Notice that the value MUST NOT be enclosed in any character. They're just the Velocity Var Names separated by a comma.
