### ISSUE TITLE
Replace all metadata calls and remove old metadata methods from contentlet

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19234]
Replace calls for file attributes that now go to the FS, with calls for metadata (file name, file size, mod_date, contentType, isImage, dimensions). Metadata generation needs to happen for all binary fields - not just those that are indexed - if a binary is marked as indexed and the first binary field, then we generate the full metadata for it. If not, then we only generate the basic metadata.

**Comment by wezell** [comment]
This PR was an initial attempt at removing old metadata from contentlet: PR #19365

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/19591

**Comment by wezell** [comment]
## Notes

Metadata notes:

1. metadata should always be generated lazily, then cached
- Indexed Binaries will call getMetadata when they are reindexed
- Metadata on other binaries will be generated/cached when requested

2. Rename getMetadataNoCache() to getFullMetadataNoCache()

3. remove the Dimensions from Fileasset - use the metadata 

4. get rid of old code that generates any anything that should be in the Metadata

5. I think our default metadata impl should be storing metadata on disk, next to the binaries

6. When saving a contentlet that has previous versions, we should copy the metadata

7. Review where we are using the contentlet.getBinary() method and see where we can replace the calls to the underlying file with metadata cache

**Comment by fabrizzio-dotCMS** [comment]
- [x]  Verify Metadata mappings on the index (ensure we need or not the _dotraw versions of the following fields)  (done)

   Excluded from the dotraw treatment (by default) are (content, isimage, sha256)

- [x] Remove mechanism that calculates FileAsset properties (width, height, length, size) and replace them by uses of the API. (done)

- [x] Add a remove MD method to the API and test it (done)

- [x] Make the get-metadata Methods capable to generate it whenever it is missing and test it. (done)

- [x] Mechanism to remove the metadata upon removing/destroying the contentlet (done)

- [x] Identify uses of FileAssetAPI.getContentMetadataAsString()  and replace them with the new Metadata-API and deprecate the method. (done)

- [x] Currently we have in the table `storage` a column called metadata which is storing a JSON version of the file-metadata. 
   This info is repetitive since the metadata is stored and grabbed from joining the tables `storage_data` + `storage_x_data`
   We need to remove such column and the logic that populates it (done)

- [ ] Identify uses of Tika outside the new Metadata-API and replace them with the new Metadata-API 
   (From now on TikaUtils will be a private class only used by the new MetadataAPI classes) (in progress)

- [ ] Identify and uses of setMetadata in Push publish and ensure the new MD is set and pushed

- [ ] Revise any additional use of `Contentlet.getBinary()` and see where we can replace the calls to the underlying file with metadata cache 

- [ ] Copy metadata attributes on check-in (in-progress)

- [ ] Modify focal point to store update using the new Metadata-API (in progress)

- [ ] Upgrade task to destroy all metadata files and replace them by doing a full-reindex

- [ ] 14- FP integrate with Will's new FP branch 

- [ ] if no changes happen during check-in do no regenerate the MD just copy it

**Comment by fabrizzio-dotCMS** [comment]
Note for QA:
This is quite big so bear with me please as I try to cover what needs to be tested here. 

There are basically two scenarios here. Storing the Metadata in the database and storing it in the file system. 
Those two are controlled by a property "DEFAULT_STORAGE_TYPE" You can change it to "FILE_SYSTEM" or "DB"
The default storage out of the box. Must be the DB. (So here's something to test)

One important thing here is that both scenarios need to be tested under the upgrade perspective.

When the storage device of choice is the File System. The metadata lives under the assets folder in a json file. 
Like this: 
![Screen Shot 2021-03-24 at 13 27 38](https://user-images.githubusercontent.com/37148755/112372390-58120300-8ca5-11eb-883e-b669e14fd1e0.png)

The file inside the green rectangle holds new properties added in this version. Therefore the old files aren't compatible. And needed to be cleaned up. Using an upgrade task.  The old metaData folder that appears on the screenshot above must be gone after an upgrade. Or a fresh install. 

So how can you recognize a new metadata file from the old one? The new Metadata file has additional properties like 
"isImage" ,"sha256", "fileName", "title" 

Every single file Asset must have

**Comment by nollymar** [comment]
**Passed internal QA:** All the scenarios described were tested and they're working correctly.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.05 // Postgres // FF. tested based in the provided comment
