### ISSUE TITLE
Update starter import/export format to be json

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#19400]
This is part of a bigger feature where the main goal is to avoid relying on Hibernate.

**Acceptance criteria:** Import/Export functionality should keep working as always

**Comment by john-thomas-dotcms** [comment]
So from the description I think the plan is to still support the existing CSV format; but just to be clear - I think the import/export using CSV files will still need to be supported, because it's much, much easier for customers to export CSV files and work with them in a spreadsheet program than it would be for them to work with JSON files.

So if we update the format, we'll need to have two separate/parallel import/export format readers/writers (one for CSV and one for JSON).  But the underlying code which takes those results and does things like validate them can (and should) be shared for both formats.

**Comment by nollymar** [comment]
PR: #21236

**Comment by bryanboza** [comment]
Fixed, tested on release-22.07 // Docker // FF. 

Now we are able to start the server using a JSON format file as starter, but this is a breaking change, now we are unable to start using a previous starter.
