### ISSUE TITLE
Load System Theme

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19415]
We already add the vtl file regarding the **system_theme** in this issue #19086 but to use it right now you need to create the folders `application/themes/system` and add the vtl.

We need to enable the idea of load the vtl directly from the assets and make it available for the users.

If there is no other theme in the host, **system_theme** should be selected by default. If there are other themes, we need to add the System Host to the theme selector so users can use it if they want.

Users can select **system_theme** to a template and the page should render it.

**Comment by erickgonzalez** [comment]
PR: https://github.com/dotCMS/core/pull/20050

**Comment by erickgonzalez** [comment]
Steps to Test:
1- Create a new template using the system theme and the system container.
2- Create a new contentlet of any content type.
3- Create a new page using the template above.
4- Add the contentlet to the page.

Page should render without issues.

**Comment by erickgonzalez** [comment]
This is missing UI work to show the **System Theme**.

**Comment by fmontes** [comment]
We need to fix the thumbnail.

![image](https://user-images.githubusercontent.com/751424/113627519-e0d35c00-9620-11eb-8b32-b4f12894fbc8.png)

**Comment by erickgonzalez** [comment]
> We need to fix the thumbnail.
> 
> ![image](https://user-images.githubusercontent.com/751424/113627519-e0d35c00-9620-11eb-8b32-b4f12894fbc8.png)

We make this call `http://localhost:8080/dA/{themeThumbnail}/130w/130h/thumbnail.png` but we expect that **{themeThumbnail}** brings an Id since the image inside dotcms, but for the system theme it lives in tomcat so **{themeThumbnail}** brings a path `/html/images/system-theme.png`.

We need to check that if is the system theme avoid to call the `dA` endpoint and call something like `<img src="/html/images/system-theme.png"/>`

**Comment by bryanboza** [comment]
Fixed, tested on master // Postgres // FF
