### ISSUE TITLE
Mechanism to prevent dotCMS from setting default 'title' values on widgets

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#19474]
As reported in zendesk ticket: https://dotcms.zendesk.com/agent/tickets/102658

When saving a widget, dotCMS 5x will automatically copy the 'widget-title' value into a field with the velocity variable 'title' even if it is left blank. 

Request is for a mechanism to prevent this default behavior. 

**Describe the solution you'd like**
A mechanism, such as a checkbox on the field properties, to prevent the 'widget-title' value from being copied to the 'title' field.

**Describe alternatives you've considered**
One can workaround this issue by changing any 'Title' field velocity variable to something other than the default 'title'.

**Comment by john-thomas-dotcms** [comment]
This happens on title fields of other content types as well, as in this ticket: https://dotcms.zendesk.com/agent/tickets/103846

We've had 3 customers run into this, and in all cases it's a significant problem for the customer.  Since they have content types which were migrated from earlier versions, they have a field with the velocity varname `title`, and it causes this problem.

But since you can't change the velocity varname of a field after the content type has been created, there's no way to resolve this problem for the customer unless we manually run SQL queries against their DB to change the velocity varname of the field AND they then modify their code to look for the new varname.

So, I'm wondering -rather than saying customers can't use velocity varnames which conflict with the

**Comment by john-thomas-dotcms** [comment]
This happens on title fields of other content types as well, as in this ticket: https://dotcms.zendesk.com/agent/tickets/103846

We've had 3 customers run into this, and in all cases it's a significant problem for the customer. Since they have content types which were migrated from earlier versions, they have a field with the velocity varname `title`, and it causes this problem.

But since you can't change the velocity varname of a field after the content type has been created, there's no way to resolve this problem for the customer unless both of the following have to be done:
1. We must manually run SQL queries against their DB to change the velocity varname of the field, AND
2. They must then modify their code to look for the new varname.

We're going to keep seeing this as customers migrate from pre-5.3.x releases to 5.3.x.  I'm not sure our current solution (preventing customers from creating content type variable names which conflict with `title` and other "reserved" ES index system fields) is a good one.

**Comment by wezell** [comment]
I think this is resolved in this issue:  #20655
