### ISSUE TITLE
Allow restriction of the "Key" value in a Key/Value field to a white list of acceptable keys

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19562]
**Is your feature request related to a problem? Please describe.**

The Key/Value field allows addition of multiple values to a content item within a single field, which is a commonly needed feature.  However as it is, the field allows content editors to enter any value for the key - which means that different content items may end up with completely different keys that are really meant to hold the same type of information.

**Describe the solution you'd like**

Allow specification of a list of acceptable key values for any Key/Value field.  For example, for a K/V field intended to store laptop specifications, you would be able to enforce that content editors can add keys for "Screen Resolution", "Power Consumption", "Screen Size", etc. - but prevent them from adding a key which is not in the list.

**Describe alternatives you've considered**

There are a couple of possible alternatives to this that are sometimes used:
* Use a relationship, where each key/value pair is entered as a different content item, and then related via a 1-N or M-N relationship.
* Use a custom field - where the customer has to write all the code to display the keys, allow the keys to be entered, encode the keys and values, etc.

**Additional context**

It would be ideal if, with a whitelist of keys specified, the user was given a drop-down list to choose the key from (but one they can type into, which will automatically match valid keys based on what they type).

It would also be ideal if, even if the keys are not restricted, entering keys behaved almost the same as entering tags - including autocomplete of previously used keys and/or values.  I think this is a heavier lift, though, than just restricting the keys to a list of acceptable values.

**Comment by ian-b-cooper** [comment]
Support requested for this issue as seen in this ticket: https://dotcms.zendesk.com/agent/tickets/105827

**Comment by wezell** [comment]
We just need a field variable of the `keyValueConfig` that would specify the acceptable `keys` and we can include their acceptable `values`.  We would constrain the entries in the key value field to the values that have been specified.

This constraint would be handled at the UI level. 

We will need to modify our webcomponent to allow for restful key/value suggestions and enforcement AND also modify our webcomponent to allow for reordering of the keys.

**Comment by wezell** [comment]
Something like:
```
{
   "key1":["val1", "val2"],
   "key2":[],
   "key3":[]
}
```

**Comment by wezell** [comment]
Here is the endpoint to get the field and fieldVariable information:

https://demo.dotcms.com/api/v1/contenttype/57897dfb36ef211ebfb4128de818787/fields/id/efa7498ccba0565b74979b110d4fa467

**Comment by wezell** [comment]
Our web component should take a data element of the acceptable keys and their acceptable values so that it can be used across different implementations.

**Comment by alfredo-dotcms** [comment]
PRs:
core = https://github.com/dotCMS/core/pull/21766/files
core-web = https://github.com/dotCMS/core-web/pull/1900/files

**Comment by alfredo-dotcms** [comment]
note to QA: 
- D&D functionality implemented. 
Demo --> https://monosnap.com/file/WEcnH0V8ICvFvnpdvFAdmPvf35Pw1D

- to enable the white list key variable must be named `white-list` and the value must be like this https://github.com/dotCMS/core/issues/19562#issuecomment-1033018088
Demo --> https://monosnap.com/file/aVnaDyezpnnWohygDjxmEAtu6tw3mn

**Comment by wezell** [comment]
let us change the field variable to `camelCase`

**Comment by fabrizzio-dotCMS** [comment]
Looks like storing a json in a field variable Breaks the content-edit-window
with the following stack trace:

`Caused by: org.apache.jasper.JasperException: An exception occurred processing [/html/portlet/ext/contentlet/field/edit_field.jsp] at line [1118]

1115:         }
1116:
1117:         keyValueDataRaw = keyValueDataRaw.substring(0, keyValueDataRaw.length() - 1) + "}";
1118:         dotKeyValueDataRaw = dotKeyValueDataRaw.substring(0, dotKeyValueDataRaw.length() - 1);
1119:
1120:         List<FieldVariable> fieldVariables=APILocator.getFieldAPI().getFieldVariablesForField(field.getInode(), user, true);
1121:         String whiteListKeyValues = "";
`

**Comment by nollymar** [comment]
**PR Core:** https://github.com/dotCMS/core/pull/21859

**Comment by fabrizzio-dotCMS** [comment]
Another issue found:
Upon adding a second key-value field makes the first one lose its whiteList capabilities

**Comment by alfredo-dotcms** [comment]
PR core: https://github.com/dotCMS/core/pull/21865/files

**Comment by fabrizzio-dotCMS** [comment]
looks good to me.

**Comment by wezell** [comment]
The key value field is no longer respecting "ReadOnly" mode.  You can see this on the metadata for fileAssets.

**Comment by alfredo-dotcms** [comment]
PRs:
https://github.com/dotCMS/core/pull/21980/files
https://github.com/dotCMS/core-web/pull/1942/files

**Comment by nollymar** [comment]
**Internal QA:** After the fix, the read-only mode is respected: 

![Screen Shot 2022-04-07 at 6 24 30 PM](https://user-images.githubusercontent.com/8741395/162335336-71fa76a3-a26a-44b8-ac5e-30f49f4271df.png)


However, the editable version seems to break when I try to add an existing key: 


https://user-images.githubusercontent.com/8741395/162335699-2e1e50d1-dba4-475a-b5ee-dc0baf2b82c1.mov



It should behave as in previous versions where a message was displayed to the user. Otherwise, the user might think that something is broken with the functionality:


https://user-images.githubusercontent.com/8741395/162335715-4ff35a5a-513b-4670-b091-8728449a85e6.mov

**Comment by nollymar** [comment]
**Internal QA:** Here my findings: 
- [ ] There is a typo on this message: "The key already exist"
- [ ] The key/value fields are not being displayed as select boxes when a whileList is configured and I can type any value. The white list is not respected:
<img width="1493" alt="Screen Shot 2022-04-12 at 5 26 11 PM" src="https://user-images.githubusercontent.com/8741395/163067477-8c807a28-b940-47c4-ae7a-74d7e5c28855.png">

- [ ] The metadata tab still shows "Delete" buttons and key/value fields:
<img width="1198" alt="Screen Shot 2022-04-12 at 5 39 44 PM" src="https://user-images.githubusercontent.com/8741395/163067610-fa753ac5-6ff8-40ff-acd0-89cb38c17b49.png">

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1952/files

**Comment by nollymar** [comment]
**Internal QA:** Now, everything works as expected

**Comment by bryanboza** [comment]
Tested after the changes and now it is working as expected, we just need to hide the "key already exist" message every time you change the dropDown value. This because right now,  once you try to add a key that already exist the message is not disappearing, we need to clear this when  I change the key value 
![image](https://user-images.githubusercontent.com/2641437/163846752-34b948c4-7b27-455e-8c42-8405184a2ed7.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1958/files

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested on release 22.04 // Docker // FF
