### ISSUE TITLE
Create component that allows user to select/preview material icons from a list

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19592]
We allow users to input a material icon when they are adding an icon to a layout.   This is now a free form input.   Additionally, we want to give users the ability to add icons to content types as well.   We should make a custom component that will allow a user to select an icon and preview it from the list of available material icons.  Here is the list of available icons as json 

[material-icons.json.txt](https://github.com/dotCMS/core/files/5554415/material-icons.json.txt)

**Comment by fmontes** [comment]
We need to create a web component because this could be use in jsp and in angular (layout is dojo and content type is angular)

## Autocomplete
The idea is that users can select an icon but since we have hundreds of icons in material design we need to make a autocomplete so user can type what they are looking for, the same way that autocomplete works in primeng: http://primefaces.org/primeng/showcase/#/autocomplete

The source of the icons is the [file](https://github.com/dotCMS/core/files/5554415/material-icons.json.txt) @wezell add to the description.

Please take into considerations that is a +70kb file so do what's best for performnace here.

### Accesibility
We need this to be accesible so read this https://www.grapecity.com/blogs/making-web-components-accessible#:~:text=The%20first%20step%20required%20to,translated%20into%20the%20accessibility%20tree.

**Comment by wezell** [comment]
Please include a color picker that can drive the icon's color as well

**Comment by nollymar** [comment]
PR: https://github.com/dotCMS/dotcms-webcomponents/pull/47

**Comment by nollymar** [comment]
Tested on #19933.

Additionally, the component was published on https://dotcms.github.io/core-web/?path=/story/dotcmswebcomponents_elements--material-icon

<img width="1678" alt="Screen Shot 2021-03-01 at 12 54 55 PM" src="https://user-images.githubusercontent.com/8741395/109538516-2d5dd180-7a8e-11eb-98f3-10c6849f486a.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-21.03 // Postgres // FF
