### ISSUE TITLE
Add a route to create a piece of content of passed content type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#19597]
### The URL ~~/new/{CONTENT-TYPE}~~ --> `/c/content/new/{CONTENT-TYPE}`

When the user hits the url it should pop this dialog (will be different depending of the content type).

![image](https://user-images.githubusercontent.com/751424/99537965-ed0c9480-2971-11eb-9def-628b4ab77c0a.png)

- If the content type is PAGE when the user hit **save** we need to redirect it to edit mode
- if the dialog is opened starting from the "Starter" page or directly putting the url link in the browser address bar, when it gets closed the it will redirect to the Content Search page
- The dialog will be opened anywhere in the app
- This will need BE and FE work

**Comment by alfredo-dotcms** [comment]
CORE: https://github.com/dotCMS/core/pull/19765/files
CORE-WEB: https://github.com/dotCMS/core-web/pull/1538/files

**Comment by alfredo-dotcms** [comment]
Core draft: https://github.com/dotCMS/core/pull/19779 needs some work on the BE https://github.com/dotCMS/core/issues/19683#issuecomment-756361227

CORE-WEB: https://github.com/dotCMS/core-web/pull/1538/files

**Comment by nollymar** [comment]
Additional rollback: https://github.com/dotCMS/core/pull/19803

**Comment by nollymar** [comment]
**Internal QA:** Passed.

A new popup is displayed to create a new piece of content. For example:

- http://localhost:8080/dotAdmin/#/c/content/new/persona
<img width="1107" alt="Screen Shot 2021-01-25 at 5 40 42 PM" src="https://user-images.githubusercontent.com/8741395/105775302-9a80c300-5f34-11eb-85aa-dfe31059cb4d.png">

- http://localhost:8080/dotAdmin/#/c/content/new/blog
<img width="1111" alt="Screen Shot 2021-01-25 at 5 41 08 PM" src="https://user-images.githubusercontent.com/8741395/105775310-a076a400-5f34-11eb-99df-a99e363d0e96.png">

**Comment by bryanboza** [comment]
Need a better error handle and a friendly message in case you try to add a pice of content of a EE base type, right now we are showing an unexpected error and a big stack trace in the log 
Log: https://gist.github.com/bryanboza/9915cfaee337885abbc022307c13c9ae
![image](https://user-images.githubusercontent.com/2641437/108921273-b80c7f80-75fb-11eb-801b-328a447fab91.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core-web/pull/1597/files   -->. _Also, after add a new piece of content by this URL, when you close the new content modal, we need to refresh the list of contents in order to display the added one._

**Comment by nollymar** [comment]
Additional PR to fix the first issue reported by @bryanboza : https://github.com/dotCMS/core/pull/20019

This fix won't prevent the popup to be displayed, however, if the user tries to save a Persona or Form without setting an enterprise license, an error will be shown.

**Comment by bryanboza** [comment]
We need some extra work here, this because does make sense show the modal and allow enter all the data and at the end show a message that you can't add this piece of content, we need to show a license message in the moment you request this URL. 
![image](https://user-images.githubusercontent.com/2641437/109567044-58eeb500-7aaa-11eb-841a-72a6529f72c8.png)

Also, from backend we can't access to this modal because the persona type does not exist in the list of types in the content types portlet. Then we need to be consistent 
![image](https://user-images.githubusercontent.com/2641437/109566868-175e0a00-7aaa-11eb-8a86-d4a4f1c97a27.png)

**Comment by nollymar** [comment]
@bryanboza we should discuss the change in flow you are suggesting because it requires additional work that I'm not sure is supported by the legacy portlets we use to edit content. 

IMO this is an improvement, out of the scope of the original task. As I stated above: 
_"This fix won't prevent the popup to be displayed, however, if the user tries to save a Persona or Form without setting an enterprise license, an error will be shown."_

**Comment by wezell** [comment]
@bryanboza, your latest issue that you reported should be moved to another card - as we don't have a direct link to the endpoint for personas in the getting started screen.  We can take this on at a later date.

**Comment by bryanboza** [comment]
Fixed, requested changes moved to a new card #20035

**Comment by bryanboza** [comment]
We are unable to see the permissions message in some browsers: 
Able to see on: Chrome & FF
Unable to see:  Safari & IE

![image](https://user-images.githubusercontent.com/2641437/110371294-622fd280-8012-11eb-9cdf-0cc3c5440fce.png)

**Comment by bryanboza** [comment]
Seems this error is out of the main scope, it's ok for now... Passed
