### ISSUE TITLE
Push Publish Batch Button selects all assets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19620]
- if you go to Content > Products
- Then select the header checkbox to select all items
- and then you click in the message "All 40 content item(s) on this Page are selected. Select all 68 content(s)."
- now pick Push Publish under Available Workflow Actions
   - (add a fake remote on your install)

When you go to see what it's being push published, it is not just the 68 content, it seems to try to push publish every item on the site.

This happens to us a lot when we're trying to push publish a single content type that spans multiple pages

**Comment by craigWagner99** [comment]
As seen in https://dotcms.zendesk.com/agent/tickets/102920

v5.3.9

**Comment by fabrizzio-dotCMS** [comment]
Per my findings :
All the assets are rolled into one single attempt because the query that is passed from the front-end got all the "+" signs stripped off. Therefore what initially was meant to be interpreted as an AND condition is transformed into an OR causing all the items to be included.

this is the query that gets sent to the dwr endpoint 
`"assetIdentifier: query_ contentType:Product  (conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST)  languageId:1  deleted:false  working:true"`

Screenshot 1. shows the query before it gets passed to pp dialog component via a Custom Event. 

![Screen Shot 2020-12-07 at 08 27 45](https://user-images.githubusercontent.com/37148755/101363854-817a6080-3867-11eb-8656-06a738595b0d.png)

Screenshot 2. shows the form-data that gets sent to the dwr.
![Screen Shot 2020-12-07 at 08 27 26](https://user-images.githubusercontent.com/37148755/101363893-8b03c880-3867-11eb-9cb7-e25f419c2f68.png)

I would say these needs work from the UI team.

**Comment by wezell** [comment]
We should use the new POST `/_search` method in the UI to prevent these types of encoding issues future forward.

**Comment by fabrizzio-dotCMS** [comment]
I am marking it as UI so it can be attended by the Angular experts.

**Comment by alfredo-dotcms** [comment]
`core-web` PR: https://github.com/dotCMS/core-web/pull/1528/files

**Comment by nollymar** [comment]
Passed internal qa. It is working as expected. However, I found another non-related issue: https://github.com/dotCMS/core/issues/19734

**Comment by bryanboza** [comment]
Fixed, tested on release-21.02 // Postgres // FF
