### ISSUE TITLE
Rules on pages do not show push publishing options

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#19708]
If you add a rule to a page, you cannot see the "Push Publish" or "Add to Bundle" options under the elipsis - it does work on a host and in the rules portlet.

![Screen Shot 2020-12-15 at 3 52 44 PM](https://user-images.githubusercontent.com/934364/102271680-b5035d80-3eed-11eb-8b0e-9d3c538868d2.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/19716

**Comment by alfredo-dotcms** [comment]
@QA and @wezell the action "Push Publish" has never been implemented on Rules. So when testing this the only actions available are "Delete Rule" and "Add to Bundle"

**Comment by nollymar** [comment]
Passed internal qa: 

![Screen Shot 2020-12-29 at 5 06 50 PM](https://user-images.githubusercontent.com/8741395/103317012-48618600-49f8-11eb-955b-146256defa7e.png)

**Comment by bryanboza** [comment]
Now we are able to see both options in the list, but if you add a page rule to a bundle and then try to push it, even when you have selected the "Everything and dependencies" filter, we are failing because the page does not exist. 

In this case we need to send the page by dependency and also push the rule too. 
![image](https://user-images.githubusercontent.com/2641437/104344515-d9d5fb00-54c2-11eb-99c5-c7a8b278b787.png)

**Comment by bryanboza** [comment]
Fixed, the related error was moved to a new card, and we can close this one since now we are able to see the options without problems, tested on Master // Postgres // Chrome
