### ISSUE TITLE
Enable "white labeling" of back-end

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#19970]
**Is your feature request related to a problem? Please describe.**

Some customers use dotCMS to serve their own customers, and need to replace the dotCMS logo in the BE to ensure it's clear to their customers what product they're using.

Related support ticket: https://dotcms.zendesk.com/agent/tickets/103526

**Describe the solution you'd like**

1. Allow the dotCMS logo in the BE (top left of all screens) to be replaced.
    * By default, cloud customers should not be able to replace the logo.
    * So, this option should be controlled by something which is part of the distro rather than the BE.
        * For example, a file in the distro, configuration property, etc.
2. Add small a "Powered by dotCMS" label in the the footer (bottom right).
    * This should only display if the BE logo has been replaced.

**Describe alternatives you've considered**

Customers can currently replace the logo on the login screen, but can not replace the logo in the BE.  There is currently no way to replace the BE logo (without a plugin).

**Additional context**

My suggestion would be that we look for a file with a specific name in the distro, and if that file exists, use that in place of the dotCMS logo in the BE.  If that file doesn't exists, use the dotCMS logo.

**Comment by ivorpad** [comment]
Requirements:

1. Upload two logos, one for comms and overall site and other for the drawer and login. If no logo is found then fallback to placeholder.
2. The logo in the drawer must be shown only when open
3. Use the drag & drop component, adapt if necessary.
4. The  comms logo must be uploaded to dotassets and the other to `saveCompanyLogo` endpont

**Comment by bryanboza** [comment]
We have some problems here, and others thing that maybe needs discussion @wezell @fmontes 

- If you enable the "NavBar logo" and navigate between tabs in the configuration when you bring it back to this tab, the component disappears and you need to refresh the page to get this component again

- Maybe we need to remove the checkbox "override navBar logo" or if not if you disable this and save the changes, we need to remove the logo and bring back to the default 

- Once you change the company logo, and then you remove the image, we need to bring back to the default instead show an error message "the company logo cannot be empty"

- This component should allow to navigate into the dotAssets in order to allow select an existing dotAsset instead to upload the same image again

**Comment by fmontes** [comment]
- If you enable the "NavBar logo" and navigate between tabs in the configuration when you bring it back to this tab, the component disappears and you need to refresh the page to get this component again
**Fixed**

- Maybe we need to remove the checkbox "override navBar logo" or if not if you disable this and save the changes, we need to remove the logo and bring back to the default
N/A

- Once you change the company logo, and then you remove the image, we need to bring back to the default instead show an error message "the company logo cannot be empty"
**Good for v2**

- This component should allow to navigate into the dotAssets in order to allow select an existing dotAsset instead to upload the same image again
**Good for v2**

- If I already have a company logo selected and I try to drag and drop a new image, maybe we need to replace the existing one. Right now we need to delete the existing image and then upload the new one.
**Good for v2**

**Comment by wezell** [comment]
@fmontes we are still missing the DND drop zone dotted line

**Comment by wezell** [comment]
@fmontes @bryanboza updating the navbar  logo should be an EE only feature

**Comment by bryanboza** [comment]
Fixed, now this is just for EE edition, new enhancements moved to a new card #20599
