### ISSUE TITLE
Unable to load very large images

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20446]
Loading very large images, e.g. images that are 30000x20000 pixels and 200mb on disk will cause dotCMS to churn and you will ultimately end up with an OOM exception

**Comment by wezell** [comment]
Here are very large images to test 

https://commons.wikimedia.org/wiki/Commons:Very_high-resolution_file_downloads

https://upload.wikimedia.org/wikipedia/commons/6/6f/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg

**Comment by victoralfaro-dotcms** [comment]
Using the birth of Venus image (224.6 MB)
<img width="1197" alt="Screen Shot 2021-07-07 at 08 28 49" src="https://user-images.githubusercontent.com/64026161/124779683-36105980-deff-11eb-9ca1-54742a2117b0.png">
<img width="1132" alt="Screen Shot 2021-07-07 at 08 39 05" src="https://user-images.githubusercontent.com/64026161/124779693-37418680-deff-11eb-93e0-c379f2cf72a0.png">
<img width="1405" alt="Screen Shot 2021-07-07 at 08 38 22" src="https://user-images.githubusercontent.com/64026161/124779724-3e689480-deff-11eb-8b0f-61ff8d14dac3.png">
<img width="1194" alt="Screen Shot 2021-07-07 at 08 36 39" src="https://user-images.githubusercontent.com/64026161/124779771-47f1fc80-deff-11eb-905b-41fa54652c61.png">
<img width="1196" alt="Screen Shot 2021-07-07 at 08 36 13" src="https://user-images.githubusercontent.com/64026161/124779811-4fb1a100-deff-11eb-8ccd-491231354da5.png">
<img width="1196" alt="Screen Shot 2021-07-07 at 08 35 36" src="https://user-images.githubusercontent.com/64026161/124779824-5213fb00-deff-11eb-8e0c-281c301d3a1f.png">
<img width="1196" alt="Screen Shot 2021-07-07 at 08 34 46" src="https://user-images.githubusercontent.com/64026161/124779841-550eeb80-deff-11eb-8cc5-ac8b5ebced4c.png">

**Comment by victoralfaro-dotcms** [comment]
BTW all the backend actions were done using Safari since with Chrome it just won't load the image for edition and when it's opened in separate browser tab.
![Screen Shot 2021-07-07 at 08 52 27](https://user-images.githubusercontent.com/64026161/124781833-f5b1db00-df00-11eb-852e-d6ef196ef9b4.png)
![Screen Shot 2021-07-07 at 08 52 13](https://user-images.githubusercontent.com/64026161/124781850-f9ddf880-df00-11eb-9aa8-0ab76a1a5ac9.png)

**Comment by bryanboza** [comment]
Fixed, tested on Safari and works fine, seems chrome have problems rendering those kind of images, but this is external to dotCMS. Tested on release-21.07 // Postgres // Safari

**Comment by bryanboza** [comment]
New card related to the edit image editor here #20639

**Comment by jcastro-dotcms** [comment]
The fix touches too many files. The risk of putting this in the LTS is too high.

**Comment by wezell** [comment]
@jcastro-dotcms @swicken-dotcms  this needs to be backported into the next planned release of 21.06 LTS - this causes many issues with customers who rely on the image processing - not just with large images but also where multiple servers are reading and writing the same files.

**Comment by jcastro-dotcms** [comment]
### Note for 5.3.8.7 testing:

Because of the size of the image, it can take more than a minute for the thumbnail to be generated. Also, clicking the **INFO** button in the Image content and clicking the `File Link` can take a few seconds to load. These situations are expected, and no error is thrown in the log anymore.
