### ISSUE TITLE
"Back end user" role breaks front end user permissions

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#20452]
**Describe the bug**
When you have a user that has both "front end user" and "back end user" checked then strange things happen when you are logged in as a frontend user. Either parts of pages will not be displayed or you are not allowed to view entire pages. This happens on 21.05 and 5.3.8.4.

**To Reproduce**
1. Add a piece of content on the homepage of demo.dotcms.com
2. Set the permissions of the content to 'intranet' with view only permissions, remove CMS anonymous
3. View the page in a separate browser: the text will not be displayed
4. Go to the /login page and login as bill@dotcms.com
5. Go to the homepage: the piece of content should be visible
6. In a separate browser set the 'back-end user' checkbox on bill@dotcms.com + save
7. View the page again: you get a 403

**Expected behavior**
You should still be able to view the page and the content. You should be able to be both front-end and back-end user, especially for testing. In our environment (5.3.8.4) we are only missing parts of pages when the back-end user checkbox is checked, on the demo site (21.05) the entire page is suddenly restricted.

**Workaround**
Have separate users for front-end login and back-end login.

**Comment by Xander-Steinmann** [comment]
I think the !isBackendUser() is no longer valid in this line: https://github.com/dotCMS/core/blob/3283e9732fe28b329cf3fd3633534a76a6f4806d/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java#L358

It should probably be isFontendUser()

**Comment by Xander-Steinmann** [comment]
Did nobody encounter this issue before?

**Comment by wezell** [comment]
The line that you referenced before is intended to enforce the rule that unpublished content is never served to non-backend users - via api or otherwise.  

https://github.com/dotCMS/core/blob/3283e9732fe28b329cf3fd3633534a76a6f4806d/dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java#L358

Meaning, you have to be logged in and a "back end" user in order to see drafted or non-published content.  It still makes sense to me.  Is your issue happening because you are logged into the system and are looking at pages in edit mode?  It seems that if you are both a backend user and a front end user then that line would still allow you to see the content.  Or is it that the content you are trying to preview only has front end user permissions?

**Comment by Xander-Steinmann** [comment]
Hi Will, I'm trying to view content in the front-end as a logged in front-end user without being logged in in the back-end. My problem is that I can only view the content when my account does not have back-end user permissions. I tried to find the cause of the issue but the line I referenced wasn't the cause. But there must be some code somewhere that assumes that you can't be both front-end and back-end user, I don't have any other explanation. It all worked fine before our upgrade from 5.2 to 5.3.8.4 and I see the same issue on demo.dotcms.com.

**Comment by nollymar** [comment]
Internal QA: I still can reproduce the error in master
https://user-images.githubusercontent.com/8741395/127712315-3136bdfc-103a-4600-939c-59ffb6183021.mov

**Comment by wezell** [comment]
@nollymar Is your report an issue?

**Comment by nollymar** [comment]
It is @wezell

**Comment by nollymar** [comment]
I recorded a new video with more details to reproduce the issue. I follow the steps in the description:
dotCMS version: 21.09

https://user-images.githubusercontent.com/8741395/130109042-de2ba0a4-b527-4aac-ba56-ec3b89f9351a.mov

**Comment by nollymar** [comment]
**Internal QA:** Now it works
