### ISSUE TITLE
Relationship error trying to add a comment from FE

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20517]
When you are navigating on FE and you try to add a comment, we are getting an error and you can't add the comment 

Here the log: https://gist.github.com/bryanboza/6c57c9b1b2633b183561c1138642753a

**To Reproduce**
- Go to the FE page 
- Navigate to travel blog 
- Select any of the contents here 
- try to add a comment 

**Expected behavior**
We need be able to add comments without problems 

**Desktop (please complete the following information):**
 Tested on release-21.06 // Postgres // FF

**Comment by nollymar** [comment]
This is an implementation issue. It fails when a user tries to add more than one comment in the same post (it includes the Anonymous user).

The related content cannot be included because the relationship between BlogCommenter and BlogComment fails when an existing user already exists, it means: the commenter already added a comment on the blog post.  Unfortunately, it is not possible to add a related content more than once in the same relationship.

**Comment by wezell** [comment]
This is an implementation issue with the starter. Nothing to see here.
