### ISSUE TITLE
GraphQL Metadata Postman test failing 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#20536]
Take a look at https://raw.githack.com/dotCMS/test-results/master/projects/core/current/curl/postgres/reports/html/GraphQLTests.html

```
Iteration 1 - AssertionError - File Metadata - Request File Asset metada fields
Failed Test: FileAsset metadata attributes
ASSERTION ERROR MESSAGE
expected 0 to deeply equal 1200
```

**Comment by fabrizzio-dotCMS** [comment]
I reviewed the cause of this failing test. It is due to a mismatch in the image dimensions. 
Every time I run the test locally it works for me. But whenever it gets run from a postman runner apparently Tika cacluclaes 0,0 dimensions on this image.
The db has

`{"contentType":"image/jpeg","fileSize":215384,"height":0,"isImage":true,"length":215384,"modDate":1623429526000,"name":"actn-legioss.jpg","path":"e/f/efca9375-c1a4-47e0-b1c7-9b7c2ebc5558/fileAsset/actn-legioss.jpg","sha256":"ffe7157a4b7c8dd772f57dc2de8694ea974b87653b5605f854924a43bbfbb0ce","title":"actn-legioss.jpg","width":0}`

But if we remove the contentlet and rebuild it by calling the Postman test one by one manually the metadata gets created as expected.

**Comment by fabrizzio-dotCMS** [comment]
Worth checking JAVA_OPTS	-Djava.awt.headless=true

**Comment by fabrizzio-dotCMS** [comment]
This https://github.com/dotCMS/core/issues/21486 took care of this broken test.
On Tika failure we rely on our own Image API for widht and height calculations
