### ISSUE TITLE
JSP error adding files to contentlets assigned to a workflow 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#20571]
When you try to attach some file to some contnet that is assigned to a workflow,  we are getting a JSP error and you can't attach the file. After this, we are unable to open the file information. 

Here the log: https://gist.github.com/bryanboza/39f2c379e71ba67a1842e001466250ec

**To Reproduce**
- Load-up a dotCMS instance using full starter
- Login as admin
- Go to task portlet 
- Select some of the assigned task here ("Colorado & the Rockies")
- Go to the "attach file" tab 
- Try to attach some asset 

**Expected behavior**
We need be able to attach assets without problems 

**Desktop (please complete the following information):**
Tested on release-21.06 // Postgres // FF

**Comment by fabrizzio-dotCMS** [comment]
The problem is we're trying to assign a dotAsset to the task. Which breaks when converting the contentlet into a FileAsset 
The best solution here seems to be filtering dotAssets from being shown as optional attachable images. since the dialog component is used in many places I am researching the best way to do that.
