### ISSUE TITLE
Users without the 'Login As' Role are still able to select Login As and see all Users 

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#20677]
As reported in https://dotcms.zendesk.com/agent/tickets/104775 v5.2.8.3
Tested in current Demo - v21.06

**Describe the bug**
Users without 'Login As' are still able to select Login As and see all Users. They cannot complete the login as process - they just see all users.

**To Reproduce**
1. Login to dotCMS as a USer without Login As permissions
2. Select the user button at the top right of the screen and click 'Login As'
3. All users can be seen.

SCREENSHOTS:

1. Login to dotCMS as a User who does not have the 'Login As' Role:

![image](https://user-images.githubusercontent.com/49727631/125977642-aeac7a47-ea22-4ff2-a6e1-f458d961ca06.png)

2. Select the user button at the top right. Login As is there: 

![image](https://user-images.githubusercontent.com/49727631/125977802-9526b36b-7813-4ad0-9c4b-f82dd646d5d7.png)

3. Click 'Login As' - all users can be seen:

![image](https://user-images.githubusercontent.com/49727631/125977860-a04b091a-4f7b-419e-9d2b-bbdc511e5367.png)

**Comment by john-thomas-dotcms** [comment]
This is a privacy issue, since it exposes the names of users.  The security implications are not as strong, since the list shows the names of users, but not their email addresses.  So, the potential impact is limited because:

* At no point are any of the actual login credentials exposed.
* This list is only accessible by authenticated users.

This issue presents a greater privacy risk on multi-tenant systems, however, because it allows users on one tenant site to see the names of users on other tenant sites (even though they can't see which other site those users belong to).

**Comment by fmontes** [comment]
@jdotcms did the backend, we need to update the FE.

**Comment by bryanboza** [comment]
Fixed, tested on release-21.09 // Postgres // FF

**Comment by jcastro-dotcms** [comment]
PR cannot be back-ported to dotCMS 5.3.8.7 because of differences in existing code.
