### ISSUE TITLE
We need to obfuscate some environmental variables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20757]
In the backend of dotCMS Maintenance > System Info, we spit the list of system and environmental variables that are used to configure dotCMS.  These can include things like the DB password, the SES password, api tokens etc.  

We need to use a regex that matches certain keys and if the key matches, we obfuscate the value for that key. My inital thoughts on the regex matcher is using something like 
```
/passw|pass|secret|key|pwd/gi
```

If the env or system key matches those, then the value is shown as `********`

**Comment by fabrizzio-dotCMS** [comment]
Note for QA:
The new resource can be accessed here http://localhost:8080/api/v1/jvm
The part that needs verification is how any sensitive info like passwords or secrets is displayed when presented by this resource. 
e.g. If there's any sensitive environment variable. The value will get presented as a string of `*` instead of the real value. 
This way any system property or environment variable can be obfuscated.

So In order to test this feature, for example, you can create an environment variable and name it something like MY_IMPORTANT_PASSWORD=This_is_a_very_secure_password
And then request the resource. then verify it gets presented as `*********` 

The properties that get obfuscated are chosen based on a regular expression which by default value is `/passw|pass|secret|key|pwd/gi`

it can be changed via system properties using the following key OBFUSCATE_SYSTEM_ENVIRONMENTAL_VARIABLES
So it would be nice to test different expressions here.

**Comment by nollymar** [comment]
**Internal QA:** Needs work

When I tried to access this endpoint `http://localhost:8080/api/v1/jvm` I got a 500 error. I think the reason is that my dotCMS instance is running on docker. 

The log throws this exception: https://gist.github.com/nollymar/fc0a0a18a77c9c67b44a9f66071dbb85

On the other hand, I got the same exception when I tried to access the System Info tab and the page was blank: 

![Screen Shot 2021-08-16 at 4 12 38 PM](https://user-images.githubusercontent.com/8741395/129630115-6100dc0b-095e-4780-8d61-d4a9c743a350.png)


I think that when the java.lang.NoClassDefFoundError gets fixed, the System Info tab will work again.

**Comment by nollymar** [comment]
**Internal QA updates:**
Now it works. I can see many of my sensitive environment keys obfuscated, however, variables like: 
```
PWD_ABCD
OLDPWD
```

aren't obfuscated. 

According to the regex `/passw|pass|secret|key|pwd/gi`, it should.

![Screen Shot 2021-08-17 at 12 04 02 PM](https://user-images.githubusercontent.com/8741395/129769757-1ceb04cd-b35e-4884-a8f4-e3d40716ef9e.png)

**Comment by ian-b-cooper** [comment]
Quality Control Tested by Non-Dev, fix confirmed
