### ISSUE TITLE
Add initial maven build structure

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#21036]

**Comment by wezell** [comment]
@spbolton do any of the changes here break the existing build flow?  Can these be merged on top of our existing code or do we need a hard cut over?

**Comment by syndic8-stephen** [comment]
There are are couple of changes in the existing code that are required due to upgraded dependencies.  We would need to.upgrade the same in grade to match.  The rest is mainly layered on top of what we have already with extra folders and files.  It should otherwise still work with the existing build.  It may just confuse someone downloading the source into their ide as it will see both a cradle and maven project.   Also there is a .java-version file set to java 11 which could cause cradle build to be done with java 11 if jenv is used, but that is not essential and can be removed.

**Comment by spbolton** [comment]
https://github.com/dotCMS/core/commit/9c3a5b910cea56fafe4ac70efbe109761a0322d7

**Comment by spbolton** [comment]
This commit pulls in core web as a submodule,  this will only be used during a maven build currently and nothing needs to be done when building on gradle.   It works the same as enterprise and can be tied to latest master commit for testing.
