### ISSUE TITLE
Update docker image to set uid/gid to standard range

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21440]
We have a number of customers running in openshift/bitbucket that cannot run our current LTS image due to the fact that our UID/GID is set to `1000000000`.  We need to update those to be something in the "normal" unix range somewhere between `0-65535`.  In our case, let us change the UID/GID that dotCMS runs as to `65001`

For installations running dotcms as `1000000000`, you will need to run something like the following commands - **Note this is just an example**.  These need to be customized based on the linux user name and the volumes dotcms docker is using

```
usermod -u 65001 dotcms
groupmod -g 65001 dotcms
find /data -group 1000000000 -exec chgrp -h dotcms {} \;
find /data -user 1000000000 -exec chown -h dotcms {} \; 
```

**Comment by wezell** [comment]
PR: #21444

**Comment by nollymar** [comment]
Another PR: #21448

**Comment by nollymar** [comment]
**Internal QA:** Passed

It's working in our servers and I'm able to upload images without any problem

**Comment by bryanboza** [comment]
Fixed, tested with the last generated image. I'm able to start without problems.

**Comment by cobbg** [comment]
Due to some of the more restrictive Security Context Constraints (SCC) with OpenShift, such as the default restricted SCC, containers are run using an arbitrarily assigned user ID and require a GID of 0. Directories and files that are written to by processes in the image must be owned by the root group and be read/writable by that group.

This will require a small change in our Dockerfile as well since it attempts to issue a `groupadd` for the passed in GID, which will fail since GID 0 already exists.

I think we should probably use 65001:0 moving forward.

Here's some additional references:
[Adapting Docker and Kubernetes containers to run on Red Hat OpenShift Container Platform](https://developers.redhat.com/blog/2020/10/26/adapting-docker-and-kubernetes-containers-to-run-on-red-hat-openshift-container-platform#group_ownership_and_file_permission)
[Support arbitrary user ids](https://docs.openshift.com/container-platform/4.5/openshift_images/create-images.html#images-create-guide-openshift_create-images)
[Managing SCCs in OpenShift](https://cloud.redhat.com/blog/managing-sccs-in-openshift)
