### ISSUE TITLE
SVG files are not showing up in Image Field

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21447]
Reported via Support ticket: [106094](https://dotcms.zendesk.com/agent/tickets/106094)
Reproducible as of dotCMS 21.06.4, up to latest master (21.12)

An `Image` field in a Content Type allows you to browse files that have been uploaded to the dotCMS content repository. Those are the files that you can see in, for example, the **Site Browser** portlet. However, if you need to reference SVG files in your content, the File Selector widget is not displaying them, so content authors cannot select them.

**To Reproduce**
1. Create a new Content Type called `My CT` with an **Image** field.
2. Upload one or more SVG files to any folder in dotCMS.
3. Try to create a piece of content of type `My CT`. Click the `BROWSE...` button of the **Image** field, and go to the folder were you uploaded the SVG files.
4. The SVG files don't show up. There are no errors neither in the browser nor the `dotcms.log` file.

**Expected behavior**
The File Selector widget must display SVG files, and any other missing image type we support.

**Additional context**
For the time being, the only workaround for this issue is to use another image types, such as PNG files.

**Comment by swicken-dotcms** [comment]
After internal review, it appears this is not an issue. Per this Stackoverflow:

https://stackoverflow.com/questions/38169475/svg-in-html5-when-is-xml-declaration-xml-version-1-0-encoding-utf-8

The relevant section is this:

```
Note regarding external SVG (thanks, [@Kaiido](https://stackoverflow.com/users/3702797/kaiido)): SVG referenced via HTML5 img or CSS background-images must have its own XML declaration and should use the following DOCTYPE declaration:

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
          "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
```

We have found that the only SVGs that do not show up in the image selector are ones that do not have the relevant doctype/xml declarations in their header. Raw SVG is meant for embedding, not for files.  

In order to resolve this issue, you must add these relevant declarations to the files you are using.
