### ISSUE TITLE
Problems uploading files with long names and special characters

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21478]
We are getting a problem uploading some files and this seems that is regarding the name of the file, we need to take look what is affecting the functionality . 

The name of the file is `3 Self-Study Guide N°16.pdf`

The system is trying to upload in the background but we get an error and we are unable to upload the file, the next time that you try we are showing an error in the UI

Here the error in the log: https://gist.github.com/bryanboza/e9ba9cf4e711b8a6523bd19b65f00812

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/19972#issuecomment-1004385086_

**Comment by john-thomas-dotcms** [comment]
@bryanboza we've made some changes to file uploads.  Does this problem still exist?

**Comment by jcastro-dotcms** [comment]
This issue is NOT reproducible anymore.

I tested with the Docker image `trunk_a12617a`, and the `InvalidPathException` for a file with the specified special characters is no longer present. I tested uploading binary files and dotAssets, and the special character -- the `°` sign -- is being removed, as expected.

**Comment by bryanboza** [comment]
closing this since I'm unable to reproduce in the latest version.
