### ISSUE TITLE
URL Mapped content is not showing up in site search when using the include functionality

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21613]
**Describe the bug**
When you include a folder in Site Search, URL mapped content that is mapped to that folder/subfolders is not being included in the site search index. 

Reproduced on: 21.06, 5.3.8, 21.01

**To Reproduce**
1. Start up dotCMS with a demo starter
2. Create a site search index that includes `/store/products/*` 
3. Search the index, none of the products mapped to that path are listed.

**Expected behavior**
When including a folder it should include URL mapped content that is in the path.

**Additional context**
URL mapped content is properly indexed/ignored when using exclude, or when mapping the whole site. 

I tested placing the contentlet in the url mapped location as well, this did not help.

**Comment by jcastro-dotcms** [comment]
### NOTE TO DEVS:
Using Demo data and the steps provided by @swicken-dotcms , the Lucene query generated by the `UrlMapBunlder` class is:
```
+(structureName:Blog structureName:Product structureName:calendarEvent structureName:Activity structureName:Video ) +(urlMap:"/store/products/*" ) +(conhost:SYSTEM_HOST conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 )
```
Which returns no results. However, if the double quotes from the `urlMap` search term are removed:
```
+(structureName:Blog structureName:Product structureName:calendarEvent structureName:Activity structureName:Video ) +(urlMap:/store/products/* ) +(conhost:SYSTEM_HOST conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 )
```
Data is returned as expected.

As double quotes were added in order to NOT have problems with blank spaces in the `urlMap` value, I have a few questions:

- Should the code internally remove **ALL** blank spaces from the include/exclude patterns when kicking off the Site Search job? Or should it just NOT use double quotes when only one path is being included/excluded?
- The `URL Pattern` field in the Content Type properties allows blanks spaces. Is that the expected behavior?

**Comment by dsilvam** [comment]
Passed Internal QA: Site-search with URL-mapped content working as expected. Tested with case in the description

**Comment by bryanboza** [comment]
Fixed, tested with the provided description and this is working as expected. Tested on release-22.04 // Docker // FF

**Comment by erickgonzalez** [comment]
customer ticket https://dotcms.zendesk.com/agent/tickets/107162
