### ISSUE TITLE
OSGI multi uploads not working

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21685]
When I drag and drop osgi assets into dotCMS, they never load.  Also, if I upload a new osgi jar, it does not seem to be adding the imports to the extras file.

**Comment by rjvelazco** [comment]
#### Note
  It seems that it is a problem with the web components, they are not being loaded in the project.

<img width="540" alt="Screen Shot 2022-03-10 at 3 46 19 PM" src="https://user-images.githubusercontent.com/72418962/157743714-be57771a-0a7a-4cd7-bf56-9f4b921fb9c3.png">

**Comment by wezell** [comment]
currently broken on demo / 22.03

**Comment by wezell** [comment]
This does not work on docker

**Comment by bryanboza** [comment]
Tested on docker, using the last version of release-22.04 and we still having problems here, now we are able to D&D but we are not uploading the plugin, we just show a waiting message, but this process never finish 
![image](https://user-images.githubusercontent.com/2641437/162266338-986c2c2b-c3d2-4a20-b26c-54e0dd482230.png)

**Comment by fmontes** [comment]
@bryanboza any errors in the logs?

**Comment by oidacra** [comment]
Used the docker `22.04_5c2df5e_SNAPSHOT`, empty database.
The drag and drop works, upload the file, but 1 small bug:
- When the process of upload is finished, show an error in the console, and the list of plugins not is shown. To see the list need press the Refresh button.
Video of the test: https://www.loom.com/share/ae67f99de3254a74816f08b8401a224f

**Comment by rjvelazco** [comment]
These are happening on demo. The reason that both bugs exist:

1. The console error is due to a problem with Dojo/dijit. If you go to dotcms.demo.com and refresh the plugins, having two/more plugins already uploaded, we get the same error.

https://user-images.githubusercontent.com/72418962/164510356-fbcf4410-7fd1-4c38-82d0-1f89737d1daa.mov

2. When we upload a plugin, we have a `setTimeout`, to determine when to refresh the plugins list. As we are using a `timeout`, it's not exact and leads to a problem like some plugins are not shown when they are loaded -The same thing can happen when uploading a plugin without using the `drag&drop` due it also uses a `setTimeout` -. We have a `setTime` due to a problem we OSGI. ([See the full reason here](https://github.com/dotCMS/core-web/blob/cbd58706143735d220bd588555c52a36944c2517/apps/dotcms-ui/src/app/view/components/_common/iframe/iframe-component/iframe.component.ts#L184-L189)). This was already talked to Will.

**Comment by fmontes** [comment]
New issue for the error: https://github.com/dotCMS/core/issues/22057

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF. Now we are able to D&D, the other issue has been moved to a new card.
