### ISSUE TITLE
Problems pushing entire sites

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21695]
We are getting problems when you try to push an entire copy of the demo site,  we are getting an error with the `TemplateHandler` and the publishing job never finishes. 
Here the error: 
https://gist.github.com/bryanboza/ad77239029dca22ba0ff5e1a1a61744f

Here is the log trying to finish the job:
https://gist.github.com/bryanboza/b98e11ec53d7cfefa2917aaa9f141fd9

**To Reproduce**
- Create a copy of the demo site 
- Try to publish the entire copy site 
- Check your log file 

**Expected behavior**
We need be able to push entire sites without problems 

**Desktop (please complete the following information):**
Tested on release-22.02 // Docker // mssql

**Comment by freddyucv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/21695?planning-poker) with ZenHub @dsilvam @victoralfaro-dotcms

**Comment by freddyucv** [comment]
The Fix here was make the theme attribute no mandatory in template, we want to be able to create template and set the theme later, when a Template is use in a page and not has any theme set then the System Theme is used for render.

The demo.dotcms.com has several template that has theme set that does not exists so when it is send to a receiver and try to saved it fails because the theme does not exists, that is the reason why it affect the site Push Publishing.

**Comment by dsilvam** [comment]
core-web PR https://github.com/dotCMS/core-web/pull/1948

**Comment by dsilvam** [comment]
Passed Internal QA. Now publishing the entire `demo` site doesn't fail because of missing themes, however, the containers as files are not being pushed correctly (missing their container.vtl file) making the pages to not render. There's a workaround which is pushing individually the container.vtl of each missing container and flushing the _Multitree_ and _Velocity2_ cache regions. This will be captured on another ticket. Passing Internal QA on this one.

**Comment by bryanboza** [comment]
This card will be continued on #22030

**Comment by bryanboza** [comment]
We can pass and close this card for now
