### ISSUE TITLE
Create and endpoint to add a custom content tool

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#21796]
**Is your feature request related to a problem? Please describe.**
As a developer, I want to be able to **create and add to the menu** a custom content tool to the menu from an endpoint.

**Describe the solution you'd like**
The endpoint should receive:

1. Name of the content tool
2. The content type
3. If default view is card or list
4. Menu under where to be added

For the menu, I think we can use the `id`, that way in the UI we can use the menu endpoint (`/api/v1/menu`) to create a selector to pick where to put it.

**Additional context**
Just for an idea, [this is the UI](https://user-images.githubusercontent.com/751424/156364426-9e2656b5-4ef9-4647-861b-8f7966bd0abe.png) we use now.

But after this, then we have to added under a menu, the idea of this endpoint is to do both tasks at the same time.

**Comment by wezell** [comment]
This should be added to the PortletResource

**Comment by bryanboza** [comment]
We need to generate some JavaDoc on this endpoint 
![image](https://user-images.githubusercontent.com/2641437/170139049-a150c6a9-b08e-4e8a-80e2-02988c2391e1.png)

- At UI level the field `tool Name` and `Id` both are required, wich avoid to create two portlets with the same name, but at endpoint level just the name is required, and the auto-generation of the ID allow to have multiple ones with the same name 
UI: 
![image](https://user-images.githubusercontent.com/2641437/170139622-fc2db50a-1899-4f3b-8ac2-de94d93d730a.png)
![image](https://user-images.githubusercontent.com/2641437/170140632-bf5f8025-0bd5-4f18-9042-9944ed960a35.png)
![image](https://user-images.githubusercontent.com/2641437/170139733-755308fc-9780-4a57-be77-cea9f6786dc9.png)

**Comment by bryanboza** [comment]
Tested on release-22.06 and we need some work here: 

- In the postman test we are sending some body that is not necessary here, we need just the call to the url:
![image](https://user-images.githubusercontent.com/2641437/170146020-fdf237c5-52f8-42fd-b517-5bc25a188a06.png)
- If you call the same this twice we are returning a 400 error with the message `Unable to save Object to Hibernate Session` we need be more specific in the error 
![image](https://user-images.githubusercontent.com/2641437/170146118-74ddea75-d305-4771-9eb5-a4b142b67eab.png)
- If you send a portlet that does not exist we are returning a 401 Unauthorized error, we need to return a 404 since this is not a permissions error if not we are unable to found the {layoutId} 
![image](https://user-images.githubusercontent.com/2641437/170146561-5fae73e9-e401-4224-be06-bde26cc7759b.png)

**Comment by fabrizzio-dotCMS** [comment]
new PR https://github.com/dotCMS/core/pull/22284

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by bryanboza** [comment]
Fixed, tested after the changes and now it is working as expected...
