### ISSUE TITLE
We are not pushing the folder dependencies after you push the folder twice

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#21963]
If you have a push environment and push some folder, we are pushing the complete folder and all the dependencies, but if you manually delete the folder from the receiver side and push the same folder again, we are just pushing the folder and we are not including the dependencies. This is because we are not detecting changes in the dependencies and then we are skipping the content into it. 

I'm using the default push filter "Everything and dependencies"

**To Reproduce**
- Configure your push environment 
- Create or use any folder on the sender side and upload some files 
- Push the complete folder 
- From receiver, remove the folder manually
- Now push the entire folder again (both cases using the "Everything and dependencies folder") 

**Expected behavior**
Maybe when you remove the folder we need to delete the push history to avoid that case. 

**Desktop (please complete the following information):**
Tested on release-22.04 // Docker // FF

**Comment by nollymar** [comment]
You need to force push in order to see the dependencies in the receiver. The reason is that we keep a push history in the sender and for future pushes we exclude the pieces of content that were already sent (the mod_date didn't change after the first push). The push history in the sender is not deleted because you're removing the folder only in the receiver.

This behavior has been this way for a while. I tested this scenario in 22.06.

**Comment by john-thomas-dotcms** [comment]
If the dependencies haven't changed, then they should not be pushed again.  The scenario to test would be:
1. Create folder
2. Push
3. Delete folder
4. Recreate folder
5. Modify one of the dependent objects
6. Push again

**Comment by nollymar** [comment]
Agreed. The scenario described by @john-thomas-dotcms is working correctly.

**Comment by bryanboza** [comment]
ok, according to the comments mentioned above, this is expected, nothing to do here.
