### ISSUE TITLE
Add a "Push Remove Now" Action

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22021]
We have a "Push Now" actionlet that is super helpful when you want to enable push publishing in a workflow without forcing user intervention.  The only issue is that we do not have a "Push Remove Now" actionlet that does the same work when un-publishing content in a workflow.

**Comment by nollymar** [comment]
**Internal QA:** Needs work

It isn't so clear for an end user that a Push Remove Now is a Push Now with a flag in true. Ideally, there should be a 'Push Remove Now' actionlet. Otherwise, we need to doc. Any thoughts @wezell ? 

Besides, there is a missing key in the Language.properties that is not being resolved. 

https://user-images.githubusercontent.com/8741395/169621785-f5b2336f-2737-400c-a057-4c8c11c9dc9f.mov

**Comment by fabrizzio-dotCMS** [comment]
New PR https://github.com/dotCMS/core/pull/22340

**Comment by nollymar** [comment]
**Internal QA:** Needs work

The dropdown displays correctly: 
![Screen Shot 2022-06-06 at 6 16 01 PM](https://user-images.githubusercontent.com/8741395/172264580-1a3e2f99-8fa4-47d9-a558-b923ec4e7452.png)



But, the sub-action label still says "Push Now" instead of "Push/Remove Now": 

![Screen Shot 2022-06-06 at 6 12 50 PM](https://user-images.githubusercontent.com/8741395/172264606-07eafea9-8901-4fd7-89bf-35c43ef3f082.png)

**Comment by fabrizzio-dotCMS** [comment]
new PR https://github.com/dotCMS/core/pull/22363

**Comment by nollymar** [comment]
**Internal QA:** Passed
![Screen Shot 2022-06-13 at 10 26 59 AM](https://user-images.githubusercontent.com/8741395/173389399-a927449a-8664-48b1-89c1-7f13679dbd03.png)

**Comment by bryanboza** [comment]
Fixed, tested on release-22.06 // Docker // FF

**Comment by bryanboza** [comment]
This is woking, but we need an improvement here: 

- We need to notify the user that we need some config to use this action, also we need a better error in case you just add this and don't add the corresponding configuration, this because if you don't configure the action we just show a `null` error and we are printing a big log but isn't specific 
![image](https://user-images.githubusercontent.com/2641437/173452999-78bae70a-caae-4bf5-a805-e0a9b54726ed.png)
Here the log error: 
https://gist.github.com/bryanboza/075a032f257e40e133d3d4a60a1cf047

**Comment by nollymar** [comment]
@bryanboza I agree with you but I think your observations should be in a new card for two reasons:
1.  The missing configuration notification should be part of the Workflow functionality, not just the Push Remove. For example: you will get an error if you forget to configure the 4 eyes workflow as well.
2. This is how the "Push Now" has worked from previous versions. We just modified the existing workflow to support the remove.

**Comment by bryanboza** [comment]
Fixed, the reported improvements was moved to a new card: #22412
