### ISSUE TITLE
Doing a selection moving up is broken

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22029]
**Describe the bug**
When you select blocks or text moving UP the selection is broken.

**To Reproduce**

https://user-images.githubusercontent.com/751424/163277496-dcc001db-a4ed-4a63-b432-f2baa847efc2.mp4

**Expected behavior**
The selection should be clean both directions, up and down.

**Proposal solution**

https://user-images.githubusercontent.com/751424/163277903-faf96f04-1af5-4c05-9f26-3453bff7d810.mp4

**Comment by rjvelazco** [comment]
#### Bug

If you are selecting more than one paragraph using the keyboard, and you stop the section on an empty line, even though there is text selected, the bubble menu is never shown.

#### To Reproduce

https://user-images.githubusercontent.com/72418962/164087066-0974a9d1-52ab-4913-8ba6-f846d81c8914.mov

#### More information

This bug seems to be related to this conditional:

<img width="884" alt="Screen Shot 2022-04-19 at 4 14 56 PM" src="https://user-images.githubusercontent.com/72418962/164088299-4750aba5-e1fa-426b-b9f1-10281088f937.png">

**Comment by bryanboza** [comment]
Fixed, tested on release-22.04 // Docker // FF
