### ISSUE TITLE
JAVA_VERSION does change the version of java included in docker image

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#22274]
**Describe the bug**
Following the directions here:  https://github.com/dotCMS/core/tree/v22.03.1/docker/dotcms I expected to be able to change the version of Java that was put in the docker image; however, it did not seem to affect anything.

**To Reproduce**
1. On local filesystem inside of dotCMS/core repo, ran `git checkout v22.03.1`
2. Built the dotCMS docker image to check initial java version:
  * ran 'docker build --pull --no-cache --build-arg BUILD_FROM=TAG --build-arg BUILD_ID=v22.03.1 -t dotcms-test .`
  * from inside docker container ran `java -version`
  * output was `Corretto-11.0.14.10.1`
3. Built the dotCMS docker image to update the java version it used:
  * ran `docker build --pull --no-cache --build-arg BUILD_FROM=TAG --build-arg BUILD_ID=v22.03.1 --build-arg JAVA_VERSION=11.0.15.9.1-amzn -t dotcms-test .`
  * from inside docker container ran `java -version`
  * output was `Corretto-11.0.14.10.1`

**Expected behavior**
Expected the Java version to be `Corretto-11.0.15.9.1`

**Screenshots**
![CleanShot 2022-05-23 at 11 10 51](https://user-images.githubusercontent.com/3208956/169862116-fa2c9aed-7aa9-4791-a45b-4b009f019a3e.png)

**Additional context**
I also tried this on the 21.06.7 LTS version with the same results

**Comment by wezell** [comment]
This is a documentation issue.  Since we have moved to the `java-base` to deliver our java version, you need to first build the `java-base` by passing the right `JAVA_VERSION`

https://github.com/dotCMS/core/tree/master/docker/java-base

and then reference that as the base for your new image

https://github.com/dotCMS/core/tree/master/docker/dotcms/Dockerfile#L35
