### ISSUE TITLE
Relationship is not showing the right parent

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#22549]
**Describe the bug**
When creating a relationship many to one, the "child" actually is the parent and the "parent" is the child, but in the UI it's shown the other way around.

**To Reproduce**
1. Go to Content Types portlet
3. Create a content type
4. Add a Relationship Field, set the Cardinality to **Many to One**.
5. Open the just created Field, and check the UI of the relationship.

**Expected behavior**
The child should be marked as the parent and the parent as the child.

**Screenshots**
DB Definition:
![Screen Shot 2022-07-11 at 9 16 43 AM](https://user-images.githubusercontent.com/5278970/178298047-dca9b473-04cf-4ea2-9d8c-a60befe18cd0.png)

Relationship Definition:
![Screen Shot 2022-07-11 at 9 17 10 AM](https://user-images.githubusercontent.com/5278970/178298138-eec6e0bf-efb1-45fe-b805-a583c5e9fb39.png)

Parent Id:
![Screen Shot 2022-07-11 at 9 18 30 AM](https://user-images.githubusercontent.com/5278970/178298403-dac39668-df93-41dd-af28-7d571e1ad677.png)

Reproducible in 22.03 LTS and 22.06 (demo).
Customer ticket: https://dotcms.zendesk.com/agent/tickets/107691

**Comment by nollymar** [comment]
PR: 22726

**Comment by nollymar** [comment]
**Internal QA:** Needs work
The relationship is not showing correctly on the other side of the relationship

**Steps to reproduce:** 
1. Create two content types (Type1 and Type2) 
2. Add a ManyToOne relationship field on Type1. Type1 is shown as child and Type2 as parent which is ok.
3. Go to Type2 and create the other side of the same relationship. In this case Type2 is shown as child and Type1 as parent which is not correct because is the same relationship.

I've attached a video for further details

https://user-images.githubusercontent.com/8741395/188009891-f96b2172-1aef-4ff0-80f2-10b680962458.mov

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/22934/files

**Comment by nollymar** [comment]
**Internal QA:** Needs work

From the parent side (Parent Content Type) I was able to add the relationships and the icons displayed correctly.
<img width="1324" alt="Screen Shot 2022-09-15 at 11 49 01 AM" src="https://user-images.githubusercontent.com/8741395/190462445-29367f2d-5e39-4b15-aaf8-b7b7177369a8.png">



However, when I tried to add all the existing relationships on the other side (Child Content Type), I only see 3 of the 4 existing relationships

<img width="1676" alt="Screen Shot 2022-09-15 at 11 49 44 AM" src="https://user-images.githubusercontent.com/8741395/190462449-5adf743f-9cd7-4e83-b9e4-d062db44f2f6.png">

**Comment by nollymar** [comment]
**Internal QA (Update):** Passed

**Comment by bryanboza** [comment]
Fixed, tested on release-22.10 // Docker // FF

**Comment by erickgonzalez** [comment]
Test if also fixes this https://github.com/dotCMS/core/issues/22532
