### ISSUE TITLE
Push / Pull Sites 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#22672]
Using the Quarkus example supplied by Steve, we should begin the process of building out a CLI that can "sync" e.g. pull and push Sites to dotCMS.

Questions:

Hostname vs. hostId
Deterministic Ids?
Use content type var everywhere
hide default fields
e.g. don't show props that have false/0/empty string
How to handle content type updates / deletes

**Comment by nollymar** [comment]
**Internal QA:** Needs work

- [ ] Trying to run `host switch -in={site_name}` fails with https://gist.github.com/nollymar/f36d65bf63ee1093d0517f8f9b8d2fcc
- [ ] `host remove` message should be fixed. It says: "Site **[%] delete** successfully"

**Comment by nollymar** [comment]
**Internal QA:** Needs work

- the `host switch` is not failing now but the site is never switched even when it says `Successfully switching to site: [mysitename].`
- I keep seeing this typo `Site [test2] **delete** successfully`

**Comment by fabrizzio-dotCMS** [comment]
host switch command does not work for our CLI client because we're not sending the session tracking bits. 
All we send is an authentication token
The site switch operation occurs at the session level on the server side. But it is failing to track a session for the cli 
so getting the fallback which is the getting the current site.
 @spbolton  you think is it possible to add the missing bits to accomplish session tracking?

**Comment by wezell** [comment]
we should not host switch with the CLI.  the CLI needs to be stateless.

**Comment by fabrizzio-dotCMS** [comment]
ok, then I'll remove the site switch command

**Comment by dcolina** [comment]
Internal QA:

Step by step:

1. Login via CLI with the command `login -u admin@dotcms.com -p admin.`

![Screenshot 2023-06-02 at 15 13 33](https://github.com/dotCMS/core/assets/29883881/9e33f74d-9016-4663-afb4-5f41c4d0591f)

2. Download the default site with the command `site pull --format=YAML -to=backup.dotcms.com.yaml demo.dotcms.com`.

![Screenshot 2023-06-02 at 15 14 43](https://github.com/dotCMS/core/assets/29883881/53db6a5a-f02b-479f-a51c-93d9f2171330)

3. Using a text editor, change some properties of the file **backup.dotcms.com.yaml**. For example

```
---
siteName: "backup.dotcms.com"
tagStorage: "SYSTEM_HOST"
keywords: "CMS, Web Content Management, Open Source, Java, J2EE, DXP, NoCode, OSGI,\
  \ Apache Velocity, Elasticsearch, RESTful Services, REST API, Workflows, Personalization,\
  \ Multilingual, I18N, L10N, Internationalization, Localization, Docker CMS, Containerized\
  \ CMS"
description: "dotCMS testing site pull / push command ::::"
languageId: 1
modDate: "2023-06-02T00:00:00.000+00:00"
modUser: "dotcms.org.1"
live: true
working: true
```

4. Once the file is saved, we publish it with the command site` push --force --format=YAML backup.dotcms.com.yaml.`

![Screenshot 2023-06-02 at 15 16 33](https://github.com/dotCMS/core/assets/29883881/e92117e9-cbd7-4a24-a7a2-fa507e7dbaed)

**HINT:** 
Instead of checking **[ERROR]** ❗` No site named [backup.dotcms.com] was found`. a **[WARN]** might be better because after all the push operation is running correctly.

5. As a last step, we list all sites with the `site` command, in the result we can see both the default site and the new site uploaded in the previous step.

![Screenshot 2023-06-02 at 15 17 27](https://github.com/dotCMS/core/assets/29883881/d670cdab-6e96-4c1b-b006-eb7eec3259ee)

**NOTE:**
When running the site help command, there is a small error in the description of the --force parameter, "Force must **me** set to true to update a site name". It should read "Force must **be** set to true to update a site name".

![Screenshot 2023-06-02 at 14 04 44](https://github.com/dotCMS/core/assets/29883881/7f824292-98aa-4e02-8af4-08fabdfac8a4)


Internal QA: PASSED
