### ISSUE TITLE
Implement GHA to run CLI tests

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#22706]
Parent Issue
#24753

A GHA should be implemented to run CLI tests (if needed) and generate a report. It's important to consider: 
- There are tests in https://github.com/dotCMS/core/tree/master/tools/dotcms-cli/api-data-model and https://github.com/dotCMS/core/tree/master/tools/dotcms-cli/cli
- The GHA should be triggered for each PR (if needed) and run the tests that belong to the module being modified (api-data-model or cli)

**Comment by fabrizzio-dotCMS** [comment]
1. We should be able to disconnect the Test Containers and run tests without them.  That is in case we need to debug locally against a specific branch or revise the information stored in a local database. We need that flexibility.

2. If I wanted to accomplish so I would need to comment out the annotation `@QuarkusTestResource(ContainerResource.class)` on `ContainerTest` but it would be nice if we could disconnect the execution via one single property across the whole application

3. We should only have one single class to configure and launch the test containers currently each module has its own `ContainerResource` I think we could have only one class for that purpose.

4. ContainerResource requires that a few properties should be injected via Environment variables. If I don't do that an exception arises saying that the property can not be expanded which is completely fine for our development environments. 
I did set the properties prior to running them in my terminal window and it all worked fine. However, when running against test containers from my IDE (when running an integration test for example) The Test won't run because there's no way for the IDE to know about that variable. We need to find a way to tell the IDE about those props or indicate that a fallback can be used here 
`testcontainers.dotcms.license.file=${DOTCMS_LICENSE_FILE:/local/license/path}`

**Comment by fabrizzio-dotCMS** [comment]
it all looks good from my perspective I can see the link to the report. 
It shows okay when nothing breaks, shows an error when there are failing tests, and once I get to fix a test the build picks the fix pretty quickly. 
Tested the build locally using the instructions suggested above and it all looks okay too. 
The only observation I have is in regard to the separation of unit and integration tests
Since the fail-safe report is supposed to hold only info related to IT and Surefire is intended to have only unit test-related info
I see certain test results appear in both reports 
![Screenshot 2023-08-30 at 17 01 49](https://github.com/dotCMS/core/assets/37148755/5be305be-2882-41e2-9e01-4884ad05284a)

**Comment by fabrizzio-dotCMS** [comment]
I verified that the reports were shown correctly and also that changes made in the backend were getting picked.
I'm passing it.
