### ISSUE TITLE
Console error trying to download images from image editor 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#22891]
When you edit some image using the image editor feature and then you try to download the image, we are getting an error in console and we are unable to download the image. 
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/2641437/187540241-3f720b9a-952a-40ed-9954-d9d13fab830c.png">

**To Reproduce**
- Login as admin
- From site browser upload a new image file 
- Try to edit using the image editor
- Try to download the image 
- Check your console log 

**Expected behavior**
We need be able to download without problems 

**Desktop (please complete the following information):**
Tested on release-22.09 // Docker // FF

**Comment by muhammadfaizandotcms** [comment]
One of our customers wants to have an option in the UI to download the file in all supported formats.
Relevant Ticket: https://dotcms.zendesk.com/agent/tickets/109244
Maybe we can provide them with a dropdown so that users can select and download it in their desired format.
The functionality is already available through the URL.
Here are a couple of examples.
PNG
https://demo.dotcms.com/contentAsset/image/d77576ce-6e3a-4cf3-b412-8e5209f56cae/image/filter/Resize,Jpeg/resize_w/200
JPEG
https://demo.dotcms.com/contentAsset/image/d77576ce-6e3a-4cf3-b412-8e5209f56cae/image/filter/Resize,Jpeg/resize_w/200/jpeg_q/65
WEBP
https://demo.dotcms.com/contentAsset/image/d77576ce-6e3a-4cf3-b412-8e5209f56cae/image/filter/Resize,Jpeg/resize_w/200/webp_q/65
PNG
https://demo.dotcms.com/dA/d77576ce6e3a/200w
JPEG
https://demo.dotcms.com/dA/d77576ce6e3a/200w/jpeg/80
JPEGP
https://demo.dotcms.com/dA/d77576ce6e3a/200w/jpegp/80
WEBP
https://demo.dotcms.com/dA/d77576ce6e3a/200w/webp/80We
