### ISSUE TITLE
No 'Receive From' setting option in admin UI

### ISSUE THREAD

**Issue by notmattmonroe** [dotCMS/core#22957]
### Describe the bug
When navigating to the Configuration -> Push Publishing portlet there is no place to add "Receive From" information as there has been in previous releases

### To Reproduce
1. Configuration -> Push Publishing portlet 

### Expected behavior
There should be a Receive From block here to enter configuration information
![Screen Shot 2022-09-12 at 12 22 51 PM](https://user-images.githubusercontent.com/44986962/189717596-48470fb6-a8d8-440c-b117-b727acbd5e79.png)

**Comment by bryanboza** [comment]
Hey, @notmattmonroe this has been deprecated some time ago, we have multiple releases with the new authentification using JWT instead the `signature validation`, now when you add a push environment, you need to define the credentials in the remote server in order to get the token to push the content. 

However, we have a property in the `dot-marketing.config.properties` file to disable this and bring it back to the legacy method.  `USE_JWT_TOKEN_IN_PUSH_PUBLISH`

**Comment by notmattmonroe** [comment]
Ah, ok, that makes sense.   The documentation on the dotCMS website does not reflect this from what I was able to find, it still references the admin UI setting.
