### ISSUE TITLE
UI - Favorite Page: Listing Favorite page contentlets

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#23058]
### Parent Issue
#22343 

As a user once I need a new Pages portlet that displays the DotFavoritePage contentlets created and a list of Pages of all the site.

this task only includes the area in the red box

![image](https://user-images.githubusercontent.com/37185433/201963133-5bbb89fb-a508-41e6-a4e8-130a579a4d5a.png)

Acceptance criteria
- DotFavoritePages should initially list only 5 items
- Star icon should be highlighted if the favorite page was created by the user, if it's assigned by an admin then the star icon should not be highlighted
- PrimeNG Card component needs to be used
- The order of listing favorite pages should be based on `Order` field
- Scope is Only for listing favorite pages, no click interaction will be done

Added more commentaries/notes at the bottom

**Comment by alfredo-dotcms** [comment]
More requirements:
![image](https://user-images.githubusercontent.com/37185433/205177251-abd579e5-59ff-4f7f-ba3d-e14faf08a4bb.png)

![image](https://user-images.githubusercontent.com/37185433/205177404-24c606e8-e3fd-4343-b134-aea8c51e4fc6.png)

![image](https://user-images.githubusercontent.com/37185433/205177655-65340249-7502-4f4c-8551-a05b7c1ce381.png)

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23437/files

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/24335

**Comment by jgambarios** [comment]
**Internal QA:** Needs work

### Archive content in Favorites pages grid
https://user-images.githubusercontent.com/923947/225692114-79ccc7fc-a203-41de-afba-4b0de0aef70c.mp4

1. Error: After archiving the content the grid shows an empty space where the favorite page used to be.
2. Error: After archiving the content the contextual menu does not work any more.

In order to come back to a normal state the "SEE LESS" button needs to be use to fired a refresh of the component.

### Show Archived not working
https://user-images.githubusercontent.com/923947/225692301-8e3735cf-fa5c-4e36-9fa1-438bd8aa6680.mp4

1. Error: After archiving content from the Favorites grid, the "Show Archived" in the pages list does not display any page.

**Comment by alfredo-dotcms** [comment]
@jgambarios 
- issues 1 & 2, does not apply anymore due to this change of requirement https://github.com/dotCMS/core/issues/24442
so once that task gets merged it won't be happen again!

- issue 3: a bug was found related to that archived functionality, so I'm doing the fix and relating it to this task
PR: https://github.com/dotCMS/core/pull/24635/files

**Comment by jgambarios** [comment]
As commented in https://github.com/dotCMS/core/issues/23058#issuecomment-1507703487 the main scope of the ticket is done, some missing behaviors are being tracked in https://github.com/dotCMS/core/issues/24561 and https://github.com/dotCMS/core/issues/24442

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_2e52dde7_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
