### ISSUE TITLE
UI - Favorite Page: Click on a Favorite page in Listing portlet should open it in Edit Page mode

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#23060]
As a user once I need that once I click a favorite page on the Listing Favorite portlet, it will take me to the Edit page mode of that favorite page so I can edit it

Acceptance criteria
- When a favorite page is clicked it should load the EDIT PAGE, setting the same params that were used to created the favorite page, such as SITE, LANGUAGE and DEVICE

**Comment by alfredo-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/23483/files

**Comment by fabrizzio-dotCMS** [comment]
Let's say I create a new favorite page "by hand" (Which I'm not sure why it's allowed) and I messed the url
Then an invalid entry gets created like this:

![Screen Shot 2022-12-22 at 17 31 05](https://user-images.githubusercontent.com/37148755/209242555-44170543-99db-4945-8500-a9e8c3f5b820.png)

First thing is that we should have a 404 image thumbnail (showing that preview isn't allowed)  in this case instead of showing the broken image that the browser sets

Second when clicking on the invalid entry the following dialog is shown (which is perfect)

![Screen Shot 2022-12-22 at 17 31 11](https://user-images.githubusercontent.com/37148755/209242536-272505fc-053d-4f69-b211-521a32c63720.png)

Now the odd behavior here is that the user gets kicked out from the favorite pages portlet. The user should be redirected back into it.

**Comment by alfredo-dotcms** [comment]
the decision made is that the the URL field should be read only, that will be applied on task https://github.com/dotCMS/core/issues/23061

**Comment by alfredo-dotcms** [comment]
@fabrizzio-dotCMS look at comment https://github.com/dotCMS/core/issues/23060#issuecomment-1373821611 and check if we can put it as Passed QA

**Comment by fabrizzio-dotCMS** [comment]
I'm passing it since the URL field will be set to read-only in this card https://github.com/dotCMS/core/issues/23060

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.03_511ed969_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0

Page does not link to the Edit Page mode 

https://user-images.githubusercontent.com/110418590/223511006-028572f8-31a0-4f8a-9e45-6c8c08f7506e.mov

**Comment by nollymar** [comment]
According to our last discussion with @wezell , we decided to keep the behavior it has.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_7d8de130_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0.1
