### ISSUE TITLE
Make it easy for admins to view/manage content types

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23231]
When developing a site, developers are constantly jumping back and forth to the content type screen to check and modify a content type's definition.  It would be nice to have a quick contextual link that would allow an admin to jump to the content type of the content they are looking at.

![Screen Shot 2022-10-25 at 3 59 02 PM](https://user-images.githubusercontent.com/934364/197870097-85daf36c-03e5-4a34-a2f7-63f7fd049a12.png)

**Comment by jcastro-dotcms** [comment]
# Internal QA: FAILED
If you create a Contentlet first, close the modal window, re-open it, and then click the Content Type's name -- which is a link now -- then it takes you to the Content Type's edit page.

However, the following scenarios will fail:
* Click `Add New Content` to open the modal window for creating a contentlet of type `Content (Generic)`, and **immediately click the Content Type's name**. It will leave the modal window open.
* Create a content of type `Content (Generic)`, publish it, and **immediately click the Content Type's name**. It will leave the modal window open as well.

In both situations, you have to manually close the modal window in order to see the Content Type's edit page.

As discussed with @fmontes , we're moving this ticket to the next release.

**Comment by josemejias07** [comment]
**Failed QA** - Tested on **23.01_ca54c27a_SNAPSHOT** // Docker // macOS 13.0 // FF v107.0.1

After creating a content type using the content search portlet and saving it, the link does not close the iframe, but it does redirect to the content type. The iframe should be close to show the content type portlet. 

References: 
![hyperlink](https://user-images.githubusercontent.com/110418590/207434918-c78e560b-d313-497a-8974-411c774172cf.gif)

**Comment by hmoreras** [comment]
**QA** Per conversation with Will, show the link only when the dialog is open for editing and not the first time when is creating the content for the first time.

**Comment by zulqarnainvd** [comment]
[screen-capture (8).webm](https://user-images.githubusercontent.com/113915849/210795049-5271385c-cea5-46e0-84ac-04af6c9ed11c.webm)

**Comment by zulqarnainvd** [comment]
**Internal QA Failed**

**Comment by fmontes** [comment]
### Known issue:
If users create a new content, save and publish the link will not be active, is only active ON edit.

Code limitation.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.02_3220636c_SNAPSHOT** // Docker // macOS 13.0 // FF v109
