### ISSUE TITLE
Password validation failed for few characters

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#23292]
### Describe the bug
Password validation is failing despite the number of characters entered is more than required.
Reproduces on 22.03.2 and 22.10
Related Ticket: https://dotcms.zendesk.com/agent/tickets/109001

### To Reproduce
1. Go to the demo site.
2. Go to Settings->Users.
3. Try to change the password for any user with the following values.
password. 
password$
password*
pa$sword
4. Getting validation error.

### Expected behavior
Password should be changed if it's valid

### Additional context
Password failed with these characters:
. ("dot")
&
^
*
(
)
{
}
[
]

**Comment by erickgonzalez** [comment]
This is our password regex 
```
passwords.regexptoolkit.pattern=/[!#%+1234567890:=?@ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz]{8,}\\Z/
```

looks like is expected that those char aren't being accepted.

**Comment by swicken-dotcms** [comment]
This is actually still an issue. 

```
pa$$word -> fails (gives error)
password$ -> fails (gives error)
$password -> passes (without error)
$$password -> passes (without error)
$pa$$word -> fails (with error)
```

We have inconsistencies with how we are handling passwords. It has something to do with our regex string. A user reported this regex string works well for them:

```
"DOT_PASSWORDS_REGEXPTOOLKIT_PATTERN": '/([A-Z]|[a-z]|[0-9]|[!-\/]|[:-@]|[\[-`]|[{-~]){8,}\\Z/'
```

This allows all valid ASCII chars.

**Comment by m27iu4** [comment]
- I have tested `"DOT_PASSWORDS_REGEXPTOOLKIT_PATTERN": '/([A-Z]|[a-z]|[0-9]|[!-\/]|[:-@]|[\[-`]|[{-~]){8,}\\Z/'` but it still fails for characters like ^ or £
- I tried the less restrictive regex `/^.{8,}$/` and below are the results:

- this regex only checks that the password is at least 8 characters long and does not enforce any other constraints
- `D3l3t3.th1s!` fails because it looks like it counts only alphabetical (A-Z) and the "at least 8 chars" condition fails;
- `D3l3t3.th1s!sss` passes because there are 9 chars (A-Z) contained in the pass
- `D3l3t3.th1s£sss` fails
- `D3l3t3.th1s^` fails, although Java and JavaScript tests pass
- `D3l3t3.th1s^sss` fails, although Java and JavaScript tests pass

`function useRegex(input) {
    let regex = /^.{8,}$/;
    return regex.test(input);
}

console.log(useRegex('D3l3t3.th1s£'))`

- the code above logs `true`

- when I tested `D3l3t3.th1s£ `and `D3l3t3.th1s£sss` with a Java online compiler I got this error:
`ERROR!
/tmp/ohRSAgkKAO/PasswordValidator.java:6: error: unmappable character (0xC2) for encoding US-ASCII
        String password = "D3l3t3.th1s??sss";
                                      ^
ERROR!
/tmp/ohRSAgkKAO/PasswordValidator.java:6: error: unmappable character (0xA3) for encoding US-ASCII
        String password = "D3l3t3.th1s??sss";`

- my conclusion is that in the first place passwords fail because of the way we count characters (only A-Z)
- the second problem is that `^` and`£` are not passing our regex

**Comment by dsolistorres** [comment]
**Additional note**
To include all the regular ASCII characters in the password validation regex (without control characters) this value can be used for the `passwords.regexptoolkit.pattern` property:
```
passwords.regexptoolkit.pattern=/^[\\x20-\\x7F]{8,}$/
```
To include also all characters from the extended ASCII set (that includes symbols like `£`) this value can be used:
```
passwords.regexptoolkit.pattern=/^[\\x20-\\xFF]{8,}$/
```

**Comment by erickgonzalez** [comment]
NOTE TO QA:

This was an issue with the REGEX. According to it, these 2 passwords should fail, but one of them was working.

D3l3t3. -> fails
D3l3t3.th1s!sss -> works

After the fix, both passwords should fail.
