### ISSUE TITLE
Make Events in Experiments work when running from Docker

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#24271]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

When you run dotCMS from Docker, the events in Experiments are not registered because a problem in the resolution of the hostname. It takes the Docker container id instead of the actual hostname. 

### Steps to Reproduce

1. Bring up the analytics infrastructure using the `analytics-compose.yml` 
2. Bring up dotCMS using `docker-compose.yml` file
3. Create and run a new experiment 

Events won't be registered

### Acceptance Criteria

Running as described above needs to register events and report results. 

### dotCMS Version

23.03

### Proposed Objective

Core Features

### Proposed Priority

Priority 1 - Show Stopper

**Comment by dsilvam** [comment]
Passed Internal QA: Experiments running from Docker.

**Comment by bryanboza** [comment]
We need some work here: 

- Tested according to the acceptance criteria and this is not working yet. A lot of things need be implemented

I do all the analytics configurations to make sure we are able to run experiments on docker, here the current results  

- When I create an experiment, and start it, we need to clear the dotCMS cache in order to start getting the variants, if not you always will get the original variant 

- We are counting the events but just from the cube console `http://localhost:4001` 
![image](https://user-images.githubusercontent.com/2641437/234401809-567df1f7-205e-424e-9edb-174332594be9.png)
if you call the endpoint we are not returning results, everything comes in 0 
```
{
    "entity": {
        "goals": {
            "primary": {
                "goal": {
                    "conditions": [
                        {
                            "operator": "CONTAINS",
                            "parameter": "url",
                            "value": "/QA/page2"
                        },
                        {
                            "operator": "CONTAINS",
                            "parameter": "referer",
                            "value": "/QA/page1"
                        }
                    ],
                    "name": "Primary Goal",
                    "type": "REACH_PAGE"
                },
                "variants": {
                    "DEFAULT": {
                        "details": {},
                        "multiBySession": 0,
                        "uniqueBySession": {
                            "count": 0,
                            "totalPercentage": 0.0,
                            "variantPercentage": 0.0
                        },
                        "variantName": "DEFAULT"
                    },
                    "dotexperiment-9cdd93d91f-variant-1": {
                        "details": {},
                        "multiBySession": 0,
                        "uniqueBySession": {
                            "count": 0,
                            "totalPercentage": 0.0,
                            "variantPercentage": 0.0
                        },
                        "variantName": "dotexperiment-9cdd93d91f-variant-1"
                    }
                }
            }
        },
        "sessions": {
            "total": 1,
            "variants": {
                "DEFAULT": 0,
                "dotexperiment-9cdd93d91f-variant-1": 1
            }
        }
    },
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```
- If you go to the results or graphics, this is not implemented yet, this is showing a hardcoded report with fake data , since as you can see the data is old dates and include 3 variants, and we are able to add just 2. 
![image](https://user-images.githubusercontent.com/2641437/234402670-9ea239f9-093d-498d-b37a-1d4041d210cf.png)



According to the provided steps and the acceptance criteria I can't pass this card because we are unable to confirm the experiments are running property on docker. Needs some work here

**Comment by dsilvam** [comment]
@bryanboza can you please share the params for the analytics app that you used? I had a similar issue and it was because wrong parameters (wrong port)

**Comment by bryanboza** [comment]
Please retest all the points because I'm pretty sure my configuration is ok @dsilvam

**Comment by dsilvam** [comment]
Passed Internal QA. This is working on master. Please reach out to me if it doesn't work to check the parameters used.

**Comment by bryanboza** [comment]
Since this is an old card, we can pass this, now experiments runs on docker instances without problems, new issues reported in a different cards
