### ISSUE TITLE
dotCMS CLI: Implement pull command

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24737]
### Parent Issue

#24732

### User Story

As a user, I'd like to execute a `files pull` command. The "pull" operation should allow me to download a file or folder from a remote server to my local machine. I should be able to specify the location of the remote file or folder, as well as the location on my local machine where it should be saved.

Example
`dotcli files pull --src=https://demo.dotcms.com/images  
 --dest=./`

### Acceptance Criteria

- [ ] The "pull" operation should allow the user to download a file or folder from a remote server to their local machine.
- [ ] The "pull" operation should prompt the user for the location of the remote file or folder, as well as the location on their local machine where it should be saved.
- [ ] The "pull" operation should display appropriate progress messages as the file or folder is downloaded.
- [ ] Support the `--force-overwrite` parameter
- [ ] Implement tests accordingly
- [ ]  Make sure zero length files can be pushed. Related to #24042

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/25347

**Comment by fabrizzio-dotCMS** [comment]
We're seeing a failure when pulling files with blanks in between the file name. Clearly, this is a back-end issue.  
But after a little debugging, I believe we need to encode just the asset name (if it has any blanks in it). If the full path gets encoded the URL parsing fails. Therefore only the pieces corresponding to the asset name should be encoded.

here's an example of a bad request

POST
{
   "assetPath":"//demo.dotcms.com/xyz/canto 1.txt",
   "language":"en_US",
   "live":false
}

the "assetPath" property describes the asset we want to pull 

a valid request would be :

POST
{
   "assetPath":"//demo.dotcms.com/xyz/canto%201.txt",
   "language":"en_US",
   "live":false
}

And once again this is a back-end issue but I'm reporting it here since I believe it is easier if we do the encoding here

**Comment by fabrizzio-dotCMS** [comment]
Command Help wise other file commands like `tree` and `ls` (that also take a path) show in their help that such param is named `path` but the `pull` command shows its name is `source` so we need to standardize it.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/25783

**Comment by fabrizzio-dotCMS** [comment]
From the CLI perspective in order to get a hold of a file whose name contains blank spaces we could do
`dot files pull "//default/text/La Odisea.txt"`
or 
`dot files pull //default/text/La+Odisea.txt`

a postman request must be escaped like this

{
  "assetPath":"//default/text/La+Odisea.txt",
  "language": "en-us",
  "live": false
}

which I think is fine 

just a small nitpick 
Let's say we want to download a file that contains blanks and we do 
`dot files pull //default/text/La Odisea.txt`
The error message we see is this

java.lang.IllegalArgumentException: Path [/Users/../Coding/core/tools/dotcms-cli/cli/Odisea.txt] must be a directory
	at com.dotcms.common.WorkspaceManagerImpl.workspace(WorkspaceManagerImpl.java:64)

That is because the blank space makes the cli think that "Odisea.txt" is the second param workspace. I
 revised the the code and the command `FilesPull` must use the WorkspaceMixin instead of a File
