### ISSUE TITLE
dotCMS CLI: Implement files ls command

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24733]
### Parent Issue

#24732

### User Story

As a user, I'd like to execute a `files ls` command. The "ls" operation should allow me to list the files and folders within a specified directory, similar to the "ls" command in a terminal.

Example:
`dotcli files ls https://demo.dotcms.com/images `

### Acceptance Criteria

- [ ] The "ls" operation should allow the user to list the files and folders within a specified directory.
- [ ] The "ls" operation should display the files and folders in a format that is easy to read and understand.
- [ ] Tests should be implemented accordingly

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/25128

**Comment by fabrizzio-dotCMS** [comment]
In order to test the CLI 
 built it from the cli maven module doing 
`../mvnw package -Dquarkus.package.type=uber-jar`
Then you can create an alias like` alias  dot='java -jar cli-1.0.0-SNAPSHOT-runner.jar' `
so you can use the jar calling it like this

`dot files ls  //demo.dotcms.com/ -ee`

Common problems found applying Glob filters in `tree` and `ls` sub-commands
for example, when specifying the filter options -ia (include asset) like` -ia="*.txt"`
The expected output should include all files with the extension `.txt` 

Setup an instance of dotCMS using current master with full starter
there's a file `robots.txt`  in the root folder of the default site `demo.dotcms.com`

So if we do 

`dot files ls  //demo.dotcms.com/ -ee`
 live
     └── 🌐 en-us
         └── demo.dotcms.com
             └── robots.txt
 working
     ├── 🌐 en-us
      │   └── demo.dotcms.com
      │       └── robots.txt
     └── 🌐 pt-br
         └── demo.dotcms.com
             └── robots.txt 

We should see it

Now if we do

`dot files ls  //demo.dotcms.com/ -ee   -ia='*.txt'`

we should still see it

but the output is 

 live
     └── 🌐 en-us
         └── demo.dotcms.com

Something similar happens when I do

dot files ls //demo.dotcms.com -ef='application'

which should exclude the folder application. But the output is 

live
     └── 🌐 en-us
         └── demo.dotcms.com
             ├── robots.txt
             ├── 📂 activities
             ├── 📂 application
             ├── 📂 blog
             ├── 📂 campaigns
             ├── 📂 contact-us
             ├── 📂 destinations
             ├── 📂 events
             ├── 📂 images
             ├── 📂 login
             ├── 📂 members
             ├── 📂 search
             ├── 📂 store
             └── 📂 xyz


We need to include in the help of the command options -ea, -ia, -ef, -if that the filters must be enclosed within quotes
