### ISSUE TITLE
Remove `lodash` from core-web

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24842]
### Task

`lodash` is problematic and has security issues, besides we're not using it a lot.

Let's remove `lodash`.

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- [x] Remove `lodash`
- [x] Replace the used methods with vanilla JavaScript when possible (when no possible, let's talk in the frontend channel)

**Comment by mbiuki** [comment]
1- patch it 
2- remove it

**Comment by mbiuki** [comment]
It's a front-end component.

**Comment by mbiuki** [comment]
FYI, new version is .21
https://github.com/lodash/lodash/issues/5851

**Comment by mbiuki** [comment]
@fmontes - please take it forward. Do we need to remove lodash, or should we upgrade to newer version?

**Comment by zJaaal** [comment]
# Note to QA 

Please be sure that all the portlets where the Template Builder is present, works as expected.

I removed the Old Template Builder code, because it had `lodash` code and therefore deleted all logic to render the old or the new template builder by checking the Feature Flag, so we need to test that Templates Portlet, Old & New Edit Mode work as expected with the Template Builder.

**Comment by KevinDavilaDotCMS** [comment]
# Passed IQA
tested in master 

https://github.com/user-attachments/assets/137a8c04-3067-40dd-b04a-f3f28a2370ff

**Comment by bryanboza** [comment]
Fixed, I made a smoke validation on containers and pages and everything is working normally!
