### ISSUE TITLE
Define startup and liveness probes

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24885]
### User Story

We have a few endpoints that we use as probes when running dotCMS in K8.  We have the 
- `/api/v1/appconfiguration` which we use but its response has gotten too large (>10k) to be used by kubernetes native `HTTPGet` probes, which are really only intended to look at the HTTP response code.
- `/api/v1/monitor-status` which is better but it runs checks on all the dotCMS subsystems, DB, ES indexes, Local and remote FileSystems which can cause too much unneeded load to be used constantly, and can falsely report dotCMS to be down, when it is a subsystem that is down/slow (e.g. db) and the dotCMS systems is still capable of serving information.

We need to, once and for all, define what our probes should be.  We will need 3 endpoints that map to the standard k8 probes:

1. `/api/v1/probes/startup `  <--  is the dotCMS up and ready to take requests
2. `/api/v1/probes/ready`  <--  pretty much the same thing as `startup`
3. `/api/v1/probes/alive`  <-- is the dotCMS up or does it need to be restarted?  This can be a lightweight probe that only checks if the cache is alive, for example.  Keep in mind that all requests that come to the `/api` endpoints have to go through and be validated by the CMSFilter, have rules applied etc... so this check should be good enough. 

### Acceptance Criteria

Have those endpoints return 200, else something north of 400

Need to document as well

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
### NOTE TO QA:
In a local development environment, it's very easy to simulate failures in order to have the new endpoints return a 503 status. All you need to do is bring Elasticsearch and/or your database down and do a `GET` on any of the endpoints in the ticket's description.

Additionally, make sure you test the configuration property that restricts access to the probes: `SYSTEM_STATUS_API_IP_ACL`. Just set a value that doesn't allow localhost to check the status. For reference, see: https://github.com/dotCMS/core/blob/2d0478290442ea30eb3f62858b43419747c35f55/dotCMS/src/main/java/com/dotcms/rest/api/v1/system/monitor/MonitorHelper.java#L52

**Comment by wezell** [comment]
Jose:

Just to be clear - taking the DB or ES down should not take this down -
unless the cache is empty.  This endpoint should really rely on a
loaded cache.  Is that correct?

**Comment by jcastro-dotcms** [comment]
@wezell yes, that's correct.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_74dd67e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0


   curl -k -i --location --request GET 'http://localhost:8082/api/v1/probes/ready' \
    --header 'Authorization: Basic YWRtaW5AZG90Y21zLmNvbTphZG1pbg==' \
