### ISSUE TITLE
Validate that the Page of the experiment was visited before the Page selected for the Reach Page Goal

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25104]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### Problem Statement

Currently when setting a Reach Page goal to a specified Page, it doesn't required having the Page of the Experiment to be visited before. 

It is needed to count the conversion when the Page of the Experiment was visited before the Reach(ed) Page. 

### Steps to Reproduce

* Add a new Experiment with a Reach Page Goal to a Page. 
* Start the Experiment and navigate straight to that Page, without first visiting the Experiment Page. 

It will be counted as a conversion, which should not. 

### Acceptance Criteria

* Count a conversion for the Reach Page Goal only if the Page of the Experiment was visited before in the same session.

### dotCMS Version

master / 23.06

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA: Page of the experiment needs to be visited before the page defined in the "Reach Page" goal.

**Comment by bryanboza** [comment]
We need some work here: 

I’m creating a folder called QA , when I navigate in the browser I’m going to localhost:8080/QA but internally we are changing this to lowercase, then we are not counting the conversions, if I do the same case but in the experiment I use qa  it is working.

Then the issue is because the experiment is case sensitive
