### ISSUE TITLE
CMS Admin should be able to view all the bundles regardless of the user who create it

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25127]
### Problem Statement

Right now Bundles are per user, so only the user who creates it can see them.

As CMS Admin Role, I should be able to view and manage all the bundles.

### Steps to Reproduce

1- Login as Chris Publisher
2- Create a bundle
3- Log out
4- Login as Admin
5- Go to the Bundles Portlet
6- No results found are shown. 

### Acceptance Criteria

Users with CMS Admin Role should be able to view/edit all the bundles.

### dotCMS Version

22.03 +

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/111645

**Comment by erickgonzalez** [comment]
another customer hitting this https://dotcms.zendesk.com/agent/tickets/113284

**Comment by bryanboza** [comment]
Fixed, now we are able to see the bundles from other users when you are logged as admin. 

But after play a little bit after this fix, we have some scenarios that can cause confusion to the user, the we open this new card in order to improve a little bit this functionality 

Card: https://github.com/dotCMS/core/issues/26224
