### ISSUE TITLE
Template Builder: Can't Save Templates

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25157]
### Problem Statement
Users of the dotCMS Template Builder are unable to save their templates.

### Steps to Reproduce
1. Log in to the dotCMS admin panel.
2. Navigate to the Template Builder.
3. Create a new template.
4. Add the same Container twice, save the Template.
5. Edit the Template and remove the first of the Container.
6. Attempt to save the template.

### Acceptance Criteria
1. Check the SQL query for the Template Builder to make sure it is correct.
2. If any issues are found, update the SQL query and test the template builder again.
3. If the query is valid, try to identify any other cause of the issue.

### External Links
<img width="2269" alt="image" src="https://github.com/dotCMS/core/assets/751424/112238d1-793b-4494-8c4a-3ae0389e25af">

### Assumptions & Initiation Needs
It is assumed that the user has the necessary permissions to access and modify the Template Builder.

### Quality Assurance Notes & Workarounds
Test the Template Builder after any changes to the SQL query to make sure that the issue has been resolved. If the issue persists, try to identify any other cause of the issue.

**Comment by wezell** [comment]
It is important to know why this broke and why no tests picked this up. We need a test here.

**Comment by jdotcms** [comment]
After a research I was able to reproduce and diagnostic about the issue:
1) The system template should be always true, I have made a fix for it on this **branch: issue-25157-template-builder** I recommend to continue using this branch for the rest of the fix.
2) The issue was introduced on Issue 23181 modifying designer template removes content from pages (#24145), basically when a layout UUID changes the updateMultiTrees method is fired on the MultiTreeAPIImpl; in the scenario the database is new, so there is not any reference to any pages, so the parameter collection pagesId is empty and the remplacement:

```
final String updateQuery = String.format("UPDATE multi_tree set relation_type = ? WHERE parent1 in (%s) AND parent2 = ? AND relation_type = ?",
                pagesId.stream().map(value -> "'" + value + "'").collect(Collectors.joining(",")));
```

Ends such as 

```
com.dotmarketing.exception.DotDataException: ERROR: syntax error at or near ")"
  Position: 60{
  "SQL": ["UPDATE multi_tree set relation_type = ? WHERE parent1 in () AND parent2 = ? AND relation_type = ?"],
  "maxRows": [-1],
  "offest": [0],
  "params": [
    "3",
    "SYSTEM_CONTAINER",
    "4"
  ]
}
```

Not sure what was trying to achieve but should take this case in consideration and provides a fallback for this scenario

Assigning to Falcon to continue with the research and fix

**Comment by freddyucv** [comment]
PR: https://github.com/dotCMS/core/pull/25186

**Comment by bryanboza** [comment]
Tested with the last image of release-23.06 and we still getting the same error

**Comment by freddyucv** [comment]
> Tested with the last image of release-23.06 and we still getting the same error https://gist.github.com/bryanboza/9f4001240a2cc18b859180c34b77c49c
> 
> We need some work here

It is happening in 23.05 as well so I think this is another issue

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_92c6837e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **23.06_f30e8d2c_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
