### ISSUE TITLE
PP - Integrity Checker, fixing conflicts is not populating the contentlet_as_json field

### ISSUE THREAD

**Issue by AndreyDotcms** [dotCMS/core#25229]
### Problem Statement

The contentlet_as_json fields are being set to null when fixing conflicts with the Integrity Checker, which causes the title is being shown as empty.

### Steps to Reproduce

1. Start two dotCMS instances, and set the PP.
2. Publish a picture on the root folder of the sender instance and a different picture on the root folder of the receiver instance (Both pictures must have the same name).
3. Run the Integrity Checker.
4. It should generate a conflict.
5. Use the following query to verify that the contentlet_as_json is set: `select contentlet_as_json from contentlet where identifier = 'IDENTIFIER'`
6. Fix the conflict with IC.
7. Clean cache.
8. Run again the query to verify that the contentlet_as_json is set (actually the value is being set to null): `select contentlet_as_json from contentlet where identifier = 'IDENTIFIER'`

### Acceptance Criteria

The acontentlet_as_json fields should not be set to NULL when the conflict is fixed.

### dotCMS Version

23.01 +

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

**Comment by swicken-dotcms** [comment]
Related git issue: https://dotcms.zendesk.com/agent/tickets/111993

**Comment by fabrizzio-dotCMS** [comment]
Note for QA
The proper way to generate a conflict between a sender and a receiver bypassing the deterministic identifiers would be as follows:

1. Create a folder in the same location in both nodes sender and receiver. 
3. Upload the same file asset under that folder in both instances sender and receiver
4. Now on the receiver move the file we just uploaded and place it in the site root folder.
5. Upload once again the same file asset under the folder we originally. Just like we did before.
6. On the receiver end. The FileAsset must exist in the root folder and also under the folder we created.

e.g.
Let's say we create a folder named foo/ like `demo.dotcms.com/foo/`
In both instances now we upload a file underneath that folder so that it looks like this:
`demo.dotcms.com/foo/test.jpg`
At this point this file must have the exact same identifier in both ends sender and receiver. 
Now in order to create the conflict we move the file on the receiver. placing it under the site root folder so it'll look like this:
`demo.dotcms.com/test.jpg`
and we reupload the exact same file again under the folder `foo` so we have 2 files named test.jpg but in different locations on the receiver end. 
The second file we just uploaded under the folder /foo must have a different identifier this time. There it is our conflict.

**Comment by nollymar** [comment]
**Internal QA**: Passed

I was able to generate a conflict using a local environment (sender) and demo site (receiver). Subsequently, I fixed the conflict successfully.



![Image](https://github.com/dotCMS/core/assets/8741395/35a2be10-3fe8-4758-94b9-24d7055a66f4)
