### ISSUE TITLE
Design System: Implement `button` component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25356]
### Parent Issue

#25355 

### User Story

As a stakeholder, I want you to implement the button component new design for primeng and dojo widgets.

### Acceptance Criteria

1. Match the design provided with all the types and severities in primeng
2. Add Storybook stories for the buttons with the same structure of primeng
3. Implement the buttons in dojo
4. User the CSS variables accordingly

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

[Figma](https://www.figma.com/file/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?type=design&node-id=42%3A689&mode=dev)

### Assumptions & Initiation Needs

[_No response_](https://github.com/dotCMS/core/assets/751424/52512905-2ff6-46c3-8244-cb472ab1a83e)

**Comment by bryanboza** [comment]
Fixed, after play a little bit around the application, now all the buttons have the new implemented style. 

Now we have some differences between the angular icons and JSP but this will be fixed in a separate card. 

Also the "Sign in" button in the logout window looks different. But this case have a new card too.
