### ISSUE TITLE
2 UT has the same date

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25502]
### Task

Currently, we have 2 UT that share the same date:

[https://github.com/dotCMS/core/blob/1298bdc6aaebc3830a62dbde3fe3244613601116/dotCM[…]/dotmarketing/startup/runonce/Task220825CreateVariantField.java](https://github.com/dotCMS/core/blob/1298bdc6aaebc3830a62dbde3fe3244613601116/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220825CreateVariantField.java)
[https://github.com/dotCMS/core/blob/1298bdc6aaebc3830a62dbde3fe3244613601116/dotCM[…]ng/startup/runonce/Task220825MakeSomeSystemFieldsRemovable.java](https://github.com/dotCMS/core/blob/1298bdc6aaebc3830a62dbde3fe3244613601116/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220825MakeSomeSystemFieldsRemovable.java)

By looking at our Impl and a couple of customer's DBs, the second one `Task220825MakeSomeSystemFieldsRemovable` is not been run since when the first one is ran, we update the db_version.

I don’t think is so tragic, since what the UT does is only allow to remove some fields, but we should update the name of this UT so it runs

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 4 - Low

### Acceptance Criteria

After discussing with @jcastro-dotcms let's remove this UT `Task220825MakeSomeSystemFieldsRemovable`. Since there is a new UT which do the same work (and better)

**Comment by jcastro-dotcms** [comment]
@erickgonzalez just so you know, that old https://github.com/dotCMS/core/blob/1298bdc6aaebc3830a62dbde3fe3244613601116/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220825MakeSomeSystemFieldsRemovable.java didn't take into account other base types.

So, in order to solve that situation, we added a new one: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task230110MakeSomeSystemFieldsRemovableByBaseType.java . If the `Task220825CreateVariantField` is running fine, I believe we're good here.
