### ISSUE TITLE
Loading the /api/v1/appconfiguration every mouse click

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25552]
### Problem Statement

We seem to be loading the `/api/v1/appconfiguration` endpoint with every mouse click on our main navigation.  Take a look at the screencap.  I tried it with "Disable Cache" checked and unchecked and saw the same behavior.

### Steps to Reproduce

Open your Network tab and browse the backend, you will see repeated calls to `/api/v1/appconfiguration`

https://github.com/dotCMS/core/assets/934364/237c658e-a665-424a-9bde-8914e052a66c

### Acceptance Criteria

There should be 1 call to the `/api/v1/appconfiguration` and the result should be stored in our app for future use and never requested again.

### dotCMS Version

23.07

### Proposed Objective

Application Performance

### Proposed Priority

Please Select

**Comment by fmontes** [comment]
Is around here: https://github.com/dotCMS/core/blob/master/core-web/libs/data-access/src/lib/dot-license/dot-license.service.ts#L93

**Comment by rjvelazco** [comment]
### Failed Internal QA 

**Docker image**: [`dotcms/dotcms:master_524e70e`]

I've encountered a bug where the initial load of dotCMS triggers two requests to `/api/v1/appconfiguration` instead of just one. We can take a look and address this issue in this ticket.

**Steps to reproduce:**

1. Open Dev tools
2. Go to network tab
3. Disable cache.
4. Do a hard refresh on `dotCMS`
5. See the error.


https://github.com/dotCMS/core/assets/72418962/313dca05-1308-47ab-aa48-5cc4da75ba9e

**Comment by zJaaal** [comment]
This is expected, due to a race condition between the initial load of the application after the reload and the License Service triggered by the router itself.

We have talked about creating a global state for the app configuration to have a single source of truth and prevent this kind of race condition or double requests. In the mean time we can left it as it is and consider this problem for a future implementation of a global state.

**Comment by rjvelazco** [comment]
We have been discussing the concept of a global state for some time now, and it could be beneficial in these situations.

**Comment by bryanboza** [comment]
Fixed, tested according the previous comment and this is working as expected, tested on master // Docker // FF
