### ISSUE TITLE
[UI] Verify the ConfirmPopup of Promote Variant (Experiment Reports)

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25623]
### Parent Issue
#24343

### User Story
Improve promote variant dialog to follow standards 

### Acceptance Criteria
- The icon on the left should be aligned with the top of the text, I see they have it aligned in the middle
- the Confirm Popup should be 0.5 Rems from the button, they can see it how I placed it on Figma
https://www.figma.com/file/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?type=design&node-id=2687-52157&mode=design
- Make Promote variant button secondary 

### dotCMS Version
master

### Proposed Objective
_to_define_

### Proposed Priority
_to_define_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
_to_define_

### Assumptions & Initiation Needs
_to_define_

### Quality Assurance Notes & Workarounds
_to_define_

### Sub-Tasks & Estimates

**Comment by hmoreras** [comment]
### Changes
* Improve margins / styles of the `ConfirmationPopUp`
* Promote btn correct color 

#### Before 

<img width="353" alt="image" src="https://github.com/dotCMS/core/assets/31667212/c676213b-abb8-4b24-903b-dc7db036632a">

<img width="432" alt="image" src="https://github.com/dotCMS/core/assets/31667212/1997288c-b003-4829-9ace-9d26a4a7fbd0">

<img width="442" alt="image" src="https://github.com/dotCMS/core/assets/31667212/65e894a0-7861-46c7-90fd-c4b6da3b43f1">



#### After 

<img width="358" alt="image" src="https://github.com/dotCMS/core/assets/31667212/86ee5e05-0ff5-4c90-ad0a-f238a0f989ad">

<img width="423" alt="image" src="https://github.com/dotCMS/core/assets/31667212/cb95d865-7b03-415b-8d21-60c638ecc714">

<img width="429" alt="image" src="https://github.com/dotCMS/core/assets/31667212/f7c7abf5-d48a-49f9-a5a6-11cc64e16b71">


QA Note: The margins regarding the button that calls the popup, will be not respected, we need to update the Figma file, since the behavior comes directly from the primeng component, set the element in position absolute in the document and do not have a configuration options to add some sort of offset.

**Comment by dsilvam** [comment]
Passed Internal QA: correct color for button and dialog properly placed.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
