### ISSUE TITLE
UI: Workflow action takeover requires alignment adjustment

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25630]
### Parent Issue

[Pages]

### Problem Statement

The workflow action takeover appears to be misaligned.

### Steps to Reproduce

1. Go to https://localhost:8443/dotAdmin/#/pages
2. Observe that the alignment of the takeover elements is off

### Acceptance Criteria

The workflow action takeover should be aligned correctly.

### dotCMS Version

23.07

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

![Screenshot 2023-07-26 at 9 58 26 AM](https://github.com/dotCMS/core/assets/129882031/9cd2f90b-1f12-498d-ab4a-ccdb4247a181)

**Comment by zJaaal** [comment]
This issue is being solved by this [PR](https://github.com/dotCMS/core/pull/25404) that question mark icon is a button that needed a refactor. 

#### Screenshot of the branch `issue-25356-design-system-implement-button-component`

![Screenshot 2023-07-27 at 12 02 17 PM](https://github.com/dotCMS/core/assets/63567962/ade22071-4db5-4806-9b1a-f8f94adefcbf)

**Comment by rjvelazco** [comment]
### Passed Internal QA

**Docker Image**: [`dotcms/dotcms:master_524e70e`]

<img width="1630" alt="Screenshot 2023-08-04 at 12 13 26 PM" src="https://github.com/dotCMS/core/assets/72418962/c80343d0-fb8a-420c-a109-145eb665a9cf">

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_524e70e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
