### ISSUE TITLE
Favorite Pages: Unusual loading or search icon appears in the search field of 'Workflow Action'

### ISSUE THREAD

**Issue by josemejias11** [dotCMS/core#25632]
### Parent Issue

[Pages]

### Problem Statement

An unusual loading or search icon appears in the search field of the 'Workflow Action'.

### Steps to Reproduce

1. Go to https://localhost:8443/dotAdmin/#/pages
2. Observe the search field; a peculiar loading or search icon shows up.

### Acceptance Criteria

Search field should display a standard search or loading icon for user recognition and ease of use.

### dotCMS Version

23.07

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Quality Assurance Notes & Workarounds

https://github.com/dotCMS/core/assets/129882031/6860c264-b0d1-4b43-8842-35dee6c04c9a

**Comment by zJaaal** [comment]
Fixed in this [PR](https://github.com/dotCMS/core/pull/25404). The icon appears and disappears that fast because the request is really fast in local environments. I made the fix to move the loader to the left so it doesn't overlaps with the helper icon and tested it with network throttling and you can see that the icon displays as expected.

https://github.com/dotCMS/core/assets/63567962/6dc3d3e1-dd1b-42c7-a22a-d105bf2d5f91

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker image: `dotcms:master_524e70e_SNAPSHOT`

As explained by @zJaaal , what we were seeing on screen was the loading GIF quickly appearing and disappearing when typing in values in the text field. Such a GIF was now moved to the left in order to correctly display both the loading GIF and the help button.

@josemejias11 please watch the video that Jalinson [attached to his comment](https://github.com/dotCMS/core/issues/25632#issuecomment-1656328097) so you can simulate a slow 3G connection. That way you can see how the loading GIF shows up.

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_a07a969_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
