### ISSUE TITLE
Block Editor: Copy - Paste Word Doc creates an image instead of a paragraph in Chrome and Mac

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#25726]
### Problem Statement

When pasting the text shows up as an image block and is added as a file in media.

This only happens for Chrome and Mac.

### Steps to Reproduce

1- Ask Support for the Word Doc
2- Open the Word Doc using Word for Mac
3- Copy the Text
4- Create a Content Type with a Block Editor Field.
5- Paste the text in the Block Editor Field.
6- It gets pasted as an Image.

### Acceptance Criteria

The text should have been added as text in a paragraph block.

### dotCMS Version

23.01 +

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112725

**Comment by erickgonzalez** [comment]
Only for 23.01 LTS

**Comment by rjvelazco** [comment]
Word content copy is now pasted as content instead of an image in Chromium-based browsers. This issue has been addressed in this PR: https://github.com/dotCMS/core/pull/25727.

However, it seems that certain formats, like lists, are not being well adapted. Tiptap has several open issues regarding this matter:

- https://github.com/ueberdosis/tiptap/issues/1526
- https://github.com/ueberdosis/tiptap/issues/3756

**Comment by fmontes** [comment]
Tested in LTS, needs to confirm in master

**Comment by josemejias11** [comment]
**Approved QA** - Tested on **master_792865e_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0
