### ISSUE TITLE
Setup Announcements Feed Caching Mechanism

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25736]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Assumptions & Initiation Needs

I think we wanted to make sure we weren't doing a ton of external calls, so maybe we phone home and cache the Announcements once a day?

We want to to make sure the caching we use will be smart enough to update or delete feed items that we need to update. Like if we put out a feed item with a typo, and it gets consumed and cached, and then we pull in an update... let’s make sure the old version gets updated, or deleted.

@nollymar or @spbolton - Are we sure we don't just want to load this in real time? Thinking more about this... is the cache necessary?

**Comment by spbolton** [comment]
@damen-dotcms Yes the cache would be necessary.  It is not a good pattern to ignore caching when making requests from the server inline with the initial request as it may be requested to every page to force a network call to another server.   If you have 10 concurrent requests it would trigger 10 concurrent requests from the http client out to get the data and a delay for each of them to respond as well as putting more traffic on the destination and client request threads on the server,   You can destroy server performance this way the more concurrent requests you get especially as this will show on most pages, browser caching can help but for something like this where it does not need to be live updated to the ms it is better for the server to grab in a single thread as a background task and the server just returns the cached value without delaying a request,  even better if it is able to be cached in memory.

**Comment by nollymar** [comment]
Initially, we'll have an endpoint that will provide a JSON output with the announcements (#25734 ). The endpoint will use a caching strategy (cache flushing can happen every 24hrs? ).  We can use a cron job that executes every so often (maybe every 2hrs?) to check if there are new announcements, this way we can cover new updates (because of a typo, last minute news, etc).

**Comment by fabrizzio-dotCMS** [comment]
It was agreed that the cache would be set to expire in 3 hours

**Comment by manuelrojas** [comment]
**Internal QA: Approved**, To validate the system, I generated a new announcement, observed its inclusion in the API response after a one-hour period.

**Comment by bryanboza** [comment]
We are able to generate announcements with future dates, this sice we are not associating the announcement date as a publish date in the content type
![Image](https://github.com/dotCMS/core/assets/2641437/6303d476-8d34-4ac8-b99a-81ae4d088df2)

**Comment by fabrizzio-dotCMS** [comment]
The ContentType was fixed in the authoring environment.  I'll get the Postman examples fixed myself

**Comment by bryanboza** [comment]
In the postman test we are just validating the response code is 200 as a test, we need to add some other validations here, since this endpoint always are returning 200 code. Even if an error happens, then this is not a valid case since never will fail in case of error 

![Image](https://github.com/dotCMS/core/assets/2641437/c9525a4e-6b53-489c-a9fe-4d04380a8e0e)



![Image](https://github.com/dotCMS/core/assets/2641437/125e5d88-044a-4ee5-898e-0a33011b7ac0)

**Comment by fabrizzio-dotCMS** [comment]
let's focus on the rocks. shall we?

**Comment by manuelrojas** [comment]
**Failed Internal QA:**

![image](https://github.com/dotCMS/core/assets/3438705/fbe78a0e-6797-4533-8bc7-b1caf0b2df20)

Using a   "contentType": "fake content type" all the tests are passing.

@fabrizzio-dotCMS ☝️

**Comment by manuelrojas** [comment]
Passed Internal QA



![Image](https://github.com/dotCMS/core/assets/3438705/7224879d-7947-40d7-b5f2-af56147829ad)

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
