### ISSUE TITLE
Updates to Site Selector Menu

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25740]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

These are just intended to be visual updates to the existing UI to bring them into alignment with the new Announcement Menu designs.

Note, we will only attempt to do this work if it won't impact getting the "core" issues from this epic included into the next LTS. 

- Some users may have hundreds of entries here. This menu will max out at the same height that the Announcements Menu maxes out, and have a scroll bar after that.
- 
This should not be behind the feature flag, any updates to this menu can go out for all users.

- Search is just a "Filter" for the list that starts to filter as soon as you type more than 1 letter.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?type=design&node-id=264-50573&mode=design&t=SoL7QkLHLl5dFBUC-0

**Comment by nollymar** [comment]
**Internal QA:** Needs work 

The scroll is not being displayed. I can't see all my sites



![Image](https://github.com/dotCMS/core/assets/8741395/ed03b1f6-ede8-45dc-a341-6371e0ab32ee)

**Comment by jgambarios** [comment]
![image](https://github.com/dotCMS/core/assets/923947/686b5486-d88b-439b-b2cb-6ec1807dc7da)

Looking good, I see the scroll now.

**Comment by bryanboza** [comment]
I have some questions here: 

- We are not listing all the sites, we are just listing the first 15 sites, then we never have scroll 
- The icon for the default sire is a check, which is confused because the selected site is just the name in bold... Should we use another icon for default site ? 
- In case you select a site that is not in the first 15 sites, we are not showing the selected site in the drop down, we need to include the selected as the first in the list?

**Comment by manuelrojas** [comment]
@bryanboza I will work with Melissa about this questions!

**Comment by wezell** [comment]
Because we only show 15 hosts, take this case

You have these hosts : 
```
testing1.host.dotcms.com
testing2.host.dotcms.com
testing3.host.dotcms.com
testing4.host.dotcms.com
testing5.host.dotcms.com
testing6.host.dotcms.com
testing7.host.dotcms.com
testing8.host.dotcms.com
testing9.host.dotcms.com
testing11.host.dotcms.com
testing12.host.dotcms.com
testing13.host.dotcms.com
testing14.host.dotcms.com
testing15.host.dotcms.com
testing16.host.dotcms.com
testing17.host.dotcms.com
testing20.host.dotcms.com
host.dotcms.com
```
And search for: `host.dotcms.com`
It is possible to NOT get the `host.dotcms.com` back in your 15 results.

Sorting by the shortest means that if you search for `host.dotcms.com` it will come back as the top result.


We need to maintain wildcarding on both sides, e.g. `like '%host.dotcms.com%'`

dupe issue #26615

**Comment by nollymar** [comment]
@bryanboza here the answers to[ your questions](https://github.com/dotCMS/core/issues/25740#issuecomment-1876099741) 

The site selector doesn't support pagination. It was decided on [this card](https://github.com/dotCMS/core/issues/22734#issuecomment-1216079537)
After a discussion with @wezell and @damen-dotcms, we agreed:
- The site selector won't highlight the default site, only the selected site (using the check icon)
- In case the selected site is not part of the current 15 sites listed, we won't show it

Those changes are being implemented here

Besides, @wezell asked to change the logic we use to filter results in the dropdown ([see the comment above](https://github.com/dotCMS/core/issues/25740#issuecomment-1885664041)) . As this change is out of the scope of the original requirements, I'll file a new card for it, we will implement it asap.

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b5a86b8**, Docker, macOS 13.0, FF v121.0.1
<img width="1280" alt="Screenshot 2024-01-18 at 12 04 46 PM" src="https://github.com/dotCMS/core/assets/129882031/59b33260-c7e9-4188-a75b-ffebd3b02827">
