### ISSUE TITLE
Updates to Sign In As Menu

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25743]
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

These are just intended to be visual updates to the existing UI to bring them into alignment with the new Announcement Menu designs.

Note, we will only attempt to do this work if it won't impact getting the "core" issues from this epic included into the next LTS. 

This should not be behind the feature flag, any updates to this menu can go out for all users.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/3f17xtGfHmJx3RuC9YhQox/What%E2%80%99s-New-Menu?type=design&node-id=301-9212&mode=design&t=SoL7QkLHLl5dFBUC-0

**Comment by manuelrojas** [comment]
https://github.com/dotCMS/core/pull/26580

**Comment by nollymar** [comment]
**Internal QA:** Passed

After applying the design changes, it is displaying as expected.

**Before**



![Image](https://github.com/dotCMS/core/assets/8741395/5396cf24-7b9b-481c-9b61-94907b159d8b)


**After**



![Image](https://github.com/dotCMS/core/assets/8741395/b93c732d-2a53-49da-afad-c2ecaa6edad8)

**Comment by bryanboza** [comment]
We need some UX work here: 

We are adding a distinction for the default site with a check mark, which is confusing because from sites portlet to set a default we are using another icon. 
![Image](https://github.com/dotCMS/core/assets/2641437/0f38d5cb-17d3-46d9-9374-1c40ff2688cc)

![Image](https://github.com/dotCMS/core/assets/2641437/560be2c9-ede8-447c-b16c-48575b0ad4eb)


Also, when you have multiple sites and you select some one specific, when you open again the site selector we are displaying the selected in <bold> letter. For me the selected should be the one with the checkmark and in bold, and we need to use the default icon for distinction of the default one.

**Comment by nollymar** [comment]
@bryanboza I think this is out of the scope of the card. We were asked to change only the User Menu. The issue you're reporting is for the sites context menu

**Comment by fmontes** [comment]
@manuelrojas @nollymar when you select the option in the dropdown there is like a weird jump... or at least I am seeing that in master.

**Comment by bryanboza** [comment]
This problem was moved to a new card #27074

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF 

Reported problem was moved to a new card
