### ISSUE TITLE
Experiments API should return number of sessions

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#25779]
Currently, the API returns the number of conversions, but not the number of sessions.

We need to update the API to also return the number of sessions and the conversion rate by day.  

This is required for the completion of https://github.com/dotCMS/core/issues/25638.

Changed to:
- Retrieve conversionRate not session (we send the number calculated to no do this in Frontend)

**Comment by oidacra** [comment]
IQA Passed:
- `conversionRate` now comes from the API
<img width="588" alt="Screenshot 2023-09-11 at 1 10 15 PM" src="https://github.com/dotCMS/core/assets/1909643/2c99e517-9903-49cc-993e-97c5427ad4b8">

**Comment by bryanboza** [comment]
We need a  test here: https://github.com/dotCMS/core/pull/25844#discussion_r1327736649

**Comment by freddyucv** [comment]
> We need a test here: [#25844 (comment)](https://github.com/dotCMS/core/pull/25844#discussion_r1327736649)It is not possible to create any Postman test here because the Jitsu Server and all the  Infrastructure stuff is not running on the PostmanTest Environment.

but we have IT for it 


https://github.com/dotCMS/core/blob/ed071e0ab5c9d1d966e33d7753d84c72c381ef72/dotCMS/src/integration-test/java/com/dotcms/experiments/business/ExperimentAPIImpIntegrationTest.java#L8087-L8098

The IT is possible because we are mocking the Jitsu Server with this Util 

https://github.com/dotCMS/core/blob/14f9a850bb545d5b8e0d709523cb8e10be4e8a81/dotCMS/src/main/java/com/dotcms/http/server/mock/MockHttpServer.java#L26

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
