### ISSUE TITLE
Edit Contentlet: Create dropzone component

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#25782]
### Parent Issue

#25445

### Task

We need to develop a component that enables Drag & Drop functionality for file uploads. We can take a look at this `PrimeNg` component to see if we can use it: https://primeng.org/fileupload

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- Should allow Drag&Drop for files.
- Should allow browser files and select one.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://github.com/dotCMS/core/issues/24362

**Comment by fmontes** [comment]
The idea behind this component is that we should be able to put it inside areas or zones of any page and allow the user to drop files in it... once the file is dropped we need to emit that file to the parent so it can take care of whatever.

I think we need to build this on top of a `<input type="file">` because then we can use all the HTML native attributes and events... maybe this is even a directive to just modify that file? Not sure... but it worth exploring.
