### ISSUE TITLE
Verify that IC keeps working with variants 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#25798]
### Parent Issue

https://github.com/dotCMS/core/issues/22760

### User Story

As a User of the Push Publish feature, I want to be able to use the Integrity Checker functionality as normal now that Experiments feature was developed. 

### Acceptance Criteria

Integrity checker working as expected. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Pass IQA: Work as Expected, The Persona Drop Down is not disabled anymore when you go inside the Variant

**Comment by freddyucv** [comment]
Pass Internal QA

Cases Tested in IQA:

- Case 1:
Create a Page and Experiment on the Sender
Push it
Run IC, No Conflicts 

- Case 2:
Create a Page and Experiment on the Sender
Create a Page with the same name on the Receiver, but on diferent path.
Move the Page on the Receiver to the same path where it exits on the sender
Run the IC, Conflicts detected with the Page.
No matter if the conflicts is fixed with Local or Remote the Experiment on the sender is not lost
 
- Case 3
Create Page/Experiment/Variant on the Sender
Add a Image on the Variant on the Sender
Create a Image on the root directory with the same name from the sender on the receiver
Run the IC, no conflicts
Even when you push everything go right, I mean any of the images (sender and receiver) got changes

**Comment by freddyucv** [comment]
Pass Internal QA

Cases Tested in IQA:

- Case 1:
Create a Page and Experiment on the Sender
Push it
Run IC, No Conflicts

- Case 2:
Create a Page and Experiment on the Sender
Create a Page with the same name on the Receiver, but on diferent path.
Move the Page on the Receiver to the same path where it exits on the sender
Run the IC, Conflicts detected with the Page.
No matter if the conflicts is fixed with Local or Remote the Experiment on the sender is not lost

- Case 3
Create Page/Experiment/Variant on the Sender
Add a Image on the Variant on the Sender
Create a Image on the root directory with the same name from the sender on the receiver
Run the IC, no conflicts
Even when you push everything go right, I mean any of the images (sender and receiver) got changes

**Comment by bryanboza** [comment]
Fixed, tested the 3 scenarios mentioned above and now it is working as expected.
