### ISSUE TITLE
"New" Elements are Missing Tooltips

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25816]
[![Screenshot_2023-08-17_19-25-36.png](https://mrkr.io/s/64de7430a209e725ae32cc71/2)](https://mrkr.io/s/64de7430a209e725ae32cc71/0)

<img width="401" alt="image" src="https://github.com/dotCMS/core/assets/114953617/e33ab143-04f7-44be-93e3-d055a5b05eb2">

### Parent Issue

https://github.com/dotCMS/core/issues/25811

### Problem Statement

We're missing tooltips on the "new" elements.

I think those got left out of the original requirements, sorry!

Edit - Edit Page Content

Preview - Preview Page

Lock - Lock Page

What's Changed - Compare Changes

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fthe-ultimate-family-ski-trip-packing-list%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fblog%2Fpost%2Fthe-ultimate-family-ski-trip-packing-list%3Fhost_id%3D48190c8c-42c4-46af-8d1a-0cd5db894797&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64de7430a209e725ae32cc74_8b986490744be5fb?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 116.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3008 x 1692</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>3008 x 1304</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by nollymar** [comment]
Internal QA: Needs work

Almost all the tooltips are working perfectly. Just a small detail: the "What's Changed" should be just "Compare Changes" instead of "What's Changed - Compare Changes"


![Image](https://github.com/dotCMS/core/assets/8741395/f9784f5c-9b60-4897-8509-1b131d1a96dc)

The others work ok!
![Image](https://github.com/dotCMS/core/assets/8741395/29ed9e67-7112-4512-9ff5-67770c9ecd31)
![Image](https://github.com/dotCMS/core/assets/8741395/82c89f81-8217-4c14-b807-092934a87b43)
![Image](https://github.com/dotCMS/core/assets/8741395/8afd9f57-c113-4a74-bc1b-0fb6300fe567)

**Comment by nollymar** [comment]
**Internal QA:** passed



![Image](https://github.com/dotCMS/core/assets/8741395/15d90cca-afb5-4ac7-b4b2-64d4e67d8c44)

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_7713bff_SNAPSHOT**, Docker, macOS 13.0, FF v113.0
