### ISSUE TITLE
Move to mvn Testing

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25890]
### Task

We need to move to a place where all our tests are green.

Now that we have the Maven Unit and IT tests done, we need to do the following

- \[x\] Remove the gradle based Unit and IT tests
- \[x\] Move the postman tests to Maven
- \[x\] Add the postman test reports to the maven reporter

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

*No response*

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

*No response*

### Assumptions & Initiation Needs

*No response*

### Quality Assurance Notes & Workarounds

*No response*

### Sub-Tasks & Estimates

*No response*

**Comment by spbolton** [comment]
@victoralfaro-dotcms We need to get on the same page with the publishing of the docker generated from maven.   Maven is using the docker-maven-plugin to build and run the docker image and it is also able to tag and push using buildx with our multi build params.  Theoretically we can just pass maven the push secret and repo and it can do the whole build and push in the first step.  The build is actually very quick if the layers are cached.   We can also skip the docker build and push in the Initial JDK 11 Build step and have a separate docker build and push step that can use the docker repo exposed by the initial build step in the same way the integration and unit tests use.   This would be slower to get to the point of having the image created just because of the overhead of initializing and pulling the repo from the previous step but will run in parallel with the unit and integration tests. 

The one thing I a working out how we should solve is how we make sure that layers are cached between builds so that it does not have to pull the base layers every time.   Essentially I need to see if we can get docker-maven-plugin make use of the cache-to and cache-from parameters.    https://docs.docker.com/build/cache/backends/gha/.  If we can then everything else for setting up docker would be the same, we would just be replacing the docker-build-push action with a maven command.  

With the newman tests you are on the right track with the exec plugin as one option as we do need the binary to run.  I think there may be a more generic solution though to use the the frontend-maven-plugin to install newman with npm and work just like core-web although we don't need to actually build any node code.  What I would want if doing this though is for the postman test module to be able to make use of the same node cache as core-web.  The tests can be run in a separate module that is dependent on dotcms-core and by default uses the locally built image.   If we do this as a module we then just make a new step in the github action workflow that runs after the step that builds the image build.

We have options also for passing around the docker built image during the workflow itself.   The image can be saved as a tar artifact or we publish, using the commit id and build id as tag
