### ISSUE TITLE
Implement "sync" feature for languages

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26002]

**Comment by jgambarios** [comment]
### Note for QA:
**What to test:** The functionality to call the language push command for a folder inside a valid CLI workspace or for a specific language file is now available.

#### 1. If "push" is called for a specific file, for example:
```console
lang push <workspace-path>/languages/es-es.json
```
The CLI will determine whether it's a new language that should be created on the server, if it needs updating, or if no changes are detected and nothing will be done.

To determine the specific operation "push" will execute, you can run the command with the `--dry-run` flag.

```Console
lang push <workspace-path>/languages/es-es.json --dry-run
```

#### 2. If "push" is called for a folder:
```Console
lang push <workspace-path>
```
The specified folder must be at the root or inside a valid CLI workspace, and it will push the files located inside the <workspace-path>/languages/ folder.

The CLI will decide for each language file whether it's a new language that should be created on the server, if it needs updating, or if no changes are detected and nothing will be done.

To determine the specific operation "push" will execute, you can run the command with the `--dry-run` flag.

```Console
lang push <workspace-path> --dry-run
```

Additionally, you can pass the `--removeLanguages` flag, and the CLI will compare the local language files against the server languages to decide if any languages need to be deleted on the server. In other words, if a language exists on the server but not in the list of language files, the CLI will delete that language.

```Console
lang push <workspace-path> --removeLanguages --dry-run
```

---
I highly recommend using the `--dry-run` option as it is very useful for understanding the actions the CLI will attempt without making changes to the server.

**Comment by bryanboza** [comment]
We need work here: 

We need to exclude the property `isoCode` as part of the json, this because when you create the lang from the admin console, we don't need to define this value, this is auto-calculated based in the provided parameter. Now when you push we need to provide this parameter and all the other ones are calculated based on the iso code. 

**Example:** 
- If you send some language from some specific country, but in the isoCode you just send the language, we are ignoring the properties and we set the new language just calculating the parameters of the iso code. 

- Also, once that you set the parameters and try to push, we are losing the parameter if you don't send correctly the `isoCode`

Here the language portlet 
![Image](https://github.com/dotCMS/core/assets/2641437/67d0e643-7daa-4055-973c-9dde6844ec80)

Here the lang.json
```
{
  "dotCMSObjectType" : "Language",
  "id" : 4963328,
  "languageCode" : "es",
  "countryCode" : "",
  "language" : "Spanish",
  "country" : "",
  "defaultLanguage" : false,
  "isoCode" : "es"
}
```

**Comment by nollymar** [comment]
we need to discuss it with @wezell , as the `isoCode` is the only property required to create a language. The current behavior is part of the initial requirements

**Comment by nollymar** [comment]
After further discussion, we agreed that @bryanboza 's request will be implemented on [this card](https://github.com/dotCMS/core/issues/27448)

**Comment by bryanboza** [comment]
We can close this card, the new request will be handled in a new card
