### ISSUE TITLE
[UI] Persona Drop Down is Disabled inside Variant

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#26024]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### Problem Statement

Wen the Default Persona i not the current Persona then the Persona Drop Down is disabled inside a Variant  

### Steps to Reproduce

1. Start dotCMS witrh the full Starter
2. Create a Page
3. Create an Experiment
4. Create a Variant
5. Go to the Edit Page outside Experiment and select any no Default Persona.
6. Go to Edit the Variant, the Persona drop down is going to be disabled

The same happen if ant the last step refresh the page instead of Go to Edita Variant.

### Acceptance Criteria

The drop down must be enabled

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by freddyucv** [comment]
Pass IQA: Work as Expected, The Persona Drop Down is not disabled anymore when you go inside the Variant

**Comment by freddyucv** [comment]
Pass IQA: Work as Expected, The Persona Drop Down is not disabled anymore when you go inside the Variant

**Comment by bryanboza** [comment]
We need some work here, problem description in the follow video: 

https://github.com/dotCMS/core/assets/2641437/7006dbea-5f2e-45b0-82b0-865af772f9ee

**Comment by john-thomas-dotcms** [comment]
@bryanboza this behavior isn't a problem.  In fact, it's the way the page editor works everywhere other than Experiments.

For example, if you select the Persona and make changes, and then view Layout or Rules, then go back to Content, the previously selected Persona is still selected.  So, keeping it the same when you go into Experiments is consistent with how it works everywhere else.

It's also actually probably the best behavior for how users will actually use Experiments.  If someone has an Experiment set up (but not yet running, so it can still be edited), and they come into the main page and change the main page for a specific Persona, there's a very good chance that they'll want to change the variants *for that same Persona*.

So, not only is this not a problem, it's actually the desired behavior.  By design, selection of the Persona should persist, whether you're editing the main page or a variant.

**Comment by bryanboza** [comment]
@john-thomas-dotcms you are right, but look this 

https://github.com/dotCMS/core/assets/2641437/00098cbe-7a68-4a65-9da4-8fa69fe5e32f

Is not the same behavior when you are out of experiments

**Comment by wezell** [comment]
This behavior, while not ideal, is ok
