### ISSUE TITLE
Design System: Style the primeng autocomplete component

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26056]
### Parent
#25355

### User Story
As a developer, I want to be able to style the primeng autocomplete component, so I can create a consistent and attractive UI.

### Acceptance Criteria
- Update the SCSS to match the Figma file provided.
- Ensure that the autocomplete component follows the styling guidelines.
- Add the story to Storybook

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
[Figma](https://www.figma.com/file/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?type=design&node-id=939%3A22023&mode=design&t=RVFFPcHwOMxBoTXV-1)

### Assumptions & Initiation Needs
- Familiarity with SCSS and Figma.

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
## Notes to QA

I created another ticket to make a final fix and add the storybook for this component. We needed to make a quick fix for a big issue that was affecting the UX. 

Here is an screenshot of the issue we fixed in this ticket. See the `Detail Page` field, the height of the Autocomplete was totally off. It was a blocker for the release.

<img width="1512" alt="Screenshot 2023-10-05 at 3 42 13 PM" src="https://github.com/dotCMS/core/assets/63567962/386dbaa1-0e2d-4ce1-8a7d-7612853ad1f4">

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_3f81f03**, Docker, macOS 13.0, FF v113.0
![Screenshot 2023-10-05 at 3 12 02 PM](https://github.com/dotCMS/core/assets/129882031/c832ef08-f230-4a43-91de-0aac620e5a7d)

Additional work https://github.com/dotCMS/core/issues/26376
