### ISSUE TITLE
Consider ways to clean up old indices automatically

### ISSUE THREAD

**Issue by AndreyDotcms** [dotCMS/core#26069]
### Parent Issue

This issue has been split from:
https://github.com/dotCMS/core/issues/24816

### Problem Statement
Old Site search indexes take up space in the FS, let's remove automatically these ones.

### Acceptance Criteria

We should automatically clean up old indices that don't meet the following criteria: 
- Default
- Created within the last 24 hours
- Have an alias.

The job should run once a week.

### dotCMS Version

Master/23.01.2

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Assumptions & Initiation Needs

There is already a Job `DeleteInactiveLiveWorkingIndicesJob` which according to the doc it only removes ES ones, let's verify this and if is true let's also add here to delete the SS indexes.

**Comment by erickgonzalez** [comment]
Notes for Doc:

- `ENABLE_DELETE_OLD_SS_INDICES_JOB` property to activate/deactivate the job (is activated by default).
- `DELETE_OLD_SS_INDICES_JOB_CRON_EXPRESSION` cron job expression property to define how often the job runs (by default is once per week, Sundays at midnight).

**Comment by bryanboza** [comment]
@erickgonzalez please add more info about how to test it...

**Comment by erickgonzalez** [comment]
Since a requirement was not to delete indices created in the last 24 hours, this is a 2-day QA.

On the first day:
1- Set up the env var property: `DOT_DELETE_OLD_SS_INDICES_JOB_CRON_EXPRESSION: "0 */2 * * * ?"` (to run the job every 2 minutes).
2- Navigate to the Site Search Portlet.
3- Create three indices:
- Alias: Index 1, set as Default.
- Alias: Index 2
- Alias: Index 1 (this will make that the index alias is blank). --> This could be another GH issue.

After 25 hours of the creation of the third index:
1- Navigate to the Site Search Portlet.
2- The third index (the one with the blank alias) should have been deleted.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a5d4962**, Docker, macOS 13.0, FF v124.0.2

Index was deleted after the completion of the time elapsed 
<img width="1280" alt="Screenshot 2024-04-26 at 2 58 27 PM" src="https://github.com/dotCMS/core/assets/129882031/c7cef8cf-b7a7-47fa-b1e8-571598babd54">
