### ISSUE TITLE
mvn clean -pl core-web does not clean nx cache

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#26183]
### Problem Statement

When we run a `mvn clean`, we expect it to clean all build and build artifacts.  Unfortunately, `nx` has its own build cache under `./node_modules/.cache/nx` that needs to be wiped out if we want to build the backend from scratch. We need to add this directory to be cleaned when we run `mvn clean`.

### Steps to Reproduce

1. build dotcms.
2. edit a typescript file (like a label)
3. run a `mvn clean install` and run dotCMS again. 
4. Your changes will not be picked up.

### Acceptance Criteria

You front end code changes should be visible.

### dotCMS Version

23.09

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by spbolton** [comment]
@fmontes @wezell. I feel we should not need to clear out the nx cache on every maven clean build as it will remove the benefit that nx provides.    The nx cache should be explicitly tied to the version of the code that was built and should produce the same result from rebuild or from the cache.   There may be some small cases where there are problems with the nx cache and cleaning it up would help.  I am wondering whether instead of cleaning the nx cache on every maven clean build we create a maven profile ./mvnw clean -Pfull-clean we can use for the nx cache and possibly other caches in the case where the main clean is not producing reproducible results.

**Comment by fmontes** [comment]
I don't think the nx cache influence directly on not picking up typescript changes, I never clean my nx cache to get typescript changes. Maybe what we need to clean is the build output folders?

**Comment by wezell** [comment]
Right - this should not be done on every build, but only on `mvn clean`.  And I think Freddy is right, we should not clean the `nx` cache at all but we should remove the target/output folders.

**Comment by spbolton** [comment]
I think this is the existing functionality then.   maven clean always removes the target folder and all its contents by default but for core-web we are also removing the core-web/dist folder on a maven clean using the maven-clean-plugin configuration.   If this is the case we have nothing to do here @fmontes let me know if there is anything else that should be cleaned up on a maven clean to ensure a repeatable build.

**Comment by fmontes** [comment]
Closing, as no issues have arisen.
