### ISSUE TITLE
dotCMS docker containers may require extra licenses to properly restart

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#26354]
### Problem Statement

When using a "limited license" in dotCMS containers, that license will not be available to dotCMS after a quick container restart. The license server will free up that license eventually, at which time the license can be manually applied.

This impacts on-prem customers running current dotCMS as well as Cloud Engineering. Numerous, quick restarts of a single server can exhaust numerous server licenses, as may occur when troubleshooting. Cloud Engineering works around this by uploading many licenses to each cluster - about 4-5 licenses/node.

The "server ID" of dotCMS docker containers changes with each restart. The generated "server ID" is saved to a file in `/data/local` and that file does not survive a container restart.

### Steps to Reproduce

1. Start dotCMS from docker
2. Upload and apply a single "limited license"
3. Restart the container
4. The license will not be applied

### Acceptance Criteria

"Limited licenses" should work predictably when used in dotCMS docker containers.

### dotCMS Version

All current LTS and agile run from docker containers

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

**Comment by wezell** [comment]
I believe this was improved in #20856 but if the issue still exists in later installs, it is possible to work around the issue by doing one or more of the following:

1. lowering the `DOT_HEARTBEAT_TIMEOUT` to 120 seconds so licenses are reclaimed faster, 
2. In your stateful set, mount in a `/data/local/dotsecure/license` folder that will persist the `server_id` across restarts 
3. over-provision the licenses available in a cluster so that this issue is effectively never seen.

**Comment by prestonso** [comment]
@yolabingo Any thoughts here on @wezell's recommendation?

**Comment by yolabingo** [comment]
AFAIK this is no longer an issue.

Our solution for Cloud servers was 
`3) over-provision the licenses available in a cluster - say by 2x - so that this issue is effectively never seen
`
so I'm afraid we cannot say if license release behavior has improved. We have not heard of license issues from self-hosted customers recently, and Will offers to viable solutions if this does arise.
