### ISSUE TITLE
How show to the user an error when you are trying to generate content with AI Content Extension

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26851]
### Define the Problem

The user does not have a visual hint when the generation of content with Ai Content Extension on Block Editor fails.

### Who's Facing the Problem?

The content creator using the Block Editor and AI Content Extension to generate new content.

### Relevant Links and Resources

- We use OpenAI to generate content. It fails a lot, and we depend on the traffic of their endpoint. In some occasions, the endpoint is busy and we don't have a way to inform the user there is an error generating the content if they want to cancel or retry.on

**Comment by melissarojas-dotcms** [comment]
Here is the redesign for the error message, now it'll be a dialog instead of having it inside the Block Editor.

Figma File: [Link](https://www.figma.com/file/JF3P9JQVJHQOujhdpCRmJG/Block-Editor?type=design&node-id=1990%3A11012&mode=design&t=lkgWZcBsI6P853CH-1)

![image](https://github.com/dotCMS/core/assets/150382008/7f16af87-5845-49ce-b726-71a7bfca027d)
![image](https://github.com/dotCMS/core/assets/150382008/24023ba2-b2e7-4d34-98b5-6b242eed7190)
