### ISSUE TITLE
Create endpoint to send Metrics data to in order be persisted

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27170]
### Parent Issue

https://github.com/dotCMS/core/issues/27130

### Task

We'll create an endpoint which dotCMS can write the metrics data to.
To do this, we'll use the [dot-analytics configurator](https://github.com/dotCMS/internal-infrastructure/tree/main/dot-analytics/configurator).

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Having the endpoint available to take Metrics data and persist to the underlying storage.

**Comment by spbolton** [comment]
1. Create an Immutables object as a DTO e.g. dot-analytics/configurator/src/main/java/com/dotcms/analytics/keymanagement/api/model/IAPIKey.java. 
2. Create a rest resource to capture the request and map the json data posted to the DTO object e.g. dot-analytics/configurator/src/main/java/com/dotcms/analytics/keymanagement/rest/DotcmsAnalyticsResource.java 
3. Create a service e.g. (dot-analytics/configurator/src/main/java/com/dotcms/analytics/keymanagement/DefaultAPIKeyService.java)  that Maps the Resource Request and DTO object passed to the Entity (dot-analytics/configurator/src/main/java/com/dotcms/analytics/keymanagement/repository/entities/ApiKeyEntity.java)  and Repository (dot-analytics/configurator/src/main/java/com/dotcms/analytics/keymanagement/repository/ApiKeyPanacheRepository.java)  created using Panache https://quarkus.io/guides/hibernate-reactive-panache .  During development make sure the database generation configuration is set to automatically create the db e.g. . quarkus.hibernate-orm.database.generation = drop-and-create.  After entity changes are done the ddl can be extracted and a flyway script can be added to update db on startup.

**Comment by spbolton** [comment]
The endpoint can be exposed by updating the ingres helm chart to map the specific path. dot-analytics/deployment/charts/ingress/templates/alb-ingres.yaml.   The public endpoint should essentially be write only, returning only a simple status response e.g. { status: :"OK" }.  We should think about some basic validation to prevent attempted script injection.   

We may want to have a number of fixed known fields that will create columns in the db which will help with quick filtering and indexing and then allow further metrics to be added as a map.   This hashMap<String,String> could be mapped to a separate Panache entity that is joined 1-many, but it would mean that all these values would be stored as strings even if numeric, alternatively, we just store as a json blob, using JsonNode in the DTO instead of hashMap<String,String> may help in this case, may be able to make use of Postgres json blob field in this case.   I am not sure though at the moment we need flexibility to a deep object structure of metrics here that would require storage as Json rather than additional name value pairs for metrics that can be achieved using regular relational db object mappings of a collection.

**Comment by victoralfaro-dotcms** [comment]
PR: https://github.com/dotCMS/internal-infrastructure/pull/588
