### ISSUE TITLE
Make all metrics/experience log messages debug

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#27499]
The metrics (experience plugin) is intended to run silently, collecting telemetry data without affecting the user experience in any way.

Currently, the plugin generates some log messages which may be visible by end users when they view the logs on their server.

We need to change all log messages generated by the plugin to debug level messages.  This means they won't be visible during normal operation, but if we need to enable them to troubleshoot a problem with the metrics, we can turn them on with an API call.

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.experience/pull/25/files

**Comment by dsilvam** [comment]
This is working for the telemetry code. However we can't control if the logging is happening on other classes outside the scope of telemetry. E.g. DotConnect, CircuitBreakerUrl.

 In order to test: 
1. Change the CRON expression to have the job running once a minute. In the docker-compose file include `DOT_METRICS_SAVE_SCHEDULE: "0 * * * * ?"`
1. Change the logging level the telemetry classes by running: 
```
PUT /api/v1/logger

 {
        "level": "DEBUG",
        "name": "com.dotcms.experience.business.MetricsAPI, com.dotcms.experience.job.MetricsStatsJob"
   
}
```

There should be a DEBUG message logged every minute saying: 
`DEBUG job.MetricsStatsJob - MetricsStatsJob is running`

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_0a0ddf5**, Docker, macOS 13.0, FF v121.0.1
![Uploading Screenshot 2024-02-13 at 3.08.48 PM.png…]()
