### ISSUE TITLE
Exploring New Angular Features and State Management Options

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27525]
> [!NOTE]  
> Timebox to 1h

### Task Description
As a member of the dotCMS frontend team, I need to compile a list of the new Angular features and state management options. This list will help us initiate discussions on how to adopt this new technology within our team. 

### Acceptance Criteria
- The list should include all the new Angular features that are relevant to our project.
- Each feature should have a brief description.
- The list should also include different state management options available in Angular.
- The list should be prioritized based on its relevance to our project and ease of implementation.

### External Links
None

### Assumptions & Initiation Needs
- The frontend team is familiar with Angular and its basic features.
- The team has access to the latest version of Angular documentation and resources.
- The team can allocate time for research and experimentation with the new features and state management options.

**Comment by KevinDavilaDotCMS** [comment]
# Principal new features on Angular

- Signals [Long explanation here](https://blog.angular-university.io/angular-signals/)
- Interop Signals with RxJS
- takeUntilDestroy - destroyRef

Changes in Developer Preview: (Preferably we should not use them yet, until they are stable, since several things can change, and it can be difficult to test)

- Signals inputs
- Deferrable views
- Server Side Rendering / SSG 
- ViewTransition API
- New template Syntax

For dotCMS, i think the most important angular features are

- Signals => For component state managment / Share info between components or services
- New template syntax => Its doesnt need specific test, work equals the old syntax, is more lighter and improves performance
- takeUntilDestroy - destroyRef => To replace takeUntil() operator. Now this operator kill the subscription when the component is destroyed.

We should take a look at it, to implement it when it is stable:

- Signals inputs: To avoid and delete getters, input setter and unnecesary code about @Input()
- Deferrable views: To have a nive mechanism to load anything with placeholder, spinner and custom triggers to load components. [More doc](https://angular.dev/guide/defer)
-ViewTransition API: To create moderns transitions in some porlets.

Here is an stackblitz with each stable functionallity:
https://stackblitz.com/edit/stackblitz-starters-yfgzw7?file=src%2Fmain.ts

Suggestions with these new features:
- Use signals inside components to manage the component state.
- Use signals inside services to manage data to share betweeen components, but dont use effects inside services, because here cannot be auto-deleted.
- Dont use signals as inputs yet (We can create a signal, and pass it as input component, then catch that variable and transform to signal inside the component, but this isnt a good approach, we must wait to official signal inputs)
- Try to use the new template syntax, especially the @for, because it improves the performance and reduce bundle

Additional, exploring the new NgRX lib with Signals, i think this is the best option to create a global state managment, because the flow to create the store, read and update is so clear and lighter than other options
This needs a discussion, but i think is the best option, because is simple as Elf, but with strong community for be NgRx

[Here is an example](https://stackblitz.com/edit/stackblitz-starters-yfgzw7?file=src%2Fngrx-signals%2Fstore%2Fcontent.store.ts&file=src%2Fngrx-signals%2Fcontent%2Fcontent.component.html)

**Comment by fmontes** [comment]
Close because we already research this and work with other teams.
