### ISSUE TITLE
Download database not working in latest version

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27537]
### Parent Issue

We need to be able to dump the database from the backend of dotCMS

### Problem Statement

Our pg_dump version is not working in our cloud environments

### Steps to Reproduce

Go to the demo site or master and try to use the download database functionality

### Acceptance Criteria

We need a postman test that tests both this and the download assets.

### dotCMS Version

latest

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
@wezell we already have postman tests for both downloading assets and db dump but the db dump one was ignored because it was one of the ones working locally and failing on GHA. Sounds the moment to include it back. 

Collections are: 
* Maintenance Resource - Donwload Assets
* Maintenance Resource - Download DB Dump 
      The exclusion happen in `exclude DB Dump` -> Test tab ->  `postman.setNextRequest("invalidateSession")`. That last 
       piece of code needs to be removed to include it again.

**Comment by rjvelazco** [comment]
### Passed internal QA

- Tested on Docker: [`dotcms:master_c088f59`]

#### Video

https://github.com/dotCMS/core/assets/72418962/6c98d875-e6b7-4424-a9e9-0b65b33aac56

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_9587235**, Docker, macOS 13.0, FF v121.0.1

**Comment by wezell** [comment]
This is not working in the latest master - the downloaded file is empty

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_ed06491**, Docker, macOS 13.0, FF v121.0.1
<img width="569" alt="Screenshot 2024-03-05 at 1 31 04 PM" src="https://github.com/dotCMS/core/assets/129882031/158a8153-f36c-4932-a678-aa733172b17b">

**Comment by fmontes** [comment]
Server has a different version.

`pgdump < server version` it failed. Only work in Postgres 15

**Comment by jcastro-dotcms** [comment]
The following ticket is part of the fix as well: https://github.com/dotCMS/core/issues/27871 , which includes `pg_dump` from the `pg-base` Dockerfile to the `java-base` Dockerfile, thus eliminating the need for the `pg-base` image and simplify our process.

We're working on re-generating the base image so that the changes get picked up.

**Comment by yolabingo** [comment]
I believe #28134 "remove pg base docker image" will fully resolve this.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
- Docker Image: Build Number `1cce60d` in the [Master QA Instance](https://dotcms-qa-master.dotcms.site/dotAdmin/#/c/maintenance)

After getting over some issues related to the new naming convention for Docker Image tags, @yolabingo and I were able to confirm that you can generate the database dump from the dotCMS backend without issues now. For QA, keep in mind that this issue was never reproducible in a local environment as it relied on a specific setup that needed to be supported.

**Comment by jcastro-dotcms** [comment]
The existing `Maintenance_Resource-Download_DB_Dump.json` Postman test verifies the behavior of this feature as much as possible.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
