### ISSUE TITLE
CLI: Do not require identifiers when updating content type fields

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#28264]
There is a couple of improvements suggested when updating content type fields using the CLI: 
 

- [ ] Updating fields, we should not require the contentType.id in the fields properties - it is known because the fields are a property of the content type

- [ ]  Updating a field should not require the field.id - it should be enough to use the varName.

**Comment by nollymar** [comment]
**Internal QA:** Passed

The feature is working pretty well. I was able to add/edit/remove fields from a content type without requiring their ids, only their variables. Besides, the content type id is not included as part of the fields properties.

**Comment by bryanboza** [comment]
Tested in the latest trunk // docker and we will need some work here:

# At API level:

- We are allowing changes to the field variable, which is a key. Changing this will break all the scripts from containers that pull based on this variable. We need to avoid this. At the UI level, we don't have a way to do this, but via CLI, it is important to prevent because it is easier to cause this kind of problem.

- We need to prevent ignoring all the boolean fields that have been set to false. When you change any of those values, such as searchable, indexed, listed, or required, we are ignoring this property and excluding it from the JSON, which is causing confusion at the CLI level when you try to read the JSON file.

- We need better handling of this case for the endpoint `/api/v1/contenttype/id/{{contentTypeVariable}}`

![image](https://github.com/dotCMS/core/assets/2641437/334ee1bc-c627-4760-a865-02ca8c3291b1)


# From Postman side:

- As part of the security changes, we need to start avoiding the use of Basic Auth, which sends user/pass as plain text in every request and also gives us more work in terms of maintaining tests. Instead, we need to start using the "inherit auth from parent" method for every HTTP request and folder inside the collection. The authentication should be generated in the top collection folder's pre-script section. It consists of generating a new token and sending it as a parameter to all child items in the collection. (More info about this can be found in the Postman guideline doc.)

- We need to add clearer information in the HTTP request descriptions, indicating what is expected from each request, what options will be taken into consideration, and in what order.

- Validating that we are just returning a 200 code is never enough. We need to include specific validations about the response to ensure we are returning the expected JSON in the response.

- We can re-use common validations by moving those to the folder level. This way, the validation will be applied to all the requests within the folder.

### Content Types level

- Negative tests that evaluate sending the ID in the path parameter are not valid. If you send a valid ID as a path parameter, we are not considering this and always return a 404 error. (We need to revalidate this functionality and add a positive test for it)

![image](https://github.com/dotCMS/core/assets/2641437/5f31ab7c-c585-4d4a-9189-c796cfd7de35)

- Some negative tests could be added

### Fields Level

- need to add explicit tests to validate that the new method of sending the `contentTypeId` and the previous method both work. We need to ensure both ways are functioning and have corresponding tests for each case.

- Need to remove the "Copy" word for the folders (`Creation with non existing id Copy and Multiple update permutations Copy`) this under the `Fields` folder

**Comment by fabrizzio-dotCMS** [comment]
@bryanboza 
This : 
`We need to prevent ignoring all the boolean fields that have been set to false. When you change any of those values, such as searchable, indexed, listed, or required, we are ignoring this property and excluding it from the JSON, which is causing confusion at the CLI level when you try to read the JSON file.`

That is by design, @wezell requested this to work that way. This was done in the spirit of simplifying the JSON file.

**Comment by fabrizzio-dotCMS** [comment]
I think it works very well. 
There are no repetitive fields, I can add or remove fields.  
The defaults are not included because that's by design.

sending dupes does not produce an error dupes are getting ignored. 
It does not throw an error. To me this is acceptable 
I'm passing it.

**Comment by bryanboza** [comment]
Fixed, tested on master // docker // postman
