### ISSUE TITLE
Add / Edit new Language

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#28477]
### Parent Issue

#28474

### User Story

As a user, I need the ability to add new Locale for eventual listing. This will provide me with a comprehensive view of the available languages within the system and empower me to contribute new languages as needed.

### Acceptance Criteria

- [ ] Users should be able to add new locales via a user-friendly interface integrated into the listing table.
- [ ] Follow Designs. 

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/tTWRVYunjnzTAWaj8Ctvra/Locales-%2F-Languages?node-id=472-21986&mode=dev

DEMO: https://www.figma.com/proto/tTWRVYunjnzTAWaj8Ctvra/Locales-%2F-Languages?page-id=0%3A1&type=design&node-id=356-41347&viewport=-1747%2C-4187%2C0.26&t=fx8jP5j5bAGXSHbC-1&scaling=scale-down&starting-point-node-id=356%3A41347&show-proto-sidebar=1

Reference: https://github.com/dotCMS/core/issues/25605 

### Sub-Tasks & Estimates

**Comment by jgambarios** [comment]
I found a couple of points to fix/discuss doing internal QA.

1. I created a Custom locale with `uu-dd` as the Locale ID, the problem I see is we are not parsing correctly the language code, and it is just present under the Language column and not broken down as Language code: `uu` and Country code: `dd`, that could also be be reflected in the DB where the value `uu-dd` is stored in the language code column.
![image](https://github.com/dotCMS/core/assets/923947/9c14edf7-faf5-4aa8-83fd-3c2c6c3d105e)

2. When attempt to change the default language we got a modal with a message saying:
    > Setting this language as the default will alter the language of all site content and communications.
    >
    > Be mindful of any unintended consequences.

    ![image](https://github.com/dotCMS/core/assets/923947/513d339b-34b8-4f77-a024-60288c7e7c88)

    Not sure if changing the default language changes the "communications", we are not changing the Admin language to affect that.
    
3. When trying to delete a language with related content, the system fails saying you cannot delete a language with related content, that's perfect, the issue is, that for some reason, after that process, the portlet is in a weird state where subsequent delete operations just won't work.
![2024-06-07_12-25-57 (1)](https://github.com/dotCMS/core/assets/923947/3bab4ada-6010-47cf-986c-934c0567e302)

**Comment by john-thomas-dotcms** [comment]
@jgambarios Humberto and I reviewed your feedback for #1 and #2.I sent him some new text for the modal that I think is clearer.

**Comment by john-thomas-dotcms** [comment]
@jgambarios Humberto and I reviewed your feedback for #1 and #2.

For #1, any locale which uses a known language and country should use the Standard Locale.  And for Custom Locale, we need to treat the whole string as a block (rather than splitting it into language and country) because we need to be able to support some legacy locales that may be up to 5 characters without a dash in them.

For #2, I sent him some new text for the modal that I think is clearer.

**Comment by hmoreras** [comment]
QA Note: 

1. Go to Settings - Roles & Tools, System and add the `Locales` Toot in the menu. 
2. Go to http://localhost:8080/dotAdmin/#/locales

**Comment by victoralfaro-dotcms** [comment]
Findings:
- When confirming Locale deletion, after typing the locale name and a couple of blank spaces, a dot (`.`) is added to the text input.

**Comment by victoralfaro-dotcms** [comment]
### Adding Standard Locale
![image](https://github.com/dotCMS/core/assets/64026161/cd7eebce-66c1-4fa7-b4db-db2bbb155a12)
![image](https://github.com/dotCMS/core/assets/64026161/9c6578cb-ae61-4d8f-bf4e-621dc1b310db)
### Editing recently added Locale
![image](https://github.com/dotCMS/core/assets/64026161/cf392e10-2a19-472a-95dc-791605363d8b)
![image](https://github.com/dotCMS/core/assets/64026161/d797ad0e-1222-4028-9cb2-bd1804cfc746)
### Setting as default recently edited Locale
![image](https://github.com/dotCMS/core/assets/64026161/5bba6813-43c2-4c44-b27f-c9f5b2d3cc17)
Text is what was provided after @jgambarios pointed out
![image](https://github.com/dotCMS/core/assets/64026161/eb347cc4-1098-4622-85f3-2ab0cdeeaa91)

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_ebf61ad**, Docker, macOS 14.5, FF v126.0.1

We should defined a by default sorting as the same as other protlets within the app

<img width="1326" alt="Screenshot 2024-06-26 at 12 22 32 PM" src="https://github.com/dotCMS/core/assets/129882031/bdf0f225-b524-4187-ae63-88f027f9fba2">

After selecting a sorting for the elements and going to another portlet and back, the previously selected sorting gets lost 

https://github.com/dotCMS/core/assets/129882031/734b8242-3c79-417e-b7f5-c768fea68477

Scrolling is not working when sufficient elements are added to the feature. Should we have pagination?

<img width="1530" alt="Screenshot 2024-06-26 at 12 58 43 PM" src="https://github.com/dotCMS/core/assets/129882031/5db74448-5b50-458b-8e00-a590a45464f4">

Please use the message after coping to the clipboard is done

<img width="1326" alt="Screenshot 2024-06-26 at 10 11 12 AM" src="https://github.com/dotCMS/core/assets/129882031/01e08bb4-c550-4455-8605-30d6f8004f86">

**Comment by hmoreras** [comment]
regarding Jose feedback, the first point "We should defined a by default sorting as the same as other protlets within the app" will be worked under https://github.com/dotCMS/core/issues/29040

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_5d577dc**, Docker, macOS 14.5, FF v126.0.1

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_8d0420b**, Docker, macOS 14.5, FF v126.0.1

I'm not seeing the changes implemented yet on the latest trunk/master

**Comment by hmoreras** [comment]
@josemejias11 just checked and changes are there. reach me if is not the case.

**Comment by josemejias11** [comment]
**Failed**: Tested on **trunk_8c2a1e5**, Docker, macOS 14.5, FF v126.0.1

Please use the message after coping to the clipboard is done 
<img width="1326" alt="343300755-01e08bb4-c550-4455-8605-30d6f8004f86" src="https://github.com/dotCMS/core/assets/129882031/0122f1ad-e2b2-4fff-9d05-1eaa9be68558">

Please use the below image as reference
![Screenshot 2024-07-02 at 11 14 17 AM](https://github.com/dotCMS/core/assets/129882031/e94d3b6c-c452-44c7-a254-d65f92c06c6e)

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_eeca0f8**, Docker, macOS 14.5, FF v126.0.1
