### ISSUE TITLE
fix: avoid NPE on Patch WF API when there is not any contentlet map

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#28580]
### Task

Right now to fire a bulk merge you have to 
```
curl --location --request PATCH 'https://dotcms-qa-lts2301.dotcms.site/api/v1/workflow/actions/default/fire/Publish' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGk0NWJlZGI1OC05MGVmLTQwOTctYTllOC1iNzc3YjE4YzVhODUiLCJ4bW9kIjoxNzA0NzQ5ODMxMDAwLCJuYmYiOjE3MDQ3NDk4MzEsImlzcyI6ImRvdGNtcy1xYS1sdHMyMzAxIiwibGFiZWwiOiJwb3N0bWFuIiwiZXhwIjoxNzk5Mzg4MDAxLCJpYXQiOjE3MDQ3NDk4MzEsImp0aSI6ImFmZGRjOWQzLThjYjAtNDlkYy04NGRlLTU0MDk2NTZiZjAwNiJ9.1C5c5vg2_WM7Cw1Zhsoo4OGAg2u8Y5s1gmUr10ved2k' \
--data '{
    "query":"+contentType:TestContentType",
    "contentlet" :{}
}'
```

The contentlet is not need but it is throwing a NPE just trying to realized the index policy

### Proposed Objective

Core Features

### Proposed Priority

Priority 4 - Trivial

### Acceptance Criteria

The request can be made without contentlet node

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on docker: [`dotcms/dotcms:trunk_ 7b54550`]

#### Video

https://github.com/dotCMS/core/assets/72418962/7ba33040-afe5-4622-9ffa-d22b2dd6ce5d

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker

**Comment by bryanboza** [comment]
We merged this without fix the requested changes: 

- @jdotcms you need to update your postman version locally in order to avoid include the `uuid` in every header. 
More info here: https://community.postman.com/t/huge-git-diff-due-to-dynamic-uuids-for-headers/60760
You need to upgrade to v11 to fix. 

- We need change the auth type to JWT, by security changes we are not sending http request using basic auth, who send user/pass in plain text, we need to use JWT instead, you can follow some basic guideline in this doc... https://shorturl.at/6fdrD

**Comment by bryanboza** [comment]
We move the pending work to a new card here: #28902 

We can pass this for now
