### ISSUE TITLE
Moving Containers inside a Layout on a Specific Variant, affect the DEFAULT Variant

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#28655]
### Problem Statement

When you move containers with contentlets inside them in a specific variant, the contentlets in the default variant are also relocated.

### Steps to Reproduce

1. Create a page with a layout that has two rows, each containing an instance of the same container.
2. Add different contentlets to each instance.
3. Create an experiment.
4. Create a variant and move the second row to the top in the layout.
5. Open the page outside the experiment; you'll see that the contentlets have moved.

### Acceptance Criteria

- [x] The DEFAULT Variant must remain unaffected by moving the Containers in the Specific Variant.
- [ ] Integration test

### dotCMS Version

latest in master

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by jcastro-dotcms** [comment]
This issue is NOT REPRODUCIBLE In the latest master. Updating the Template's Layout in the Variant only is not affecting the Layout in the original page.

However, there's a problem with the Contentlets placed on each row/Container. When you update the Variant's Layout, the Contentlets remain where they are instead of going with the row when you move the bottom row to the top position. As per discussion with @dsilvam , the best way to proceed is to have @freddyDOTCMS take a look at the layout update code as he's the expert on it.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `nightly_c6741bd`

After following the STRs in the ticket's description, I can no longer reproduce the issue. Changing the Variant's Layout is not affecting the original page's Layout.

This is the original page:
<img width="1147" alt="Screenshot 2024-07-22 at 12 22 29 PM" src="https://github.com/user-attachments/assets/17a460ab-80a7-46b5-963d-1ba135123dd1">

And this is the Variant:
<img width="1148" alt="Screenshot 2024-07-22 at 12 22 50 PM" src="https://github.com/user-attachments/assets/e30e1a33-4d6e-4ff0-921a-bac1192a631c">

Notice how the `Upper Content` and `Lower Content` Contentlets are not moving and stay within their corresponding Containers, which is the expected scenario.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_2c23184**, Docker, macOS 14.5, FF v126.0.1
