### ISSUE TITLE
Locked page error text wrapping incorrectly

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#28735]
### Problem Statement

The text of the Locked page error that pops up when trying to unlock it isn't wrapping correctly so you get words that start at the end of one line and continue on the next line. 

### Steps to Reproduce

I logged into the demo site on two browsers, 
Opened a page and locked it in one of the browsers
Opened the same page in the other browser and clicked the lock icon to view the error.

### Acceptance Criteria

Proper text wrapping  of the error

### dotCMS Version

Demo 24.05.31, 
Ticket 24.04.24

### Proposed Objective

User Experience

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116561

![Screenshot 2024-06-03 at 9 24 08 AM](https://github.com/dotCMS/core/assets/157033896/360c956e-6642-4ba9-8ec1-ad584f3e78a3)

**Comment by erickgonzalez** [comment]
With the new UVE, there is no lock/unlock when editing a page. Let's fix this directly in 24.04 LTS.

**Comment by erickgonzalez** [comment]
![Image](https://github.com/user-attachments/assets/e2f442f0-20b8-43d8-923b-86809712ec12)

Now the message is showing correctly.

**Comment by jdcmsd** [comment]
This is the same issue seen in https://github.com/dotCMS/core/issues/28644. 

I wonder if the change that fixed this might also suffice to solve that one, if ported to Current. Easy way to test: Does the 24.04.24 LTS QA server have the v10 patch applied? 

It looks like that server's page tools still have the same problem, but that could be because it's not running v10. System info doesn't mention a hotfix patch, so I'm not sure.
