### ISSUE TITLE
Spike: Evaluate what is required to push/pull content type layouts using dotCLI

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#28880]
### Task

We need to do some research in our code (CLI and Content Type API in core) and identify what changes are needed to support pushing/pulling content type layouts.

Please document your findings on this card. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Sub-Tasks & Estimates

- [ ] https://github.com/dotCMS/core/issues/29083
- [ ] https://github.com/dotCMS/core/issues/29086
- [ ] https://github.com/dotCMS/core/issues/29084
- [ ] https://github.com/dotCMS/core/issues/29087

**Comment by jgambarios** [comment]
As part of this discovery ticket, we found four main points to tackle to properly support the fields’ layouts from the CLI:

1. In the CLI, we should remove the `layout` attribute from the content type descriptor. This attribute is used internally, and changes made to it won’t be reflected on the server, as this section is not even read by the `ContentTypeResource`.

2. There is a validation made in the UI that is not done in the CLI. Adding more than four columns to a row should result in an error:
    > This row is full
    > The maximum number of columns per row is limited to four.

3. When saving fields from the CLI, there is a bug changing the sort order. Even when the sort order is defined properly in the content type descriptor, there is a logic when saving fields that “moves” fields, altering the sort order. This bug is altering the order I provide in the descriptor, breaking the layout in the edit content type portlet. Modifying the sort order manually directly in the DB fixes the layout.

4. From the CLI, it is possible to send fields without a layout structure, meaning without rows and columns. In this case, we need to apply the same logic we have when deleting fields, where it “fixes” or actually creates an initial simple layout if no layout fields are provided.
