### ISSUE TITLE
fix: KeyValue Type dont work on WF API

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#28930]
### Problem Statement

When trying to create a type with key value fields, the json enclosed should work.
Currently it is not working, throws bad request

curl --location --request PUT 'http://localhost:8080/api/v1/workflow/actions/default/fire/NEW' \
--header 'Content-Type: application/json' \
--data '{
    "contentlet": {
        "contentType": "Product",
        "title": "supporttest",
        "titleFeature": {"12345":"d=2024-06-20&d2=2024-06-21&c=prc&v=56"},
        "titleEurope": {"12345":"d=2024-06-20&d2=2024-06-21&c=prc&v=56"}
    }
}'

### Steps to Reproduce

Create a type called "Product" or whatever with a couple keyvalue and run the curl previously enclosed

### Acceptance Criteria

The curl should work fine

### dotCMS Version

master

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by josemejias11** [comment]
**Failed**: Tested on **dotcms-postman/src/main/resources/postman/Workflow_Resource_Tests.json**, Postman, macOS 14.5

Add Documentation to Every Request. Currently we don't have any documentation added to any of the request 

![Screenshot 2024-07-02 at 11 40 00 AM](https://github.com/dotCMS/core/assets/129882031/f7cb84b1-af97-4d11-9069-d3e2dfae511f)

Add Pre-Script for JWT Authentication for the main folder 

<img width="832" alt="Screenshot 2024-07-02 at 11 48 53 AM" src="https://github.com/dotCMS/core/assets/129882031/6e58c766-214f-4ac4-b02a-f7f4da3780bb">


Credentials are set as BASIC AUTH

![Screenshot 2024-07-02 at 11 36 32 AM](https://github.com/dotCMS/core/assets/129882031/b80c8be0-b084-40b1-acfc-e3f08639b474)

**Comment by jdotcms** [comment]
The only change introduced at this scope on postman was the subfolder SavingKeyValues
That one already has all reqs: doc + jwt
not fix needed

**Comment by bryanboza** [comment]
Hey guys, looking at the change, we are ok skipping validation for the entire resource since the WF resource is one of the resources with the highest number of tests. We need to do a big migration to JWT to avoid having tests fail sporadically. However, it's important to use best practices in all newly added tests.

Looking at this change, the `SavingKeyValues` folder only includes two HTTP requests, so it is an easy change.

We are okay with the folder documentation, but we need to improve two things here:

- We are using an old JWT generation method because we are hardcoding the username and password in the code:```
 if (!pm.environment.get('jwt')) {
        const username = 'admin@dotcms.com';
        const password = 'admin';
        const basicAuth = btoa(`${username}:${password}`);
        ```
- We need to use the provided example that takes the credentials from collection secret variables, which you can find in the example resource (`ContentResourceV1`). This also needs to be located at the top collection level (Workflow Resource Tests [/api/v1/workflows]). This to allow reuse in any other folder inside the collection and avoid duplicate code. 

- Finally, the `CreateKeyValueContentType` test currently only validates the 200 response code. We need to add an extra validation to ensure the response includes information from the created content type.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d501a60**, Docker, macOS 14.5, FF v126.0.1
