### ISSUE TITLE
UVE: Refresh contentlets outside containers after editing

### ISSUE THREAD

**Issue by zJaaal** [dotCMS/core#28996]
### Parent Issue

TBD

### User Story

As a content editor, I want to be able to see the latest changes I made on a piece of content that is outside of a container, so I can have a smooth flow of work while creating content inside the UVE. 

### Acceptance Criteria

Contentlets should show the latest changes after being edited inside the UVE 

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

1. You understand the update cycle of the UVE 
2. You understand how the Contentlets outside Containers work 

### Quality Assurance Notes & Workarounds

The only workaround is to refresh the page after editing a piece of content that is not part of the main layout of a page.

**Comment by fmontes** [comment]
Closing this because we are already working on the “reactive” subscription to content within the editor here: https://github.com/dotCMS/core/issues/28949 and I rather go this route that try to fix an edge case.

Furthermore, we should not support contentlets outside the container but instead provide a solution to add dynamic content to the header or footer.
