### ISSUE TITLE
UVE: 🐛 Trigger a workflow while in a non-default language redirect to default language

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28997]
### Problem Statement
In the Universal Visual Editor, when a user triggers a workflow with the page in a non-default language, it redirects back to the default language instead of staying in the selected language.

### Steps to Reproduce

https://github.com/dotCMS/core/assets/751424/13631f81-93cd-4eec-be30-3a2c9b035ffe

### Acceptance Criteria

- [ ] User should be able to trigger workflow actions and stays in it selected language

### External Links
- Support ticket https://dotcms.zendesk.com/agent/tickets/116818

### Assumptions & Initiation Needs
- Assumption: The workflow language bug is caused by a redirection issue in the Universal Visual Editor.
- Initiation Need: Investigation and debugging of the workflow language bug to identify the root cause.

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
After some digging, we found out that this issue is related to the fact that we can access a page in other language and this page does not have a version in that language. 

We have an issue to take care about this problem. So we are closing this in favor of this one https://github.com/dotCMS/core/issues/28958
