### ISSUE TITLE
UVE: Page Tools Not Working with Traditional Rendering

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29206]
### Problem Statement
Users are unable to utilize page tools analytics when using traditional rendering in dotCMS.

### Steps to Reproduce
1. Log in to dotCMS.
2. Edit a page in traditional mode
3. Try to use page tools analytics such as tracking and reporting.

### Acceptance Criteria
- Page tools analytics should be functional in both UVE and traditional rendering modes.
- Page Tools should have the `host_id` in the url to support multi site.
 
### External Links
N/A

### Assumptions & Initiation Needs
- It works in headless rendering

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
We should test this again it could be fixed with this card https://github.com/dotCMS/core/issues/28947

**Comment by valentinogiardino** [comment]
After conducting some research and investigation, we've determined that it is not necessary to change the domain of the current site in order to address the issue with page tools analytics.

Instead, we can leverage the `host_id` parameter from the Page API by passing the corresponding ID of the page's site. This approach is already implemented; however, we are encountering some issues related to how the search parameters are being applied. These issues are causing page tools to fail in recognizing the correct site ID.

#### Next Steps:

- **Fix the Search Parameters Issue:** We need to investigate and correct the issues with how search parameters are currently being formatted and sent. This will ensure that the page tools can properly recognize and utilize the `host_id` parameter.

**Comment by zJaaal** [comment]
I updated the ticket with valentino's findings

**Comment by zJaaal** [comment]
# Failed IQA 

It works for all the tools but the Mozilla Observatory, it looks like it expects a domain, not the full url. See the video.

Docker Image: `[dotcms/dotcms:trunk_c8f8051]`

## Screenshot

https://github.com/user-attachments/assets/45888a59-3f76-423e-baf3-16dfde180a7c

**Comment by rjvelazco** [comment]
## Passed Internal QA

- Tested on Docker image: [`dotcms/dotcms:trunk_1c414a1`]
- dotCMS Server: [dotCMS QA Master](https://dotcms-qa-master.dotcms.site/)

### Video


https://github.com/user-attachments/assets/16ff4bd6-c41f-486d-bc7f-71fcc2c8ee18

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker // FF
