### ISSUE TITLE
Remove async nature to the IA actionlets

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#29381]
### Parent Issue

https://github.com/dotCMS/core/issues/29380

### User Story

As an user, I want to be able to fire actions on batch without needing any async nature on the actionlets code

### Acceptance Criteria

As part of the previews work, the IA Actionlets have been annotated to be ran in the UI only as batch, so we need to remove the async methods since it is not longer needed

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by jdotcms** [comment]
Note to QA:
since we have removed the async nature of the actionlets when you add the AI actionlet wont be visible on content editor, this means will be only able to be fired on batch/content search.
At the end the functionality is pretty much the same it was before, but not running on a separated thread by default.
Another important point, at the level the save+publish has been also removed from some of the AI actionlets, it means if you do not add the save actionlet after the AI actionlet, wont see any generation reflected.

**Comment by hmoreras** [comment]
iQA notes findings: 

1. The AI token in the AI app, will work only in under the system host configuration, if is added in `demo.dotcms.com` wont work: 
<img width="725" alt="image" src="https://github.com/user-attachments/assets/1e9ff677-15ee-4e9a-9453-640427b7baeb">

2. If a workflow contains an IA sub actions the option `Show When` -> `Editing` is disabled. which is the expected behavior. 
https://github.com/user-attachments/assets/ecde87c7-9171-4f72-a4e3-233ea4bb8de7

3. The AI imagen generation workflow is not working. 

LOG: https://gist.github.com/hmoreras/25dff1815a4d35e7888e0f9c8767909d

https://github.com/user-attachments/assets/6c175a82-016c-4918-a005-157a6054a2e8

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_600b4f3**, Docker, macOS 14.5, FF v126.0.1
