### ISSUE TITLE
PP - pushing content fails with tags that live on another host that does not exist on reciever 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#29397]
### Problem Statement

If I have a piece of content that lives on system host but uses a tag that lives on another host, one that does not exist on the receiver, the content fails to Push Publish with a totally unhelpful message:

```
Failed to publish because an error occurred: An error occurred when processing Contentlet in '/data/shared/assets/bundles/01J425NKY5MPYKBK2CFKHQ43AB/live/System Host/1/0-content.3ed1f576-57b1-4d19-ab2a-6e5b653ec514.content.xml' with ID '27f4c4d0cdf5c34690da87ce14ffcca3': 'null'
```

### Steps to Reproduce

1. new starter
2. add a new host
3. create a content type with a
- title
- site/folder
- tags
Makes sure it lives on the system host.
4. create a piece of this content on the new host, adding tags, etc.
5. re-save this content on the system host
6. make sure that the tags added live on the new site
7.  try to push the content to demo.dotcms.com

### Acceptance Criteria

If the tag site does not exist, we should save the tag on the system host and not fail the Push publish

### dotCMS Version

*

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dsilvam** [comment]
Passed Internal QA. 
Followed the described steps and the tags are properly saved under _system host_ instead of failing. They originally lived on a host that didn't exist on the receiver. 

Content with tags. Content under system host and tags under "secondSite" 

![Image](https://github.com/user-attachments/assets/fa4c5717-bd70-497a-a449-b89231219d35)

Tags under "secondSite" 

![Image](https://github.com/user-attachments/assets/e962b589-8f31-4c00-ad3f-4e5190bae142)

Tags saved under "system host" on the receiver

![Image](https://github.com/user-attachments/assets/01b2f1f8-ad54-49af-bd50-3667ba8c9d48)

Content on the receiver: 

![Image](https://github.com/user-attachments/assets/7600f427-2c78-4da9-832e-03669d3c71b1)

**Comment by josemejias11** [comment]
**Approved**: Tested on ** trunk_0b665e2**, Docker, macOS 14.5, FF v126.0.1
