### ISSUE TITLE
Enable CDI : Timebox - Check if existing work can be easily merged now

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#29552]
Create branch based upon https://github.com/dotCMS/core/tree/steve-poc-add-cdi 

Thorough testing of existing code and endpoints

**Comment by fabrizzio-dotCMS** [comment]
Note to QA: We upgraded to a more recent version of Jersey for this task, specifically 2.28. This update introduced some issues that were subsequently resolved. For instance, form validation in the **/api/environment** endpoint stopped functioning correctly; the response lost its JSON format and started being returned as plain text. This issue was successfully addressed.

However, it would be a good idea to test other endpoints that perform similar validation, such as:

The secret creation endpoints. Test by sending both valid and invalid values, and verify against previous versions of the endpoints:
POST: **/v1/apps/{key}/{siteId}**
POST: **/v2/languages/**
Additionally, we need to test loading dynamic plugins that deploy a new REST endpoint.

Here's the refined and translated version of your text:

---

We now have a `JerseyApplicationEventListener` class that allows us to track the loaded resources. It can be used alongside the previous code to generate a list comparing the current resources with the expected ones, helping to detect if something is missing or if there are any extra resources.

**Comment by jgambarios** [comment]
While working on the new job queue system I was able to validate CDI is working correctly.
