### ISSUE TITLE
Spike: Determine approach and effort to fix duplicated IDs for content types with Unique fields

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29707]
### Task

Main issue: https://github.com/dotCMS/core/issues/29459

### The Landscape
* There are several different approaches to resolve this bug.
    * We need to discuss the approaches and identify the approach to take.
* We don't know for sure what the cause of the bug is.
    * The issue is rare enough that we can't reproduce it, even on the systems of customers that have experienced it repeatedly.
* We do know that the way we currently check for uniqueness is likely to fail at times.
    * When a user creates a new contentlet of a content type with a Unique field, in order to determine if there's a duplicate value for the unique field, we do a query against the ES index.
        * But we know that indexes can become corrupted, and that there can be race conditions where content which has already been saved to the DB has not yet been indexed.

### Potential Fixes

So far, the following potential fixes have been proposed:
1. Just change the query from an ES query to a DB query.
   * Pros:
       * Effort: Probably the lowest effort solution.
       * Risk: Likely the lowest risk solution (less likely to impact any other features).
   * Cons:
       * Uncertainty: Since we don't know the cause of the issue, we can't be 100% sure it will fix it.
2. Add a column to the table in the DB and add a DB constraint to ensure uniqueness on that column.
    * Pros:
        * There's some chance it will prevent some issues that option 1 won't.
            * But we don't actually know that it will be any better - or even how likely it is that it's better
    * Cons:
        * Effort: Higher effort than option 1.
        * Risk: Higher risk than option 1.
        * Uncertainty: Since we don't know the cause of the issue, we can't be 100% sure it will fix it.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by crak-atudor** [comment]
Hi @john-thomas-dotcms,

We've successfully identified a consistent workflow to reproduce the issue. It seems that creating 10 contentlets with the same uniqueID within a second or so can lead to DotCMS generating up to 10 contentlets. This behavior suggests a race condition, as you mentioned.
However, this doesn’t fully explain all scenarios, particularly the occurrences with older contentlets, which seem to be caused by something other than a race condition.

Thank you,
Andrei Tudor

**Comment by john-thomas-dotcms** [comment]
Hi @crak-atudor,

We currently check uniqueness by looking at the ES index.  This presents two different use cases where the uniqueness check might fail:
1. A race condition, where the index hasn't been updated yet.
2. When the index is out of sync
    * In other words, a search of the index for an existing unique content item incorrectly fails.

Your ability to reproduce the first case with multiple fast submissions confirms that it's likely caused by hitting the index instead of the DB.  The cause of the second case is harder to confirm, since index sync issues aren't an every day occurrence; but we do know that the ES index can sometimes get out of sync, and if it does, we would expect this problem to happen.

Our initial fix for this (both cases) is going to be to perform the uniqueness check against the DB instead of the index.  This is the fastest approach, and offers the least risk since it affects the smallest area of the code.  The chance that this resolves the first case is high; whether or not it resolves the second case is yet to be seen.

We don't know yet if this fix will be viable from a performance perspective, but we'll verify that as part of the work.  If we do find performance issues, we'll undertake a deeper fix which involves database changes.

Thank you,
John Thomas
Product Manager

**Comment by freddyDOTCMS** [comment]
**Bug Investigation Steps:**

**Identifying the Bug Source:**

- First, I created a Playwright test to generate a Contentlet and ran it 10 times to determine if it was a race condition. The test code can be found [here](https://gist.github.com/freddyDOTCMS/ddd6c3dbe56fd4d7ed033997a91b6e17).
- After running the test four times, I was able to reproduce the error a couple of times. I also added a log [here](https://github.com/dotCMS/core/blob/ede8b781a051bc9b8d047a5046280854c0f3a4b2/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L7674) to capture the value of size.
- When the bug was reproduced, the size value was incorrect, showing 0 instead of 1 or more, as expected.
- Before testing, I created a new Content Type called type_1 with two fields: title and unique, with the latter being a unique field.

**Performance Test (No Changes):**

- I ran 100 requests directly to this endpoint:

`POST http://localhost:8082/api/v1/workflow/actions/default/fire/PUBLISH`

**Body:**

```
{
  "contentlet" : {
      "title" : "content_{{unique}}",
      "unique": "{{unique}}",
      "languageId" : 1,
      "stInode": "a78a224a7c1b95a6701c23751858fa51"
  }
}

```

- The unique field was randomly generated for each request, while "a78a224a7c1b95a6701c23751858fa51" is the type_1 ID. Here are the results:


Run | Avg Response Time | Duration
-- | -- | --
1 | 184 ms | 20s 511 ms
2 | 340 ms | 36s 126 ms
3 | 37 ms | 5s 30 ms
4 | 35 ms | 4s 817 ms
5| 34 ms | 4s 712 ms

- The first two response times were much higher, likely due to local issues, so I decided to ignore them.


**Performance Test (Same Unique Value):**

- I ran the same test but used a constant unique value to trigger the unique constraint error each time. Here are the results:

Run | Avg Response Time | Duration|Duplicates
-- | -- | --
1 | 33 ms | 4s 627 ms | 17 Duplicates
2 | 32 ms | 4s 570 ms| No Duplicates
3 | 63 ms | 7s 820 ms| No Duplicates
4 | 31 ms | 4s 434 ms| No Duplicates
5| 30 ms | 4s 271 ms| No Duplicates

**Database-Level Unique Validation**

- I then modified the unique field validation to query the database directly using the following SQL:
```

SELECT contentlet.inode as inode 
FROM contentlet, contentlet_version_info, identifier
WHERE structure_inode =? 
    AND contentlet.identifier != ? 
    AND contentlet_as_json->'fields'->'unique'->>'value' = ? 
    AND contentlet.inode = contentlet_version_info.working_inode 
    AND lang = ? 
    AND identifier.id = contentlet.identifier 
    AND host_inode = ?

```

- Here are the results with random unique values:

Run | Avg Response Time | Duration
-- | -- | --
1 | 38 ms | 5s 139 ms
2 | 35 ms | 46s 892 ms
3 | 33 ms | 8s 710 ms
4 | 34 ms | 4s 688 ms
5| 38 ms | 5s 221 ms

- And with the same unique value, forcing the unique constraint error:

Run | Avg Response Time | Duration|Duplicates
-- | -- | --
1 | 23 ms | 3s 592 ms | No Duplicates
2 | 26 ms | 4s 731 ms| No Duplicates
3 | 46 ms | 12s 507 ms| No Duplicates
4 | 22 ms | 3s 487 ms| No Duplicates
5| 25 ms | 11s 870 ms| No Duplicates


**Conclusion:**
The performance remained consistent before and after applying the database-level unique validation.

**Comment by wezell** [comment]
How many pieces of content?  Please test with 2,000,0000 + contents.

**Comment by wezell** [comment]
also, @freddyDOTCMS live and working inodes are not always the same.  You can have 1 unique value on live and a different unique value on working.

**Comment by freddyDOTCMS** [comment]
I tried with a local database that Ihave with more than 21 millions of Contentlets, and just run the query directly into the Database 

I mean this query 

```
SELECT contentlet.inode as inode 
FROM contentlet, contentlet_version_info, identifier
WHERE structure_inode =? 
    AND contentlet.identifier != ? 
    AND contentlet_as_json->'fields'->'unique'->>'value' = ? 
    AND contentlet.inode = contentlet_version_info.working_inode 
    AND lang = ? 
    AND identifier.id = contentlet.identifier 
    AND host_inode = ?
```

First I tried with a type with more than 7 millions of Contentlets I stoped it after a while.
Later I try again with a type with more than 400k and it took more than 20 seconds so it is not a good fix

**Comment by freddyDOTCMS** [comment]
> also, @freddyDOTCMS live and working inodes are not always the same. You can have 1 unique value on live and a different unique value on working.

ok, so then the real query is even more complex

**Comment by freddyDOTCMS** [comment]
In my last test, I created a new ContentType with two text fields, one of which was unique. I then created over 400,000 Contentlets, with about 90% of them belonging to this new ContentType. While this isn't 2 million Contentlets, what's more important is how many of these belong to the unique ContentType.

I tested three approaches:

- ElasticSearch and the current implementation.
- Direct database query without any structural changes. The query is as follows:
```

SELECT contentlet.inode as inode 
FROM contentlet, contentlet_version_info, identifier
WHERE structure_inode = ? 
  AND contentlet.identifier != ? 
  AND contentlet_as_json->'fields'->'unique'->>'value' = ? 
  AND (contentlet.inode = contentlet_version_info.working_inode 
       OR contentlet.inode = contentlet_version_info.live_inode)
  AND lang = ? 
  AND identifier.id = contentlet.identifier 
  AND host_inode = ?
```

This query works for both LIVE and Working versions. I've implemented the full solution, but it's quite raw and needs refinement.

- Using an extra table where the fields determining unique values are set as a Primary Key. Here's the structure:

```
CREATE TABLE unique_field (
      content_type_var_name VARCHAR(255),
      field_var_name VARCHAR(255),
      language_id VARCHAR(255),
      site_id VARCHAR(255),
      field_value TEXT,
      PRIMARY KEY (content_type_var_name, field_var_name, language_id, site_id, field_value)
);
```

In practice, we plan to include the content ID as a separate field, not part of the primary key. I excluded it here due to issues with duplicate values already present in my local database. I also migrated existing unique values to this extra table.

**Remaining Fixes:**
The complete solution should also include:

- **Table cleanup:** We need to clean up this table when a Contentlet, field, or ContentType is removed.
- **Content ID inclusion:** Adding the Content ID to this table will help update values when Contentlets are modified or removed.
- **Validation adjustment:** I removed a validation [here](https://github.com/dotCMS/core/blob/3977a3bf5c1c4d38aab663a0df05c944bdae74d6/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L7694) (to be honest, I'm not sure what it does). The content ID or inode needs to be in the table for this.
- **Cache integration:** We're considering adding caching to improve performance, but this hasn’t been implemented yet.


**Performance Testing:**

I ran 100 requests to create Content five times and averaged the response times. Each request used a different unique value, so the validation and Contentlet creation were triggered every time.

Results:

**ElasticSearch approach:**

Avg Resp Time: 48 ms | Duration: 6s 101 ms
Avg Resp Time: 48 ms | Duration: 6s 69 ms
Avg Resp Time: 43 ms | Duration: 5s 636 ms
Avg Resp Time: 46 ms | Duration: 5s 868 ms
Avg Resp Time: 42 ms | Duration: 5s 484 ms

**Direct Database query approach:**

Avg Resp Time: 237 ms | Duration: 25s 23 ms
Avg Resp Time: 246 ms | Duration: 25s 882 ms
Avg Resp Time: 242 ms | Duration: 25s 529 ms
Avg Resp Time: 242 ms | Duration: 25s 529 ms
Avg Resp Time: 243 ms | Duration: 25s 653 ms

**Extra table approach:**

Avg Resp Time: 81 ms | Duration: 9s 447 ms
Avg Resp Time: 74 ms | Duration: 8s 702 ms
Avg Resp Time: 78 ms | Duration: 9s 60 ms
Avg Resp Time: 77 ms | Duration: 8s 982 ms
Avg Resp Time: 82 ms | Duration: 11s 254 ms

While both the direct query and extra table approaches prevent duplicate values, the extra table method is more complex to implement. Also the cache can improve the performance I think it can be implemented for the last 2 approach.

**Comment by freddyDOTCMS** [comment]
One more test 

Now I tested with the same Database with more than 400k Contentlets, and I imported 100 Contentlets each time, I used the same type I created for the previous tests.

The Import process has 2 steps first it ask for show a preview where it validated but does not save any Contentlet, after it dotCMS showed you a summarize of the Contentlets that are going to be created and allow you to save this Contentlets in a second step

Results

**ElasticSearch approach:**

1. Preview: 1.3 s Save: 5.3 s
2. Preview: 1.2 s Save: 4.5 s
3. Preview: 1.2 s Save: 4.5 s
4. Preview: 1.0 s Save: 4.6 s
5. Preview: 2.1 s Save: 3.9 s

**Direct Database query approach:**

1. Preview: 20.0 s Save: 43.3 s
2. Preview: 19.2 s Save: 41.0 s
3. Preview: 18.2 s Save: 39.9 s
4. Preview: 18.1 s Save: 40.6 s
5. Preview: 14.2 s Save: 40.9 s

**Extra table approach:**

1. Preview: 4.8 s Save: 11.2 s
2. Preview: 5.0 s Save: 10.9 s
3. Preview: 4.3 s Save: 10.6 s
4. Preview: 4.6s Save: 11.2 s
5. Preview: 4.9 s Save: 11.4 s

**Comment by freddyDOTCMS** [comment]
I didn't test the approach of adding a new field to contentlet_version_info because:

We would need to manage values for both the WORKING and LIVE versions, meaning we'd actually require two fields.
Additionally, since we allow multiple unique fields within the same ContentType, we would need to handle values for each of these fields individually. Simply concatenating the values wouldn't work because each one needs to be validated independently.

**Comment by freddyDOTCMS** [comment]
I ran another test. Previously, when applying the fix for the Extra table, I would first check the database to see if there were any duplicates. If no duplicates were found, I would save the contentlet and add a new entry to the unique table.

Now, instead of checking the unique table first, I try to add a new entry directly. If the operation fails, it means the unique validation has failed. Remember, we already have a constraint in place to prevent duplicate values in the unique table.

Results 

1. Validation: 3907 ms Save: 2982 ms 
2. Validation: 548 ms Save: 2373 ms
3. Validation: 486 ms Save: 2171 ms
4. Validation: 566 ms Save: 2552 ms
5. Validation: 492 ms Save: 2135 ms
