### ISSUE TITLE
Swagger Documentation for `/v1/api-token` Endpoints

### ISSUE THREAD

**Issue by gavriella-dotcms** [dotCMS/core#29742]
### Parent Issue

[28600](https://github.com/dotCMS/core/issues/28600)

### Task

Add Swagger documentation to api-token endpoints.

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Add endpoints should contain the following information in playground:
- Tags
- Descriptions
- Parameters
- Request bodies
- Example values if necessary
- Return schema

### Sub-Tasks & Estimates

Endpoints being documented:
- `/v1/apitoken`
- `/v1/apitoken/{tokenId}`
- `/v1/apitoken/{tokenId}/jwt`
- `/v1/apitoken/{tokenId}/revoke`
- `/v1/apitoken/{userId}/tokens`
- `/v1/apitoken/remote`
- `/v1/apitoken/users/{userid}/revoke`
- `/v1/apitoken/users/revoke`

**Comment by valentinogiardino** [comment]
### IQA FAILED

Tested on `trunk_477606b`

You can view the detailed findings here: [Document](https://docs.google.com/document/d/1_z7j9sRbIlZv-aIjj1eBlOY8TU014cTCDsej6W6MF-A/edit?usp=sharing).

In summary, I found inconsistencies between the response descriptions and the actual outputs returned by the endpoints. There are also some typos and discrepancies in the parameter names.

I couldn't test the POST request as it returns a 400 error. This might be due to an issue with the body I'm passing, but I haven't identified the exact problem. The `PUT /api/v1/apitoken/remote` request also failed, returning a 500 error with the following message:
```
"message": "Index 251 out of bounds for length 65"
```

**Comment by jdcmsd** [comment]
Good comments in that doc. I'll do a review as well as soon as I can. That said, that out-of-bounds error likely points to a value mismatch of some sort; Gavriella was getting it while using dummy values (like `"expirationSeconds": "0"`) but it went away with appropriate ones in a push-publishing enabled environment, such as this: 

https://github.com/dotCMS/core/tree/master/docker/docker-compose-examples/push-publish

For example, I was able to succeed with the following data payload from the (8081) sender environment:

```
{
  "token": {
    "network": "0.0.0.0/0",
    "expirationSeconds": "100",
    "userId": "dotcms.org.1",
    "claims": {
      "label": "Push Publish"
    }
  },
  "remote": {
    "host": "localhost",
    "port": "8082",
    "protocol": "http"
  },
  "auth": {
    "login": "admin@dotcms.com",
    "password": "YWRtaW4="
  }
}
```

**Comment by valentinogiardino** [comment]
### IQA PASSED
Tested on `trunk_7d5223d`
All inconsistencies identified in the previous IQA have been resolved.

**Comment by bryanboza** [comment]
Fixed, tested in the last trunk and now the doc looks ok
