### ISSUE TITLE
Add UI to override config variables

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#29793]
### User Story

@jdotcms  added the system_table which can be used to override and persist config changes in dotCMS.   This includes cache region changes, feature flags, the whole thing.  

These changes persist for the lifecycle of an environment.

But we were getting no value out of this great addition.  This card adds the ability to add config overrides from the UI without having to change the k8 manifest.

System > Maintenance > System Info will now allow you, by clicking on the `configOverrides` to edit config properties that will get picked up either immediately or on a restart.

### Acceptance Criteria

Make sure we can override properties - for example a cache region - using this.

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by jdotcms** [comment]
Very nice

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `trunk_2585d6d`

The `Config Overrides` feature is working as expected. Checking the expected behavior is very easy by following Will's video. Now, it's very important to take into consideration the way configuration properties are retrieved:

1. The `com.dotmarketing.util.Config` class checks for the existence of an Environment Variable with the specified name -- appending the `DOT_` prefix, if required.
2. If not present, looks for the property in one the `dotmarketing-config.properties` or the `dotcms-config-cluster.properties` files in the system.
3. Finally, if still not present, reads from the System Table returns its value, if exists.
