### ISSUE TITLE
Create Content Analytics flag And Avoid to run all the Analytics logic if the Analytics App is not config

### ISSUE THREAD

**Issue by freddyDOTCMS** [dotCMS/core#30076]
### Parent Issue

#29711

### User Story

We need to add a flag that allows enabling or disabling the Content Analytics feature as desired. This flag should prevent the Analytics Interceptor from being included and executed when the feature is disabled.

Additionally, if the Analytics app is not configured, none of the Content Analytics processes should run. In this case, the interceptor should still be added and executed, but it should perform no actions.

Finally, we need to ensure that if any exceptions are thrown, the interceptor does not interfere with or block the normal request flow.

### Acceptance Criteria

- Create a Flag to Enabled/disabled the CA.
- Avoid to run any CA code if the Analytics App is not config, Important if you config the App, Content Analytics should start working without restart dotCMS.
- If any Exception is thrown during we executing the CA code the request need to finish normally

### Proposed Objective

Core Features

### Proposed Priority

Please Select

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: You can enabled and disabled the flag and it is working as expected

**Comment by josemejias11** [comment]
**QA Comment**

In order to complete the work on this we are going to need a couple of things

1. Please add the proper docker compose configuration if any additional lines need to be added besides the FF
2. Please add instructions to perform the require test 

It will be advisable if the IQA is performed for another developer other than the one who worked the card.

cc @john-thomas-dotcms @dsilvam 

Thanks!

**Comment by jcastro-dotcms** [comment]
@josemejias11 in this doc you can find the steps you need to follow in order to set up the Docker image, and the configuration for the `Analytics Integration` App inside dotCMS: 

- https://docs.google.com/document/d/13KFFCX3S7sQWkNOwoZgcE_aPCbvyFLFKBILrm5PZvWQ/edit

The name of the Feature Flag is `DOT_FEATURE_FLAG_CONTENT_ANALYTICS`. It is enabled by default, so you can set it to `false` in order to disable the Content Analytics feature.

Regarding the IQA process, what is advisable is to not have the developer who created the fix revalidate the issue as well. In this case, Jonathan Sanchez created the fix, and Freddy Rodriguez did the IQA.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_a12617a**, Docker, macOS 14.5, FF v126.0.1
