### ISSUE TITLE
UVE: Support `#editContentlet` Macro in Universal Visual Editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#30218]
### Problem Statement
The Universal Visual Editor (UVE) currently does not support the #editContentlet macro, which limits developers' ability to customize and edit contentlets within the editor.

### Steps to Reproduce
1. Open the Universal Visual Editor.
2. Try to use the #editContentlet macro within the editor.
3. Notice that the macro is not recognized or supported by the editor.

### Acceptance Criteria
TBD

### External Links
N/A

### Assumptions & Initiation Needs
- It is assumed that developers will need to utilize the #editContentlet macro for more dynamic content editing within the Universal Visual Editor.
- Initiation needs include updating the UVE codebase to recognize and support the #editContentlet macro.

### Quality Assurance Notes & Workarounds
- Currently, developers can manually edit contentlets outside of the UVE to include the #editContentlet macro.

**Comment by zJaaal** [comment]
We will take care of the reorder menu macro in this ticket https://github.com/dotCMS/core/issues/30445

**Comment by zJaaal** [comment]
## Note to QA 

### Headless 

Right now this is only implemented in NextJS. It should work in any framework, but if you don't want to go and modify the code. You can just run the NextJS example, go to the footer and you should see an small `edit` button in the contentlets of the footer. Be aware, that we didn't take in count any styles or hide/show functionality, we only want it to work in this iteration. It should pop the edit contentlet and also refresh the contentlet on save. We have [another issue](https://github.com/dotCMS/core/issues/30534) to create components for this button and enhance the visual funcionality, this ticket also cover the integration in other frameworks 

#### Edit Button
<img width="614" alt="Screenshot 2024-10-31 at 10 42 29 AM" src="https://github.com/user-attachments/assets/16ee1b85-446a-4020-bdcd-2d4ce45c530e">


### Traditional 
In order to see the correct button in the page, you can go to `application/vtl/blog/blog-listing.vlt`delete the code from line 32 to line 36 and add the macro with the inode of contentlet as arguments. It should look something like: `#editContentlet($con.inode)`

And then you can test the button on the blog listing page `/blog/index.` 

#### Visual Reference
You should see a pencil above the contentlet, with no title and nothing else but a pencil

<img width="983" alt="Screenshot 2024-10-31 at 10 47 41 AM" src="https://github.com/user-attachments/assets/1867d938-3f1f-4a4c-a801-1333ff3f6603">

**Comment by rjvelazco** [comment]
### Passed IQA

- Tested on docker image: [`dotcms/dotcms:trunk_c0a01e6`]

#### Traditional

https://github.com/user-attachments/assets/79d9d9d8-c80c-42c4-9894-5a5683f56233

#### Headless

https://github.com/user-attachments/assets/101ab2d5-4ff4-45e0-98a2-baa22cc3e8a8

**Comment by bryanboza** [comment]
Fixed, tested on the Next JS and Angular SDK and now we are able to use this macro as expected. 

Issue related to button UI was created here: https://github.com/dotCMS/core/issues/30534
