### ISSUE TITLE
Edge PP issues

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#30370]
### Problem Statement

Working with Marc on identifying PP issues that are preventing him from importing a bundle.

- [x] Folder on a non-pushed host gets dragged along in the dependency tree
> Failed to Publish	Failed to publish because an error occurred: An error occurred when processing Folder in '/data/shared/assets/bundles/01J9Y3ERJFZ37E3GY8SBYJ7E2N/ROOT/1753550752892eb018ce8cee7ecc2178.folder.xml': You can only create an identifier on a host of folder. Trying: null

- [x] Container with live!=working inode 
> fails to publish because it seems we are only pushing the live inode/version but we try to write the container_version_info from the sender, which references a working inode that might not exist on the receiver. 

- [x] Content on a non-pushed host get dragged along and fails to publish
> Failed to publish because an error occurred: An error occurred when processing Contentlet: You can only create an identifier on a host of folder. Trying: null
### Steps to Reproduce

~Ask me for the broken bundle.~ Ask Jose Castro for the broken bundle.

### Acceptance Criteria

the bundle should import without issue.

### dotCMS Version

latest

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

**Comment by wezell** [comment]
This change introduces a minor breaking change in that it disables the antique `/DotAjaxDirector/com.dotcms.publisher.ajax.RemotePublishAjaxAction/cmd/uploadBundle` endpoint and suggests to use the `/api/bundle/sync` endpoint to upload a bundle.

The old endpoint can be reactivated if needed by setting the variable `DOT_ENABLE_OLD_BUNDLE_UPLOAD_ENDPOINT` = to `true`

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `trunk_7a5f044`

The broken bundle can be imported without problems now. There are a couple of this to take into consideration:

* The bundle is 141.6MB in size, which means it has a lot of data. Make sure your dotCMS instance has enough memory to handle the publishing process.
* Start dotCMS with the Empty Starter, and delete the `Video` Content Type before importing the bundle.
* In order to verify that everything worked as expected, you must check that the status of the bundle in the `Site Manager > Publishing Queue > STATUS / HISTORY` portlet shows as `Success`.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_65c8ebb**, Docker, macOS 14.5, FF v126.0.1
![Screenshot 2024-11-11 at 8 51 48 AM](https://github.com/user-attachments/assets/db28552e-3d68-43d0-98d6-517190214c2b)
