### ISSUE TITLE
Folder names should be case sensitive. NOw you cannot change the case of the name without getting an error.

### ISSUE THREAD

**Issue by isaaceindhoven** [dotCMS/core#3041]
I edit the name of a folder and only change the case. DotCMS will shown the error: "Folder already exists, please enter a different name". I think folder name should be case sensitive because URL's are case sensitive as well and the name is used in the URL.

**Comment by jcastro-dotcms** [comment]
Note to QA: This issue is NOT reproducible with the latest pull from Git. Folder names can be changed without problems (from upper-case to lower-case and viceversa). As of https://github.com/dotCMS/core/issues/7918 , all URLs in the ``identifier`` table are lower-case now in order to take advantage of DB index scans.

**Comment by bryanboza** [comment]
Unable to reproduce on master-4.1
