### ISSUE TITLE
[Spike] SDK: Fix Next.js Real-Time Updating in dotCMS 24.04 🐛

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#30485]
### User Story
As a Front-end Developer or Content Editor, I want the edits I make in the Next.js example page to reflect in real time on dotCMS 24.04, so I can see updates immediately without needing to manually refresh the page.

### Spike 🔺
In this task, we need to understand why the Next.js example is not refreshing the content of the page in UVE in dotCMS 24.04.

> [!TIP]
> My guess is because the `latest` sdk is waiting for the data from UVE and in 24.04 we don't do that, we need to confirm this.

```[tasklist]
### Acceptance Criteria
- [ ] Find out why is not refreshing
- [ ] If is related with the version of the SDK, find out what version of the SDK works with 24.04
- [ ] Identify what we need to do to make the SDK retro compatible with 24.04 (if possible)
- [ ] Conduct tests across multiple browsers (e.g., Chrome, Firefox, Edge) to confirm that the issue isn’t browser-specific.
```

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
[Placeholder for external links]

### Assumptions & Initiation Needs
- Assumption that all necessary infrastructure components for live updates functionality are properly set up.
- All related systems and technologies are up-to-date according to dotCMS and Next.js compatibility standards.

### Quality Assurance Notes & Workarounds
- Ensure testing in staging environments simulating various real-use scenarios.

### Technical Details
- Versioning: dotCMS 24.04, a compatible version of Next.js as per documentation.

**Comment by KevinDavilaDotCMS** [comment]
# Results
After an investigation, it was found that the `dotCMS LTS 24.04` version works correctly with the SDK libraries version `0.0.1-alpha.22.`

Therefore, a branch is created with this version, modifying the nextjs example so that it works correctly with that version.

The cause of the error of the latest version 0.0.1-alpha.47 with the LTS 24.04 version of dot was not determined, but this solution is sufficient to continue to meet the needs of the partners.
