### ISSUE TITLE
🐛 SDK: Fix React SDK Crash on Empty Containers (dotcms.com)

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#30496]
### User Story
As a React SDK consumer, I want the SDK to handle empty containers gracefully, so that my Next.js page does not crash when the containers is empty and users have a seamless browsing experience.

```[tasklist]
### Acceptance Criteria
- [x] When the [`/test-folder/structured-content-quarantine-please-dont-edit`](https://new-dotcms-com.vercel.app/test-folder/structured-content-quarantine-please-dont-edit) page has an empty container, it should not cause the entire page to crash.
- [x] Property access from undefined objects within the React SDK does not crash the page.
- [x] Error handling mechanisms are improved to provide clear and informative feedback instead of page crashes.
- [x] Regression tests confirm that fixes have not introduced new issues elsewhere in the product.
- [x] The fix should be documented clearly in the project's development documentation.
```

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- Assumes that source code access and debugging tools are available to identify the root cause.
- A development environment setup mirroring the production where the issue is replicated.

### Quality Assurance Notes & Workarounds
- Ensure all potentially affected pages are included in the regression testing scope.

### Technical Details
- React SDK (specific version to be determined during the root cause analysis)

**Comment by zJaaal** [comment]
I sent a fix in the PR I linked, this will prevent production to break in this case. But we probably will open another ticket. We are still digging in the root cause of it. At this moment, seems like a backend bug. 

The issue was related to a container having contentlets under the uuid: `uuid-dotParse_XXX` instead of the expected format `uuid-XXX` which caused an access to an undefined variable that breaks the Frontend.

### Expected format: 
<img width="902" alt="Screenshot 2024-10-30 at 2 14 17 PM" src="https://github.com/user-attachments/assets/742b12dc-6db2-45a7-8859-4025b1aecf24">

### Recieved format (is the same object):
<img width="960" alt="Screenshot 2024-10-30 at 2 15 22 PM" src="https://github.com/user-attachments/assets/a8eb16e6-6090-42dc-b127-502aaa3687ef">


This is an unexpected behavior and we are still looking into it, meanwhile what I did will print a log in the console advising about this odd behavior and also recommending the user a workaround it.

We will link the ticket following our findings when we have it.

**Comment by zJaaal** [comment]
## Note to QA 

I couldn't find a way to test this on a local environment, we had to put in quarantine the broken page in order to have something to investigate this issue further. So I'm not really sure how can we test this. 

The only thing that can work is to update production and test this on the isolated page that is broken.

cc: @fmontes @nollymar

**Comment by fmontes** [comment]
@nollymar We need to create a ticket to research on how the page gets corrupted. @zJaaal left a copy of the page that backends can use, is not perfect but is something. Also, we spoke with @freddyDOTCMS and he can have some ideas.

**Comment by nollymar** [comment]
[A new card](https://github.com/dotCMS/core/issues/30536) for research was created

**Comment by rjvelazco** [comment]
### Failed IQA

- Tested on docker image: [`dotcms/dotcms:trunk_c0a01e6`]
- SDK: ` "@dotcms/client": "latest"` and ` "@dotcms/react": "latest"` [latest=alpha.47]


### Video

https://github.com/user-attachments/assets/69f8057d-a1cb-4eac-8a0a-258d7f9d7e90

**Comment by rjvelazco** [comment]
### Passed IQA

- Tested on docker image: [`dotcms/dotcms:trunk_7408571`]
- SDK: ` "@dotcms/client": "latest"` and ` "@dotcms/react": "latest"` [latest=alpha.47]

###Video

https://github.com/user-attachments/assets/44b23d0b-44c1-4755-9516-f27cbd6c81cf

**Comment by bryanboza** [comment]
Fixed, tested on trunk// docker // FF
