### ISSUE TITLE
Spike: API Investigation for Multi-language Content Support

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#30581]
## Parent Issue
#30371

## Task
Technical investigation (spike) to determine:
* How to retrieve all available languages for a contenType/contentlet
* How to identify which languages have existing contentlet (already translated and missing)
* How to determine the default language (this will be used for copy content)
* Data structure for language availability

## Acceptance Criteria
* Documentation of required API endpoints
* Proposed data structure for language management
* Implementation recommendations
* List of any potential technical limitations

## External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C058GCQ7T39/p1730828201841249?thread_ts=1730827058.966279&cid=C058GCQ7T39

## Proposed Objective
Same as Parent Issue

## Proposed Priority
Same as Parent Issue

**Comment by jcastro-dotcms** [comment]
### Results
The `PageResource` REST Endpoint already provides a similar implementation of what we need to accomplish here:

https://github.com/dotCMS/core/blob/427124831f7a8585d2b0a15561c3f989cb45f3c0/dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java#L1389-L1405

We can do some refactoring in the existing code in order to reuse the logic and include ALL kinds of Contentlets, not just HTML Pages. This way, just like with do with the aforementioned endpoint, we can return a list of Languages and indicate whether the specified piece of Content has a version in a given language or not. For instance, this is the JSON response when when querying for the available languages for an existing HTML Page:
```json
{
    "entity": [
        {
            "country": "United States",
            "countryCode": "US",
            "id": 1,
            "isoCode": "en-us",
            "language": "English",
            "languageCode": "en",
            "translated": true
        },
        {
            "country": "Espana",
            "countryCode": "ES",
            "id": 2,
            "isoCode": "es-es",
            "language": "Espanol",
            "languageCode": "es",
            "translated": true
        }
    ],
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```
In this case, the page is available in the two existing languages in the dotCMS instance. You can check that via the `"translated"` attribute. We can do the same for all types of Contentlets.

Finally, it seems we don't have a specific REST method that returns the current default language. This will be a very small method, but must be added.
