### ISSUE TITLE
Introduce some static "label" field that can be used as Hint in ContentType

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#30592]
### User Story

Different customers have use cases where they need to add a Hint for another field to explain the usage, so they relay a custom field name with no value. This workaround works but is not ideal for this use case, so if dotCMS introduces a Hint field, that will be shown in the content to clear more ideas about the specific fields.

### Acceptance Criteria

A field that can be used as a hint in contenttype

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.freshdesk.com/a/tickets/28173

**Comment by john-thomas-dotcms** [comment]
In the new content edit screen (due to be released by end of Q1 2025), the hint text on fields is shown inline in the screen, rather than on hover.

![Image](https://github.com/user-attachments/assets/1cee101d-6c5c-4d38-a114-a0a4d27b327b)

If customers want to show more than this, a custom field is the best solution, since it allows them to choose both how to display the text (font size, color, etc.) and where to show it (above, below, etc.).

We do not plan to add any new fields to support static text in the content edit window, beyond these two (hints and custom fields).
