### ISSUE TITLE
Storyblock infinite recursion when combined with relationship field

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#30609]
### Parent Issue

* https://github.com/dotCMS/core/issues/30437

### Problem Statement

When you create a circular relationship between content by using both a relationship field and a blockeditor field, requesting one of the contents using the default depth=2 (and even depth=1) makes it go into an infinite recursion and as consequence throwing a OutOfMemoryError: Java heap space

```
dotcms-1      | 21:20:50.560  INFO  log.accessLog - Method execution failed:
dotcms-1      | java.lang.OutOfMemoryError: Java heap space
dotcms-1      | 	at java.base/java.util.Arrays.copyOfRange(Arrays.java:3856) ~[?:?]
dotcms-1      | 	at java.base/java.lang.String.<init>(String.java:4788) ~[?:?]
dotcms-1      | 	at java.base/java.lang.String.<init>(String.java:1507) ~[?:?]
dotcms-1      | 	at java.base/java.lang.StringBuilder.toString(StringBuilder.java:475) ~[?:?]
dotcms-1      | 	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:505) ~[?:?]
dotcms-1      | 	at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:114) ~[?:?]
dotcms-1      | 	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4041) ~[?:?]
dotcms-1      | 	at com.dotcms.contenttype.business.StoryBlockAPIImpl.toJson(StoryBlockAPIImpl.java:330) ~[?:?]
dotcms-1      | 	at com.dotcms.contenttype.business.StoryBlockAPIImpl.refreshStoryBlockValueReferences(StoryBlockAPIImpl.java:103) ~[?:?]
dotcms-1      | 	at com.dotcms.contenttype.business.StoryBlockAPIImpl.lambda$refreshReferences$2(StoryBlockAPIImpl.java:71) ~[?:?]
dotcms-1      | 	at com.dotcms.contenttype.business.StoryBlockAPIImpl$$Lambda/0x0000000201246200.accept(Unknown Source) ~[?:?]
dotcms-1      | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
```

### Steps to Reproduce

1. Create a new type containing a story block field and a Relationship field
2. Create items A, B, and C
3. In the relationship field relate B->A, C->B, A->C.
4. In each of the story block fields add the other 2 items directly.
5. Trace and view the value of jsonWithRelationships.toString() in ContentUtils.addRelationships.

A short cut to generating the result of jsonWithRelationships is to call the content api directly for the id of A, B or C and specify depth=2 e.g. http://localhost:58190/api/v1/content/c1492b19-e1d1-44d2-9afd-a7ff49c4dad8?depth=2
Increasing the number of items used could reach 1000 depth, but I am not sure what the limiting factor is at the moment that prevents this from creating an infinite loop. just know the document gets very large with these few items and on my vm it runs out of memory before I hit the 1000 limit but this structure is a good start to analyze the relationship between the relationship levels and structure and the json levels produced.
Each new sub object in the json tree represents a new level in the json structure.

Here is an example of the json with just 3 items

https://gist.githubusercontent.com/spbolton/5ceee774de186007c1db66812b3d5cdb/raw/6958db47532de9dd736e7d0674f1b1b6550f1c80/gistfile1.txt

If the expanded contentlet in the json has been pulled from cache it is possible that it is pulling it with "pre expanded" with sub relationships that may then continue further duplication of relationships at lower levels and breaking out of the max depth of 2 that is the default for the relationship field on its own.

### Acceptance Criteria

* Respecting the provided depth parameter even when having both a storyblock and a relationship field in the content and a circular dependency.  
* Automated tests.

### dotCMS Version

trunk_8077c29

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by nollymar** [comment]
This issue might be related to this https://github.com/dotCMS/core/issues/30661

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED ✅
* Docker Image: `trunk_e15f58e`

dotCMS is working as expected after attempting to reproduce the failure scenario described in this ticket. No OOM or StackOverflow exceptions are being logged. Here's my test scenario:

* Create a test Content Type named `My CT` with 3 fields:
  * `Title`, of type `Text`.
  * `My Rel`, of type `Relationship`.
  * `My Block`, of type `Block Editor`.
* Create 3 contents of such a type:
  * `Content 1`
  * `Content 2`
  * `Content 3`
* Relate each other like this:
  * `Content 2` with `Content 1`.
  * `Content 3` with `Content 2`.
  * `Content 1` with `Content 3`.
* This is what the JSON response from the Content REST Endpoint looks like for `Content 1`: http://localhost:8080/api/content/depth/2/id/8e752506a8057b924f559453f06895b4 - notice the `/depth/2/` in the URL, which is EXTREMELY IMPORTANT!

<img width="624" alt="Screenshot 2024-11-27 at 3 15 08 PM" src="https://github.com/user-attachments/assets/dd133acb-ac05-4dfc-8751-15877348dcf4">

Notice how the third level in the Relationship attribute is NOT included, which is the expected behavior.

* Now, open each content and reference all other contents in the Block Editor field, like this:
  * Open `Content 1`, and add `Content 2` and `Content 3` to the `My Block` field.
  * Open `Content 2`, and add `Content 1` and `Content 3` to the `My Block` field.
  * Open `Content 3`, and add `Content 1` and `Content 2` to the `My Block` field.
* This is what the new JSON response from the Content REST Endpoint looks like for `Content 1`: http://localhost:8080/api/content/depth/2/id/8e752506a8057b924f559453f06895b4  - again, notice the `/depth/2/` in the URL, which is EXTREMELY IMPORTANT!

<img width="961" alt="Screenshot 2024-11-27 at 3 21 09 PM" src="https://github.com/user-attachments/assets/e2d78a74-89e9-4125-a3ca-9d1bee3f7280">

For the `Content 2` data, the contents it's referencing inside the `My Block` field are NOT being hydrated, which is the expected behavior. This keeps the infinite recursion from happening.

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_e15f58e**, Docker, macOS 14.5, FF v126.0.1
