### ISSUE TITLE
Enhance Config Property Reloadability for Experiments Feature

### ISSUE THREAD

**Issue by victoralfaro-dotcms** [dotCMS/core#30718]
### User Story
As a software engineer, I want to identify all instances in the code for the Experiments feature where Config properties are used in a way that prevents them from being reloaded through the "System Tables" feature. Once identified, I want to make the necessary changes to ensure those properties are reloadable, avoiding caching them in final variables (instance or static).

### Acceptance Criteria
- All Config properties in the Experiments feature are reloadable via the "System Tables" feature.
- Instances of Config properties cached in final variables are identified and updated.
- Unit tests confirm the reloadability of updated Config properties.
- Documentation is updated to reflect the changes made.

### dotCMS Version
master

### Proposed Objective
Quality Assurance

### Proposed Priority
Priority 2 - Important

### External Links
- _Slack conversations_: [Link to discussion if applicable]  
- _Support tickets_: [Ticket reference if available]  
- _Figma designs_: N/A

### Assumptions & Initiation Needs
- The "System Tables" feature is operational and correctly configured for testing property reloads.
- Access to codebase and necessary permissions to implement changes.
- Collaboration with QA to validate reloadability.

### Quality Assurance Notes & Workarounds
- Validate reload functionality in staging or sandbox environments before merging to the master branch.
- Identify and test edge cases for Config property reloading.

### Sub-Tasks & Estimates
1. **Code Audit**: Identify all Config properties in the Experiments feature - **4 hours**  
2. **Implement Changes**: Update Config properties to be reloadable - **8 hours**  
3. **Testing**: Write and execute tests for reloadability - **6 hours**  
4. **Documentation Update**: Update internal documentation regarding Config property usage - **2 hours**  

Total Estimate: **20 hours**

**Comment by freddyDOTCMS** [comment]
Need works:

I don't test with this steps https://github.com/dotCMS/core/issues/30718#issuecomment-2492048551
because the DOT_FEATURE_FLAG_EXPERIMENTS is not working right so I do the follow

- Start local analytics infrastructure
- Set  these environment variables in the docker-compose file:

      DOT_FEATURE_FLAG_EXPERIMENTS: false
      DOT_ALLOW_ACCESS_TO_PRIVATE_SUBNETS: true
     DOT_ENABLE_EXPERIMENTS_AUTO_JS_INJECTION: false

- Start a dotCMS instance with NOT an empty starter
- Configure the Analytics App with this values:

```
client id: analytics-customer-customer1
client secret: testsecret
config url: http://host.docker.internal:8088/c/customer1/cluster1/keys
write url: http://host.docker.internal:8081/api/v1/event 
read url: http://host.docker.internal:4001/
```

use localhost instead of host.docker.internal if you are not using docker

- I got this error

<img width="375" alt="Screenshot 2024-11-28 at 09 01 26" src="https://github.com/user-attachments/assets/d250eda8-835c-4a12-b51c-adbfa8f2968f">

- Go to Maintenance->System Info->Config Overrides
Add DOT_ANALYTICS_IDP_URL and set it to 'http://host.docker.internal:61111/realms/dotcms/protocol/openid-connect/token'

use localhost instead of host.docker.internal if you are not using docker

- Go to the Analytics App again and save it with the same values,  you should see the Analytics Keys generated after save
- Create a Page and an Experiment, you are going to able to do it even when DOT_FEATURE_FLAG_EXPERIMENTS is equals to false, I don't know if it is a bug but for sure is out of the scope of this issue
- Publish the Page and Start the Experiment.
- Navigate to the page and see the Page Source the Experiment code is not going to be there
- Now Go to Maintenance->System Info->Config Overrides and add
    DOT_FEATURE_FLAG_EXPERIMENTS: true
    DOT_ENABLE_EXPERIMENTS_AUTO_JS_INJECTION: true

And the code is not injected so it looks like is not working for these properties

**Comment by victoralfaro-dotcms** [comment]
Okay @freddyDOTCMS this does not need work at all.
Ii seems that the way System Tables works, if the property already exist as environment variable it does not get override. So I updated my comment at 
So in other words, environment variables:
```
DOT_FEATURE_FLAG_EXPERIMENTS
DOT_ENABLE_EXPERIMENTS_AUTO_JS_INJECTION
```
Need to be removed from docker compose file.

**Comment by freddyDOTCMS** [comment]
Pass Internal QA: it is worked when the variables are removed from the docker compose file like @victoralfaro-dotcms mentioned here https://github.com/dotCMS/core/issues/30718#issuecomment-2522079783
