### ISSUE TITLE
Documentation:  document system roles

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#6551]
The page http://dotcms.com/docs/latest/SystemRoles needs beefing up.  It describes six of the system roles but there are 27 in all.

**Comment by DeanGonzalez** [comment]
Updated: http://dotcms.com/docs/latest/SystemRoles
Added: http://dotcms.com/docs/latest/ScriptingUser, http://dotcms.com/docs/latest/CurrentUser

**Comment by john-thomas-dotcms** [comment]
We cleaned this up quite a bit a while back (but I just saw this issue):
http://dotcms.com/docs/latest/system-roles
http://dotcms.com/docs/latest/legacy-system-roles

There's still more work to do here, but I think it's from the application side (see https://github.com/dotCMS/core/issues/10013), so I'm closing this, since I think the doc side has been addressed.
