### ISSUE TITLE
Able to save a page with a / in the url

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6803]
It should not be possible to save a page with a / in the url.  In fact, we ought to disallow all reserved and unsafe url characters from being entered as a pages url.   I think I would try to do this at the API level.

http://www.blooberry.com/indexdot/html/topics/urlencoding.htm

**Comment by dsilvam** [comment]
I added an extra condition in this line: https://github.com/dotCMS/core/blob/master-3.1/src/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L3672 
to check if the identifier.getAssetType is 'htmlpage', because it was saying that a page with the given url already existed but actually was a folder. 

Apart from that, I tested trying to save the page with invalid URIs and it didn't allow me, so it seems to be working good : http://screencast.com/t/1YQHZM3J

**Comment by bryanboza** [comment]
Fixed, tested on master-3.1 // H2 // FF

**Comment by john-thomas-dotcms** [comment]
This appears to be back, in both 3.7.1 (demo.dotcms.com) and 4.0.

The following folder name was created without problems in both: `test-2&$/+`.

**Comment by john-thomas-dotcms** [comment]
Note: This is actually a problem with folder URLs, not page URLs.  But it's essentially the same problem, since it invalidates the URLs to all pages and files in and below the folder.

**Comment by john-thomas-dotcms** [comment]
Created a new issue instead: https://github.com/dotCMS/core/issues/10858
