### ISSUE TITLE
Enhancement: Rethink "Max. Contents" field in new container dialog

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#6894]
When we train our clients on container creation in dotCMS, there's one thing that always trips them up: the fact that in order to select content types to go into the container, they have to first change the "Max. Contents" field from its default of 0. This is neither obvious nor clear.

Some possible alternatives:
- Add an "update" button next to the "Max. Contents" field as a call to action. (This is much more visible than the current Javascript onChange listener.)
- Add a checkbox or a pair of radio buttons to allow the user to specify whether this container can take contents or not. Show or hide the "Max. Contents" field as appropriate and don't let the field accept "0".
- Let every container have a "Code" field to define what the container displays if it doesn't have any contents. If the container does have contents then those would be shown according to specific code as at present.

**Comment by jtesser** [comment]
option 2 isn't terrible but i don't think this is a big deal

**Comment by john-thomas-dotcms** [comment]
I agreed this is confusing.  We see this in training frequently, and another user just posted an issue on the user forum with the same problem (they didn't know how to get the container to show the pre-loop and post-loop and content types).

Since containers that accept content are more common than containers that don't accept content, and confusion about _not_ seeing the pre-loop and other fields is (much) more common than confusion about how to hide those fields, I think it would be simple to solve the problem by just changing the default number of contents from 0 to a small number (like 5).
