### ISSUE TITLE
Unable to preview html page as limited user

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6921]
After you assign any html page to some workflow, when you login as the assigned user, we are having problems to open the page preview... 

To reproduce: 
- Crate a new html structure 
- Create a new page and assign to some user or role... (chris publisher)
- Login as Chris and try to open the page preview

Here the log: https://gist.github.com/bryanboza/0be20620ac95420a9da1

Tested on master-3.1 // H2 // FF

**Comment by jcastro-dotcms** [comment]
The problem was caused by the user not having permissions on the page that is part of the workflow. If that's the case, an error message will be displayed stating the reason. Please make sure you give the user the necessary permissions to view/approve the page.

PR: https://github.com/dotCMS/core/pull/7026

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-01-20 // H2 // FF
