### ISSUE TITLE
Osgi plugins issues in 3.1

### ISSUE THREAD

**Issue by prasadbhvn** [dotCMS/core#6977]
Tested Win7//Chrome//H2DB

1. com.dotcms.override,
Getting errors while uploading the plugin, Please see the error https://gist.github.com/anonymous/357c0179708d698941df .
2. com.dotcms.custom.spring,
 This plugin works well when we restart the Framework otherwise getting below errors
 https://gist.github.com/anonymous/4eda38ab7c86112b64fb

**Comment by jgambarios** [comment]
QA: In order to compile the Custom Spring example you will need some recent changes we made and those changes are not yet in Artifactory, so please use this modified version of the build.gradle:

http://paste-dotcms.appspot.com/view/ag5zfnBhc3RlLWRvdGNtc3IOCxIFUGFzdGUY0cSMBAw

Changing the line 12 pointing to a folder where a newer version of the dotcms jar lives.

**Comment by brentgriffin** [comment]
QA: do not test until this is updated in artifactory.  For this issue to really be fixed from a customers point of view, the changes need to be in artifactory.

**Comment by bryanboza** [comment]
Tested making the changes that @jgambarios suggest and works fine, but maybe need be retested after add the 3.1 version in the artifactory....

Tested on nightly build 2015-03-03 // Postgres // FF
