### ISSUE TITLE
Page refresh does not select the proper tab for the loaded portlet

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7002]
Related to #6950 

Using the same steps from the last issue when you refresh the page, now the system is continuing highlighted a different tab...

SC: http://screencast.com/t/GAmlpbEpbVoR

Tested on nightly build 2015-01-16 // H2 // FF

**Comment by jtesser** [comment]
@bryanboza please test this with the latest nightly on the site.  Or on monday. I don't think you have the right nightly build

**Comment by jtesser** [comment]
maybe a browser cache doing something weird. Lets just verify on monday and if still an issue we will relook

**Comment by bryanboza** [comment]
Tested in the latest nightly and cleared the browser cache and have the same problem... See the SC: http://screencast.com/t/du9zu4jQ

**Comment by jcastro-dotcms** [comment]
I am not able to reproduce the issue. Here's the list of steps I followed:

1. Logging in as admin, go to System > Roles & Tabs.
2. On the left pane, click System > CMS Administrator.
3. On the right pane, click the CMS Tabs tab and click the System entry at the bottom of the table.
4. In the modal window, in the Tools dropdown and lookup the "ES Search Portlet". Click Add and then Save.
5. Go to System > ES Search Portlet.
6. The selected tab is "System", even after refreshing the page.

I went through these steps with @bryanboza and he was not able to reproduce the issue either. This was probably caused by some weird caching issue.
