### ISSUE TITLE
"Remote publish page" is not working

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7019]
When you create an html page and open it in Preview, the option "Remote Publish Page" is not pushing the page to the remote server.

To reproduce:
1) Set up a push environment
2) On the sender, create a "test folder" and a "test html page” in it
3) Add some content and publish the page
4) Open the page on Preview and select the option “Remote Push Publish" on the left pane
You will see the push has failed on the receiver

Test info:
Sender: Linux // H2 // Chrome
Receiver: MacOS // H2 // FF
dotCMS version: 3.1 nightly build (2015-01-16 22:54)

Log (receiver): https://gist.github.com/shayngr/92df31d629e3c2269594

![remote publish](https://cloud.githubusercontent.com/assets/8741846/5821574/c155d464-a092-11e4-971d-06d218070c28.png)

**Comment by jtesser** [comment]
I think the issue here is the dependency manager. 

I think the folder is not being added when it is new and the page is being pushed which is under that folder and also new.

**Comment by jcastro-dotcms** [comment]
I was able to reproduce the issue and talked to Shay about the way the push publish was being kicked off. The problem stemmed from not using the "Force Push" option. Here's the list of steps:

1. In the sender, create a brand new folder and a content page inside.
2. Push the page (the bundle will also include the containing folder, "Force Push" is not required since these structures haven't been previously pushed to the receiver).
3. The page and folder show up in the receiver. Now, MANUALLY DELETE the folder.
4. Go back to the sender and push publish the page one more time WITHOUT checking the "Force Push" option.

The folder was not updated at all since the last time the page was sent, it still has the same name and properties. Therefore, the folder reference is not included in the bundle (the dependency is not added) which is correct. Repeating the steps but CHECKING the "Force Push" option will include the containing folder, and the issue will not be present.

**Comment by shayngr** [comment]
Working as expected.
Tested on:  3.1 Nightly build 2015-01-21 22:52 // Ubuntu 14.04 // Postgres // Chrome

**Comment by shayngr** [comment]
Added to test rail: http://qa.dotcms.com/index.php?/cases/view/52925
