### ISSUE TITLE
We are adding a "/" at the end of the URL in the virtual links

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7195]
Right now we are unable to resolve virtual links URL, this because the system is adding a "/" at the end of the URL when you try to open it... Then looks like a folder and not as a html page 

To recreate: 
1- Add a new link referenced to a new html page,  and enable the show on menu property 
2- Go to front end and try to open 
3- Check the URL

Tested on nightly build 2015-02-04 // H2 // FF

**Comment by jcastro-dotcms** [comment]
I validated this with @bryanboza, and Virtual Links are working as expected. The confusion is related to the fact that the demo site in the local development environment and nightly builds are pointing to http://demo.dotcms.com (which is an active domain), and is running version 3.0.1, not 3.1.

Therefore, when you create a virtual link selecting "Internal Link" as the Type value, the complete URL is pointing to http://demo.dotcms.com, not localhost. So two things happen: (1) the test page evidently only exists in localhost, and (2) the new content pages allow no extension in the URL, but this is not the case in 3.0.1, which is why the browser is adding the slash to the URL trying to resolve to a folder when hitting http://demo.dotcms.com.

Here's the list of steps to create a working Virtual Link in the local environment:

1. In the Site Browser, right-click "demo.dotcms.com" site to edit it, and change the "Host Name" value to "localhost:8080".
2. Create an example Content Page.
3. Go to the Links page to add a link. Select "Internal Link" as the "Type", browse and select the test content page you just created, and, for example, add it under the folder "/about-us" .
4. Go to the front-end. Hover over the "About Us" navigation menu, and click the virtual link you just created.
5. The test content page is showing up as expected.

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-02-06 // H2 // FF
