### ISSUE TITLE
EsSearch does not respect permissions

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7397]
When you do a content pull using the new EsSearch it does not add the permission filter properly.

Additionally, I am not sure that a post filter will work for facets. See:

http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/search-request-post-filter.html

**Comment by jtesser** [comment]
here you can see the issue: http://starter.dotcms.com:8080/news-events/news/news-by-location

**Comment by jtesser** [comment]
the issue was the loggedInSiteUser role was being treated as CMS Anonymous role. They are not the same.  This was true even for a normal pull content on the front end.

**Comment by jtesser** [comment]
@jgambarios as we discussed bring in the commit from here https://github.com/dotCMS/core/issues/7427

**Comment by jgambarios** [comment]
In order to connect ES trow http was require to add a new property ```es.http.cors.enabled``` added in the latest versions of ES.

```
http.cors.enabled

Enable or disable cross-origin resource sharing, i.e. whether a browser on another origin can do requests to Elasticsearch. Defaults to false.
```

By default it is **false**

In order to support ES http requests now we have to enable these two properties:
```
es.http.enabled=true
es.http.cors.enabled=true
```

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-http.html

Probably this change should go to our documentation.

**Comment by bryanboza** [comment]
Tested on nightly build 2015-03-12 // Postgres // FF
