### ISSUE TITLE
Documentation: "An Page"

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7479]
In several places in http://dotcms.com/docs/latest/, the phrase "an Page" occurs. This should be "a Page".

**Comment by jtesser** [comment]
ok i am going to close and mark as needs doc. @DeanGonzalez

**Comment by DeanGonzalez** [comment]
Fixed - Thanks Kivi

**Comment by DeanGonzalez** [comment]
Fixed in three different docs - thanks for the heads up Kivi!

On Wed, Mar 18, 2015 at 1:05 PM, Kivi Shapiro <notifications@github.com>
wrote:

> In several places in http://dotcms.com/docs/latest/, the phrase "an Page"
> occurs. This should be "a Page".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/7479>.
>



-- 
Thank you,

Dean Gonzalez
General Manager, dotCMS Costa Rica
Training Manager



Eurocenter Diursa
Primer Etapa, Piso 2, Oficina dotCMS
Barreal de Heredia, frente a CENADA
Heredia, Costa Rica
Main: 305-900-2001 | Direct: +506.6185.7137

dean@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>
