### ISSUE TITLE
Tag Storage is not showing new site's tag repo

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#7524]
Tag Storage only displays "All Sites" and not the tag repo of new sites

To reproduce:
1-Login with admin
2-Go to System tab > Sites
3-Create a new blank site or copy an existing one
4-Once the site is created, right click it and Edit the site properties 
5- Click on Tag Storage drop down. You will not see the new site tag repo listed 

![tag repo1](https://cloud.githubusercontent.com/assets/8741846/6852006/e95c77d6-d3a7-11e4-9b08-954da62d33a8.png)

No tag repo created for new sites

![tag repo2](https://cloud.githubusercontent.com/assets/8741846/6852014/fcde397a-d3a7-11e4-95f3-9e070e6b6468.png)

Tested on: 3.2 Nightly build 2015-03-24 22:16 // Ubuntu 14.04 // Postgres // Chrome

**Comment by shayngr** [comment]
It's working fine now, something should have happened with the build

**Comment by john-thomas-dotcms** [comment]
Reopening because this is still a problem.

This happens because the tag repo of a site which is not yet active is not displayed in the **Tag Storage** list (even when editing the site itself).  The site must be currently running (you must **Start** the site and *leave it active*) for the tag repo to show up in the list.  As soon as you **Stop** a site, it's tag repo disappears from the list (even if you already set the site to use it's own tag repo).

This causes a few issues:

**1. If you add content to a site before it's Started, you can't keep the tags in the site's own tag repo.**

So to use a Site's own tag repo, you need to Start the site before adding content (which seems kind of backward).

Note that you can use a trick to get around this (start the site, change the tag repo, then stop the site), it's not something most users will figure out how to do, and opens the door to another issue (see **3.**, below).

**2. The** ***Tag Storage*** **field displays the wrong value while the site is inactive:**

* Start the site.
* Edit the site.
	* Set **Tag Storage** to the site itself (so it has it's own tag repo) and **Save / Activate**.
* Stop the site.
* Edit the site again.
* **Result:** The **Tag Storage** shows **System Host** instead of the site's own Tag Repo.
	* ***But*** - if you continue to add tags on the Site, they will actually still be saved to the Site's own tag repo, rather than to the System Host/global tags.
	* So the displayed Tag Storage location is wrong (showing **System Host** when it's really the site's own tag repo).

**3. The** ***Tag Storage*** **field can be accidentally changed:**

* Start the site.
* Edit the site.
	* Set **Tag Storage** to the site itself (so it has it's own tag repo) and **Save / Activate**.
* Stop the site.
* Edit the site again:
	* Change any field *other than* the **Tag Storage** field and **Save**.
* **Result:** The Site's **Tag Storage** field is now *actually* changed to **System Host**.
	* If you continue to add tags on the Site, they will now be saved to System Host/global tags.
	* Even though that was not the purpose of the edit, and even though you never edited the Tag Storage field.

**Comment by brentgriffin** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/886
