### ISSUE TITLE
The multi language URL-Maps are not working as expected

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7553]
We are having problems with the multi language url maps, because when you try to go to any url different to the default language, we have a 404 error page... The system is not finding for content.... 

URL Maps should work as the documentation states on this page: http://dotcms.com/docs/latest/MultilingualURLMaps

Here the SC: http://screencast.com/t/JPIr9nyRQ

Tested on nightly build 2015-04-01 // MSSQL // FF

**Comment by jtesser** [comment]
@DeanGonzalez @brentgriffin @bryanboza I think the doc is misleading here. 

Here is the deal on how this works 
1. it will use the passed in language meaning ?language_id=2
2. it will use the language set on the session cause once you pass in language_id=2 it stores on session

Our doc currently says 
"If the url mapped pattern refers to a Spanish contentlet, then Spanish is set in the session, and the page is displayed.  If the same pattern is requested, but ends in a reference to a French contentlet, then the session will be set to French, and the page is rendered in French."

This needs to be changed

**Comment by wezell** [comment]
This actually used to work differently - and worked like it said in the doc.  Dean and I had a long discussion about it and there are a lot of different cases.  I think the best way to handle it is to set the variable of the language using the language id of the urlmap unless the language is specified as a request parameter.  Otherwise, a user cannot "share" a link to a multilingual piece of content using just the url map.

See issue #2507 for more information.

**Comment by jtesser** [comment]
Well and then there is this one which is what I was going off of https://github.com/dotCMS/core/issues/2997

**Comment by DeanGonzalez** [comment]
both cases are valid, maybe a config to let the client decide how they want url map to work?

**Comment by shayngr** [comment]
Added TC http://qa.dotcms.com/index.php?/cases/view/61333

**Comment by brentgriffin** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/142
