### ISSUE TITLE
Enhancement: group field types together

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#7610]
When you add a field to a content type, you are presented with an alphabetical drop-down list of values for "display type". As noted interaction designer Jakob Nielsen [points out](http://www.nngroup.com/articles/alphabetical-sorting-must-mostly-die/), alphabetical ordering is rarely the best choice.

One possible alternative is as follows. I've tried to put the field types that we ourselves use the most at the top, but you'd have to perform wider usability testing to know if that's actually the best.

Text
Textarea
WYSIWYG

Checkbox
Radio
Select
Multi Select

Image
File
Binary

Category
Tag
Key/Value

Date
Time
Date and Time

Line Divider
Tab Divider

Site or Folder
Permissions Field
Relationships Field

Constant Field
Hidden Field
Custom Field

**Comment by jtesser** [comment]
@fishsmith @ggranum any thoughts here?

**Comment by ggranum** [comment]
Is this an auto-complete / auto-filter dropdown-textbox combo? If not, it probably should be. More than about 5 choices in a drop down is annoying no matter what.

When using keyboard nav, tabbing to a normal Select allows a power user to type the key corresponding to the first letter of the entry they are interested in. If multiple entries start with that letter then typing it again jumps to the next letter. Try it on a list of states or countries - I habitually type 'o' three times, and if the selection is 'ontario' I press 'o' once more and Oregon is selected. Does this behavior still generally work if the Select options aren't alphabetical? I don't know. But, if not, I feel that preserving such keyboard behaviour is more important that ordering, in this particular case - unless we can add a 'most used' user preference and make that the primary sort, with alphabetical as secondary.

Otherwise I'd leave it as is and focus on addressing the usability of the entire workflow, not just this isolated interaction therein. Unless there's a specific request from one or more customers for whom it's causing real pain.

**Comment by fishsmith** [comment]
Yes, it is an auto-filter box.  I do like the way he grouped them. Personally I feel that auto filtering and alphabetical listing only works well if the user knows the name of what they are looking for, I'm not sure in this use case most people will know the exact name of the field type. 

I think the grouping make it more scannable, but I also agree with Geoff that the filtering is important too. Not sure we would want to lose that in order to get the groups.

**Comment by jkshapiro** [comment]
Right, I'm not convinced a single list is appropriate either. I'm envisioning maybe a popup dialog with a grid of items, so people can take advantage of 2-D positional memory. Yes keyboard shortcuts should be supported for convenience and also accessibility.

Absolutely agree about improving usability of this and every workflow. I see this as one way to do that, and I've entered some other enhancement requests with the same purpose. Anything else I can do to help I'd be happy.

**Comment by jkshapiro** [comment]
"Does this behavior still generally work if the Select options aren't alphabetical?"
Yup.
