### ISSUE TITLE
Sporadic copy host failures with mysql and oracle only

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#7693]
Originally encountered this issue with automated jenkins testing running in aws but have also been able to reproduce locally with mysql.

With postgres I was able to copy the m.qademo.dotcms.com host 30 times without any failures.  With mySQL, I had 7 failures with 30 attempts.  You can see the first five failures here:
![image](https://cloud.githubusercontent.com/assets/3208956/7497644/6ed4b49c-f3e1-11e4-9999-7748a364175b.png)

I have verified that in every case the schedule task method is successfully called and executed completely in QuartzUtils: https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/quartz/QuartzUtils.java#L431
However, when the copy host fails it is because the quartz job is not run.  This method is not called:  https://github.com/dotCMS/enterprise-2.x/blob/master/src/com/dotcms/enterprise/priv/HostAssetsJobImpl.java#L87

To verify this, you can see at the bottom of this screenshot, each of the seven failures has a quartz job that did not run and therefore the copy of the host was not done:
![image](https://cloud.githubusercontent.com/assets/3208956/7496778/e5b042e4-f3db-11e4-94a9-fde08c3d8d05.png)

**To recreate:**
1.  Replace starter.zip with 3.2_qastarter_v.0.4b.zip (or upgrade starter from 2.5.2)
2.  After creating and configuring mysql db, start server 
3.  Activate a license so that the copy host feature will be available
4.  In backend go to System->Sites screen and click "Add Site" button on upper right
5.  Select "Copy an existing site" and click "Next"
6.  Select "m.qademo.dotcms.com" (or "m.demo.dotcms.com" if you upgrade from 2.5.2 starter yourself) and click "Next"
7.  Enter host name of your choice - i.e. test01 and click "Save / Activate"
8.  You are then returned to the list of sites/hosts and should see a progress bar.  If the bar stays at 0%, you have recreated problem, if not, repeat steps 4-7 until problem is recreated - it is sporadic

Log annotated excerpt:  https://gist.github.com/brentgriffin/53ea346a552d029c4d0e

Full log:  https://gist.github.com/brentgriffin/23b57b0dea9e59783fc8

Ubuntu 14.04.2 LTS  //  Java Oracle 1.7.0_80  //  dotCMS 3.2 Release  //  MySQL 5.6.19

**Comment by oarrietadotcms** [comment]
We have, also, seen sporadic problems with the Host Unit Test in our jenkins, for example: https://cb.dotcms.com/view/master-3.2/job/Git_Master_JUnit_Runner_MySQL_3.2_exec/20/

I would guess this bug would be a good reason why we don't see this error every time.

**Comment by oarrietadotcms** [comment]
I did some debugging and the issue is not code related. I read about Quartz configuration and seems we need to increment our org.quartz.threadPool.threadCount. I did that and tried to reproduce the error in 3 different instances with +10 copy hosts and they all worked.

http://www.quartz-scheduler.org/generated/2.2.1/html/qs-all/index.html#page/Quartz_Scheduler_Documentation_Set/re-thr_threadpool_configuration.html

"org.quartz.threadPool.threadCount
The number of threads available for concurrent execution of jobs. You can specify any positive integer, although only numbers between 1 and 100 are practical. If you only have a few jobs that fire a few times a day, then one thread is plenty. If you have tens of thousands of jobs, with many firing every minute, then you want a thread count more like 50 or 100 (this highly depends on the nature of the work that your jobs perform, and your systems resources)."

PR: https://github.com/dotCMS/core/pull/7805

**Comment by bryanboza** [comment]
Tested in the 3.2.1 release, and i am not able to recreate.... Need @oswaldogallango start to work with this release to see if works with the automated test....
