### ISSUE TITLE
Unable to delete a single language version of html page 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7844]
Related to #7521 
We are unable to delete just a single language version of any html page, E.g If you create a new page and create versions in spanish and french to this page, when you try to delete just the spanish version the system is deleting the three versions... 
To recreate: 
- Create a new html page 
- Create a spanish version of this page 
- Try to un-publish, archive and then delete the spanish version 

We are deleting completely the page.... All the language versions 

Tested in the last nightly // MySQL // FF

**Comment by jtesser** [comment]
1. delete https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/portlets/browser/ajax/BrowserAjax.java#L1518 which should make it work as we discussed like the content search manager
2. Even if ALL languages are archived the content fails to validate and delete. This needs to be fixed in this method https://github.com/dotCMS/core/blob/master-3.2/src/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L1149
The condition is wrong.   It needs to check for other languages that have a non archived version.

**Comment by rogelio-blanco** [comment]
PR #8081
