### ISSUE TITLE
Error on log when you search content to reuse without select the structure 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7900]
Now we have the option to reuse content from multiples structures, but if you try to search by any content in the reuse window, without select the structure we are having the follow error in the log:
```ERROR ajax.ContentletAjax: An invalid structure inode =  "" was passed```

Maybe we need a validation here to indicate we need select any content type before make any search...
![2015-06-26_1528](https://cloud.githubusercontent.com/assets/2641437/8387727/49c8a230-1c18-11e5-8342-b5695d6639dd.png)
Tested on 3.2.2 // Postgres // FF

**Comment by wezell** [comment]
I think it should default to "all" like the content search screen.

**Comment by rogelio-blanco** [comment]
In order to enable "ALL" option in this window we need to do some refactor in the code because when the user selects "ALL" we need to show ONLY those "content types" allowed by the container and not just ALL the "content types" of the complete system.   Maybe we can do this as an enhancement in a different ticket.

The fix will be select the first "Content Type" that is in the combo and make the field required.

**Comment by rogelio-blanco** [comment]
PR #7925

**Comment by shayngr** [comment]
Fix is working. The combo box selects the first "Content Type" in the list
Tested on:
dotcms 3.3 build
Win7 Pro SP1
SQLServer 2012
Firefox
