### ISSUE TITLE
Documentation: JSONTool

### ISSUE THREAD

**Issue by jkshapiro** [dotCMS/core#8027]
Add information to http://dotcms.com/docs/latest/JsonTool regarding /limit parameter, per http://javaninja.net/2015/02/getting-dotcms-json-api-to-return-more-than-10-rows/

**Comment by john-thomas-dotcms** [comment]
It looks like the /limit parameter isn't the right way to limit content with the JsonTool, since the JsonTool is often used with 3rd party JSON APIs, but the /limit parameter only works with content fetches from dotCMS. So I added a short section/reminder to the JsonTool docs about how to limit the results using velocity code.

**Comment by john-thomas-dotcms** [comment]
Note: The /limit parameter is currently documented on the Content API page (http://dotcms.com/docs/latest/content-api). Is this enough, or do you think it also needs to be documented somewhere else?

**Comment by jkshapiro** [comment]
This is great, much appreciated.
