### ISSUE TITLE
Adding a relationship to content via Content API erases all existing relationships

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8088]
Recreated this bug on dotCMS 2.3.3 and 2.3.4

When relating two different content types via REST Content API method recommended here in our docs:

http://dotcms.com/docs/latest/save-content-using-rest-api

the existing relationship is destroyed instead of being appended:

Here is a screencast to show/explain: http://screencast.com/t/AM2A2C3I

Here is the Content API form code: https://gist.github.com/DeanGonzalez/89f3c7e383aa30a6043d

I also have a bundle that will upload everything to a 2.3.4 instance (current demo site).  If needed, I can pass it along for expedient testing/verification.

We need to give form creators a way to append instead of wiping out existing relationships.  This will be the expected default behavior for a form creator

**Comment by jtesser** [comment]
Right for this the API requires u to pass in all relationships.  You need to get the current ones.  It isn't an append. Maybe we could add another method but this is currently how it works and how our APIs work

**Comment by jkshapiro** [comment]
But it should be an append. Until this bug is fixed, we're going to have to write extra code to obtain the current set of relationships for a contentlet just so we can write them back to the content store again. We don't mind writing code but this is a make-work project.

On top of that, this unnecessarily increases data traffic and slows responses. For users on a slower network (e.g. mobile users on a 3G cellular connection, or geographically remote users on dialup), this can be noticeable and an impediment to user experience.

The Content API is a good thing but gotchas like this will do nobody any good.

**Comment by wezell** [comment]
I get the use case, but thinking about more than one case, how does one remove a relationship (someone removes a product from their cart)?   How would one reorder related contents?    Feels like there needs to be a relationship api endpoint.

**Comment by dsilvam** [comment]
The current (passing all the relationships) is the correct behaviour, POSTs are supposed to be Idempotent, meaning it can be called many times without different outcomes. Will's suggestions looks like the way to go, having a relationships api endpoint where you can sent POSTs to create new relationships

**Comment by jkshapiro** [comment]
Please expand re. idempotency? Since two contentlets can only be either related or not related, it's not clear how defining the same relationship multiple times (or not) makes any difference.

Relationship API endpoint would be a good thing. When designing please consider other potential enhancements to relationships such as #7947.

**Comment by brentgriffin** [comment]
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/141

**Comment by dsilvam** [comment]
@jkshapiro you are right about Idempotency. Thing is when you PUT (update) a resource, you should be able to GET that same resource and have it look exactly like what you had just PUT. This wouldn't be the case if we appended the relationships when updating the content. +1 for RelationshipAPI
