### ISSUE TITLE
[core] Push Pub: Bundle hangs when too large - Update column size in publishing_queue_audit table

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#8092]
Reported by a client running 3.2.1
Internal ticket: https://my.dotcms.com/ticket/dotcms-89

Push publishing a bundle containing a large amount of contentlets fails, leaving the items on the pending queue and not updating the status/history tab. This blocks future pushes.

**Comment by aotearoan** [comment]
+1

**Comment by wezell** [comment]
FYI: this is a MySQL only issue.

**Comment by jtesser** [comment]
simply for MySQL need to get an upgrade and update the sql file to a longtext

**Comment by joseorsini** [comment]
Updated reference in our Support Portal ticket. https://my.dotcms.com/ticket/dotcms-89

**Comment by joseorsini** [comment]
Another improvement for clients with MySQL Databases that are using Push Publishing: 

Push Publishing jobs are failing because of restrictions set at database level. Once a folder is updated, the rename_folder_assets_trigger is called, and depending on the length of the folder's parent_path, it can cause issues. Currently, the trigger handles paths with <=100 characters of length, but as per client's data (see Support portal ticket), these paths can be longer. 

These triggers have the same path length limitation for other RDBMS. 

Trigger definition in MySQL: 
https://github.com/dotCMS/core/blob/b09a409cbf32ea0e552f810d99a3c149b04eb630/src-conf/mysql.sql#L2844-L2862

Stacktrace: 
https://gist.github.com/joseorsini/1d8f33b0c8393aa7fbc5cbe9bbdc06c0

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/8915
