### ISSUE TITLE
Push publishing overwrites the site aliases in target site

### ISSUE THREAD

**Issue by aotearoan** [dotCMS/core#8125]
Hi, we have an issue with push publishing overwriting the aliases of the target site sometimes when we change and push even a single item of content. We have a 3 site setup
 - publishing pushes to staging
 - staging pushes to prod

Here's what happened:
1. I made a change in a single vtl file and uploaded this to publishing via webdav
2. I push published the single vtl file to staging
3. I push published this change from staging to prod
4. the alias in prod was changed to common-website-publishing.fpprod.corp (the publishing site alias)
5. grepping for "website-publishing" in the bundle turned up these results:

./ROOT/application/570a26d6-408d-4405-a492-b35f353ad87f.folder.xml:        <string>common-website-publishing.fpprod.corp</string>                  
./ROOT/application/themes/ltq-global/4026c75e-e19f-4022-87de-7bac6b7bb3e5.folder.xml:        <string>common-website-publishing.fpprod.corp</string>
./ROOT/application/themes/9024985c-3d87-423c-b07e-ff9a7751c1af.folder.xml:        <string>common-website-publishing.fpprod.corp</string>           
./ROOT/2e9bc260-3399-4930-856a-19e9f40b6542.folder.xml:        <string>common-website-publishing.fpprod.corp</string>                              
ROOT/application/570a26d6-408d-4405-a492-b35f353ad87f.folder.xml:        <string>common-website-publishing.fpprod.corp</string>                    
ROOT/application/themes/ltq-global/4026c75e-e19f-4022-87de-7bac6b7bb3e5.folder.xml:        <string>common-website-publishing.fpprod.corp</string>  
ROOT/application/themes/9024985c-3d87-423c-b07e-ff9a7751c1af.folder.xml:        <string>common-website-publishing.fpprod.corp</string>             
ROOT/2e9bc260-3399-4930-856a-19e9f40b6542.folder.xml:        <string>common-website-publishing.fpprod.corp</string>                                

5. I fixed the alias manually in both staging and prod
6. I made another change to the same vtl file and uploaded to publishing via webdav
7. I pushed this change to staging and then prod
8. This time the alias was unchanged
9. grepping for "website-publishing" in the bundle there were no results.

So it seems we have this issue when there is a ROOT folder in the bundle with details of the host including the aliases.

I would expect push publishing not to propagate the aliases at all. I would also expect the push publishing to be deterministic which is clearly is not.

This is a very critical bug in push publish and we cannot go live until it is fixed without the risk of our production site breaking any time we push content.

We are using dotCMS 3.2.1.

**Comment by jtesser** [comment]
this isn't a bug.  When a file is pushed it gets it dependencies like a host. So if you alter the host it will get pushed when pushing a file or other child of that host. Maybe keep both aliases for DNS purposed and control at firewall/lb

**Comment by aotearoan** [comment]
This is a bug - I can push a single vtl change TWICE, the first time the host aliases are updated, the second time the host aliases are unchanged. Is that really expected behaviour?

Please reopen.

**Comment by jbjornson** [comment]
Regardless of what the desired outcome is, surely consistent and deterministic behavior should be expected.  Having it behave differently on different invocations is clearly a bug, right?

**Comment by levosgien** [comment]
The expected behavior here is that the host be updated (alias, name, and other properties) as the rest of your data, meaning not directly in prod but from the sender. Therefor any alias change would be made on your sender(s), and pushed along with any VTLs that need to move over and which reside on that host (saved on it).

In the behavior above if I understand correctly the host alias was changed at the prod level directly, which resulted in mismatches and "data integrity" discrepancies between that same host in prod/staging. This is your issue right there if that is the case.

Remember, in push publishing you want one unique source for your data as to avoid data integrity issues.

Feel free to submit a support ticket for further clarification on the recommended process as changing aliases and updating VTLs multiple times is something that works consistently.

Thank you.
