### ISSUE TITLE
Display workflow step on content search screen

### ISSUE THREAD

**Issue by aotearoan** [dotCMS/core#8126]
When using workflows it would be useful to see the workflow step in the content search listing. It would also be useful to be able to filter by workflow step.

**Comment by jtesser** [comment]
FWIW if the Workflow is mandatory you can see it by right clicking on the content.

**Comment by aotearoan** [comment]
That doesn't help with filtering...

**Comment by john-thomas-dotcms** [comment]
+1 this would be very useful; it's a pain to have to open each item to see what step it's in, and it would be very useful for admins and managers to be able to sort and filter by workflow step.

Note also that right-clicking shows the actions available, but doesn't show what workflow step the content is in.  So that only helps if the user has memorized what actions are available in each step to figure it out.
