### ISSUE TITLE
UI should not use colors as only indicators for values

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#8144]
We have a number of areas in the UI that use colors (typically reg/green/yellow traffic lights) to indicate field values, some for fairly critical pieces of information including contentlet published status, content index status, and audit log status. This is not accessible to color-blind users, which account for about 6% of male population. Unique icons (fontawesome, etc), text values, or even alt text should be used in lieu of colors.

**Comment by john-thomas-dotcms** [comment]
I agree, and I'd add that if we expect any non-native English speakers to use the UI then a combination of easily differentiated colors and unique symbols (rather than text) is generally considered best practice. Text is a helpful addition (either as on-screen labels or hover text), particularly for new users.
