### ISSUE TITLE
Editing Child Folders results in "Folder already exists" error

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8155]
Tested on dotCMS 3.2.4 on two separate servers, including demo.dotcms.com

It is not possible to change the name of a child folder.  Parent folders can be edited, but not child folders.

To reproduce:
1) Create a parent folder
2) Inside the new parent folder, create a child folder
3) Try to edit and change the name of the child folder - results in "folder already exists" error

Screencast: http://screencast.com/t/go9XAtUPY

**Comment by levosgien** [comment]
**Additional Notes:**

ONLY happens when editing TITLE or URL field values.

**Errors in log:**

[29/10/15 09:41:45:285 EDT] INFO ajax.PermissionAjax: ##=> permissionMap: {inode=48190c8c-42c4-46af-8d1a-0cd5db894797, roleId=654b0931-1027-41f7-ad4d-173115ed8ec1, permission=1, id=12221, type=individual, isBitPermission=true}

**Comment by joseorsini** [comment]
Duplicated of https://github.com/dotCMS/core/issues/7793
