### ISSUE TITLE
All Content Searches of FileAsset Metadata fail

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#8156]
In the Content Search screen, all searches in the "Metadata" field fail.

**To reproduce** (_on the demo site or starter site_):
1. Click on Content Search.
2. Select Type "File Asset".
3. Click "Advanced" to show the advanced search fields.
4. Enter "contentType:image/gif" into the "Metadata" field.
Result: "No Results Found"

**Source of the Problem:**
The problem appears to be that dotCMS is inserting backslashes before the colon (:) and the asterisks (*) in the query.  For example, if you click **Search->Show Query** for the above example, the following Lucene Query is shown:
- +contentType:FileAsset +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +FileAsset.metaData.contenttype\\:\\*image/png\\* +languageId:1 +deleted:false +working:true

But when you copy this query into the Query Tool, it fails to return any results.

However if you remove the backslashes from the search (in the Query Tool), the search works correctly:
- +contentType:FileAsset +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +FileAsset.metaData.content:*image/png* +languageId:1 +deleted:false +working:true

**Comment by john-thomas-dotcms** [comment]
Still doesn't work in 3.3 and 3.5.  Guessing this is a fairly simple fix, and it would be good to get this fixed (right now the Metadata field in the Content Search is just useless).

**Comment by joseorsini** [comment]
This is affecting a customer running dotCMS 3.7.1 It also can be reproduced on current 4.1-release repo. 

Support ticket: https://my.dotcms.com/tickets/detail.dot?id=73370db7-29f3-48ee-9e86-8ebac61855a8

**Comment by joseorsini** [comment]
This seems to affect REST API calls. 

https://demo.dotcms.com/api/content/render/false/query/+contentType:FileAsset%20+FileAsset.metaData.contentType:*image/jpeg*%20+languageId:1%20+deleted:false%20+working:true/orderby/modDate%20desc 

This returns zero results, even after applying an Enterprise License. The same query on the Query Tool returns 27 results. 

```
+contentType:FileAsset +FileAsset.metaData.contentType:*image/jpeg*
```

**Comment by joseorsini** [comment]
For REST API calls. 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/ContentResource.java#L400

Problem comes with the contentType attrib from metadata. Since it has a slash `/` this breaks how to pull the query from the PathParam args. 

The original query, sent through this URL 

https://demo.dotcms.com/api/content/render/false/query/+contentType:FileAsset%20+FileAsset.metaData.contentType:*image/jpeg*%20+languageId:1%20+deleted:false%20+working:true/orderby/modDate%20desc 

is this one 

```
+contentType:FileAsset +FileAsset.metaData.contentType:*image/jpeg* +languageId:1 +deleted:false +working:true
```

And debugging the ContentResource class, final query handled by the endpoint is 

```
+contentType:FileAsset +FileAsset.metaData.contentType:*image
```

Again, this is a problem with the slash as part of the query, as reported here. https://github.com/dotCMS/core/issues/9857

**Comment by dsilvam** [comment]
Note to QA: please re-test original issue: https://github.com/dotCMS/core/issues/6369
