### ISSUE TITLE
Cannot set the Default Language to other language like Traditional Chinese

### ISSUE THREAD

**Issue by allychan** [dotCMS/core#8372]
Is there a way to set the default language to Traditional Chinese? To show content in Chinese.

We got referenced from this site (http://forumarchive.dotcms.com/Default-Language-Setting-td5442673.html) but still not work.

We changed the code of language from 
     "CHARSET = text/html;charset=UTF-8
     DEFAULT_LANGUAGE_COUNTRY = United States
     DEFAULT_LANGUAGE = en_US
     DEFAULT_LANGUAGE_CODE = en
     DEFAULT_LANGUAGE_STR = English
     DEFAULT_LANGUAGE_COUNTRY_CODE = US"
To
     "CHARSET = text/html;charset=UTF-8
     DEFAULT_LANGUAGE_COUNTRY = Hong Kong
     DEFAULT_LANGUAGE = zh_HK
     DEFAULT_LANGUAGE_CODE = zh
     DEFAULT_LANGUAGE_STR = Traditional Chinese
     DEFAULT_LANGUAGE_COUNTRY_CODE = HK"

After we changed the language code, the website fail to load vtl files and only display text in inner page and display error 404 in homepage.

Thanks.

**Comment by levosgien** [comment]
Hi, what is you "DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE=" property set to? Try to set it to "true" so that if it doesn't find a Chinese version of content it defaults back to English.

We do have clients running default languages other than English so it's either a setting or an issue with the Chinese language specifically.

Take a look at our documentation and email me if you have any additional questions. Thanks.

https://dotcms.com/docs/latest/page-language-configuration

**Comment by allychan** [comment]
Hi, The DEFAULT_CONTENT_TO_DEFAULT_LANGUAGE was set to true, but we can’t load any vtl files in front-end and the error is the dotcms can’t find the vtl path. However, we can found the default language is changed to Chinese in back-end panel.
The process we did 
1. Change the language setting and save the file 
2. Restart the server 

May I know if there any process we missed?

**Comment by jgambarios** [comment]
@allychan I think we can move this conversation to our community group as we use github just to report bugs but let me help you here: when you changed your language to **DEFAULT_LANGUAGE = zh_HK** along with the other properties that's the right way to change the default language, the problem here is that all the widgets are already saved in English, so when you are trying to reach them using the default language the widgets are not found, the system is trying to find them in Chinese, you must change them manually to your default language in order to use them properly.
