### ISSUE TITLE
Problems after change the relationship cardinality in structures  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8567]
Related to #6753 

We have some problems after change the relation cardinality using between two structures... This because we are not validating if the existing data is violating the conditions of the new relationship...

To Recreate: 
- Create a new structures A and B
- Create a new relationship "many to many" 
- Create 2 new contents in the structure B
- Create 2 new contents in structure A and relate both with the two contents of the relation B
- Go to the structure relations and change the type to "one to many"
- Try to edit any of the contents of the structure A and click in save and publish

We are having an error because one "child" content must have just one parent, and we aren't validating this case when change the relation type...

Here the error: 

```
[03/02/16 11:30:55:437 CST] ERROR business.ESContentletAPIImpl: Contentlet's fields are not valid
[03/02/16 11:30:55:437 CST] ERROR business.ESContentletAPIImpl: com.dotmarketing.portlets.contentlet.business.DotContentletValidationException: Contentlet's fields are not valid
List of non valid relationships
BADCAR: Parent-Child, 
```

**Comment by jcastro-dotcms** [comment]
This issue has also been reported via Support: https://my.dotcms.com/tickets/detail.dot?id=4231c25b-114e-4b53-91ed-edb8be6d8e3f

**Comment by john-thomas-dotcms** [comment]
Two things:
1. This issue shows up in the starter/demo site (see below).
2. This issue appears to happen because, when you change the relationship from M-N to 1-N, some relationships are duplicated (see below).
    * You can prevent this error by manually removing the duplicate relationships.

## 1. Starter Site Shows the Problem

You can not make changes to any of the content items of the following content types on the starter site that have comments associated with them:

* News
* Blog
* Comments

Since these relationships appear to have been changed from M-N to 1-N at some point in the past, all existing content of these content types have this problem.

## 2. Duplicated Relationships

However also note that if you view the "Relationships" tab on any comment on the starter/demo site, the Comment contentlet shows 2 relationships to the same piece of content - which is why there is a constraint violation.

I verified that the duplication happens when you change a relationship from M-N to 1-N.  Steps to reproduce:

1. Create a "Many to Many" relationship between 2 content types (e.g. Products-Comments).
2. Create a relationship between 2 content items of the appropriate content types.
    * If necessary, create a new child content item before relating it to an item of the parent content type.
3. View the relationships in the parent content item and the child content item.
    * Result: Both content items show a single relationship to the appropriate piece of content.
4. Change the relationship to "One to Many".
5. View the relationships in the parent content item and the child content item again.
    * RESULT: The parent content item shows a single relationship to the child content item, but the child content item shows two relationships to the parent content item (two relationships to the same contentlet).
6. Attempt to make changes to the parent content item.
    * Result: You get an error (both in the logs, as mentioned in the bug report above, and in a pop-up window).
7. Open the child content item and manually remove the duplicate relationship.
8. Attempt to make changes to the parent content item.
    * Result: It now works without problems.

## Conclusions/Suggestions:

1. It appears this problem happens because, when the relationship is changed from M-N to 1-N, all existing relationships are duplicated within the child content items (which naturally causes a constraint violation).
2. Even if we don't fix the code that causes this duplication, we should manually remove the duplicate relationships from the starter site, so we don't see this error on the starter or demo sites.
