### ISSUE TITLE
FileAssetMap does not have 'host' field anymore

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#8575]
If you have a contentType with a field of type 'File' or 'Image' and you do  
'$myContent.myImageField' or '$myContent.myFileField', the resulting Map that gets printed does not include the 'host' anymore, so doing '$myContent.myImageField.host' does not print the host identifier.

'host' propery was included in the resulting map in 3.2.4, but it is not since 3.3

This is because the 'host' property does not get copied in this line:

https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/viewtools/content/FileAssetMap.java#L34

It is there in the original object:
https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/viewtools/content/FileAssetMap.java#L30

but it does not get copied to the resulting object:
https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/viewtools/content/FileAssetMap.java#L36

Reproduced in 3.3 and latest master-3.5

**Comment by dsilvam** [comment]
https://my.dotcms.com/tickets/detail.dot?id=dea6be43-2600-4326-89b4-7a9ed3ca29ea

**Comment by wezell** [comment]
Is this a pull request Daniel?

**Comment by dsilvam** [comment]
@wezell I hotfixed for 3.3 by manually copying the host: https://github.com/dotCMS/support/blob/master/hotfixes/hotfix-GIT-8575-v3.3/src/com/dotmarketing/viewtools/content/FileAssetMap.java#L33

but would be worth taking a look about what is going on

**Comment by wezell** [comment]
I think that would be good enough for a pull request, no?  The issue is
that the fromContent method is setting the host as a string on the
FileAsset (which is right) but we want the Host object on the FileAssetMap
front end version.

https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/portlets/fileassets/business/FileAssetAPIImpl.java#L188




On Fri, Feb 5, 2016 at 10:08 AM, Daniel Silva <notifications@github.com>
wrote:

> @wezell <https://github.com/wezell> I hotfixed for 3.3 by manually
> copying the host:
> https://github.com/dotCMS/support/blob/master/hotfixes/hotfix-GIT-8575-v3.3/src/com/dotmarketing/viewtools/content/FileAssetMap.java#L33
>
> but would be worth taking a look about what is going on
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/issues/8575#issuecomment-180393757>.
>



-- 






3059 Grand Avenue
Suite 410-B
Miami FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by dsilvam** [comment]
We want the Host identifier only in the FileAssetMap (like 3.2.4), not the whole Host object:

https://github.com/dotCMS/support/blob/master/hotfixes/hotfix-GIT-8575-v3.3/src/com/dotmarketing/viewtools/content/FileAssetMap.java#L33

fam.setHost(fa.getHost()); 

fa.getHost returns host identifier

**Comment by dsilvam** [comment]
Problem is BeanUtils.copyProperties is not copying the 'host' from the original object :
https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/viewtools/content/FileAssetMap.java#L34

**Comment by dsilvam** [comment]
sent the PR 
https://github.com/dotCMS/core/pull/8576

**Comment by dsilvam** [comment]
Even though still curious on why this used to work in 3.2.4 (String 'host' was copied by BeanUtils.copyProperties) and now it is not
