### ISSUE TITLE
DOTCMS_LOGGING_HOME should be configurable

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/core#8633]
This is the logging base for log4j2, set in https://github.com/dotCMS/core/blob/master-3.5/src/com/dotmarketing/listeners/ContextLifecycleListener.java#L64. This needs to be configurable.

**Comment by john-thomas-dotcms** [comment]
I agree that making this configurable would be good.

*Note that it's possible to change the logging location via the log4j2.xml file, but there are a number of issues with this, such as potential upgrade issues and hard-to-find conflicts with other properties.*

However this also touches on another issue, that customers (and even our own site) frequently have mismatches between the TAIL_LOG_LOG_FOLDER and DOTCMS_LOGGING_HOME properties.  This happens because a change to the DYNAMIC_CONTENT_PATH property automatically changes DOTCMS_LOGGING_HOME, but does **not** change TAIL_LOG_LOG_FOLDER.  This means that when a user changes the DYNAMIC_CONTENT_PATH property, they usually end up unable to see their logs in the dotCMS admin console.

So it would be ideal if, in addition to making DOTCMS_LOGGING_HOME configurable, we also:

1. Remove the TAIL_LOG_LOG_FOLDER property from the properties file (but still allow users to add it if they want to).
2. Change the code so that if TAIL_LOG_LOG_FOLDER is **not** set in the properties file, then it gets automatically set to match the DOTCMS_LOGGING_HOME property.

**Comment by jgambarios** [comment]
PR: https://github.com/dotCMS/core/pull/9940
