### ISSUE TITLE
Display more descriptive asset title in the Status/History tab of Push Publish 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#8705]
When you go to 'Site Browser' -> 'Publishing Queue' -> 'Status/History' the title column shows {asset-type}:{name} for every asset in the Bundle. That information can be ambiguous when assets have the same name but have a different parent, i.e., two htmlpages called 'home' living on different sites/folders will show exactly the same, so there is no way to locate them if needed. 

![00000002](https://cloud.githubusercontent.com/assets/1576794/13500989/790fcece-e12a-11e5-8e59-0652253b9d5d.png)

Enhancement will be to show: full-path-of-asset/asset-name and keep the asset type.

**Comment by john-thomas-dotcms** [comment]
The other thing that's needed here is to show all the assets in the bundle, rather than just the first 3 items.

When you first do a push of a more than 3 assets, both the **Pending** and the **Bundles** tab show all assets in the bundle (with links to each piece of content - which is very nice).  However once the bundle moves to the **Status/History** tab, it only shows the first 3 assets and then **"...X more assets in the bundle"**.  Even if you click on the bundle in the **Status/History** tab to see the **Bundle Detail** popup, all the individual assets aren't shown.

So once a bundle with more than 3 assets has been sent, there is no way to know which assets were in the bundle that was sent.

Maybe the simplest enhancement for both these issues would be to just change the **Bundle Detail** popup in the **Status/History** tab, so it shows all the assets in the bundle, and the full path to each (or a link to each).

**Comment by dsilvam** [comment]
@john-thomas-dotcms +1
