### ISSUE TITLE
Need clear the content references after delete pages 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#8996]
Related to #7512 

After this fix, now we can delete pages in different languages individually, but we are keeping the content references of this pages....

To recreate: 
- Create a new page in the default language (English)
- Add some versions of this page in other languages (ES, FR, DE)
- Create some content to every one of this languages, and add to the page in their respective language 
- Now delete the page in one of the languages (FR)

- Now go to the content management and select the content in the language that you delete the page (FR), In the language properties navigate to the reference tab

We are keeping the reference here, and this page does not exist in this moment, this needs be deleted... 

![r1](https://cloud.githubusercontent.com/assets/2641437/14999727/523b8948-1148-11e6-85f6-d312e047296c.gif)

FYI: Also if you create the (FR) version of the page again, the system is adding the contents of the old page....

Tested on master-3.5 // Postgres // FF

**Comment by shaydotcms** [comment]
Issue persists. 
When you create a page in the same language as the one deleted before (i.e.: if you deleted a page in French named "index", add another page in French with the same name), the system is adding the contents of the old page again by itself.

This happens when you do the following:
- Right click over one of the available pages > Page Properties
- In "Page Asset" dropdown, select French
- Click Yes button in the dialog
- Click Save/Publish
