### ISSUE TITLE
Static/S3 Publishing Overview

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9045]
*Branch core and ee*: static-publishing

## Will use the PPublishing Framework

- Will use the current PP Configuration → Server Model
- At the server level, the protocol becomes a selector
- Setting up a Static Push target would be just like setting up a Server
- Will be built on 3.6
- Ability to statically push to a remote endpoint
- SuperPrime only feature
- Will create an interface `EndPointPublisher` that can be implemented to deliver static site/content to 3rd party endpoints.  The first implementation would be an `S3EndPointPublisher`
- The endpoint publisher will have a at least two methods. In psuedo-code
   - CanConnectSuccessfully
   - PushBundleToEndpoint

## Would be nice to have:

- via OSGI

## Things to note

- Logging deletes including renames within dotCMS and syncing those \(You will need to “push delete”\) in order to delete on the target
- All pushes will respect CMS\_ANON - no limited roles
- Rename = create new \(old persists\) ?? \(same folder inode, maybe not\)
- Static Push is not versioned \(current published only\)

---
![screen shot 2016-12-09 at 10 19 57 am](https://cloud.githubusercontent.com/assets/934364/21055466/6e71c668-bdff-11e6-93df-c2a2ceea070b.png)

**Comment by chrismccracken** [comment]
From https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html, uploadFileList() is probably the most appropriate method to use here for the static publisher.

**Comment by jtesser** [comment]
dotCMS documentation:
https://dotcms.com/docs/latest/time-machine
https://dotcms.com/docs/latest/time-machine-snapshots
https://www.youtube.com/watch?v=NK0r6oUDkHc


AWS documentation:
Static Web Hosting.


Logs:
dotcms.log: Creating Time Machine Snapshot


Source code
List of TimeMachine File Bundlers. 


Step to follow:
Create basic PoC for S3 upload files using AWS SDK in order to have a list of all the things needed like credentials, file paths, etc.
Modify Push Publish UI to include S3 option (See Github issue).
Bucket Name.
AWS Credentials.
Code (See Github issue).
Gradle dependency.
Test, test, test.


Licensing 
Need a 500 level Platform 
Change is in license code https://github.com/dotCMS/license 
Check in EE code Proxy 
Need to update license generation code also to generate a 500 level 
https://github.com/dotCMS/plugin-dotcms-license/blob/master-3.x/src/main/java/com/dotcms/license/servlet/GenerateLicenseServlet.java
https://github.com/dotCMS/SupportPortal/blob/master-3.x/src/main/java/com/dotcms/support/util/LicenseUtil.java#L71
/global/vtl/contractListing.vtl  this is where the form is that submits to the the LicenseUtil on SupportPortal 


Regarding Buckets 
2 ways.  Host is a folder at root of bucket OR bucket is a host 
Make a config option for which to use. bucketIsHostRoot=true|false
Based on option if folder or bucket doesn’t exist create.  Will use naming convention of host name for bucket or folder in bucket’s name
