### ISSUE TITLE
Explicitly close db for jobs/Threads

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9159]
Like #9157, we have jobs/Threads without finally db.close() logic.  

- HostAssetsJobProxy
- EscalationThread
- UpdateContentsOnDeleteHost
- PublishThread, called by RemotePublishAjaxAction
- https://github.com/dotCMS/core/blob/ae72c1bd822523b8a7924c1d0afabe46839977b8/src/com/dotcms/rest/ESIndexResource.java#L67
- https://github.com/dotCMS/core/blob/ae72c1bd822523b8a7924c1d0afabe46839977b8/src/com/dotcms/rest/IntegrityResource.java#L322
- https://github.com/dotCMS/core/blob/ae72c1bd822523b8a7924c1d0afabe46839977b8/src/com/dotcms/timemachine/ajax/TimeMachineAjaxAction.java#L303
- https://github.com/dotCMS/core/blob/ae72c1bd822523b8a7924c1d0afabe46839977b8/src/com/dotmarketing/portlets/contentlet/action/ImportContentletsAction.java#L200

**Comment by nollymar** [comment]
The following functionalities were affected by these changes:
* Import Content
* Integrity Checker (send/receiver hosts)
* Add Bundle

For testing purposes:
- It is important to activate logAbandoned flag in datasource configuration and monitor connections in catalina.out. When testing Integrity Checker, monitor send/receiver hosts logs.
- Execute each functionality many times in order to stress the server and demand more db connections.

The following classes did not required changes: HostAssetsJobProxy.java and EscalationThread.java

**Comment by nollymar** [comment]
Pull request for this task: [https://github.com/dotCMS/core/pull/9190](url)
