### ISSUE TITLE
Vanity URL's lookup by site is not case insensitive

### ISSUE THREAD

**Issue by vianneychacon** [dotCMS/core#9258]
I've seen this problem after migrating a site to version _3.5_. The Vanity URLs continue to be active, they are just not shown on the backend.

Working along with @joseorsini, the lookup should be case-insensitive around [here](https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/virtuallinks/business/VirtualLinkFactoryImpl.java#L56).

**Comment by joseorsini** [comment]
Related to: https://my.dotcms.com/tickets/detail.dot?id=8290033a-5db6-448b-ae92-06ee8513f5a8

Steps to reproduce:

1. Change the Site name from "demo.dotcms.com" to "myDEMO.dotCMS.com".
2. Go to Website Browser and create a test page, e.g., /vanity-page-redirect
2. Go to Vanity URLs Portlet and create a new Vanity URL like the next one

<img width="1374" alt="screen shot 2016-08-08 at 5 08 53 pm" src="https://cloud.githubusercontent.com/assets/1717110/17496340/d36ba1b8-5d8a-11e6-8ee2-58f7aeaa3247.png">

Once it's saved, the message indicating the Vanity URL was saved is displayed, however, nothing is listed there. The new virtual link has the Site name hardcoded in the url field, in lower case

```
# select * from virtual_link;
                inode                 |        title         |                   url                   |              uri              | active
--------------------------------------+----------------------+-----------------------------------------+-------------------------------+--------
 4b8c55de-a9c1-4fd6-ab7b-cb66d574ac6b | 404 Error Page       | companyY.com:/cms404Page                | /demos/404-override-test.html | t
 5dd071ee-699c-43a1-b362-e87416fa740d | News                 | companyY.com:/MyNews                    | /news-events/index.html       | t
 010c3115-1e8a-422f-9991-198f1b7dc2aa | vanity-page-test-001 | mydemo.dotcms.com:/vanity-page-test-001 | /vanity-page-redirect         | t
```

But the lookup in the DB, as @vianneychacon stated in his comment, is case-sensitive, so no results are displayed. If we change the Site name from 'myDEMO.dotCMS.com' to 'myDEMOupdated.dotCMS.com', the Virtual Link definition will remain broken and won't be updated with the new Site Name. 

The only way to bring it back is by changing the site name to an all-lowered case one, which should match the current Url in the DB. Otherwise, the Virtual Links won't be listed.

**Comment by joseorsini** [comment]
PR: https://github.com/dotCMS/core/pull/9525
