### ISSUE TITLE
Content let api don't return relationships

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#9411]
When you do a request with "/api/content/query/<your-query>" the relationships field aren't returned. You should be able to specify a depth up to 2 to pull the content graph.

We need to deprecate the ContentRelationshipsResource as the functionality will be subsumed by this.

**Comment by wezell** [comment]
We need to allow a `?depth=` param (max value = 2) that will return the nested content objects.  
if you don't pass a depth, we return a list of [identifiers] of the related objects 
if you pass  `depth=1` we return the related content objects.
if you pass  `depth=2` we return the related content objects for each of the content.

**Comment by nollymar** [comment]
After these changes, the Contentlet API will return relationships this way:

* when `depth=0`: https://gist.github.com/nollymar/4384e802baad356ac72412d4f888debe
* when `depth=1`: https://gist.github.com/nollymar/cb188607096a9f592a7d5ee4a1ab7518
* when `depth=2`: https://gist.github.com/nollymar/0ae747a7b8c412d83363e7bfdca12af5

**Note: ** In case the `depth` parameter is not sent as part of the request, by default `depth=0`

**Comment by wezell** [comment]
We need to use the field.variable as the property key.
If the remote end of the relationship is `one`, send the entry not an array
not the relation name
e.g. `youtubes`

**Comment by nollymar** [comment]
Implemented here: https://github.com/dotCMS/core/pull/15852/

**Comment by nollymar** [comment]
**Note to QA:** this change was applied on this endpoint: `http://localhost:8080/api/es/search` as well

**Comment by erickgonzalez** [comment]
If depth is set to an invalid value should return 400.
E.g: `depth = 5` or `depth = xyz`

**Comment by bryanboza** [comment]
Ok, tested after the fix and we have some pending changes: 

- [ ] Both endpoints should be able to receive the `depth` parameter. Right now just the `/api/content/query/ ` is able to do it. 

- [ ] The list of relationships should be separated only by (,), right now we are adding `/` 
SC: https://screencast.com/t/ga1aQje9l

**Comment by nollymar** [comment]
New changes implemented here: https://github.com/dotCMS/core/pull/15970

**Note to QA:**

1. `depth` now supports 4 values: 
     *  0 --> The contentlet object will contain the identifiers of the related contentlets
     *  1 --> The contentlet object will contain the related contentlets
     *  2 --> The contentlet object will contain the related contentlets, which in turn will contain the identifiers of their related contentlets
     *  3 --> The contentlet object will contain the related contentlets, which in turn will contain a list of their related contentlets

2. `http://localhost:8080/api/es/search` now supports the `depth` param which must be sent as a query param this way  `http://localhost:8080/api/es/search?depth={depth_value}`

3. `http://localhost:8080/api/content/` supports the `depth` as a path param, so that it must be sent as `http://localhost:8080/api/content/depth/{depth_value}`

4. If the remote end of the relationship is `one` (for One-to-One and One-to-Many cardinalities), an object is returned which could be an identifier or a hydrated contentlet, according to the `depth` value. Otherwise, a list is returned.

**Comment by bryanboza** [comment]
New card reported here #16008...  We can close this one
