### ISSUE TITLE
dotCMS Compatibility Issues with IE 11 (11.0.9600.18314)

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#9422]
1. Selecting Host/Folder does not work always:
   When clicking on the “+” to select some actual asset folders, the pop-up window closes again instead of expanding.

![screen shot 2016-07-26 at 10 11 28 am](https://cloud.githubusercontent.com/assets/1561349/17141219/55c2cca8-5319-11e6-8731-8da97544559d.png)

In Chrome browser, the same function works:
![screen shot 2016-07-26 at 10 11 53 am](https://cloud.githubusercontent.com/assets/1561349/17141245/67b0703c-5319-11e6-917e-ada58761982a.png)

Same Problem seems to exists with any kind of expandable menu within the cms:
![screen shot 2016-07-26 at 10 12 36 am](https://cloud.githubusercontent.com/assets/1561349/17141276/802ebed4-5319-11e6-8d99-33ae7b988862.png)

VS Chrome view:
![screen shot 2016-07-26 at 10 13 01 am](https://cloud.githubusercontent.com/assets/1561349/17141307/9213d616-5319-11e6-8300-8743ab18ac75.png)

**Comment by john-thomas-dotcms** [comment]
I have this problem sometimes in Chrome as well (on Windows 7 Pro), though it usually happens further down in the tree.  It also doesn't happen in every location where you can select files/folders; I'll try to note the specific locations next time it happens, and update here.

In any case, since it seems a little intermittent/inconsistent, I'm guessing this might be some kind of timing or event issue with the file selection code.  Or perhaps it's a Windows compatibility issue rather than IE?
