### ISSUE TITLE
Backend: Login Improvements

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#9423]
- [x] On failed login attempts we want to wait on the server for a couple of seconds before to return, this is a security measure for attacks, this time should be configurable.
- [x] **Security issue:** On failing login attempts the error message is different depending if the user exist or not.  We should NOT have different messages as they can indicate if a user id or email exists in the system.

**Comment by jcastro-dotcms** [comment]
PR: https://github.com/dotCMS/core/pull/9471

**Comment by jcastro-dotcms** [comment]
Hey @john-thomas-dotcms , these are the properties that we need to document:

* ``auth.failedattempts.delay.enabled``
* ``auth.failedattempts.delay.strategy``

Please let me know when you working on this so I can provide the details.

**Comment by bryanboza** [comment]
New improvements created on #9540

**Comment by bryanboza** [comment]
TC: http://qa.dotcms.com/index.php?/cases/view/61948

**Comment by john-thomas-dotcms** [comment]
Documented the `auth.failedattempts.delay.enabled` property: http://auth.dotcms.com/docs/latest/login-and-session-configuration

Note: I didn't doc the `auth.failedattempts.delay.strategy` property, since there currently appears to be only 1 possible value for the property (so it's not really configurable).  I'll update this when configuration options are added (or I'm corrected on my understanding).
