### ISSUE TITLE
Related structure updated when pushing content to another server (dotCMS 3.3.2)

### ISSUE THREAD

**Issue by bartplasmans** [dotCMS/core#9440]
Hi,

we ran into the following issue:

On our UAT server we have made changes to a certain structure named "Brand", we added 3 extra fields.
On the Production server we have an older version of the brand structure without the new fields.
Our customer asked us to import some faq content from Production to UAT. 
The faq content is related to the brand structure. 
When we published the FAQ's in UAT, all the changes to the Brand structure were gone.

It seems that not only the content you published is updated, but also related structures/content.
This is not expected behaviour, could you have a look at why this happens?

Perhaps it would be better to at least give a warning of the content which is going to be overwritten?

greetings Bart Plasmans

**Comment by jtesser** [comment]
Yes this is expected. Structures are a dependency of content

**Comment by john-thomas-dotcms** [comment]
So to give a little more detail on why this happened (and why it's expected):

The documentation which describes push publishing dependencies is here: http://dotcms.com/docs/latest/push-publishing-dependencies

The real problem here is that you published backward - push publishing is explicitly intended to only be done one way (from the authoring server to the production server, for example).  You pushed the opposite direction, which means you have a chance to overwrite newer content on your authoring server with older content from your production server.  You're actually lucky that only the Content Type was overwritten - the dependencies can include much more content, up to and including the host itself.

One way you might have been able to prevent this particular problem is to push the Content Type (with the new fields) first from the authoring server to the production server, then export the content from the prod server (which would then have the new Content Type).  However you STILL might have other problems, since the Content dependencies include more than just the Content Type.

As a (strict) general rule, never publish anything backward - you should only push and publish one direction.  Create content on the authoring server and push it, and don't allow new content to be created on the production server.  If you want clients to be able to create any content, give them (limited) access to the authoring server instead.
