### ISSUE TITLE
What's change support for multilingual pages

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#9447]
Tested in 3.5 and 3.6

What's change' only works with default language, if the user clicks on "What's Change" from another language the differences shown are from the default language.

**Comment by erickgonzalez** [comment]
To Reproduce:

1. Create a content (e.g Generic Content) with versions in Spanish and English.
2. Create a page in English and add the content.
3. Modify inline the content.
4. Click "What's Change" and check the diff.
5. Create a Spanish version of the page (there is no need to add content since the Spanish version of the content will be automatically added).
6. Modify inline the content.
7. Click "What's Change" and check the diff.
8. Use the language combo on the left to change between languages and click "What's Change" the diff should appear according to the language.

PR: https://github.com/dotCMS/core/pull/9469

**Comment by shaydotcms** [comment]
Passed QA. Using the language combo on the left to change between languages allows to see the diff according to the language.
Tested locally in:
master-3.6 // Win7 Pro SP1 // SQLServer 2012 // Chrome
master-3.6 // Mac OS 10.10 // MySQL 5.6.23 // Firefox
