### ISSUE TITLE
Recovery password enhancements on front end 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#9557]
If you try to recover password and enter a not existing email, the system should show an info message about the error  in front-end, this to avoid confusion with the end users... 

This by Usability standard, always we need try keep the end user updated of the process and avoid the user is waiting for an email, without know if was typed a wrong info.

Also right now after you try this we are having a js error: "NetworkError: 401 Unauthorized - http://localhost:8080/api/v1/forgotpassword"
SC: http://screencast.com/t/13zMfrUpAvv

Tested on master-3.7 // postgres // FF

**Comment by john-thomas-dotcms** [comment]
There's a potential security issue here, as normally if someone enters an email and password combo and it fails, the standard behavior is to not let the user know whether it was the user/email name or the password which was invalid.  This helps prevent attackers from using the login form to figure out which user/email names are valid.

The same might be true here - this could be used to try and figure out what user/email names are.  Since we obviously can't ask for a password on this form, we may not want to notify the user if the email typed was invalid.

Note that this isn't as important here as on a login form, since if someone is fishing for email addresses to try and hack, the user who owns that email address will receive a password reset email, which is a clue that something's wrong.  But it's still something we should consider (especially considering attacks on weekends or holidays where the email might not be read for a while).

An alternative we could do (which I've encountered on other sites) would be to make the message to the user just be explicit about it - something along the lines of:

    If you entered a valid email, you will receive an email with password reset instructions.
    If you do not receive an email within XX minutes, please check your spam folder, and
    then either return to this form and make sure to enter your email address correctly, or
    contact your system administrator.
