### ISSUE TITLE
Hostname in 'Forgot Password' e-mail needs to be configurable via .properties file

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#9631]
The hostname of the URL in the e-mail sent to users when the forgot their password needs to be configurable. Specifically, the running port must not be included in the URL.

**Comment by jgambarios** [comment]
@jcastro-dotcms we are not using the host used to access the login page?, I mean, if I try to recover from **host.b.com** we should use that host in the email right?, and I think the port is being sent because we are using **localhost:8080** for testing, I think that if you use a domain no port is sent, can we verify that @bryanboza ?

**Comment by bryanboza** [comment]
Ok @jgambarios, i tested that, and we sending the mail with the same request URL, and the port is not included...

**Comment by jgambarios** [comment]
Not an issue
