### ISSUE TITLE
Creating new content language version, from non-default content version, breaks image field pathing

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#9646]
Creating new content language version, from non-default content version, breaks image field pathing.
This works on demo.dotcms.com in 3.5 but is broken in 3.6.  Easy to reproduce:
1) add an image field to the generic content type
2) add new generic content in spanish first (Not the default English) with an image uploaded to a folder and save and publish.
3) Open the content again and choose any other language, english or other secondary language... after the popup asks you if you want to copy the spanish content, and you say yes, the path to the image file is broken and there is no way to correct it.

http://screencast.com/t/1X9APqHuBI7B

**Comment by oarrietadotcms** [comment]
I talked with @DeanGonzalez about this, in 3.5 works because the File Assets didn't have multi language support in that version. Every File Asset was assigned to the Default Lang and it looked like the image was copy successfully in every language.

For 3.6 we don't have a clean solution here and actually this is part of this issue: https://github.com/dotCMS/core/issues/9625. We need to analyse the best approach for next releases.

**Comment by wezell** [comment]
See: #9625
