### ISSUE TITLE
Item list of large bundles is very confusing

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#9733]
When bundles for push publishing get bigger, it is sometimes necessary to check which items are already included in the bundle and which items are still missing. But the item list of a bundle appears in unsorted order, therefore it is very hard to find a particular item. It would be desirable that the item list is sorted - first by type and then alphabetically.

To reproduce this problem in dotCMS 3.6.0 on demo.dotcms.com, you can follow these steps:
- Add many contentlets of many different types to a new bundle
- Go to "Site Browser" -> "Publishing Queue"
- Go to the "Bundles" tab and try to find a specific contentlet in the large item list

**Comment by john-thomas-dotcms** [comment]
+1.

It would be ideal to have the list of items in a bundle in multiple columns, where you can select each column to resort the list.  Columns that would be very helpful:

* Title
* Content Type
* Modified Date
* Modified User

**Note:** It might be a little challenging to do columns in the current `Bundles` tab, since the tab can list multiple bundles.  A couple possible solutions:
1. Simplest: Have a single sort order, which is applied to all bundles shown in the tab.
    * This is probably the easiest to implement without changing the current tab much.
2. Ideal: Clicking on a bundle opens a separate screen showing only that bundle.
    * This is ideal because if we do it this way, in the Bundles tab could just show a list of the bundles (i.e. just the title of each bundle), without the individual items in each bundle.  That would also make it easier to see and manage multiple bundles in the tab.

**Comment by john-thomas-dotcms** [comment]
See Also:

* https://github.com/dotCMS/core/issues/5743
* https://github.com/dotCMS/core/issues/5743
* https://github.com/dotCMS/core/issues/4244
