### ISSUE TITLE
Feature Request: allow specification of root path of dotCMS - currently, only "/" supported

### ISSUE THREAD

**Issue by rtraebing** [dotCMS/core#9923]
Feature Request: allow specification of the root path of the dotCMS application.
## Expected Behavior

Instead of all content only available at...
http://example.mycontent.net/   - eg http://example.mycontent.net/contentAsset/image-thumbnail/...

... content should be available at...
http://mycontent.net/example/contentAsset/image-thumbnail/...

(Admin page reachable at http://mycontent.net/example/admin/)

This makes the dotCMS application much easier to integrate into a site that uses paths and a single domain, instead of sub-domains, to integrate different systems.
## Current Behavior

dotCMS is currently only able to deliver content with "/" as root path.

(We were informed by your support team of this restriction and asked to make a feature request here in Github.)
## Known Workarounds

We will attempt to use a reverse proxy with nginx and mod_proxy to be able to provide this functionality (but it hasn't yet been realised/integrated).
## Steps to Reproduce (for bugs)

Not applicable. This restriction is plainly visible and was confirmed by dotCMS Support as not being a supported functionality.
## Context

This feature is something that many web applications and almost all web servers and backend frameworks provide. dotCMS is Tomcat based, and Tomcat provides this functionality through the Context setting in the server.xml (for example).
## Your Environment

- dotCMS version used: 3.6
- Browser Name and version: Not applicable
- Operating System and version: Not applicable
- Application Server and version: Not applicable
- Java Brand and version: Not applicable
- Database and version: Not applicable
- Application module (if apply): Not applicable

**Comment by levosgien** [comment]
[This is a cloud customer]

**Comment by wezell** [comment]
I believe this is a dying problem with the upcoming NG2 UI redesign and patterns therein

**Comment by rtraebing** [comment]
Is this REALLY going to be covered by a the aforementioned "NG2 UI redesign and patterns therein" or are you just trying to close this issue? I don't understand what this means and would prefer to have an honest answer that you won't do it, if this is the case. I am assuming that a User Interface (if indeed that is what "UI" means in this case) is not going to drill down to something as fundamental as a base path definition. Please clarify what you mean by this.

**Comment by wezell** [comment]
It is not minor work to make the context of dotCMS configurable or provide QA and support on such a setup.  Because of this, as of now, we have no plans to change the fact that dotCMS requires the ROOT context to serve web sites and content.

By a dying problem, I meant that if you are running a separate web app with dotCMS filling the content management role, the pattern we would suggest is to keep your app separate and use the RESTful APIs to retrieve and display content in your app context as needed and not co-mingle multiple web apps in the container.  With the new UI/UX, we are writing more of these APIs every day, all of which will be useful when consuming content in other applications.
